// ---- 9세대 (cobbleverse.wiki/spawns/gen9) ----
const SPRIGATITO=["Cherry Grove","Flower Forest","Meadow","Sunflower Plains","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Sakura Grove","Sakura Valley","Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley"];
const QUAXLY=["Plains","Sunflower Plains","Brushland","Shrubland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Arid Highlands","Ashen Savanna","Desert Oasis","Hot Shrubland","Red Oasis","Savanna Slopes","Windswept Savanna","River","Warm River"];
const LECHONK=["Fungal Caves","Plains","Sunflower Plains","Cherry Grove","Forest","Flower Forest","Meadow","Birch Forest","Grove","Old Growth Birch Forest","Brushland","Shrubland","Steppe","Valley Clearing","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Alpine Highlands","Sakura Grove","Sakura Valley","Temperate Highlands","Arid Highlands","Blooming Plateau"];
const TAROUNTULA=["Forest","Cherry Grove","Flower Forest","Birch Forest","Dark Forest","Old Growth Birch Forest","Pale Garden","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle","Mangrove Swamp","Swamp","Orchid Swamp"];
const WATTREL=["Mushroom Fields","Mirage Isles","Ocean","Warm Ocean","Lukewarm Ocean","Cold Ocean","Deep Ocean","Deep Cold Ocean","Deep Warm Ocean"];
const WATTREL2=["Stony Shore","White Cliffs","Mushroom Fields","Mirage Isles","Ocean","Warm Ocean","Lukewarm Ocean","Cold Ocean","Deep Ocean","Deep Cold Ocean","Deep Warm Ocean"];
const FLAMIGO=["Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Hot Shrubland","Red Oasis","Savanna Slopes","Shrubland","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];
const CETODDLE=["Frozen Peaks","Ice Spikes","Glacial Chasm","Siberian Taiga","Siberian Grove","Ice Marsh","Alpine Grove","Snowy Cherry Grove","Snowy Shield","Cold Shrubland","Wintry Forest","Wintry Lowlands","Snowy Plains","Snowy Badlands"];
const DUDUNSPARCE=["Dripstone Caves","Lush Caves","Sulfur Caves","Andesite Caves","Desert Caves","Diorite Caves","Fungal Caves","Granite Caves","Underground Jungle"];

add(906,"나오하","Sprigatito",null,[e("X","5-31",["sky"],B(SPRIGATITO))]);
add(907,"나로테","Floragato",null,[e("X","16-41",["sky"],B(SPRIGATITO))]);
add(908,"마스카나","Meowscarada",null,[e("X","36-53",["sky"],B(SPRIGATITO))]);
add(909,"뜨아거","Fuecoco",null,[e("X","5-31",["sky"],B(BADLANDS)),e("X","5-31",[],B(["Nether Wastes"]))]);
add(910,"악뜨거","Crocalor",null,[e("X","16-41",["sky"],B(BADLANDS)),e("X","16-41",[],B(["Nether Wastes"]))]);
add(911,"라우드본","Skeledirge",null,[e("X","36-53",["sky"],B(BADLANDS)),e("X","36-53",[],B(["Nether Wastes"]))]);
add(912,"꾸왁스","Quaxly",null,[e("X","5-31",["sky","water"],B(QUAXLY)),e("X","5-31",["inwater","sky"],B(QUAXLY))]);
add(913,"아꾸왁","Quaxwell",null,[e("X","16-41",["sky","water"],B(QUAXLY)),e("X","16-41",["inwater","sky"],B(QUAXLY))]);
add(914,"웨이니발","Quaquaval",null,[e("X","36-53",["sky","water"],B(QUAXLY)),e("X","36-53",["inwater","sky"],B(QUAXLY))]);
add(915,"맛보돈","Lechonk",null,[e("C","1-18",["sky","n025"],B(LECHONK)),e("C","1-18",["sky","n025"],B(SWAMP))]);
add(916,"퍼퓨돈","Oinkologne",null,[e("C","18-49",["sky","n025"],B(LECHONK)),e("C","18-49",["sky","n025"],B(SWAMP))]);
add(917,"타랜툴라","Tarountula",null,[e("C","1-14",["sky","d025"],B(TAROUNTULA))]);
add(918,"트래피더","Spidops",null,[e("C","15-40",["sky","d025"],B(TAROUNTULA))]);
add(919,"콩알뚜기","Nymble",null,[e("C","3-22",["seeSky"],B(BADL))]);
add(920,"엑스레그","Lokix",null,[e("R","25-38",["seeSky"],B(BADL))]);
add(921,"빠모","Pawmi",null,[e("U","5-17",[],B(PLAINS))]);
add(922,"빠모트","Pawmo",null,[e("U","18-34",[],B(PLAINS))]);
add(923,"빠르모트","Pawmot",null,[e("R","30-45",[],B(PLAINS))]);
add(924,"두리쥐","Tandemaus",null,[e("C","6-31",["sky","d025"],B(ZIGZAGOON)),e("C","6-31",["sky","d025"],S(TIMBURR)),e("C","6-31",["indoor"],S(MANSION))]);
add(925,"파밀리쥐","Maushold","네 식구",[e("C","25-47",["sky","d025"],B(ZIGZAGOON)),e("C","25-47",["sky","d025"],S(TIMBURR)),e("C","25-47",["indoor"],S(MANSION))]);
add(925,"파밀리쥐","Maushold","세 식구",[e("C","25-47",["sky","d025"],B(ZIGZAGOON)),e("C","25-47",["sky","d025"],S(TIMBURR)),e("C","25-47",["indoor"],S(MANSION))]);
add(926,"쫀도기","Fidough",null,[e("C","6-25",["sky"],B(EKANS)),e("C","6-25",["sky"],S(VILALL))]);
add(927,"바우첼","Dachsbun",null,[e("C","26-48",["sky"],B(EKANS)),e("C","26-48",["sky"],S(VILALL))]);
add(928,"미니브","Smoliv",null,[e("U","1-24",["sky","n025"],B(RAT))]);
add(929,"올리뇨","Dolliv",null,[e("U","25-35",["sky","n025"],B(RAT))]);
add(930,"올리르바","Arboliva",null,[e("U","35-51",["sky","n025"],B(RAT))]);
add(931,"시비꼬","Squawkabilly",null,[e("C","17-42",["day","sky"],B(WOOBAT)),e("C","17-42",["clear","day","sky"],S(TIMBURR))]);
add(932,"베베솔트","Nacli",null,[e("C","3-23",["sky"],B(BADLANDS)),e("C","3-28",[],B(["Basalt Deltas"]))]);
add(933,"스태솔트","Naclstack",null,[e("C","24-37",["sky"],B(BADLANDS)),e("C","24-37",[],B(["Basalt Deltas"]))]);
add(934,"콜로솔트","Garganacl",null,[e("C","38-50",["sky"],B(BADLANDS)),e("C","38-50",[],B(["Basalt Deltas"]))]);
add(935,"카르본","Charcadet",null,[e("U","5-26",[],NETH),e("U","5-26",["clear"],S(["Ruined Portal"]))]);
add(936,"카디나르마","Armarouge",null,[e("R","28-53",[],NETH),e("U","28-53",["clear"],S(["Ruined Portal"]))]);
add(937,"파라블레이즈","Ceruledge",null,[e("R","28-53",[],NETH),e("U","28-53",["clear"],S(["Ruined Portal"]))]);
add(938,"빈나두","Tadbulb",null,[e("C","2-27",["sky","t5"],B(["River","Swamp","Mangrove Swamp","Orchid Swamp","Warm River"]))]);
add(939,"찌리배리","Bellibolt",null,[e("C","22-50",["sky","t5"],B(["River","Swamp","Mangrove Swamp","Orchid Swamp","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Hot Shrubland","Red Oasis","Savanna Slopes","Shrubland"]))]);
add(940,"찌리비","Wattrel",null,[e("C","3-24",["sky","t5"],B(WATTREL)),e("C","3-24",["night","sky","t5"],B(["Stony Shore","White Cliffs"])),e("U","3-24",["surf","sky","t5"],B(WATTREL2))]);
add(941,"찌리비크","Kilowattrel",null,[e("C","25-49",["sky","t5"],B(WATTREL)),e("C","25-49",["night","sky","t5"],B(["Stony Shore","White Cliffs"])),e("U","25-49",["surf","sky","t5"],B(WATTREL2))]);
add(942,"오라티프","Maschiff",null,[e("C","9-29",["sky"],B(BADL)),e("C","9-29",["sky"],S(VILALL)),e("C","9-29",["sky"],S(["Pillager Outpost"])),e("C","9-29",["sky"],S(MANSION))]);
add(943,"마피티프","Mabosstiff",null,[e("C","30-51",["sky"],B(BADL)),e("C","30-51",["sky"],S(VILALL)),e("C","30-51",["sky"],S(["Pillager Outpost"])),e("C","30-51",["sky"],S(MANSION))]);
add(944,"땃쭈르","Shroodle",null,[e("C","4-27",["night","sky"],B(JUNGLE))]);
add(945,"태깅구르","Grafaiai",null,[e("C","28-49",["night","sky"],B(JUNGLE))]);
add(946,"그푸리","Bramblin",null,[e("C","3-28",["sky","n15"],B(CACNEA)),e("C","3-28",[],B(["Soul Sand Valley"]))]);
add(947,"공푸리","Brambleghast",null,[e("C","23-48",["sky","n15"],B(CACNEA)),e("C","23-48",[],B(["Soul Sand Valley"]))]);
add(948,"들눈해","Toedscool",null,[e("C","7-29",["sky"],B(SAVANNA)),e("C","7-29",[],B(["Crimson Forest"]))]);
add(949,"육파리","Toedscruel",null,[e("C","30-52",["sky"],B(SAVANNA)),e("C","30-52",[],B(["Crimson Forest"]))]);
add(950,"절벼게","Klawf",null,[e("U","20-45",["sky"],B(BADLANDS))]);
add(951,"캡싸이","Capsakid",null,[e("C","5-30",["sky"],B(EKANS)),e("C","5-30",[],B(["Crimson Forest","Warped Forest"]))]);
add(952,"스코빌런","Scovillain",null,[e("C","25-49",["sky"],B(EKANS)),e("C","25-49",[],B(["Crimson Forest","Warped Forest"]))]);
add(953,"구르데","Rellor",null,[e("C","2-27",[],B(EKANS))]);
add(954,"베라카스","Rabsca",null,[e("C","22-47",[],B(EKANS))]);
add(955,"하느라기","Flittle",null,[e("U","1-26",["sky","n025"],B(EKANS))]);
add(956,"클레스퍼트라","Espathra",null,[e("U","35-53",["sky","n025"],B(EKANS))]);
add(957,"어리짱","Tinkatink",null,[e("C","5-24",["sky"],S(["Cobblemon Ruins (All Types)"])),e("U","5-24",["sky"],B(MEDITITE))]);
add(958,"벼리짱","Tinkatuff",null,[e("C","24-35",["sky"],S(["Cobblemon Ruins (All Types)"])),e("U","24-35",["sky"],B(MEDITITE))]);
add(959,"두드리짱","Tinkaton",null,[e("C","38-61",["sky"],S(["Cobblemon Ruins (All Types)"])),e("R","38-61",["sky"],B(MEDITITE))]);
add(960,"바다그다","Wiglett",null,[e("C","1-25",["sky"],B(["Beach"])),e("C","1-25",["floor","seeSky"],B(HORSEA))]);
add(961,"바닥트리오","Wugtrio",null,[e("C","26-43",["sky"],B(["Beach"])),e("C","26-43",["floor","seeSky"],B(HORSEA))]);
add(962,"떨구새","Bombirdier",null,[e("U","35-60",["sky"],B(["Beach","River","Warm River"]))]);
add(963,"맨돌핀","Finizen",null,[e("U","7-32",["sub","seeSky"],B(OCEAN)),e("U","7-32",["sub","indoor","sky"],B(OCEAN))]);
add(964,"돌핀맨","Palafin",null,[e("U","38-46",["sub","seeSky"],B(OCEAN)),e("U","38-46",["sub","indoor","sky"],B(OCEAN))]);
add(965,"부르롱","Varoom",null,[e("U","5-38",["sky"],B(BADLANDS)),e("U","5-38",["sky"],S(VILALL))]);
add(966,"부르르룸","Revavroom",null,[e("U","40-55",["sky"],B(BADLANDS)),e("U","40-55",["sky"],S(VILALL))]);
add(967,"모토마","Cyclizar",null,[e("R","25-50",["sky","n025"],B(MUDBRAY))]);
add(968,"꿈트렁","Orthworm",null,[e("U","23-48",["sky"],B(CACNEA)),e("C","23-48",["dim","minY0"],B(CACNEA)),e("C","23-48",["dim","minY0","iron"],B(KLINK)),e("R","23-48",[],B(["Soul Sand Valley"]))]);
add(969,"초롱순","Glimmet",null,[e("C","10-35",["dim","amethyst"],OW()),e("R","10-35",[],B(LUSHC))]);
add(970,"킬라플로르","Glimmora",null,[e("C","35-53",["dim","amethyst"],OW()),e("R","35-53",[],B(LUSHC))]);
add(971,"망망이","Greavard",null,[e("R","3-29",["seeSky","night"],B(DARK)),e("R","3-29",["night"],S(["Crown Cemetery"]))]);
add(972,"묘두기","Houndstone",null,[e("R","30-59",["seeSky","night"],B(DARK)),e("R","30-59",["night"],S(["Crown Cemetery"]))]);
add(973,"꼬이밍고","Flamigo",null,[e("C","25-50",["sky","n025","water"],B(FLAMIGO)),e("U","25-50",["surf","day","sky"],B(FLAMIGO))]);
add(974,"터벅고래","Cetoddle",null,[e("U","8-33",["sky"],B(SEEL)),e("U","8-33",["sky"],B(CETODDLE))]);
add(975,"우락고래","Cetitan",null,[e("U","28-52",["sky"],B(SEEL)),e("U","28-52",["sky"],B(CETODDLE))]);
add(976,"가비루사","Veluza",null,[e("U","23-48",["sub","seeSky"],B(OCEAN)),e("U","23-48",["sub","indoor","sky"],B(OCEAN)),e("U","23-48",["sub","indoor","subY"],S(SSC))]);
add(977,"어써러셔","Dondozo",null,[e("R","28-53",["sub","seeSky"],B(SWAMP)),e("R","28-53",["sub","indoor","sky"],B(SWAMP))]);
add(978,"싸리용","Tatsugiri",null,[e("R","23-48",["sky"],B(SWAMP)),e("R","23-48",["sub","seeSky"],B(SWAMP)),e("R","23-48",["sub","indoor","sky"],B(SWAMP))]);
add(979,"저승갓숭","Annihilape",null,[e("C","35-62",["sky"],B(["Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Meadow","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater","Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle"]))]);
add(980,"토오","Clodsire",null,[e("C","20-43",["sky"],B(PWOOP)),e("C","20-43",["sub","seeSky"],B(PWOOP)),e("U","20-43",["sub","seeSky"],B(SAVANNA)),e("U","20-43",["sky","water"],B(SAVANNA)),e("C","20-43",["sub","indoor","sky"],B(PWOOP)),e("U","20-43",["sub","indoor","sky"],B(SAVANNA))]);
add(981,"키키링","Farigiraf",null,[e("C","32-55",["sky","n025"],B(SAVANNA))]);
add(982,"노고고치","Dudunsparce","두 마디폼",[e("U","32-52",["dim"],B(DUDUNSPARCE))]);
add(982,"노고고치","Dudunsparce","세 마디폼",[e("U","32-52",["dim"],B(DUDUNSPARCE))]);
add(983,"대도각참","Kingambit",null,[e("X","72-85",["n25"],B(["Bamboo Jungle"]))]);
add(984,"위대한엄니","Great Tusk",null,[e("R","40-65",["seeSky"],B(EKANS))]);
add(985,"우렁찬꼬리","Scream Tail",null,[e("R","45-60",["rain"],B(FLOWER))]);
add(986,"사나운버섯","Brute Bonnet",null,[e("R","45-60",["night"],B(JUNGLE))]);
add(987,"날개치는머리","Flutter Mane",null,[e("R","45-60",["night"],B(DARK))]);
add(988,"땅을기는날개","Slither Wing",null,[e("R","45-60",["seeSky"],B(JUNGLE)),e("R","50-60",[],B(["Crimson Forest"]))]);
add(989,"모래털가죽","Sandy Shocks",null,[e("R","45-60",["seeSky"],B(EKANS))]);
add(990,"무쇠바퀴","Iron Treads",null,[e("R","40-65",[],B(GEO))]);
add(991,"무쇠보따리","Iron Bundle",null,[e("R","45-60",[],B(FREEZE))]);
add(992,"무쇠손","Iron Hands",null,[e("R","45-60",["seeSky"],B(SAND))]);
add(993,"무쇠머리","Iron Jugulis",null,[e("R","40-65",["seeSky","night"],B(GEO))]);
add(994,"무쇠독나방","Iron Moth",null,[e("R","45-60",["seeSky"],B(["Savanna Plateau","Blooming Plateau","Cherry Grove","Meadow","Wooded Badlands","Arid Highlands","Yosemite Cliffs"]))]);
add(995,"무쇠가시","Iron Thorns",null,[e("R","40-65",[],B(GEO))]);
add(996,"드니차","Frigibax",null,[e("R","20-34",["seeSky"],B(SNOWSAND))]);
add(997,"드니꽁","Arctibax",null,[e("R","35-53",["seeSky"],B(SNOWSAND))]);
add(998,"드닐레이브","Baxcalibur",null,[e("X","58-67",["seeSky"],B(SNOWSAND))]);
add(999,"모으령","Gimmighoul","도보폼",[e("C","5-30",["minY48"],S(["Cobblemon Ruins (All Types)"])),e("C","5-30",["minYm37","maxY10"],S(["Crumbling Arch Ruins","Rooted Arch Ruins"]))]);
add(999,"모으령","Gimmighoul","상자폼",[e("R","5-30",["minY48"],S(["Cobblemon Ruins (All Types)"])),e("R","5-30",["minYm37","maxY10"],S(["Crumbling Arch Ruins","Rooted Arch Ruins"]))]);
add(1001,"총지엔","Wo-Chien",null,[e("X","65-70",["special"],S(["Grasswither Shrine"]))]);
add(1002,"파오젠","Chien-Pao",null,[e("X","65-70",["special"],S(["Icerend Shrine"]))]);
add(1003,"딩루","Ting-Lu",null,[e("X","65-70",["special"],S(["Groundblight Shrine"]))]);
add(1004,"위유이","Chi-Yu",null,[e("X","65-70",["special"],S(["Firescourge Shrine"]))]);
add(1005,"고동치는달","Roaring Moon",null,[e("R","55-70",["night"],B(GEO))]);
add(1006,"무쇠무인","Iron Valiant",null,[e("R","55-70",["storm"],B(PLAINS))]);
add(1007,"코라이돈","Koraidon",null,[e("X","40-70",["seeSky"],B(["Beach"]))]);
add(1008,"미라이돈","Miraidon",null,[e("X","40-70",["seeSky"],B(["Beach"]))]);
add(1009,"굽이치는물결","Walking Wake",null,[e("X","50-70",["rain"],B(GEO))]);
add(1010,"무쇠잎새","Iron Leaves",null,[e("X","50-70",["night"],B(FOREST_ALL))]);
add(1011,"과미르","Dipplin",null,[e("R","20-45",["clear","seeSky"],B(FLOWER))]);
add(1012,"차데스","Poltchageist","짝퉁폼",[e("U","6-31",["indoor","day","minY62"],S(["Village (Desert)","Village (Savanna)"])),e("U","6-31",["night","minY62"],S(["Village (Desert)","Village (Savanna)"]))]);
add(1012,"차데스","Poltchageist","진품폼",[e("U","6-31",["indoor","day","minY62"],S(["Village (Desert)","Village (Savanna)"])),e("U","6-31",["night","minY62"],S(["Village (Desert)","Village (Savanna)"]))]);
add(1013,"그우린차","Sinistcha","범작폼",[e("U","26-51",["indoor","day","minY62"],S(["Village (Desert)","Village (Savanna)"])),e("U","26-51",["night","minY62"],S(["Village (Desert)","Village (Savanna)"]))]);
add(1013,"그우린차","Sinistcha","걸작폼",[e("U","26-51",["indoor","day","minY62"],S(["Village (Desert)","Village (Savanna)"])),e("U","26-51",["night","minY62"],S(["Village (Desert)","Village (Savanna)"]))]);
add(1014,"조타구","Okidogi",null,[e("X","60-75",["seeSky"],B(SAVANNA))]);
add(1015,"이야후","Munkidori",null,[e("X","60-75",["seeSky"],B(JUNGLE))]);
add(1016,"기로치","Fezandipiti",null,[e("X","60-75",["seeSky"],B(MEDITITE))]);
add(1017,"오거폰","Ogerpon",null,[e("X","50-75",[],B(LUSHC))]);
add(1018,"브리두라스","Archaludon",null,[e("X","50-68",[],B(SNOWSAND))]);
add(1019,"과미드라","Hydrapple",null,[e("X","45-64",["clear","seeSky"],B(FLOWER))]);
add(1020,"꿰뚫는화염","Gouging Fire",null,[e("X","60-75",[],B(["Basalt Deltas","Nether Wastes"]))]);
add(1021,"날뛰는우레","Raging Bolt",null,[e("X","60-75",["seeSky","t3"],B(SAVANNA))]);
add(1022,"무쇠암석","Iron Boulder",null,[e("X","60-75",["seeSky","night"],B(BADLANDS))]);
add(1023,"무쇠감투","Iron Crown",null,[e("X","60-75",["seeSky"],B(MEDITITE))]);
add(1024,"테라파고스","Terapagos",null,[e("X","55-75",["maxY0","amethystbase"],B(KLINK))]);
add(1025,"복숭악동","Pecharunt",null,[e("X","60-80",["seeSky"],B(DARK))]);
