// ---- 7세대 (COBBLEVERSE 모드팩 1.7.42 데이터팩 COBBLEVERSE-DP-v31 기준) ----
const ROWLET=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Haze Mountain","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"];
const ROWLET2=["Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const POPPLIO=["Stony Shore","Beach","Snowy Beach","Basalt Cliffs","Granite Cliffs","White Cliffs"];
const PIKIPEK=["Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Skylands Autumn","Skylands Spring","Skylands Summer"];
const YUNGOOS=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes"];
const GRUBBIN=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"];
const CRABOMINABLE=["Frozen Peaks","Jagged Peaks","Snowy Slopes","Stony Peaks","Emerald Peaks","Rocky Mountains","Scarlet Mountains","Windswept Spires"];
const ROCKRUFF=["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands"];
const LYCANROC=["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"];
const WISHIWASHI=["Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs"];
const MAREANIE=["Stony Shore","Beach","Basalt Cliffs","Granite Cliffs","White Cliffs"];
const MAREANIE2=["Stony Shore","Beach","Basalt Cliffs","Granite Cliffs","White Cliffs","Warm Ocean"];
const MUDBRAY=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes"];
const DEWPIDER=["River","Warm River","Mangrove Swamp","Swamp","Orchid Swamp"];
const MORELULL=["Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley","Mushroom Fields","Fungal Caves"];
const SALANDIT=["Mantle Caves","Volcanic Crater","Volcanic Peaks"];
const SALANDIT2=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Windswept Spires","Yosemite Cliffs"];
const MINIOR=["Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland"];
const MAGEARNA=["Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"];

add(722,"나몰빼미","Rowlet",null,[e("X","5-32",["sky","treetop"],B(ROWLET))]);
add(722,"나몰빼미","Rowlet","히스이 계열",[e("X","5-32",["sky","treetop"],B(ROWLET2))]);
add(723,"빼미스로우","Dartrix",null,[e("X","17-42",["sky","treetop"],B(ROWLET))]);
add(723,"빼미스로우","Dartrix","히스이 계열",[e("X","17-42",["sky","treetop"],B(ROWLET2))]);
add(724,"모크나이퍼","Decidueye",null,[e("X","34-53",["sky","treetop"],B(ROWLET))]);
add(724,"모크나이퍼","Decidueye","히스이",[e("X","34-53",["sky","treetop"],B(ROWLET2))]);
add(725,"냐오불","Litten",null,[e("X","5-32",["sky","norain"],B(JUNGLE)),e("X","34-52",[],B(["Crimson Forest"]))]);
add(726,"냐오히트","Torracat",null,[e("X","17-42",["sky","norain"],B(JUNGLE)),e("X","34-52",[],B(["Crimson Forest"]))]);
add(727,"어흥염","Incineroar",null,[e("X","34-53",["sky","norain"],B(JUNGLE)),e("X","34-52",[],B(["Crimson Forest"]))]);
add(728,"누리공","Popplio",null,[e("X","5-32",["sky"],B(POPPLIO)),e("X","5-32",["sub","seeSky"],B(POPPLIO)),e("X","5-32",["sub","indoor","sky"],B(POPPLIO))]);
add(729,"키요공","Brionne",null,[e("X","17-42",["sky"],B(POPPLIO)),e("X","17-42",["sub","seeSky"],B(POPPLIO)),e("X","17-42",["sub","indoor","sky"],B(POPPLIO))]);
add(730,"누리레느","Primarina",null,[e("X","34-53",["sky"],B(POPPLIO)),e("X","34-53",["sub","seeSky"],B(POPPLIO)),e("X","34-53",["sub","indoor","sky"],B(POPPLIO))]);
add(731,"콕코구리","Pikipek",null,[e("C","2-27",["sky","day"],B(PIKIPEK))]);
add(732,"크라파","Trumbeak",null,[e("C","14-36",["sky","day"],B(PIKIPEK))]);
add(733,"왕큰부리","Toucannon",null,[e("C","28-49",["sky","day"],B(PIKIPEK))]);
add(734,"영구스","Yungoos",null,[e("C","1-25",["sky","n025"],B(YUNGOOS))]);
add(735,"형사구스","Gumshoos",null,[e("C","20-42",["sky","n025"],B(YUNGOOS))]);
add(736,"턱지충이","Grubbin",null,[e("C","5-18",["sky"],B(GRUBBIN))]);
add(737,"전지충이","Charjabug",null,[e("U","22-45",["sky"],B(GRUBBIN))]);
add(738,"투구뿌논","Vikavolt",null,[e("R","40-67",["sky"],B(GRUBBIN))]);
add(739,"오기지게","Crabrawler",null,[e("C","9-34",["sky"],B(POPPLIO))]);
add(740,"모단단게","Crabominable",null,[e("U","29-48",["sky"],B(CRABOMINABLE))]);
add(741,"춤추새","Oricorio","이글이글스타일",[e("U","18-33",["seeSky"],B(["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands"]))]);
add(741,"춤추새","Oricorio","파칙파칙스타일",[e("U","18-33",["seeSky"],B(["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"]))]);
add(741,"춤추새","Oricorio","훌라훌라스타일",[e("U","18-33",["seeSky"],B(FLOWER))]);
add(741,"춤추새","Oricorio","하늘하늘스타일",[e("U","18-33",["seeSky"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"]))]);
add(742,"에블리","Cutiefly",null,[e("C","5-30",["sky","day","norain"],B(FLOWER)),e("C","5-30",["sky","day","norain","flowersacch"],OW(["꽃 계열"]))]);
add(743,"에리본","Ribombee",null,[e("C","25-46",["sky","day","norain"],B(FLOWER)),e("C","25-46",["sky","day","norain","flowersacch"],OW(["꽃 계열"]))]);
add(744,"암멍이","Rockruff",null,[e("U","5-20",["seeSky"],B(ROCKRUFF))]);
add(745,"루가루암","Lycanroc","황혼의 모습",[e("U","29-45",["seeSky","dusk"],B(LYCANROC))]);
add(745,"루가루암","Lycanroc","한낮의 모습",[e("U","29-45",["seeSky","day"],B(LYCANROC))]);
add(745,"루가루암","Lycanroc","한밤중의 모습",[e("U","29-45",["seeSky","night"],B(LYCANROC))]);
add(746,"약어리","Wishiwashi",null,[e("C","1-18",["sub","seeSky"],B(WISHIWASHI)),e("C","1-18",["sub","indoor","sky"],B(WISHIWASHI))]);
add(747,"시마사리","Mareanie",null,[e("U","6-31",["sky"],B(MAREANIE)),e("C","6-31",["floor","seeSky"],B(MAREANIE2))]);
add(748,"더시마사리","Toxapex",null,[e("U","38-50",["sky"],B(MAREANIE)),e("C","38-50",["floor","seeSky"],B(MAREANIE2))]);
add(749,"머드나기","Mudbray",null,[e("C","14-39",["sky","n025"],B(MUDBRAY))]);
add(750,"만마드","Mudsdale",null,[e("C","30-50",["sky","n025"],B(MUDBRAY))]);
add(751,"물거미","Dewpider",null,[e("U","2-27",["sky"],B(DEWPIDER)),e("C","2-27",["floor","seeSky"],B(DEWPIDER))]);
add(752,"깨비물거미","Araquanid",null,[e("U","22-45",["sky"],B(DEWPIDER)),e("C","22-45",["floor","seeSky"],B(DEWPIDER))]);
add(753,"짜랑랑","Fomantis",null,[e("C","1-25",["sky","d025"],B(FLOWER)),e("C","1-25",["sky","d025"],B(JUNGLE))]);
add(754,"라란티스","Lurantis",null,[e("C","34-48",["sky","d025"],B(FLOWER)),e("C","34-48",["sky","d025"],B(JUNGLE))]);
add(755,"자마슈","Morelull",null,[e("C","4-29",["light07"],B(MORELULL)),e("C","4-29",["dim"],B(LUSHC)),e("C","4-29",[],B(["Crimson Forest","Warped Forest"])),e("C","4-29",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(756,"마셰이드","Shiinotic",null,[e("C","24-41",["light07"],B(MORELULL)),e("C","24-41",["dim"],B(LUSHC)),e("C","24-41",[],B(["Crimson Forest","Warped Forest"])),e("C","24-41",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(757,"야도뇽","Salandit",null,[e("C","7-32",[],B(SALANDIT)),e("C","7-32",["dim","lavab"],B(SALANDIT2)),e("C","7-32",[],B(["Basalt Deltas"])),e("C","7-32",[],B(["Soul Sand Valley"]))]);
add(758,"염뉴트","Salazzle",null,[e("C","33-48",[],B(SALANDIT)),e("C","33-48",["dim","lavab"],B(SALANDIT2)),e("C","33-48",[],B(["Basalt Deltas"])),e("C","33-48",[],B(["Soul Sand Valley"]))]);
add(759,"포곰곰","Stufful",null,[e("C","9-34",["sky"],B(["Bamboo Jungle"]))]);
add(760,"이븐곰","Bewear",null,[e("C","27-50",["sky"],B(["Bamboo Jungle"]))]);
add(761,"달콤아","Bounsweet",null,[e("C","1-21",["sky","treetop"],B(JUNGLE))]);
add(762,"달무리나","Steenee",null,[e("C","18-29",["sky"],B(JUNGLE))]);
add(763,"달코퀸","Tsareena",null,[e("C","28-51",["sky"],B(JUNGLE))]);
add(764,"큐아링","Comfey",null,[e("U","24-49",["sky","norain"],B(FLOWER)),e("R","24-49",["sky","norain","flowers"],OW())]);
add(765,"하랑우탄","Oranguru",null,[e("R","35-70",["sky","treetop"],B(JUNGLE))]);
add(766,"내던숭이","Passimian",null,[e("R","35-66",["sky","treetop"],B(JUNGLE))]);
add(767,"꼬시레","Wimpod",null,[e("U","1-23",["sky"],B(POPPLIO)),e("U","1-23",["dim","maxY0","water"],OW(["?#cobblemon:is_deep_dark"])),e("U","1-23",["floor","dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(768,"갑주무사","Golisopod",null,[e("U","30-53",["sky"],B(POPPLIO)),e("U","30-53",["dim","maxY0","water"],OW(["?#cobblemon:is_deep_dark"])),e("U","30-53",["floor","dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(769,"모래꿍","Sandygast",null,[e("C","7-32",["sky","n15"],B(["Beach"]))]);
add(770,"모래성이당","Palossand",null,[e("C","42-48",["sky","n15"],B(["Beach"]))]);
add(771,"해무기","Pyukumuku",null,[e("U","16-41",["sky"],B(["Beach","Snowy Beach"])),e("C","16-41",["floor","seeSky","minY48"],B(["Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Ocean","Cold Ocean","Lukewarm Ocean"])),e("C","16-41",["floor","seeSky"],B(["Warm Ocean"]))]);
add(772,"타입:널","Type: Null",null,[e("X","1",["special"],S(["Resurrection Machine"]))]);
add(774,"메테노","Minior","유성의 모습",[e("R","20-30",["seeSky","day"],OW())]);
add(774,"메테노","Minior","빨간색 코어",[e("U","20-30",["seeSky","night"],B(ROCKRUFF))]);
add(774,"메테노","Minior","주황색 코어",[e("U","20-30",["seeSky","night"],B(MINIOR))]);
add(774,"메테노","Minior","노란색 코어",[e("U","20-30",["seeSky","night"],B(["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"]))]);
add(774,"메테노","Minior","초록색 코어",[e("U","20-30",["seeSky","night"],B(JUNGLE))]);
add(774,"메테노","Minior","파란색 코어",[e("U","20-30",["seeSky","night"],B(["River","Frozen River","Warm River","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"]))]);
add(774,"메테노","Minior","남색 코어",[e("U","20-30",["seeSky","night"],B(["Cold Ocean","Deep Cold Ocean","Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands","Stony Peaks","Rocky Mountains","Windswept Spires","Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Haze Mountain","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands","Gravel Desert","Rocky Shrubland","Windswept Hills","Windswept Gravelly Hills","Windswept Forest","Stony Shore","The End","Small End Islands","End Midlands","End Highlands","End Barrens"]))]);
add(774,"메테노","Minior","보라색 코어",[e("U","20-30",["seeSky","night"],B(LYCANROC))]);
add(775,"자말라","Komala",null,[e("C","23-48",["sky","leaves","treetop"],B(MINIOR))]);
add(776,"폭거북스","Turtonator",null,[e("U","24-49",[],B(["Basalt Deltas"]))]);
add(777,"토게데마루","Togedemaru",null,[e("U","19-44",["sky","t5"],B(ROCKRUFF))]);
add(778,"따라큐","Mimikyu",null,[e("R","23-48",["night"],B(["Dark Forest","Deep Dark"])),e("U","23-48",["indoor","minY62"],S(MANSION))]);
add(779,"치갈기","Bruxish",null,[e("U","23-48",["sub","seeSky"],B(["Warm Ocean"])),e("U","23-48",["sub","indoor","sky"],B(["Warm Ocean"]))]);
add(780,"할비롱","Drampa",null,[e("U","24-49",["sky","minY190"],B(CRABOMINABLE)),e("U","24-49",["sky","minY190"],B(["Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter"]))]);
add(781,"타타륜","Dhelmise",null,[e("C","27-52",["sub","seeSky"],{b:WISHIWASHI,s:["Shipwreck"]}),e("C","27-52",["sub","indoor","sky"],{b:WISHIWASHI,s:["Shipwreck"]}),e("C","27-52",["sub","subY"],{b:WISHIWASHI,s:["Shipwreck Cove (All Types)"]})]);
add(782,"짜랑꼬","Jangmo-o",null,[e("X","5-30",["minY0"],B(JUNGLE))]);
add(783,"짜랑고우","Hakamo-o",null,[e("X","35-42",["minY0"],B(JUNGLE))]);
add(784,"짜랑고우거","Kommo-o",null,[e("X","45-60",["minY0"],B(JUNGLE))]);
add(785,"카푸꼬꼬꼭","Tapu Koko",null,[e("X","50-70",["seeSky"],B(["Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"]))]);
add(786,"카푸나비나","Tapu Lele",null,[e("X","50-70",["seeSky"],B(["Cherry Grove","Flower Forest","Meadow","Sunflower Plains","Sakura Grove","Sakura Valley","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Beach","Snowy Beach"]))]);
add(787,"카푸브루루","Tapu Bulu",null,[e("X","50-70",["seeSky"],B(["River","Frozen River","Warm River","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"]))]);
add(788,"카푸느지느","Tapu Fini",null,[e("X","50-70",["seeSky"],B(["River","Frozen River","Warm River","Beach","Snowy Beach"]))]);
add(789,"코스모그","Cosmog",null,[e("X","28-42",[],END)]);
add(790,"코스모움","Cosmoem",null,[e("X","44-52",[],END)]);
add(791,"솔가레오","Solgaleo",null,[e("X","70",["seeSky","day"],B(MINIOR)),e("X","70",[],END)]);
add(792,"루나아라","Lunala",null,[e("X","70",["seeSky","night"],B(["Dark Forest","Deep Dark"])),e("X","70",[],END)]);
add(793,"텅비드","Nihilego",null,[e("X","60-78",["sub"],B(WISHIWASHI))]);
add(794,"매시붕","Buzzwole",null,[e("X","60-70",["seeSky"],B(JUNGLE))]);
add(795,"페로코체","Pheromosa",null,[e("X","55-65",["seeSky"],B(["Blooming Valley","Steppe","White Cliffs"])),e("X","55-65",[],END)]);
add(796,"전수목","Xurkitree",null,[e("X","58-72",[],END)]);
add(797,"철화구야","Celesteela",null,[e("X","65-80",[],END)]);
add(798,"종이신도","Kartana",null,[e("X","55-70",["seeSky"],B(["Cherry Grove"]))]);
add(799,"악식킹","Guzzlord",null,[e("X","70-75",[],END)]);
add(800,"네크로즈마","Necrozma",null,[e("X","70-75",[],END)]);
add(801,"마기아나","Magearna",null,[e("X","50-70",["seeSky"],B(MAGEARNA))]);
add(801,"마기아나","Magearna","500년 전의 색",[e("X","70-85",["seeSky"],B(MAGEARNA))]);
add(802,"마샤도","Marshadow",null,[e("X","45-68",["indoor"],B(["Deep Dark","Crystal Caves","Deep Caves","Frostfire Caves","Mantle Caves","Tuff Caves"]))]);
add(803,"베베놈","Poipole",null,[e("X","40",[],S(["Dawn Tower (End)","Dusk Tower (End)"]))]);
add(804,"아고용","Naganadel",null,[e("X","48-62",[],END)]);
add(805,"차곡차곡","Stakataka",null,[e("X","60-72",[],B(["Deep Dark"]))]);
add(806,"두파팡","Blacephalon",null,[e("X","55-62",["seeSky"],B(["Dark Forest","Deep Dark"]))]);
add(807,"제라오라","Zeraora",null,[e("X","45-85",["seeSky"],B(["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa"])),e("X","45-85",["seeSky"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove"]))]);
add(808,"멜탄","Meltan",null,[e("X","38-48",["seeSky","ironblock"],OW()),e("X","38-52",[],B(["Beach"]))]);
