// ---- 2세대 (cobbleverse.wiki/spawns/gen2) ----
const TAIGA=["Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Bryce Canyon","Cloud Forest","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yosemite Lowlands","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const SENT=U_([...TAIGA,...PIDGEY,"Ice Spikes","Snowy Plains","Snowy Badlands"]);
const LEDY=[...PIDGEY.filter(b=>b!=="Grove"),"Dark Forest","Pale Garden"];
const SPIN=["Forest","Birch Forest","Dark Forest","Old Growth Birch Forest","Pale Garden","Forested Highlands","Mirage Isles","Temperate Highlands",...JUNGLE,"Deep Dark"];
const DEEPO=["Deep Ocean","Deep Cold Ocean","Deep Frozen Ocean","Deep Lukewarm Ocean"];
const TOGE=["Cherry Grove","Flower Forest","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Sakura Grove","Sakura Valley","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley"];
const NATU=["Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis","Savanna Plateau","Blooming Plateau","Cherry Grove","Meadow","Arid Highlands","Yosemite Cliffs"];
const MAREEP=[...PALDEA_T,...PLAINS2];
const HOPPIP=U_([...PLAINS,...FLOWER]);
const SW3B=["Swamp","Ice Marsh","Orchid Swamp"];
const PWOOP=["Mangrove Swamp","Underground Jungle"];
const MISD=["Dark Forest","Pale Garden",...SWAMP];
const HSNE=["Meadow","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Caldera","Yosemite Cliffs"];
const TEDDY=U_([...FOREST_G,"Meadow","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Alpine Highlands","Snowy Slopes","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Blooming Plateau","Yosemite Lowlands","Caldera","Yosemite Cliffs",...TAIGA]);
const VOLC=["Volcanic Crater","Volcanic Peaks"];
const SWINUB=["Ice Spikes","Snowy Plains","Cold Shrubland","Snowy Badlands"];
const LARV=GEO.filter(b=>b!=="Alpine Grove"&&b!=="Snowy Slopes");
const OM=["Ocean Monument"], NETH={all:"nether",ex:[]}, END={all:"end",ex:[]};
const SNUB={b:[...SAVANNA,"Plains","Sunflower Plains","Meadow","Steppe","Alpine Highlands","Blooming Plateau","Valley Clearing"],s:VILALL};

[[152,"치코리타","Chikorita","5-32"],[153,"베이리프","Bayleef","16-41"],[154,"메가니움","Meganium","32-53"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("X",l,["sky"],B(FLOWER))]));
[[155,"브케인","Cyndaquil","5-31","히스이 계열"],[156,"마그케인","Quilava","17-41","히스이 계열"],[157,"블레이범","Typhlosion","36-53","히스이"]].forEach(([d,k,n,l,f])=>{add(d,k,n,null,[e("X",l,["sky"],B(PIDGEY))]);add(d,k,n,f,[e("X",l,["clear","sky"],B(TAIGA)),e("X",l,[],B(["Crimson Forest"]))]);});
[[158,"리아코","Totodile","5-31"],[159,"엘리게이","Croconaw","18-41"],[160,"장크로다일","Feraligatr","30-53"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("X",l,["sky"],B(SWAMP)),e("X",l,["sub","seeSky"],B(SWAMP)),e("X",l,["sub","indoor","sky"],B(SWAMP))]));
add(161,"꼬리선","Sentret",null,[e("C","1-22",["sky"],B(SENT))]);
add(162,"다꼬리","Furret",null,[e("C","15-42",["sky"],B(SENT))]);
add(163,"부우부","Hoothoot",null,[e("C","1-26",["night","sky"],B([...FOREST_ALL,"Deep Dark"]))]);
add(164,"야부엉","Noctowl",null,[e("C","20-45",["night","sky"],B([...FOREST_ALL,"#cobblemon:is_sky","Deep Dark"]))]);
add(165,"레디바","Ledyba",null,[e("C","2-27",["clear","day","sky"],B(LEDY))]);
add(166,"레디안","Ledian",null,[e("C","18-39",["clear","night","sky"],B(LEDY))]);
[[167,"페이검","Spinarak","1-21"],[168,"아리아도스","Ariados","22-40"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["clear","night","sky"],B(SPIN)),e("C",l,["dim"],OW(["Deep Dark"])),e("C",l,["indoor","sky0","minY0"],OW(["Deep Dark"])),e("C",l,["indoor","cobweb"],S(MANSION))]));
add(169,"크로뱃","Crobat",null,[e("C","41-54",["clear","night","sky"],B([...FOREST,...SWAMP3])),e("C","41-54",["dim","n025"],B([...FOREST,...SWAMP3])),e("C","41-54",["dim","d15"],OW(["Deep Dark","숲 계열","늪 계열"])),e("U","41-54",["indoor","sky0","d15"],OW(["Deep Dark","숲 계열","늪 계열"])),e("C","41-54",["clear","sky","n15"],B(DARK)),e("U","41-54",["dim"],B(["Deep Dark","Deep Caves"]))]);
[[170,"초라기","Chinchou","8-33"],[171,"랜턴","Lanturn","27-46"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["sub","seeSky","maxY48"],B(DEEPO)),e("C",l,["sub","indoor","sky","maxY48"],B(DEEPO)),e("C",l,["sub","indoor","subY"],S(SSC))]));
add(172,"피츄","Pichu",null,[e("U","1-21",["sky","t5"],B(FOREST_G))]);
add(172,"피츄","Pichu","알로라 계열",[e("U","16-32",["sky","t5"],B(["Beach"]))]);
add(173,"삐","Cleffa",null,[e("U","1-22",["night","sky"],B(["Dripstone Caves",...MOUNT,"Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove"])),e("U","1-22",["dim"],B(["Dripstone Caves"]))]);
add(174,"푸푸린","Igglybuff",null,[e("C","1-21",["sky","n15"],B(FLOWER)),e("C","1-21",["sky","n15"],B(PLAINS))]);
add(175,"토게피","Togepi",null,[e("R","1-25",["clear","day","sky"],B(TOGE))]);
add(176,"토게틱","Togetic",null,[e("R","20-41",["clear","day","sky"],B(TOGE))]);
add(177,"네이티","Natu",null,[e("C","7-32",["day","sky"],B(NATU))]);
add(178,"네이티오","Xatu",null,[e("C","25-47",["day","sky"],B(NATU))]);
[[179,"메리프","Mareep","3-28"],[180,"보송송","Flaaffy","15-37"],[181,"전룡","Ampharos","30-51"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["sky","n025","t5"],B(MAREEP))]));
add(182,"아르코","Bellossom",null,[e("C","35-49",["day","sky"],B(FLOWER)),e("C","35-49",["day","sky"],B(JUNGLE))]);
add(182,"아르코","Bellossom","발렌시아",[e("C","35-49",["day","sky"],B(SAVANNA))]);
add(183,"마릴","Marill",null,[e("C","14-25",["sky"],B(["River","Warm River"])),e("C","14-25",["surf","sky"],B(RIVERS))]);
add(184,"마릴리","Azumarill",null,[e("U","18-42",["sky"],B(["River","Warm River"])),e("U","18-42",["surf","sky"],B(RIVERS))]);
add(185,"꼬지모","Sudowoodo",null,[e("U","16-41",["clear","sky"],B(FOREST_G))]);
add(186,"왕구리","Politoed",null,[e("C","34-50",["rain","sky"],B(SWAMP)),e("C","34-50",["sub","seeSky","lily"],B(SWAMP)),e("C","34-50",["rain","sky","water"],B(POLI)),e("C","34-50",["sub","seeSky"],B(POLI)),e("C","34-50",["dim"],B(LUSHC)),e("C","34-50",["sub","dim"],B(LUSHC)),e("C","34-50",["sub","indoor","sky","lily"],B(SWAMP)),e("C","34-50",["sub","indoor","sky"],B(POLI)),e("C","34-50",["dim","shipY"],S(LSC)),e("C","34-50",["sub","dim","shipY"],S(LSC))]);
add(187,"통통코","Hoppip",null,[e("C","1-25",["clear","sky","n025"],B(HOPPIP))]);
add(188,"두코","Skiploom",null,[e("C","18-34",["clear","sky","n025"],B(HOPPIP))]);
add(189,"솜솜코","Jumpluff",null,[e("C","27-46",["sky","n025"],B(HOPPIP))]);
add(190,"에이팜","Aipom",null,[e("C","11-36",["sky"],B(JUNGLE)),e("C","11-36",["dim","shipY"],S(LSC))]);
add(191,"해너츠","Sunkern",null,[e("C","1-18",["sky","n025","sunflower"],B(["Sunflower Plains"])),e("C","1-18",["sky","n025","sunflower"],OW())]);
add(192,"해루미","Sunflora",null,[e("C","13-43",["sky","n025","sunflower"],B(["Sunflower Plains"])),e("C","13-43",["sky","n025","sunflower"],OW())]);
add(193,"왕자리","Yanma",null,[e("U","14-39",["surf","clear","day","sky"],B(["River","Swamp","Mangrove Swamp","Orchid Swamp"])),e("U","14-39",["surf","dim"],B(LUSHC)),e("U","14-39",["surf","dim","shipY"],S(LSC))]);
add(194,"우파","Wooper",null,[e("C","1-21",["dim"],B(LUSHC)),e("C","1-21",["sub","dim"],B(LUSHC)),e("U","1-21",["dim","maxY62","water"],OW(["무성한 계열"])),e("U","1-21",["sub","dim","maxY62"],OW(["무성한 계열"])),e("C","1-21",["rain","sky"],B(SW3B)),e("C","1-21",["sub","seeSky"],B(SW3B)),e("C","1-21",["sub","indoor","sky"],B(SW3B)),e("C","1-21",["dim","shipY"],S(LSC)),e("C","1-21",["sub","dim","shipY"],S(LSC))]);
add(194,"우파","Wooper","팔데아",[e("C","1-21",["sky"],B(PWOOP)),e("C","1-21",["sub","seeSky"],B(PWOOP)),e("U","1-21",["sky","water"],B(SAVANNA)),e("U","1-21",["sub","seeSky"],B(SAVANNA)),e("C","1-21",["sub","indoor","sky"],B(PWOOP)),e("U","1-21",["sub","indoor","sky"],B(SAVANNA))]);
add(195,"누오","Quagsire",null,[e("C","20-43",["dim"],B(LUSHC)),e("C","20-43",["sub","dim"],B(LUSHC)),e("U","20-43",["dim","maxY62","water"],OW(["무성한 계열"])),e("U","20-43",["sub","dim","maxY62"],OW(["무성한 계열"])),e("C","20-43",["rain","sky"],B(SW3B)),e("C","20-43",["sub","seeSky"],B(SW3B)),e("C","20-43",["sub","indoor","sky"],B(SW3B)),e("C","20-43",["dim","shipY"],S(LSC)),e("C","20-43",["sub","dim","shipY"],S(LSC))]);
add(196,"에브이","Espeon",null,[e("X","28-53",["sky"],B(MOUNT)),e("U","28-53",["day","sky"],OW()),e("U","28-53",["sky"],S(VILALL))]);
add(197,"블래키","Umbreon",null,[e("X","28-53",["night"],B(DARK)),e("R","28-53",["day","sky"],OW()),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor"],S(MANSION))]);
add(198,"니로우","Murkrow",null,[e("C","16-41",["n15"],B(DARK)),e("C","16-41",["night"],B(U_([...SWAMP,...TAIGA])))]);
add(199,"야도킹","Slowking",null,[e("C","37-49",["sky"],B(["Beach","Snowy Beach"]))]);
add(199,"야도킹","Slowking","가라르",[e("C","37-49",["sky","water"],B(["Mushroom Fields"]))]);
add(200,"무우마","Misdreavus",null,[e("C","19-44",["dim"],B(MISD)),e("C","19-44",["indoor","sky0"],B(MISD)),e("C","19-44",["night","sky"],B(SWAMP)),e("C","19-44",[],B(["Warped Forest"])),e("C","19-44",["indoor","shipY"],S(["Shipwreck Cove (All Types)"]))]);
add(201,"안농","Unown","A~Z",[e("C","1-100",[],END),e("C","1-100",["minY48"],S(["Trail Ruins"]))]);
add(201,"안농","Unown","!",[e("C","1-100",[],S(["Dawn Tower (End)"])),e("C","1-100",["maxY48"],S(["Trial Chambers"]))]);
add(201,"안농","Unown","?",[e("C","1-100",[],S(["Dusk Tower (End)"])),e("C","1-100",["maxY48"],S(["Trial Chambers"]))]);
add(202,"마자용","Wobbuffet",null,[e("R","15-41",["dim"],B(RAT))]);
add(203,"키링키","Girafarig",null,[e("C","21-46",["sky","n025"],B(SAVANNA))]);
add(204,"피콘","Pineco",null,[e("C","4-29",["sky"],B(TAIGA))]);
add(205,"쏘콘","Forretress",null,[e("C","31-47",["sky"],B(TAIGA))]);
add(206,"노고치","Dunsparce",null,[e("R","17-42",["indoor"],OW(["Deep Dark"])),e("R","17-42",[],B(LUSHC))]);
add(207,"글라이거","Gligar",null,[e("U","18-43",["night"],B(BADLANDS)),e("C","18-43",[],B(["Basalt Deltas"]))]);
add(208,"강철톤","Steelix",null,[e("U","34-51",["dim"],OW(["Deep Dark"])),e("U","34-51",[],B(["Basalt Deltas"]))]);
add(209,"블루","Snubbull",null,[e("C","5-30",[],SNUB)]);
add(210,"그랑블루","Granbull",null,[e("C","23-45",[],SNUB)]);
add(211,"침바루","Qwilfish",null,[e("U","19-44",["sub","seeSky"],B(HORSEA)),e("C","19-44",["sub","seeSky","maxY62"],{b:WARMO,s:OM}),e("C","19-44",["sub"],B(HORSEA)),e("C","19-44",["sub","sky","maxY62"],{b:WARMO,s:OM}),e("U","19-44",["sub","indoor","subY"],{b:WARMO,s:SSC})]);
add(211,"침바루","Qwilfish","히스이",[e("U","19-44",["sub","seeSky"],B(["Cold Ocean","Deep Cold Ocean"])),e("C","19-44",["sub","seeSky","maxY62"],{b:COLDO,s:OM}),e("U","19-44",["sub","indoor","sky"],B(["Cold Ocean","Deep Cold Ocean"])),e("C","19-44",["sub","indoor","sky","maxY62"],{b:COLDO,s:OM}),e("U","19-44",["sub","indoor","subY"],{b:["Cold Ocean","Deep Cold Ocean"],s:SSC})]);
add(212,"핫삼","Scizor",null,[e("U","45-50",["day","sky"],B(JUNGLE))]);
add(213,"단단지","Shuckle",null,[e("U","16-51",["dim"],B(LUSHC)),e("U","16-51",["dim","shipY"],S(LSC))]);
add(214,"헤라크로스","Heracross",null,[e("R","25-50",["sky","twi5","nosacch"],B(FOREST)),e("U","25-50",["sky","twi5","nosacch"],B(JUNGLE)),e("U","25-50",["sky","twi5","sacch"],OW(["얼음 계열"]))]);
add(215,"포푸니","Sneasel",null,[e("U","18-43",["d025"],B(TAIGA))]);
add(215,"포푸니","Sneasel","히스이",[e("U","18-43",["sky","n025"],B(HSNE))]);
[[216,"깜지곰","Teddiursa","8-33"],[217,"링곰","Ursaring","30-50"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["minY48","nosacch"],B(TEDDY)),e("C",l,["sky","sacch"],OW())]));
add(218,"마그마그","Slugma",null,[e("C","10-36",[],B(["Basalt Deltas","Nether Wastes"])),e("C","1-35",["inlava"],B(VOLC)),e("C","1-25",["inlava"],OW(["화산 계열"]))]);
add(219,"마그카르고","Magcargo",null,[e("C","38-53",[],B(["Basalt Deltas","Nether Wastes"])),e("C","38-43",["inlava"],B(VOLC)),e("C","38-43",["inlava"],OW(["화산 계열"]))]);
add(220,"꾸꾸리","Swinub",null,[e("C","1-25",["sky"],B(SWINUB))]);
add(221,"메꾸리","Piloswine",null,[e("C","33-45",["sky"],B(SWINUB))]);
add(222,"코산호","Corsola",null,[e("C","16-41",["floor","seeSky"],B(["Warm Ocean"])),e("U","16-41",["floor","seeSky","coral"],OW(["따뜻한 바다 계열"]))]);
add(222,"코산호","Corsola","가라르",[e("U","16-41",[],B(["Beach","Snowy Beach"])),e("C","16-41",["deadcoral"],OW()),e("C","16-41",["floor","deadcoral"],OW()),e("U","16-41",["quartz"],NETH),e("U","16-41",[],B(["Soul Sand Valley"]))]);
add(223,"총어","Remoraid",null,[e("C","5-30",["sub","seeSky"],B(OCEAN)),e("C","5-30",["sub","indoor","sky"],B(OCEAN)),e("C","5-30",["sub","indoor","subY"],S(SSC))]);
add(224,"대포무노","Octillery",null,[e("C","25-48",["floor","seeSky"],B(OCEAN)),e("C","25-48",["floor","indoor","subY"],S(SSC))]);
add(225,"딜리버드","Delibird",null,[e("U","8-33",["n025"],B(["Frozen Peaks","Jagged Peaks","Snowy Slopes","Stony Peaks","Rocky Mountains"]))]);
add(226,"만타인","Mantine",null,[e("U","30-49",["sub","seeSky","minY48"],B(HORSEA)),e("U","30-49",["sub","indoor","sky","minY48"],B(HORSEA))]);
add(227,"무장조","Skarmory",null,[e("R","22-47",["day","sky"],B([...BADLANDS,...DESERT]))]);
add(228,"델빌","Houndour",null,[e("U","8-33",["sky","n15"],B(BADLANDS)),e("C","8-33",[],NETH),e("U","18-38",["night"],S(["Ruined Portal"]))]);
add(229,"헬가","Houndoom",null,[e("U","24-50",["sky","n15"],B(BADLANDS)),e("C","24-50",[],NETH),e("U","34-60",["night"],S(["Ruined Portal"]))]);
add(230,"킹드라","Kingdra",null,[e("C","39-54",["sub","seeSky"],B(HORSEA)),e("C","39-54",["sub","indoor","sky"],B(HORSEA)),e("C","39-54",["sub","indoor","subY"],S(SSC))]);
add(231,"코코리","Phanpy",null,[e("C","8-33",["n025"],B(BADLANDS)),e("C","8-33",["n025"],B(SAVANNA))]);
add(232,"코리갑","Donphan",null,[e("C","25-50",["sky","n025"],B(BADLANDS)),e("C","25-50",["sky","n025"],B(SAVANNA))]);
add(233,"폴리곤2","Porygon2",null,[e("U","35-52",[],END)]);
add(234,"노라키","Stantler",null,[e("C","22-47",["sky","n025"],B([...AVULPIX,"Ice Spikes","Snowy Plains","Snowy Badlands"]))]);
add(235,"루브도","Smeargle",null,[e("R","1-25",["sky","n025"],S(VILALL)),e("C","10-35",["indoor","wool"],S(MANSION))]);
add(236,"배루키","Tyrogue",null,[e("U","1-21",["sky","n025"],B(MOUNT))]);
add(237,"카포에라","Hitmontop",null,[e("U","20-46",["sky","n025"],B(MOUNT))]);
add(238,"뽀뽀라","Smoochum",null,[e("U","6-31",["sky","n025"],{b:FREEZE,s:["Village (Snowy)"]})]);
add(239,"에레키드","Elekid",null,[e("U","11-36",["sky","t5"],B([...MOUNT,...PLAINS2]))]);
add(240,"마그비","Magby",null,[e("C","11-36",["clear","sky","lava"],B(MOUNT.filter(b=>b!=="Volcanic Crater"))),e("C","11-36",["clear","sky"],B(VOLC)),e("C","11-36",[],B(["Basalt Deltas","Nether Wastes"]))]);
add(241,"밀탱크","Miltank",null,[e("C","24-49",["sky","n025"],B(RAT))]);
add(241,"밀탱크","Miltank","빨간 무시탱크",[e("C","24-49",["sky","n025"],B(["Mushroom Fields"]))]);
add(241,"밀탱크","Miltank","갈색 무시탱크",[e("C","24-49",["sky","n025"],B(["Mushroom Fields"]))]);
add(242,"해피너스","Blissey",null,[e("R","40-54",["sky","n025"],B([...PIDGEY,"Cloud Forest"])),e("R","40-54",["sky","n025"],S(VILALL))]);
add(243,"라이코","Raikou",null,[e("X","60",["storm33"],S(["Burned Tower (Johto)"]))]);
add(244,"앤테이","Entei",null,[e("X","60",["day33"],S(["Burned Tower (Johto)"]))]);
add(245,"스이쿤","Suicune",null,[e("X","60",["rain33"],S(["Burned Tower (Johto)"]))]);
[[246,"애버라스","Larvitar","5-30"],[247,"데기라스","Pupitar","30-54"],[248,"마기라스","Tyranitar","55-70"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("X",l,["sky"],B(LARV)),e("R",l,["dim"],B(GEO))]));
add(249,"루기아","Lugia",null,[e("X","60-70",["special"],S(["Whirl Island (Johto)"]))]);
add(250,"칠색조","Ho-Oh",null,[e("X","60-70",["special"],S(["Bell Tower (Johto)"]))]);
add(251,"세레비","Celebi",null,[e("X","75-80",["special"],S(["Ilex Shrine (Johto)"]))]);
// 출현 시점 안내 (LUMYVERSE 공식 사이트 안내: 칠색조, 루기아, 전설의 세 마리 개는 관동 시리즈를 끝내고 챔피언 그린을 이긴 뒤에만 나옴)
Object.assign(UNLOCK,{243:"관동 시리즈 클리어(챔피언 그린 승리) 후",244:"관동 시리즈 클리어(챔피언 그린 승리) 후",245:"관동 시리즈 클리어(챔피언 그린 승리) 후",249:"관동 시리즈 클리어(챔피언 그린 승리) 후",250:"관동 시리즈 클리어(챔피언 그린 승리) 후"});
