// ---- 8세대 (cobbleverse.wiki/spawns/gen8) ----
const SKWOVET=["Forest","Cherry Grove","Flower Forest","Birch Forest","Dark Forest","Grove","Old Growth Birch Forest","Pale Garden","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yosemite Lowlands","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const ROOKIDEE=["Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Meadow","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Dark Forest","Pale Garden","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Bryce Canyon","Cloud Forest","Ice Marsh","Moonlight Grove","Shield","Siberian Taiga","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const NICKIT=["Forest","Birch Forest","Dark Forest","Grove","Old Growth Birch Forest","Pale Garden","Forested Highlands","Mirage Isles","Temperate Highlands","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yosemite Lowlands","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const WOOLOO=["Meadow","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Yosemite Cliffs","Plains","Sunflower Plains","Brushland","Shrubland","Steppe","Valley Clearing"];
const ROLYCOLY=["Dripstone Caves","Lush Caves","Sulfur Caves","Andesite Caves","Desert Caves","Diorite Caves","Fungal Caves","Granite Caves","Underground Jungle","Deep Caves","Meadow","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater","Volcanic Peaks","Yosemite Cliffs"];
const CRAMORANT=["Beach","Stony Shore","White Cliffs","Mushroom Fields","Mirage Isles"];
const ARROKUDA=["Ocean","Warm Ocean","Lukewarm Ocean","Cold Ocean","Deep Ocean","Deep Cold Ocean","Deep Warm Ocean","Mangrove Swamp","Swamp","Orchid Swamp"];
const SIZZLIPEDE=["Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis","Volcanic Crater","Volcanic Peaks"];
const CLOBBOPUS=["Ocean","Warm Ocean","Lukewarm Ocean","Cold Ocean","Deep Ocean","Deep Cold Ocean","Deep Warm Ocean"];
const SINISTEA=["Village (Plains)","Village (Taiga)","Village (Snowy)"];
const CUFANT=["Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Meadow","Alpine Highlands","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater","Savanna","Savanna Plateau","Brushland","Desert Oasis","Hot Shrubland","Shrubland"];
const DURALUDON=["Frozen Peaks","Jagged Peaks","Snowy Slopes","Stony Peaks","Rocky Mountains","Volcanic Peaks","Savanna Plateau","Blooming Plateau","Meadow","Wooded Badlands","Arid Highlands","Yosemite Cliffs"];

add(810,"흥나숭","Grookey",null,[e("X","5-31",["sky"],B(JUNGLE))]);
add(811,"채키몽","Thwackey",null,[e("X","16-42",["sky"],B(JUNGLE))]);
add(812,"고릴타","Rillaboom",null,[e("X","35-53",["sky"],B(JUNGLE))]);
add(813,"염버니","Scorbunny",null,[e("X","5-31",["sky"],B(RAT))]);
add(814,"래비풋","Raboot",null,[e("X","16-42",["sky"],B(RAT))]);
add(815,"에이스번","Cinderace",null,[e("X","35-53",["sky"],B(RAT))]);
add(816,"울머기","Sobble",null,[e("X","5-31",["sky"],B(SWAMP)),e("X","5-31",["sky","water"],B(JUNGLE)),e("X","5-31",["sub","seeSky"],B(CROAGUNK))]);
add(817,"누겔레온","Drizzile",null,[e("X","16-42",["sky"],B(SWAMP)),e("X","16-42",["sky","water"],B(JUNGLE)),e("X","16-42",["sub","seeSky"],B(CROAGUNK))]);
add(818,"인텔리레온","Inteleon",null,[e("X","35-53",["sky"],B(SWAMP)),e("X","35-53",["sky","water"],B(JUNGLE)),e("X","35-53",["sub","seeSky"],B(CROAGUNK))]);
add(819,"탐리스","Skwovet",null,[e("C","3-23",["sky"],B(SKWOVET))]);
add(820,"요씽리스","Greedent",null,[e("C","24-46",["sky"],B(SKWOVET))]);
add(821,"파라꼬","Rookidee",null,[e("C","1-17",["day","sky"],B(ROOKIDEE))]);
add(822,"파크로우","Corvisquire",null,[e("C","18-37",["day","sky"],B(ROOKIDEE))]);
add(823,"아머까오","Corviknight",null,[e("C","38-56",["day","sky"],B(ROOKIDEE))]);
add(824,"두루지벌레","Blipbug",null,[e("C","2-9",["seeSky"],B(FOREST_G)),e("C","2-9",["seeSky"],B(PLAINS))]);
add(825,"레돔벌레","Dottler",null,[e("U","11-29",["seeSky"],B(FOREST_G)),e("U","12-28",["seeSky"],B(PLAINS))]);
add(826,"이올브","Orbeetle",null,[e("R","32-47",["seeSky"],B(PLAINS)),e("R","32-47",["seeSky"],B(PLAINS))]);
add(827,"훔처우","Nickit",null,[e("C","1-17",["night","sky"],B(NICKIT)),e("U","1-17",["night","sky"],B(PLAINS3))]);
add(828,"폭슬라이","Thievul",null,[e("C","18-46",["night","sky"],B(NICKIT)),e("U","18-46",["night","sky"],B(PLAINS3))]);
add(829,"꼬모카","Gossifleur",null,[e("C","1-20",["clear","sky","n025"],B(FLOWER))]);
add(830,"백솜모카","Eldegoss",null,[e("C","20-46",["clear","sky","n025"],B(FLOWER))]);
add(831,"우르","Wooloo",null,[e("C","2-23",["sky","n025"],B(WOOLOO))]);
add(832,"배우르","Dubwool",null,[e("C","24-49",["sky","n025"],B(WOOLOO))]);
add(833,"깨물부기","Chewtle",null,[e("C","3-21",["sky"],B(SURSKIT)),e("C","3-21",["sub","seeSky"],B(SURSKIT))]);
add(834,"갈가부기","Drednaw",null,[e("C","22-49",["sky"],B(SURSKIT)),e("C","22-49",["sub","seeSky"],B(SURSKIT))]);
add(835,"멍파치","Yamper",null,[e("C","2-24",["sky","t5"],B(EKANS)),e("C","2-24",["sky","t5"],S(VILD))]);
add(836,"펄스멍","Boltund",null,[e("C","25-49",["sky","t5"],B(EKANS)),e("C","25-49",["sky","t5"],S(VILD))]);
add(837,"탄동","Rolycoly",null,[e("C","2-17",["coal"],B(ROLYCOLY)),e("U","2-17",["indoor"],B(ROLYCOLY))]);
add(838,"탄차곤","Carkol",null,[e("C","19-33",["coal"],B(ROLYCOLY)),e("U","19-33",["indoor"],B(ROLYCOLY))]);
add(839,"석탄산","Coalossal",null,[e("R","34-57",["coal"],B(ROLYCOLY)),e("X","34-57",["indoor"],B(ROLYCOLY))]);
add(840,"과사삭벌레","Applin",null,[e("U","1-25",["seeSky"],B(FOREST_ALL))]);
add(841,"애프룡","Flapple",null,[e("R","27-52",["seeSky"],B(FOREST_ALL))]);
add(842,"단지래플","Appletun",null,[e("R","36-50",["seeSky"],B(FOREST_ALL))]);
add(843,"모래뱀","Silicobra",null,[e("C","7-32",["sky"],B(SAND))]);
add(844,"사다이사","Sandaconda",null,[e("C","36-51",["sky"],B(SAND))]);
add(845,"윽우지","Cramorant",null,[e("U","23-48",["sky","n025"],B(CRAMORANT)),e("U","23-48",["surf","day","sky"],B(CRAMORANT))]);
add(846,"찌로꼬치","Arrokuda",null,[e("C","3-25",["sub","seeSky"],B(ARROKUDA)),e("C","3-25",["sub","indoor","sky"],B(ARROKUDA))]);
add(847,"꼬치조","Barraskewda",null,[e("C","26-49",["sub","seeSky"],B(ARROKUDA)),e("C","26-49",["sub","indoor","sky"],B(ARROKUDA))]);
add(848,"일레즌","Toxel",null,[e("U","1-29",["dim","n15"],B(SWAMP)),e("R","1-29",["night","sky"],B(SWAMP))]);
add(849,"스트린더","Toxtricity",null,[e("U","30-50",["dim","n15"],B(SWAMP)),e("R","30-50",["night","sky"],B(SWAMP))]);
add(850,"태우지네","Sizzlipede",null,[e("C","6-27",["sky"],B(SIZZLIPEDE)),e("C","6-27",[],B(["Basalt Deltas","Nether Wastes"]))]);
add(851,"다태우지네","Centiskorch",null,[e("C","28-53",["sky"],B(SIZZLIPEDE)),e("C","28-53",[],B(["Basalt Deltas","Nether Wastes"]))]);
add(852,"때때무노","Clobbopus",null,[e("U","6-31",["sky"],B(SHORE)),e("U","6-31",["floor","seeSky"],B(CLOBBOPUS)),e("U","6-31",["floor","indoor","subY"],S(SSC))]);
add(853,"케오퍼스","Grapploct",null,[e("U","35-48",["sky"],B(SHORE)),e("U","35-48",["floor","seeSky"],B(CLOBBOPUS)),e("U","35-48",["floor","indoor","subY"],S(SSC))]);
add(854,"데인차","Sinistea","위작폼",[e("U","6-31",["night","minY62"],S(SINISTEA)),e("C","6-31",["indoor"],S(MANSION))]);
add(854,"데인차","Sinistea","진작폼",[e("U","6-31",["night","minY62"],S(SINISTEA)),e("C","6-31",["indoor"],S(MANSION))]);
add(855,"포트데스","Polteageist","위작폼",[e("U","26-51",["night","minY62"],S(SINISTEA)),e("C","26-51",["indoor"],S(MANSION))]);
add(855,"포트데스","Polteageist","진작폼",[e("U","26-51",["night","minY62"],S(SINISTEA)),e("C","26-51",["indoor"],S(MANSION))]);
add(856,"몸지브림","Hatenna",null,[e("U","2-30",["sky"],B(MYST)),e("C","8-30",["sky"],S(["Swamp Hut"])),e("C","8-30",["indoor"],S(MANSION))]);
add(857,"손지브림","Hattrem",null,[e("U","32-40",["sky"],B(MYST)),e("C","32-40",["sky"],S(["Swamp Hut"])),e("C","32-40",["indoor"],S(MANSION))]);
add(858,"브리무음","Hatterene",null,[e("U","42-55",["sky"],B(MYST)),e("C","42-55",["sky"],S(["Swamp Hut"])),e("C","42-55",["indoor"],S(MANSION))]);
add(859,"메롱꿍","Impidimp",null,[e("C","2-29",["sky","n15"],B(["Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley","Pale Garden","Deep Dark"])),e("R","2-29",[],B(["Warped Forest"]))]);
add(860,"쏘겨모","Morgrem",null,[e("C","32-41",["sky","n15"],B(MYST)),e("R","32-41",[],B(["Warped Forest"]))]);
add(861,"오롱털","Grimmsnarl",null,[e("C","42-57",["sky","n15"],B(MYST)),e("R","42-57",[],B(["Warped Forest"]))]);
add(862,"가로막구리","Obstagoon",null,[e("C","35-52",["sky","n15"],B(TAIGA))]);
add(863,"나이킹","Perrserker",null,[e("C","28-44",["sky","n15"],B(MEOWG)),e("C","28-44",["sky","n15"],S(["Village (Taiga)","Village (Snowy)"]))]);
add(864,"산호르곤","Cursola",null,[e("U","38-51",[],B(["Beach","Snowy Beach"])),e("C","38-51",["deadcoral"],OW()),e("C","38-51",["floor","deadcoral"],OW()),e("U","38-51",["quartz"],NETH)]);
add(865,"창파나이트","Sirfetch'd",null,[e("R","33-51",["sky","n025","nowater"],B(FOREST_ALL))]);
add(866,"마임꽁꽁","Mr. Rime",null,[e("U","42-52",["sky"],B(SNOWSAND)),e("U","42-52",["sky"],S(["Village (Snowy)"]))]);
add(867,"데스판","Runerigus",null,[e("U","34-53",["night","maxY60"],B(DARK)),e("R","34-63",["night","maxY62"],S(["Ancient City"]))]);
add(868,"마빌크","Milcery",null,[e("C","2-27",["cake"],OW()),e("U","2-27",["sugarcane"],OW()),e("C","2-27",["indoor"],S(["Village (All Types)","Woodland Mansion"]))]);
add(869,"마휘핑","Alcremie",null,[e("C","22-50",["cake"],OW()),e("U","22-50",["sugarcane"],OW()),e("C","22-50",["indoor"],S(["Village (All Types)","Woodland Mansion"]))]);
add(870,"대여르","Falinks",null,[e("U","22-47",["sky","n025"],B(BADLANDS)),e("R","22-47",["maxY75"],S(["Bastion Remnant","Nether Fortress"]))]);
add(871,"찌르성게","Pincurchin",null,[e("U","19-44",["floor","seeSky","kelpsea"],B(["Beach","Snowy Beach","Stony Shore","White Cliffs","Ocean","Warm Ocean","Lukewarm Ocean","Cold Ocean","Frozen Ocean","Deep Ocean","Deep Cold Ocean","Deep Warm Ocean"])),e("U","19-44",["floor","indoor","subY"],S(SSC))]);
add(872,"누니머기","Snom",null,[e("C","15-36",["night","rain15"],B(FREEZE))]);
add(873,"모스노우","Frosmoth",null,[e("U","25-44",["night","rain15"],B(FREEZE))]);
add(874,"돌헨진","Stonjourner",null,[e("R","22-47",["sky"],B(PLAINS)),e("U","22-47",["dusk","sky"],B(PLAINS)),e("C","28-50",["sky","dusk5"],S(["Stonjourner Henge Ruins"]))]);
add(875,"빙큐보","Eiscue",null,[e("C","22-47",["sky"],B(SEEL)),e("C","22-47",["surf","sky"],B(SEEL))]);
add(876,"에써르","Indeedee",null,[e("R","35-57",["seeSky"],B(MYST)),e("C","23-48",["indoor"],S(MANSION))]);
add(877,"모르페코","Morpeko",null,[e("U","19-44",["sky","t5","berries"],B(ROWLET))]);
add(878,"끼리동","Cufant",null,[e("U","8-33",["sky","n025"],B(CUFANT))]);
add(879,"대왕끼리동","Copperajah",null,[e("U","34-50",["sky","n025"],B(CUFANT))]);
add(884,"두랄루돈","Duraludon",null,[e("R","27-54",["clear","sky"],B(DURALUDON)),e("R","27-54",["dim"],B(DURALUDON))]);
add(885,"드라꼰","Dreepy",null,[e("X","2-47",["sky","dusk5"],B(WINGULL)),e("X","2-47",["surf","dusk","sky"],B(WINGULL))]);
add(886,"드래런치","Drakloak",null,[e("X","50-59",["sky","dusk5"],B(WINGULL)),e("X","50-59",["surf","dusk","sky"],B(WINGULL))]);
add(887,"드래펄트","Dragapult",null,[e("X","60-68",["sky","dusk5"],B(WINGULL)),e("X","60-68",["surf","dusk","sky"],B(WINGULL))]);
add(888,"자시안","Zacian",null,[e("X","65-80",[],B(["Dark Forest","Pale Garden"]))]);
add(889,"자마젠타","Zamazenta",null,[e("X","65-80",[],B(["Dark Forest","Pale Garden"]))]);
add(890,"무한다이노","Eternatus",null,[e("X","70-90",["special"],S(["Eternatus Cocoon (End)"]))]);
add(891,"치고마","Kubfu",null,[e("X","30-50",[],B(VIVILLON))]);
add(892,"우라오스","Urshifu",null,[e("X","60-72",[],B(VIVILLON))]);
add(893,"자루도","Zarude",null,[e("X","70-77",[],B(["Jungle","Sparse Jungle","Bamboo Jungle"]))]);
add(894,"레지에레키","Regieleki",null,[e("X","70-80",["special"],S(["Split Decision Temple (Sinnoh)"]))]);
add(895,"레지드래고","Regidrago",null,[e("X","70-80",["special"],S(["Split Decision Temple (Sinnoh)"]))]);
add(896,"블리자포스","Glastrier",null,[e("X","65-75",["special"],S(["Crown Spire"]))]);
add(897,"레이스포스","Spectrier",null,[e("X","65-75",["special"],S(["Crown Cemetery"]))]);
add(898,"버드렉스","Calyrex",null,[e("X","75-80",["special"],S(["Crown Spire","Crown Cemetery"]))]);
add(899,"신비록","Wyrdeer",null,[e("R","42-53",["sky","n025"],B(["Ice Marsh","Siberian Grove","Snowy Cherry Grove","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Ice Spikes","Snowy Plains","Snowy Badlands"]))]);
add(900,"사마자르","Kleavor",null,[e("R","45-60",["day","sky"],B(["Forest","Cherry Grove","Flower Forest","Birch Forest","Old Growth Birch Forest","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Meadow","Alpine Highlands","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater"]))]);
add(901,"다투곰","Ursaluna",null,[e("C","45-58",["minY48","nosacch"],B(ROWLET)),e("C","45-58",["sky","sacch"],OW())]);
add(901,"다투곰","Ursaluna","붉은달",[e("R","55-68",["night"],B(["Dark Forest","Pale Garden"]))]);
add(902,"대쓰여너","Basculegion",null,[e("C","41-53",["sub","seeSky","moon04"],B(BASCULIN)),e("C","41-53",["sub","indoor","moon04","sky"],B(BASCULIN))]);
add(903,"포푸니크","Sneasler",null,[e("U","38-51",["sky","n025"],B(HSNE))]);
add(904,"장침바루","Overqwil",null,[e("U","39-51",["sub","seeSky"],B(["Cold Ocean","Deep Cold Ocean"])),e("C","39-56",["sub","seeSky","maxY62"],S(OM)),e("U","39-51",["sub","indoor","sky"],B(["Cold Ocean","Deep Cold Ocean"])),e("C","39-56",["sub","indoor","sky","maxY62"],S(OM)),e("U","39-51",["sub","indoor","subY"],S(SSC))]);
add(905,"러브로스","Enamorus",null,[e("X","50-60",["rain2"],B(SWAMP))]);
