// ---- 6세대 (COBBLEVERSE 모드팩 1.7.42 데이터팩 COBBLEVERSE-DP-v31 기준) ----
const CHESPIN=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"];
const FENNEKIN=["Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Red Oasis","Sandstone Valley"];
const FROAKIE=["River","Warm River","Mangrove Swamp","Swamp","Orchid Swamp"];
const BUNNELBY=["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Alpha Islands","Alpha Islands Winter","Lavender Forest","Mirage Isles","Sakura Grove","Plains","Sunflower Plains","Shrubland","Brushland","Steppe","Valley Clearing"];
const FLETCHLING=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"];
const SCATTERBUG=["Cherry Grove","Flower Forest","Meadow","Sunflower Plains","Sakura Grove","Sakura Valley","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Plains","Alpine Highlands","Arid Highlands","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes"];
const VIVILLON=["Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs"];
const LITLEO=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"];
const SKIDDO=["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Windswept Spires","Yosemite Cliffs"];
const PANCHAM=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"];
const ESPURR=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland","Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands"];
const INKAY=["Stony Shore","Basalt Cliffs","Granite Cliffs","White Cliffs","Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs"];
const INKAY2=["Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs"];
const BINACLE=["Stony Shore","Beach","Snowy Beach","Basalt Cliffs","Granite Cliffs","White Cliffs"];
const HELIOPTILE=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley","Beach"];
const GOOMY=["Dripstone Caves","Fractured Savanna","Stony Spires","Lush Caves","Fungal Caves","Underground Jungle"];
const NOIBAT=["Deep Dark","Crystal Caves","Deep Caves","Frostfire Caves","Mantle Caves","Tuff Caves"];

add(650,"도치마론","Chespin",null,[e("X","5-31",["sky"],B(CHESPIN))]);
add(651,"도치보구","Quilladin",null,[e("X","16-41",["sky"],B(CHESPIN))]);
add(652,"브리가론","Chesnaught",null,[e("X","36-53",["sky"],B(CHESPIN))]);
add(653,"푸호꼬","Fennekin",null,[e("X","5-31",["sky"],B(FENNEKIN))]);
add(654,"테르나","Braixen",null,[e("X","16-41",["sky"],B(FENNEKIN))]);
add(655,"마폭시","Delphox",null,[e("X","36-53",["sky"],B(FENNEKIN))]);
add(656,"개구마르","Froakie",null,[e("X","5-31",["sky"],B(FROAKIE)),e("X","5-31",["sub","sky"],B(FROAKIE)),e("X","5-31",["sky","water"],B(JUNGLE)),e("X","5-31",["sub","sky"],B(JUNGLE))]);
add(657,"개굴반장","Frogadier",null,[e("X","16-41",["sky"],B(FROAKIE)),e("X","16-41",["sub","sky"],B(FROAKIE)),e("X","16-41",["sky","water"],B(JUNGLE)),e("X","16-41",["sub","sky"],B(JUNGLE))]);
add(658,"개굴닌자","Greninja",null,[e("X","36-53",["sky"],B(FROAKIE)),e("X","36-53",["sub","sky"],B(FROAKIE)),e("X","36-53",["sky","water"],B(JUNGLE)),e("X","36-53",["sub","sky"],B(JUNGLE))]);
add(659,"파르빗","Bunnelby",null,[e("C","1-24",["minY32"],B(BUNNELBY))]);
add(660,"파르토","Diggersby",null,[e("C","20-42",["minY32"],B(BUNNELBY))]);
add(661,"화살꼬빈","Fletchling",null,[e("C","3-28",["sky","day","treetop"],B(FLETCHLING)),e("C","3-28",["treetop"],B(["Crimson Forest"]))]);
add(662,"불화살빈","Fletchinder",null,[e("C","17-38",["sky","day","treetop"],B(FLETCHLING)),e("C","17-38",["treetop"],B(["Crimson Forest"]))]);
add(663,"파이어로","Talonflame",null,[e("C","35-50",["sky","day","treetop"],B(FLETCHLING)),e("C","35-50",["treetop"],B(["Crimson Forest"]))]);
add(664,"분이벌레","Scatterbug",null,[e("C","1-20",["sky","leaves"],B(SCATTERBUG))]);
add(665,"분떠도리","Spewpa",null,[e("C","9-21",["sky","leaves"],B(SCATTERBUG))]);
add(666,"비비용","Vivillon","황야의 모양",[e("C","12-41",["sky","day","flowers"],B(["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa"]))]);
add(666,"비비용","Vivillon","팬시한 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Cherry Grove","Sakura Grove","Sakura Valley"]))]);
add(666,"비비용","Vivillon","오션의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Stony Shore","Beach","Snowy Beach","Basalt Cliffs","Granite Cliffs","White Cliffs","Warm Ocean"]))]);
add(666,"비비용","Vivillon","사진의 모양",[e("C","12-41",["sky","day","flowers"],B(["Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley"]))]);
add(666,"비비용","Vivillon","화원의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Flower Forest","Meadow","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley"]))]);
add(666,"비비용","Vivillon","정원의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Forest","Birch Forest","Old Growth Birch Forest","Alpha Islands","Alpha Islands Winter"]))]);
add(666,"비비용","Vivillon","대하의 모양",[e("C","12-41",["sky","day","norain"],B(["River","Frozen River","Warm River","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"]))]);
add(666,"비비용","Vivillon","설국의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(VIVILLON))]);
add(666,"비비용","Vivillon","설원의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Ice Spikes","Frostfire Caves","Frozen Cliffs","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Snowy Plains","Cold Shrubland","Gravel Desert","Rocky Shrubland","Snowy Badlands","Yellowstone"]))]);
add(666,"비비용","Vivillon","정글의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(JUNGLE))]);
add(666,"비비용","Vivillon","스콜의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Highlands","Grove","Windswept Savanna","Forested Highlands","Lush Valley","Moonlight Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Windswept Spires","Yosemite Cliffs"]))]);
add(666,"비비용","Vivillon","군도의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Mushroom Fields","Fungal Caves"]))]);
add(666,"비비용","Vivillon","마린의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Ocean","Cold Ocean","Lukewarm Ocean"]))]);
add(666,"비비용","Vivillon","모던한 모양",[e("C","12-41",["sky","day","norain"],S(VILALL)),e("C","12-41",["sky","day","norain","concrete"],OW())]);
add(666,"비비용","Vivillon","대륙의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Plains","Alpine Highlands","Highlands","Steppe","Valley Clearing"]))]);
add(666,"비비용","Vivillon","사바나의 모양",[e("C","12-41",["sky","day","flowers"],B(["Savanna","Savanna Plateau","Brushland","Fractured Savanna","Hot Shrubland","Savanna Badlands","Shrubland"]))]);
add(666,"비비용","Vivillon","태양의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Sunflower Plains","Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter"]))]);
add(666,"비비용","Vivillon","고아한 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Deep Dark"]))]);
add(666,"비비용","Vivillon","빙설의 모양",[e("C","12-41",["sky","day","norain","flowers"],B(["Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Shield","Siberian Taiga","Yellowstone"]))]);
add(667,"레오꼬","Litleo",null,[e("C","1-35",["seeSky"],B(LITLEO))]);
add(668,"화염레오","Pyroar",null,[e("U","37-65",["seeSky"],B(LITLEO))]);
add(669,"플라베베","Flabébé","빨간꽃",[e("C","5-30",["sky","redfl","n025"],OW())]);
add(669,"플라베베","Flabébé","노란꽃",[e("C","5-30",["sky","yellowfl","n025"],OW())]);
add(669,"플라베베","Flabébé","오렌지색꽃",[e("C","5-30",["sky","orangefl","n025"],OW())]);
add(669,"플라베베","Flabébé","파란꽃",[e("C","5-30",["sky","bluefl","n025"],OW())]);
add(669,"플라베베","Flabébé","하얀꽃",[e("C","5-30",["sky","whitefl","n025"],OW())]);
add(669,"플라베베","Flabébé","분홍꽃",[e("C","5-30",["sky","pinkfl","n025"],OW())]);
add(670,"플라엣테","Floette","빨간꽃",[e("C","19-37",["sky","redfl","n025"],OW())]);
add(670,"플라엣테","Floette","노란꽃",[e("C","19-37",["sky","yellowfl","n025"],OW())]);
add(670,"플라엣테","Floette","오렌지색꽃",[e("C","19-37",["sky","orangefl","n025"],OW())]);
add(670,"플라엣테","Floette","파란꽃",[e("C","19-37",["sky","bluefl","n025"],OW())]);
add(670,"플라엣테","Floette","하얀꽃",[e("C","19-37",["sky","whitefl","n025"],OW())]);
add(670,"플라엣테","Floette","분홍꽃",[e("C","19-37",["sky","pinkfl","n025"],OW())]);
add(670,"플라엣테","Floette","영원의 꽃",[e("X","50-65",["night","redbluefl"],OW())]);
add(671,"플라제스","Florges","빨간꽃",[e("C","32-55",["sky","redfl","n025"],OW())]);
add(671,"플라제스","Florges","노란꽃",[e("C","32-55",["sky","yellowfl","n025"],OW())]);
add(671,"플라제스","Florges","오렌지색꽃",[e("C","32-55",["sky","orangefl","n025"],OW())]);
add(671,"플라제스","Florges","파란꽃",[e("C","32-55",["sky","bluefl","n025"],OW())]);
add(671,"플라제스","Florges","하얀꽃",[e("C","32-55",["sky","whitefl","n025"],OW())]);
add(671,"플라제스","Florges","분홍꽃",[e("C","32-55",["sky","pinkfl","n025"],OW())]);
add(672,"메이클","Skiddo",null,[e("C","10-35",["sky","n025"],B(SKIDDO))]);
add(673,"고고트","Gogoat",null,[e("C","32-53",["sky","n025"],B(SKIDDO))]);
add(674,"판짱","Pancham",null,[e("C","5-31",[],B(JUNGLE)),e("R","20-30",[],B(PANCHAM))]);
add(675,"부란다","Pangoro",null,[e("U","32-68",[],B(JUNGLE)),e("R","38-56",[],B(PANCHAM))]);
add(676,"트리미앙","Furfrou",null,[e("U","22-47",["sky"],B(FLOWER)),e("C","22-47",["sky"],S(VILALL)),e("C","22-47",["sky","minY62"],S(MANSION))]);
add(677,"냐스퍼","Espurr",null,[e("C","11-36",[],END),e("C","11-36",["sky","norain","n15"],{all:"ow",ex:["건조 계열","얼음 계열"],s:VILALL}),e("C","11-36",["sky","concrete","n15"],B(ESPURR)),e("C","11-36",["sky","n15"],{b:ESPURR,s:VILALL}),e("C","11-36",["indoor","minY62"],S(MANSION))]);
add(678,"냐오닉스","Meowstic",null,[e("C","25-47",[],END),e("C","25-47",["sky","norain","n15"],{all:"ow",ex:["건조 계열","얼음 계열"],s:VILALL}),e("C","25-47",["sky","concrete","n15"],B(ESPURR)),e("C","25-47",["sky","n15"],{b:ESPURR,s:VILALL}),e("C","25-47",["indoor","minY62"],S(MANSION))]);
add(679,"단칼빙","Honedge",null,[e("U","8-33",[],NETH),e("U","8-33",["sky"],S(["Cobblemon Ruins (All Types)"])),e("U","8-33",["dim","maxY62"],S(["Stronghold"]))]);
add(680,"쌍검킬","Doublade",null,[e("U","35-45",[],NETH),e("U","35-45",["sky"],S(["Cobblemon Ruins (All Types)"])),e("U","35-45",["dim","maxY62"],S(["Stronghold"]))]);
add(681,"킬가르도","Aegislash",null,[e("U","40-50",[],S(["Bastion Remnant","Nether Fortress"])),e("U","40-50",["sky"],S(["Cobblemon Ruins (All Types)"])),e("U","40-50",["dim","maxY62"],S(["Stronghold"]))]);
add(682,"슈쁘","Spritzee",null,[e("C","14-34",[],B(FLOWER)),e("C","17-35",[],B(PANCHAM))]);
add(683,"프레프티르","Aromatisse",null,[e("U","35-47",[],B(FLOWER)),e("U","36-48",[],B(PANCHAM))]);
add(684,"나룸퍼프","Swirlix",null,[e("C","10-35",["sky"],B(["Cherry Grove","Flower Forest"]))]);
add(685,"나루림","Slurpuff",null,[e("R","35-45",["sky"],B(["Cherry Grove","Flower Forest"]))]);
add(686,"오케이징","Inkay",null,[e("U","4-29",["sky"],B(INKAY)),e("U","4-29",[],END),e("U","4-29",["sub","seeSky"],B(INKAY2)),e("U","4-29",["sub","indoor","sky"],B(INKAY2)),e("U","4-29",["sub","indoor","subY"],S(SSC))]);
add(687,"칼라마네로","Malamar",null,[e("U","30-48",["sky"],B(INKAY)),e("U","30-48",[],END),e("U","30-48",["sub","seeSky"],B(INKAY2)),e("U","30-48",["sub","indoor","sky"],B(INKAY2)),e("U","30-48",["sub","indoor","subY"],S(SSC))]);
add(688,"거북손손","Binacle",null,[e("C","6-31",[],B(BINACLE)),e("U","6-31",["floor"],B(INKAY2))]);
add(689,"거북손데스","Barbaracle",null,[e("C","39-50",[],B(BINACLE)),e("U","39-50",["floor"],B(INKAY2))]);
add(690,"수레기","Skrelp",null,[e("C","7-32",["sub","seeSky","kelp"],B(INKAY2)),e("C","7-32",["sub","indoor","sky","kelp"],B(INKAY2)),e("C","7-32",["sub","indoor","subY"],S(SSC))]);
add(691,"드래캄","Dragalge",null,[e("C","48-49",["sub","seeSky","kelp"],B(INKAY2)),e("C","48-49",["sub","indoor","sky","kelp"],B(INKAY2)),e("C","48-49",["sub","indoor","subY"],S(SSC))]);
add(692,"완철포","Clauncher",null,[e("C","8-33",["floor"],B(INKAY2))]);
add(693,"블로스터","Clawitzer",null,[e("C","37-50",["sub","seeSky"],B(INKAY2)),e("C","37-50",["sub","indoor","sky"],B(INKAY2))]);
add(694,"목도리키텔","Helioptile",null,[e("U","8-35",["seeSky","day","norain"],B(HELIOPTILE))]);
add(695,"일레도리자드","Heliolisk",null,[e("R","37-58",["seeSky","day","norain"],B(HELIOPTILE))]);
add(696,"티고라스","Tyrunt",null,[e("X","11-36",["dim"],B(LUSHC))]);
add(697,"견고라스","Tyrantrum",null,[e("X","39-52",["dim"],B(LUSHC))]);
add(698,"아마루스","Amaura",null,[e("X","11-36",["dim"],B(LUSHC))]);
add(699,"아마루르가","Aurorus",null,[e("X","39-52",["dim"],B(LUSHC))]);
add(700,"님피아","Sylveon",null,[e("X","28-53",["sky"],B(["Cherry Grove","Flower Forest","Meadow","Sunflower Plains","Sakura Grove","Sakura Valley","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley"])),e("U","28-53",["sky","concrete"],OW()),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor","minY62"],S(MANSION))]);
add(701,"루차불","Hawlucha",null,[e("C","25-50",["minY62","n025"],S(["Jungle Pyramid"])),e("U","25-50",["sky","n025"],B(["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"]))]);
add(702,"데덴네","Dedenne",null,[e("U","18-43",["sky","t5"],B(["Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland","Alpine Highlands","Cold Shrubland","Rocky Shrubland"]))]);
add(703,"멜리시","Carbink",null,[e("C","25-50",["dim","diamond"],OW(["?#cobblemon:is_deep_dark"])),e("U","25-50",[],B(["Nether Wastes"]))]);
add(704,"미끄메라","Goomy",null,[e("R","5-30",["sky","rain"],B(SWAMP)),e("X","5-30",["sky","norain","noslime"],B(SWAMP)),e("R","5-30",["sky","norain","slime"],B(SWAMP))]);
add(704,"미끄메라","Goomy","히스이 계열",[e("R","5-30",["dim"],B(GOOMY)),e("X","5-30",["dim","water","noslime"],OW(["점적석 계열","무성한 계열"])),e("R","5-30",["dim","slime"],OW(["점적석 계열","무성한 계열"]))]);
add(705,"미끄네일","Sliggoo",null,[e("R","40-45",["sky","rain"],B(SWAMP)),e("X","40-45",["sky","norain","noslime"],B(SWAMP)),e("R","40-45",["sky","norain","slime"],B(SWAMP))]);
add(705,"미끄네일","Sliggoo","히스이",[e("R","40-45",["dim"],B(GOOMY)),e("X","40-45",["dim","water","noslime"],OW(["점적석 계열","무성한 계열"])),e("R","40-45",["dim","slime"],OW(["점적석 계열","무성한 계열"]))]);
add(706,"미끄래곤","Goodra",null,[e("R","50-60",["sky","rain"],B(SWAMP)),e("X","50-60",["sky","norain","noslime"],B(SWAMP)),e("R","50-60",["sky","norain","slime"],B(SWAMP))]);
add(706,"미끄래곤","Goodra","히스이",[e("R","50-60",["dim"],B(GOOMY)),e("X","50-60",["dim","water","noslime"],OW(["점적석 계열","무성한 계열"])),e("R","50-60",["dim","slime"],OW(["점적석 계열","무성한 계열"]))]);
add(707,"클레피","Klefki",null,[e("U","22-47",[],OW()),e("U","22-47",[],S(VILALL)),e("C","22-47",["indoor","minY62"],S(MANSION))]);
add(708,"나목령","Phantump",null,[e("C","6-31",["sky","night"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"])),e("C","6-31",["sky","night"],B(["Dark Forest","Deep Dark"]))]);
add(709,"대로트","Trevenant",null,[e("C","26-47",["sky","night"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands","Deep Dark"])),e("C","26-47",["sky","night"],B(["Pale Garden"]))]);
add(710,"호바귀","Pumpkaboo",null,[e("C","9-34",["night","pumpkin"],OW())]);
add(711,"펌킨인","Gourgeist",null,[e("C","29-49",["night","pumpkin"],OW())]);
add(712,"꽁어름","Bergmite",null,[e("C","5-30",["sky"],B(VIVILLON)),e("C","5-30",["surf","sky"],B(VIVILLON))]);
add(712,"꽁어름","Bergmite","히스이 계열",[e("U","7-32",["sky"],B(["Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands"]))]);
add(713,"크레베이스","Avalugg",null,[e("C","37-51",["sky"],B(VIVILLON)),e("C","37-51",["surf","sky"],B(VIVILLON))]);
add(713,"크레베이스","Avalugg","히스이",[e("U","30-60",[],B(["Frozen Peaks","Snowy Slopes"])),e("R","30-60",[],B(["Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest"]))]);
add(714,"음뱃","Noibat",null,[e("U","1-25",["dim"],B(NOIBAT)),e("R","1-25",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(715,"음번","Noivern",null,[e("U","48-54",["dim"],B(NOIBAT)),e("R","48-54",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(716,"제르네아스","Xerneas",null,[e("X","65-75",["day"],B(FLOWER))]);
add(717,"이벨타르","Yveltal",null,[e("X","65-75",["night"],B(["Dark Forest","Deep Dark"]))]);
add(718,"지가르데","Zygarde",null,[e("X","1-10",["indoor"],B(["Dripstone Caves","Lush Caves"]))]);
add(719,"디안시","Diancie",null,[e("X","45-68",[],B(["Lush Caves"]))]);
add(720,"후파","Hoopa",null,[e("X","65-75",[],END)]);
add(721,"볼케니온","Volcanion",null,[e("X","70",["seeSky"],B(["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"]))]);
