// ---- 6세대 (cobbleverse.wiki/spawns/gen6) ----
const FROAKIE=["River","Swamp","Mangrove Swamp","Orchid Swamp","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"];
const BUNNELBY=["Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Meadow","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater","Plains","Sunflower Plains","Cherry Grove","Forest","Flower Forest","Birch Forest","Dark Forest","Grove","Old Growth Birch Forest","Pale Garden","Brushland","Shrubland","Steppe","Valley Clearing","Lavender Forest","Mirage Isles","Sakura Grove"];
const SCATTERBUG=["Cherry Grove","Flower Forest","Meadow","Sunflower Plains","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Sakura Grove","Sakura Valley","Plains","Brushland","Shrubland","Steppe","Alpine Highlands","Arid Highlands","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Hot Shrubland","Red Oasis","Savanna Slopes"];
const VIVILLON=["Cherry Grove","Sakura Grove","Sakura Valley"];
const LITLEO=["Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Desert Oasis","Hot Shrubland","Savanna Slopes","Shrubland","Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle"];
const INKAY=["Stony Shore","White Cliffs","Ocean","Warm Ocean","Lukewarm Ocean","Cold Ocean","Frozen Ocean","Deep Ocean","Deep Cold Ocean","Deep Warm Ocean"];
const GOOMY=["Dripstone Caves","Lush Caves","Fungal Caves","Underground Jungle"];

add(650,"도치마론","Chespin",null,[e("X","5-31",["sky"],B(FOREST_G))]);
add(651,"도치보구","Quilladin",null,[e("X","16-41",["sky"],B(FOREST_G))]);
add(652,"브리가론","Chesnaught",null,[e("X","36-53",["sky"],B(FOREST_G))]);
add(653,"푸호꼬","Fennekin",null,[e("X","5-31",["sky"],B(SAND))]);
add(654,"테르나","Braixen",null,[e("X","16-41",["sky"],B(SAND))]);
add(655,"마폭시","Delphox",null,[e("X","36-53",["sky"],B(SAND))]);
add(656,"개구마르","Froakie",null,[e("X","5-31",["sky"],B(SURSKIT)),e("X","5-31",["sub","sky"],B(FROAKIE)),e("X","5-31",["sky","water"],B(JUNGLE))]);
add(657,"개굴반장","Frogadier",null,[e("X","16-41",["sky"],B(SURSKIT)),e("X","16-41",["sub","sky"],B(FROAKIE)),e("X","16-41",["sky","water"],B(JUNGLE))]);
add(658,"개굴닌자","Greninja",null,[e("X","36-53",["sky"],B(SURSKIT)),e("X","36-53",["sub","sky"],B(FROAKIE)),e("X","36-53",["sky","water"],B(JUNGLE))]);
add(659,"파르빗","Bunnelby",null,[e("C","1-19",["minY32"],B(BUNNELBY))]);
add(660,"파르토","Diggersby",null,[e("C","20-42",["minY32"],B(BUNNELBY))]);
add(661,"화살꼬빈","Fletchling",null,[e("C","3-16",["day","sky"],B(FOREST_ALL)),e("C","3-16",[],B(["Crimson Forest"]))]);
add(662,"불화살빈","Fletchinder",null,[e("C","17-34",["day","sky"],B(FOREST_ALL)),e("C","17-34",[],B(["Crimson Forest"]))]);
add(663,"파이어로","Talonflame",null,[e("C","35-50",["day","sky"],B(FOREST_ALL)),e("C","35-50",[],B(["Crimson Forest"]))]);
add(664,"분이벌레","Scatterbug",null,[e("C","1-10",["sky"],B(SCATTERBUG))]);
add(665,"분떠도리","Spewpa",null,[e("C","9-12",["sky"],B(SCATTERBUG))]);
add(666,"비비용","Vivillon","군도의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(["Mushroom Fields","Fungal Caves"]))]);
add(666,"비비용","Vivillon","대륙의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(["Plains","Steppe","Alpine Highlands","Valley Clearing"]))]);
add(666,"비비용","Vivillon","고아한 모양",[e("C","12-41",["clear","day","sky","flowers"],B(["Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Pale Garden","Deep Dark"]))]);
add(666,"비비용","Vivillon","팬시한 모양",[e("C","12-41",["clear","day","sky","flowers"],B(VIVILLON))]);
add(666,"비비용","Vivillon","정원의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(["Forest","Birch Forest","Grove","Old Growth Birch Forest"]))]);
add(666,"비비용","Vivillon","황야의 모양",[e("C","12-41",["day","sky","flowers"],B(BADLANDS))]);
add(666,"비비용","Vivillon","빙설의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(["Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Bryce Canyon","Cloud Forest","Ice Marsh","Moonlight Grove","Shield","Siberian Taiga","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands"]))]);
add(666,"비비용","Vivillon","정글의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(JUNGLE))]);
add(666,"비비용","Vivillon","마린의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(["Ocean","Lukewarm Ocean","Cold Ocean","Deep Ocean","Deep Cold Ocean","Deep Warm Ocean"]))]);
add(666,"비비용","Vivillon","화원의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(["Flower Forest","Meadow","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley"]))]);
add(666,"비비용","Vivillon","모던한 모양",[e("C","12-41",["clear","day","sky"],S(VILALL))]);
add(666,"비비용","Vivillon","스콜의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(["Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Alpine Highlands","Forested Highlands","Snowy Slopes","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Temperate Highlands","Yosemite Lowlands","Caldera","Yosemite Cliffs"]))]);
add(666,"비비용","Vivillon","오션의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(["Beach","Snowy Beach","Stony Shore","White Cliffs","Warm Ocean"]))]);
add(666,"비비용","Vivillon","설국의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(SEEL))]);
add(666,"비비용","Vivillon","대하의 모양",[e("C","12-41",["clear","day","sky"],B(BASCULIN))]);
add(666,"비비용","Vivillon","사진의 모양",[e("C","12-41",["day","sky","flowers"],B(DESERT))]);
add(666,"비비용","Vivillon","사바나의 모양",[e("C","12-41",["day","sky","flowers"],B(["Savanna","Savanna Plateau","Brushland","Hot Shrubland","Shrubland"]))]);
add(666,"비비용","Vivillon","태양의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(["Sunflower Plains"]))]);
add(666,"비비용","Vivillon","설원의 모양",[e("C","12-41",["clear","day","sky","flowers"],B(["Frozen Peaks","Ice Spikes","Glacial Chasm","Siberian Taiga","Siberian Grove","Ice Marsh","Snowy Cherry Grove","Snowy Shield","Cold Shrubland","Wintry Forest","Wintry Lowlands","Snowy Plains","Snowy Badlands"]))]);
add(667,"레오꼬","Litleo",null,[e("C","1-35",["seeSky"],B(LITLEO))]);
add(668,"화염레오","Pyroar",null,[e("U","37-65",["seeSky"],B(LITLEO))]);
add(669,"플라베베","Flabébé","빨간꽃",[e("C","5-30",["sky","n025","redfl"],OW())]);
add(669,"플라베베","Flabébé","노란꽃",[e("C","5-30",["sky","n025","yellowfl"],OW())]);
add(669,"플라베베","Flabébé","오렌지색꽃",[e("C","5-30",["sky","n025","orangefl"],OW())]);
add(669,"플라베베","Flabébé","파란꽃",[e("C","5-30",["sky","n025","bluefl"],OW())]);
add(669,"플라베베","Flabébé","하얀꽃",[e("C","5-30",["sky","n025","whitefl"],OW())]);
add(669,"플라베베","Flabébé","분홍꽃",[e("C","5-30",["sky","n025","pinkfl"],OW())]);
add(670,"플라엣테","Floette","빨간꽃",[e("C","19-37",["sky","n025","redfl"],OW())]);
add(670,"플라엣테","Floette","노란꽃",[e("C","19-37",["sky","n025","yellowfl"],OW())]);
add(670,"플라엣테","Floette","오렌지색꽃",[e("C","19-37",["sky","n025","orangefl"],OW())]);
add(670,"플라엣테","Floette","파란꽃",[e("C","19-37",["sky","n025","bluefl"],OW())]);
add(670,"플라엣테","Floette","하얀꽃",[e("C","19-37",["sky","n025","whitefl"],OW())]);
add(670,"플라엣테","Floette","분홍꽃",[e("C","19-37",["sky","n025","pinkfl"],OW())]);
add(670,"플라엣테","Floette","영원의 꽃",[e("X","50-65",["night","eternalfl"],B(["Pale Garden"]))]);
add(671,"플라제스","Florges","빨간꽃",[e("C","32-55",["sky","n025","redfl"],OW())]);
add(671,"플라제스","Florges","노란꽃",[e("C","32-55",["sky","n025","yellowfl"],OW())]);
add(671,"플라제스","Florges","오렌지색꽃",[e("C","32-55",["sky","n025","orangefl"],OW())]);
add(671,"플라제스","Florges","파란꽃",[e("C","32-55",["sky","n025","bluefl"],OW())]);
add(671,"플라제스","Florges","하얀꽃",[e("C","32-55",["sky","n025","whitefl"],OW())]);
add(671,"플라제스","Florges","분홍꽃",[e("C","32-55",["sky","n025","pinkfl"],OW())]);
add(672,"메이클","Skiddo",null,[e("C","10-35",["sky","n025"],B(PIDOVE))]);
add(673,"고고트","Gogoat",null,[e("C","32-53",["sky","n025"],B(PIDOVE))]);
add(674,"판짱","Pancham",null,[e("C","5-31",[],B(JUNGLE)),e("R","8-30",[],B(FOREST_ALL))]);
add(675,"부란다","Pangoro",null,[e("U","32-58",[],B(JUNGLE)),e("R","38-56",[],B(FOREST_ALL))]);
add(676,"트리미앙","Furfrou",null,[e("U","22-47",["sky"],B(FLOWER)),e("C","22-47",["sky"],S(VILALL)),e("C","22-47",["sky"],S(MANSION))]);
add(677,"냐스퍼","Espurr",null,[e("C","11-36",[],END),e("C","11-36",["clear","sky","n15"],S(["Village (Plains)","Village (Taiga)"])),e("C","11-36",["indoor"],S(MANSION))]);
add(678,"냐오닉스","Meowstic",null,[e("C","25-47",[],END),e("C","25-47",["clear","sky","n15"],S(["Village (Plains)","Village (Taiga)"])),e("C","25-47",["indoor"],S(MANSION))]);
add(679,"단칼빙","Honedge",null,[e("U","8-33",["sky"],S(["Cobblemon Ruins (All Types)"])),e("U","8-33",["dim","maxY62"],S(["Stronghold"]))]);
add(680,"쌍검킬","Doublade",null,[e("U","35-46",["sky"],S(["Cobblemon Ruins (All Types)"])),e("U","35-46",["dim","maxY62"],S(["Stronghold"]))]);
add(681,"킬가르도","Aegislash",null,[e("U","45-60",["sky"],S(["Cobblemon Ruins (All Types)"])),e("U","45-60",["dim","maxY62"],S(["Stronghold"]))]);
add(682,"슈쁘","Spritzee",null,[e("C","14-34",[],B(FLOWER))]);
add(683,"프레프티르","Aromatisse",null,[e("U","35-47",[],B(FLOWER))]);
add(684,"나룸퍼프","Swirlix",null,[e("C","10-35",["sky"],B(VIVILLON)),e("C","10-35",["sky","cake"],S(VILALL))]);
add(685,"나루림","Slurpuff",null,[e("R","35-45",["sky"],B(VIVILLON)),e("R","35-45",["sky","cake"],S(VILALL))]);
add(686,"오케이징","Inkay",null,[e("U","4-29",["sky"],B(INKAY)),e("U","4-29",[],END),e("U","4-29",["sub","seeSky"],B(OCEAN)),e("U","4-29",["sub","indoor","sky"],B(OCEAN)),e("U","4-29",["sub","indoor","subY"],S(SSC))]);
add(687,"칼라마네로","Malamar",null,[e("U","30-48",["sky"],B(INKAY)),e("U","35-57",[],END),e("U","30-48",["sub","seeSky"],B(OCEAN)),e("U","30-48",["sub","indoor","sky"],B(OCEAN)),e("U","30-48",["sub","indoor","subY"],S(SSC))]);
add(688,"거북손손","Binacle",null,[e("C","6-35",[],B(SHORE)),e("U","6-35",["floor"],B(OCEAN))]);
add(689,"거북손데스","Barbaracle",null,[e("C","39-53",[],B(SHORE)),e("U","39-53",["floor"],B(OCEAN))]);
add(690,"수레기","Skrelp",null,[e("C","7-32",["sub","seeSky","kelp"],B(OCEAN)),e("C","7-32",["sub","indoor","sky","kelp"],B(OCEAN)),e("C","7-32",["sub","indoor","subY"],S(SSC))]);
add(691,"드래캄","Dragalge",null,[e("C","48-59",["sub","seeSky","kelp"],B(OCEAN)),e("C","48-59",["sub","indoor","sky","kelp"],B(OCEAN)),e("C","48-59",["sub","indoor","subY"],S(SSC))]);
add(692,"완철포","Clauncher",null,[e("C","8-33",["floor","seeSky"],B(OCEAN))]);
add(693,"블로스터","Clawitzer",null,[e("C","37-50",["sub","seeSky"],B(OCEAN)),e("C","37-50",["sub","indoor","sky"],B(OCEAN))]);
add(694,"목도리키텔","Helioptile",null,[e("U","8-35",["clear","seeSky","day"],B(BURMY))]);
add(695,"일레도리자드","Heliolisk",null,[e("R","37-58",["clear","seeSky","day"],B(BURMY))]);
add(696,"티고라스","Tyrunt",null,[e("X","11-36",["dim"],B(LUSHC))]);
add(697,"견고라스","Tyrantrum",null,[e("X","39-62",["dim"],B(LUSHC))]);
add(698,"아마루스","Amaura",null,[e("X","11-36",["dim"],B(LUSHC))]);
add(699,"아마루르가","Aurorus",null,[e("X","39-58",["dim"],B(LUSHC))]);
add(700,"님피아","Sylveon",null,[e("X","28-53",["sky"],B(["Cherry Grove","Flower Forest","Meadow","Sunflower Plains","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Sakura Grove","Sakura Valley","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley"])),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor"],S(MANSION))]);
add(701,"루차불","Hawlucha",null,[e("U","25-50",["sky","n025"],B(JOLTIK)),e("C","25-50",["clear","minY62","n025"],S(["Jungle Pyramid"]))]);
add(702,"데덴네","Dedenne",null,[e("U","18-43",["sky","t5"],B(["Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Hot Shrubland","Red Oasis","Savanna Slopes","Shrubland","Alpine Highlands","Cold Shrubland"]))]);
add(703,"멜리시","Carbink",null,[e("C","25-50",["dim","diamond"],B(["Dripstone Caves","Lush Caves","Sulfur Caves","Andesite Caves","Desert Caves","Diorite Caves","Fungal Caves","Granite Caves","Underground Jungle"])),e("R","25-50",[],B(["Nether Wastes"]))]);
add(704,"미끄메라","Goomy",null,[e("R","5-30",["rain","sky"],B(SWAMP)),e("X","5-30",["clear","sky"],B(SWAMP))]);
add(704,"미끄메라","Goomy","히스이 계열",[e("R","5-30",["dim"],B(GOOMY)),e("R","5-30",["slime","dim"],OW(["점적석 계열","무성한 계열"]))]);
add(705,"미끄네일","Sliggoo",null,[e("R","40-48",["rain","sky"],B(SWAMP)),e("X","40-48",["clear","sky"],B(SWAMP))]);
add(705,"미끄네일","Sliggoo","히스이",[e("R","40-48",["dim"],B(GOOMY)),e("R","40-48",["slime","dim"],OW(["점적석 계열","무성한 계열"]))]);
add(706,"미끄래곤","Goodra",null,[e("R","50-64",["rain","sky"],B(SWAMP)),e("X","50-64",["clear","sky"],B(SWAMP))]);
add(706,"미끄래곤","Goodra","히스이",[e("R","50-64",["dim"],B(GOOMY)),e("R","50-64",["slime","dim"],OW(["점적석 계열","무성한 계열"]))]);
add(707,"클레피","Klefki",null,[e("U","22-47",[],S(VILALL)),e("C","22-47",["indoor"],S(MANSION))]);
add(708,"나목령","Phantump",null,[e("C","6-31",["night","sky"],B(["Forest","Cherry Grove","Flower Forest","Birch Forest","Dark Forest","Grove","Old Growth Birch Forest","Pale Garden","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yosemite Lowlands","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands"])),e("C","6-31",["night","sky"],B(DARK))]);
add(709,"대로트","Trevenant",null,[e("C","26-47",["night","sky"],B(["Forest","Cherry Grove","Flower Forest","Birch Forest","Dark Forest","Grove","Old Growth Birch Forest","Pale Garden","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yosemite Lowlands","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands","Deep Dark"])),e("C","26-47",["night","sky"],B(["Pale Garden"]))]);
add(710,"호바귀","Pumpkaboo",null,[e("C","9-34",["night","pumpkin"],OW())]);
add(711,"펌킨인","Gourgeist",null,[e("C","29-49",["night","pumpkin"],OW())]);
add(712,"꽁어름","Bergmite",null,[e("C","5-35",["sky"],B(SEEL)),e("C","5-35",["surf","sky"],B(SEEL))]);
add(712,"꽁어름","Bergmite","히스이 계열",[e("U","7-37",["sky"],B(SNOWSAND))]);
add(713,"크레베이스","Avalugg",null,[e("C","37-59",["sky"],B(SEEL)),e("C","37-59",["surf","sky"],B(SEEL))]);
add(713,"크레베이스","Avalugg","히스이",[e("R","37-59",["sky"],B(SNOWSAND))]);
add(714,"음뱃","Noibat",null,[e("U","1-45",["dim"],B(["Deep Dark","Deep Caves"])),e("R","1-40",["dim","maxY0"],OW(["Deep Dark"]))]);
add(715,"음번","Noivern",null,[e("U","48-61",["dim"],B(["Deep Dark","Deep Caves"])),e("R","48-61",["dim","maxY0"],OW(["Deep Dark"]))]);
add(716,"제르네아스","Xerneas",null,[e("X","65-75",["day"],B(VIVILLON))]);
add(717,"이벨타르","Yveltal",null,[e("X","65-75",["night"],B(DARK))]);
add(718,"지가르데","Zygarde",null,[e("X","1-10",["indoor"],B(["Dripstone Caves","Lush Caves"]))]);
add(719,"디안시","Diancie",null,[e("X","45-68",["indoor"],B(["Lush Caves"]))]);
add(720,"후파","Hoopa",null,[e("X","55-75",[],END)]);
add(721,"볼케니온","Volcanion",null,[e("X","50-70",["seeSky"],B(VOLC))]);
