// ---- 9세대 (COBBLEVERSE 모드팩 1.7.42 데이터팩 COBBLEVERSE-DP-v31 기준) ----
const SPRIGATITO=["Cherry Grove","Flower Forest","Meadow","Sunflower Plains","Sakura Grove","Sakura Valley","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley"];
const FUECOCO=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa"];
const QUAXLY=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","River","Warm River"];
const LECHONK=["Dark Forest","Fungal Caves","Mirage Isles","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const TAROUNTULA=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Mangrove Swamp","Swamp","Orchid Swamp"];
const NYMBLE=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland"];
const PAWMI=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const TANDEMAUS=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const SMOLIV=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes"];
const NACLI=["Amethyst Canyon","Amethyst Rainforest","Skylands Winter","Yellowstone"];
const WATTREL=["Mushroom Fields","Alpha Islands","Mirage Isles","Warped Mesa","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Skylands Autumn","Skylands Spring","Skylands Summer"];
const WATTREL2=["Stony Shore","Basalt Cliffs","Granite Cliffs","White Cliffs"];
const WATTREL3=["Stony Shore","Basalt Cliffs","Granite Cliffs","White Cliffs","Mushroom Fields","Alpha Islands","Mirage Isles","Warped Mesa","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Skylands Autumn","Skylands Spring","Skylands Summer"];
const BRAMBLIN=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley"];
const TOEDSCOOL=["Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland"];
const CAPSAKID=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland"];
const FINIZEN=["Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs"];
const FLAMIGO=["Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];
const CETODDLE=["Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs"];
const CETODDLE2=["Frozen Peaks","Ice Spikes","Frostfire Caves","Frozen Cliffs","Glacial Chasm","Snowy Plains","Cold Shrubland","Gravel Desert","Rocky Shrubland","Snowy Badlands","Yellowstone"];
const IRONJUGULIS=["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"];
const FRIGIBAX=["Frozen Peaks","Ice Spikes","Frostfire Caves","Frozen Cliffs","Glacial Chasm"];
const POLTCHAGEIST=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland","Bamboo Jungle","Cherry Grove","Sakura Grove","Sakura Valley","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Temperate Highlands","Mushroom Fields","Jungle","Sparse Jungle","Underground Jungle","Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp","Caldera","Thermal Caves","Yellowstone","Mantle Caves","Volcanic Crater","Volcanic Peaks"];

add(906,"나오하","Sprigatito",null,[e("X","5-31",["sky"],B(SPRIGATITO))]);
add(907,"나로테","Floragato",null,[e("X","16-41",["sky"],B(SPRIGATITO))]);
add(908,"마스카나","Meowscarada",null,[e("X","36-53",["sky"],B(SPRIGATITO))]);
add(909,"뜨아거","Fuecoco",null,[e("X","5-31",["sky"],B(FUECOCO)),e("X","5-31",[],B(["Nether Wastes"]))]);
add(910,"악뜨거","Crocalor",null,[e("X","16-41",["sky"],B(FUECOCO)),e("X","16-41",[],B(["Nether Wastes"]))]);
add(911,"라우드본","Skeledirge",null,[e("X","36-53",["sky"],B(FUECOCO)),e("X","36-53",[],B(["Nether Wastes"]))]);
add(912,"꾸왁스","Quaxly",null,[e("X","5-31",["sky","water"],B(QUAXLY)),e("X","5-31",["sub","sky"],B(QUAXLY))]);
add(913,"아꾸왁","Quaxwell",null,[e("X","16-41",["sky","water"],B(QUAXLY)),e("X","16-41",["sub","sky"],B(QUAXLY))]);
add(914,"웨이니발","Quaquaval",null,[e("X","36-53",["sky","water"],B(QUAXLY)),e("X","36-53",["sub","sky"],B(QUAXLY))]);
add(915,"맛보돈","Lechonk",null,[e("C","1-25",["sky","n025"],B(LECHONK)),e("C","1-25",["sky","n025"],B(SWAMP))]);
add(916,"퍼퓨돈","Oinkologne",null,[e("C","18-49",["sky","n025"],B(LECHONK)),e("C","18-49",["sky","n025"],B(SWAMP))]);
add(917,"타랜툴라","Tarountula",null,[e("C","1-21",["sky","d025"],B(TAROUNTULA))]);
add(918,"트래피더","Spidops",null,[e("C","15-40",["sky","d025"],B(TAROUNTULA))]);
add(919,"콩알뚜기","Nymble",null,[e("C","3-22",["seeSky"],B(NYMBLE))]);
add(920,"엑스레그","Lokix",null,[e("R","25-38",["seeSky"],B(NYMBLE))]);
add(921,"빠모","Pawmi",null,[e("U","5-17",["seeSky"],B(PAWMI))]);
add(922,"빠모트","Pawmo",null,[e("U","18-34",["seeSky"],B(PAWMI))]);
add(923,"빠르모트","Pawmot",null,[e("R","30-45",["seeSky"],B(PAWMI))]);
add(924,"두리쥐","Tandemaus",null,[e("C","6-31",["sky","d025"],B(TANDEMAUS)),e("C","6-31",["sky","concrete","d025"],OW(["얼음 계열","모래 계열"])),e("C","6-31",["sky","d025"],{all:"ow",ex:["얼음 계열","모래 계열"],s:VILALL}),e("C","6-31",["indoor","minY62"],S(MANSION))]);
add(925,"파밀리쥐","Maushold","네 식구",[e("C","25-47",["sky","d025"],B(TANDEMAUS)),e("C","25-47",["sky","concrete","d025"],OW(["얼음 계열","모래 계열"])),e("C","25-47",["sky","d025"],{all:"ow",ex:["얼음 계열","모래 계열"],s:VILALL}),e("C","25-47",["indoor","minY62"],S(MANSION))]);
add(925,"파밀리쥐","Maushold","세 식구",[e("C","25-47",["sky","d025"],B(TANDEMAUS)),e("C","25-47",["sky","concrete","d025"],OW(["얼음 계열","모래 계열"])),e("C","25-47",["sky","d025"],{all:"ow",ex:["얼음 계열","모래 계열"],s:VILALL}),e("C","25-47",["indoor","minY62"],S(MANSION))]);
add(926,"쫀도기","Fidough",null,[e("C","6-31",["sky"],OW()),e("C","6-31",["sky"],S(VILALL))]);
add(927,"바우첼","Dachsbun",null,[e("C","26-48",["sky"],OW()),e("C","26-48",["sky"],S(VILALL))]);
add(928,"미니브","Smoliv",null,[e("U","1-26",["sky","n025"],B(SMOLIV))]);
add(929,"올리뇨","Dolliv",null,[e("U","25-35",["sky","n025"],B(SMOLIV))]);
add(930,"올리르바","Arboliva",null,[e("U","35-51",["sky","n025"],B(SMOLIV))]);
add(931,"시비꼬","Squawkabilly",null,[e("C","17-42",["sky","day","treetop"],B(["Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland"])),e("C","17-42",["sky","day","norain","concrete","treetop"],OW(["얼음 계열","모래 계열"])),e("C","17-42",["sky","day","norain","treetop"],{all:"ow",ex:["얼음 계열","모래 계열"],s:VILALL}),e("C","17-42",["sky","day","treetop"],B(["Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter"])),e("C","17-42",["sky","day","norain"],{all:"ow",ex:["얼음 계열","모래 계열"],s:VILALL})]);
add(932,"베베솔트","Nacli",null,[e("C","3-28",["sky"],B(FUECOCO)),e("C","3-28",[],B(NACLI))]);
add(933,"스태솔트","Naclstack",null,[e("C","24-36",["sky"],B(FUECOCO)),e("C","24-36",[],B(NACLI))]);
add(934,"콜로솔트","Garganacl",null,[e("C","38-50",["sky"],B(FUECOCO)),e("C","38-50",[],B(NACLI))]);
add(935,"카르본","Charcadet",null,[e("U","1-26",[],NETH),e("U","1-26",[],S(["Ruined Portal"]))]);
add(936,"카디나르마","Armarouge",null,[e("R","21-53",[],NETH),e("U","21-53",[],S(["Ruined Portal"]))]);
add(937,"파라블레이즈","Ceruledge",null,[e("U","21-53",[],NETH),e("U","21-53",[],S(["Ruined Portal"]))]);
add(938,"빈나두","Tadbulb",null,[e("C","2-27",["sky","t5"],B(["River","Warm River","Mangrove Swamp","Swamp","Orchid Swamp"]))]);
add(939,"찌리배리","Bellibolt",null,[e("C","22-50",["sky","t5"],B(["River","Warm River","Mangrove Swamp","Swamp","Orchid Swamp","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland"]))]);
add(940,"찌리비","Wattrel",null,[e("C","3-28",["sky","t5"],B(WATTREL)),e("C","3-28",["sky","night","t5"],B(WATTREL2)),e("U","3-28",["surf","sky","t5"],B(WATTREL3))]);
add(941,"찌리비크","Kilowattrel",null,[e("C","25-49",["sky","t5"],B(WATTREL)),e("C","25-49",["sky","night","t5"],B(WATTREL2)),e("U","25-49",["surf","sky","t5"],B(WATTREL3))]);
add(942,"오라티프","Maschiff",null,[e("C","9-34",["sky"],OW()),e("C","9-34",["sky"],S(VILALL)),e("C","9-34",["sky","minY62"],S(["Pillager Outpost"])),e("C","9-34",["sky","minY62"],S(MANSION))]);
add(943,"마피티프","Mabosstiff",null,[e("C","30-51",["sky"],OW()),e("C","30-51",["sky"],S(VILALL)),e("C","30-51",["sky","minY62"],S(["Pillager Outpost"])),e("C","30-51",["sky","minY62"],S(MANSION))]);
add(944,"땃쭈르","Shroodle",null,[e("C","4-29",["sky","night","treetop"],B(JUNGLE))]);
add(945,"태깅구르","Grafaiai",null,[e("C","28-49",["sky","night","treetop"],B(JUNGLE))]);
add(946,"그푸리","Bramblin",null,[e("C","3-28",["sky","n15"],B(BRAMBLIN)),e("C","3-28",[],B(["Soul Sand Valley"]))]);
add(947,"공푸리","Brambleghast",null,[e("C","23-48",["sky","n15"],B(BRAMBLIN)),e("C","23-48",[],B(["Soul Sand Valley"]))]);
add(948,"들눈해","Toedscool",null,[e("C","9-34",["sky"],B(TOEDSCOOL)),e("C","9-34",[],B(["Crimson Forest"]))]);
add(949,"육파리","Toedscruel",null,[e("C","30-52",["sky"],B(TOEDSCOOL)),e("C","30-52",[],B(["Crimson Forest"]))]);
add(950,"절벼게","Klawf",null,[e("U","20-45",["sky"],B(FUECOCO))]);
add(951,"캡싸이","Capsakid",null,[e("C","5-30",["sky"],B(CAPSAKID))]);
add(952,"스코빌런","Scovillain",null,[e("C","25-49",["sky"],B(CAPSAKID))]);
add(953,"구르데","Rellor",null,[e("C","2-27",[],B(CAPSAKID))]);
add(954,"베라카스","Rabsca",null,[e("C","22-47",[],B(CAPSAKID))]);
add(955,"하느라기","Flittle",null,[e("U","1-26",["sky","n025"],B(CAPSAKID))]);
add(956,"클레스퍼트라","Espathra",null,[e("U","35-48",["sky","n025"],B(CAPSAKID))]);
add(957,"어리짱","Tinkatink",null,[e("C","5-30",["sky"],S(["Cobblemon Ruins (All Types)"]))]);
add(958,"벼리짱","Tinkatuff",null,[e("C","24-38",["sky"],S(["Cobblemon Ruins (All Types)"]))]);
add(959,"두드리짱","Tinkaton",null,[e("C","38-51",["sky"],S(["Cobblemon Ruins (All Types)"]))]);
add(960,"바다그다","Wiglett",null,[e("C","1-25",["sky"],B(["Beach"])),e("C","1-25",["floor","seeSky"],B(HORSEA))]);
add(961,"바닥트리오","Wugtrio",null,[e("C","26-43",["sky"],B(["Beach"])),e("C","26-43",["floor","seeSky"],B(HORSEA))]);
add(962,"떨구새","Bombirdier",null,[e("U","35-63",["sky"],B(["Beach","River","Warm River"]))]);
add(963,"맨돌핀","Finizen",null,[e("U","7-32",["sub","seeSky"],B(FINIZEN)),e("U","7-32",["sub","indoor","sky"],B(FINIZEN))]);
add(964,"돌핀맨","Palafin",null,[e("U","38-46",["sub","seeSky"],B(FINIZEN)),e("U","38-46",["sub","indoor","sky"],B(FINIZEN))]);
add(965,"부르롱","Varoom",null,[e("U","5-30",["sky"],B(FUECOCO)),e("U","5-30",["sky"],OW())]);
add(966,"부르르룸","Revavroom",null,[e("U","40-50",["sky"],B(FUECOCO)),e("U","40-50",["sky"],OW())]);
add(967,"모토마","Cyclizar",null,[e("R","25-50",["sky","n025"],B(["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes"]))]);
add(968,"꿈트렁","Orthworm",null,[e("U","23-48",["sky"],B(BRAMBLIN)),e("C","23-48",["dim","minY0"],B(BRAMBLIN)),e("U","23-48",["dim","minY0"],OW(["악지 계열","사막 계열"])),e("C","23-48",["dim","minY0","iron"],OW(["악지 계열","사막 계열"])),e("U","23-48",[],B(["Soul Sand Valley"]))]);
add(969,"초롱순","Glimmet",null,[e("C","10-35",["dim","amethyst"],OW())]);
add(970,"킬라플로르","Glimmora",null,[e("C","35-53",["dim","amethyst"],OW())]);
add(971,"망망이","Greavard",null,[e("R","3-29",["seeSky","night"],B(["Dark Forest","Deep Dark"])),e("R","3-29",["night"],{b:["Dark Forest"],s:["Crown Cemetery"]})]);
add(972,"묘두기","Houndstone",null,[e("R","30-59",["seeSky","night"],B(["Dark Forest","Deep Dark"])),e("R","30-59",["night"],{b:["Dark Forest"],s:["Crown Cemetery"]})]);
add(973,"꼬이밍고","Flamigo",null,[e("C","25-50",["sky","water","n025"],B(FLAMIGO)),e("U","25-50",["surf","sky","day"],B(FLAMIGO))]);
add(974,"터벅고래","Cetoddle",null,[e("U","8-33",["sky"],B(CETODDLE)),e("U","8-33",["sky"],B(CETODDLE2))]);
add(975,"우락고래","Cetitan",null,[e("U","28-52",["sky"],B(CETODDLE)),e("U","28-52",["sky"],B(CETODDLE2))]);
add(976,"가비루사","Veluza",null,[e("U","23-48",["sub","seeSky"],B(FINIZEN)),e("U","23-48",["sub","indoor","sky"],B(FINIZEN)),e("U","23-48",["sub","indoor","subY"],S(SSC))]);
add(977,"어써러셔","Dondozo",null,[e("R","28-53",["sub","seeSky"],B(SWAMP)),e("R","28-53",["sub","indoor","sky"],B(SWAMP))]);
add(978,"싸리용","Tatsugiri",null,[e("R","23-48",["sky"],B(SWAMP)),e("R","23-48",["sub","seeSky"],B(SWAMP)),e("R","23-48",["sub","indoor","sky"],B(SWAMP))]);
add(979,"저승갓숭","Annihilape",null,[e("C","35-54",["sky","treetop"],B(["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"]))]);
add(980,"토오","Clodsire",null,[e("C","20-43",["sky"],B(["Mangrove Swamp","Underground Jungle"])),e("C","20-43",["sub","seeSky"],B(["Mangrove Swamp","Underground Jungle"])),e("U","20-43",["sub","seeSky"],B(TOEDSCOOL)),e("U","20-43",["sky","water"],B(TOEDSCOOL)),e("C","20-43",["sub","indoor","sky"],B(["Mangrove Swamp","Underground Jungle"])),e("U","20-43",["sub","indoor","sky"],B(TOEDSCOOL))]);
add(981,"키키링","Farigiraf",null,[e("C","32-45",["sky","n025"],B(TOEDSCOOL))]);
add(982,"노고고치","Dudunsparce","두 마디폼",[e("U","32-52",["dim"],OW(["?#cobblemon:is_deep_dark"]))]);
add(982,"노고고치","Dudunsparce","세 마디폼",[e("U","32-52",["dim"],OW(["?#cobblemon:is_deep_dark"]))]);
add(983,"대도각참","Kingambit",null,[e("X","72-85",[],B(["Bamboo Jungle"]))]);
add(984,"위대한엄니","Great Tusk",null,[e("R","40-65",["seeSky"],B(CAPSAKID))]);
add(985,"우렁찬꼬리","Scream Tail",null,[e("R","40-65",["rain"],B(FLOWER))]);
add(986,"사나운버섯","Brute Bonnet",null,[e("R","45-60",[],B(JUNGLE))]);
add(987,"날개치는머리","Flutter Mane",null,[e("R","45-60",["night"],B(["Dark Forest","Deep Dark"]))]);
add(988,"땅을기는날개","Slither Wing",null,[e("X","47-62",["seeSky"],B(JUNGLE)),e("R","66-76",[],B(["Crimson Forest"]))]);
add(989,"모래털가죽","Sandy Shocks",null,[e("R","60-70",["seeSky"],B(CAPSAKID))]);
add(990,"무쇠바퀴","Iron Treads",null,[e("R","50-70",[],B(["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland","Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Blooming Plateau","Highlands","Grove","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"]))]);
add(991,"무쇠보따리","Iron Bundle",null,[e("R","50-70",[],B(["Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands","Gravel Desert","Rocky Shrubland","Yellowstone"]))]);
add(992,"무쇠손","Iron Hands",null,[e("R","45-60",["seeSky","night"],B(["Desert"]))]);
add(993,"무쇠머리","Iron Jugulis",null,[e("R","70-75",["seeSky","night"],B(IRONJUGULIS))]);
add(994,"무쇠독나방","Iron Moth",null,[e("R","40-65",["day"],B(["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands"]))]);
add(995,"무쇠가시","Iron Thorns",null,[e("R","40-65",[],B(IRONJUGULIS))]);
add(996,"드니차","Frigibax",null,[e("R","26-34",["seeSky"],B(FRIGIBAX))]);
add(997,"드니꽁","Arctibax",null,[e("R","38-57",["seeSky"],B(FRIGIBAX))]);
add(998,"드닐레이브","Baxcalibur",null,[e("X","58-67",["seeSky"],B(FRIGIBAX))]);
add(999,"모으령","Gimmighoul","도보폼",[e("C","5-30",["minY48"],S(["Cobblemon Ruins (All Types)"])),e("C","5-30",["minYm37","maxY10"],S(["Crumbling Arch Ruins","Rooted Arch Ruins"]))]);
add(999,"모으령","Gimmighoul","상자폼",[e("R","5-30",["minY48"],S(["Cobblemon Ruins (All Types)"])),e("R","5-30",["minYm37","maxY10"],S(["Crumbling Arch Ruins","Rooted Arch Ruins"]))]);
add(1001,"총지엔","Wo-Chien",null,[e("X","65-70",["special"],S(["Grasswither Shrine"]))]);
add(1002,"파오젠","Chien-Pao",null,[e("X","75-80",["seeSky","special"],S(["Icerend Shrine"]))]);
add(1003,"딩루","Ting-Lu",null,[e("X","65-70",["special"],S(["Groundblight Shrine"]))]);
add(1004,"위유이","Chi-Yu",null,[e("X","65-70",["special"],S(["Firescourge Shrine"]))]);
add(1005,"고동치는달","Roaring Moon",null,[e("R","55-70",["night"],B(IRONJUGULIS))]);
add(1006,"무쇠무인","Iron Valiant",null,[e("R","55-70",["storm"],B(PAWMI))]);
add(1007,"코라이돈","Koraidon",null,[e("X","40",["seeSky"],B(["Beach"]))]);
add(1008,"미라이돈","Miraidon",null,[e("X","40",["seeSky"],B(["Beach"]))]);
add(1009,"굽이치는물결","Walking Wake",null,[e("X","60-75",["rain"],B(IRONJUGULIS))]);
add(1010,"무쇠잎새","Iron Leaves",null,[e("X","50-75",["night"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"]))]);
add(1011,"과미르","Dipplin",null,[e("R","20-35",["seeSky","day","norain"],B(FLOWER))]);
add(1012,"차데스","Poltchageist","짝퉁폼",[e("U","6-31",["indoor","day","minY62"],{b:POLTCHAGEIST,s:VILALL}),e("U","6-31",["night","minY62"],{b:POLTCHAGEIST,s:VILALL})]);
add(1012,"차데스","Poltchageist","진품폼",[e("U","6-31",["indoor","day","minY62"],{b:POLTCHAGEIST,s:VILALL}),e("U","6-31",["night","minY62"],{b:POLTCHAGEIST,s:VILALL})]);
add(1013,"그우린차","Sinistcha","범작폼",[e("U","26-51",["indoor","day","minY62"],{b:POLTCHAGEIST,s:VILALL}),e("U","26-51",["night","minY62"],{b:POLTCHAGEIST,s:VILALL})]);
add(1013,"그우린차","Sinistcha","걸작폼",[e("U","26-51",["indoor","day","minY62"],{b:POLTCHAGEIST,s:VILALL}),e("U","26-51",["night","minY62"],{b:POLTCHAGEIST,s:VILALL})]);
add(1014,"조타구","Okidogi",null,[e("X","70-75",["seeSky"],B(TOEDSCOOL))]);
add(1015,"이야후","Munkidori",null,[e("X","70-75",["seeSky"],B(JUNGLE))]);
add(1016,"기로치","Fezandipiti",null,[e("X","70-75",["seeSky"],B(["Frozen Peaks","Jagged Peaks","Snowy Slopes","Stony Peaks","Emerald Peaks","Rocky Mountains","Scarlet Mountains","Windswept Spires"]))]);
add(1017,"오거폰","Ogerpon",null,[e("X","50-75",[],B(LUSHC))]);
add(1018,"브리두라스","Archaludon",null,[e("X","70-80",[],B(FRIGIBAX))]);
add(1019,"과미드라","Hydrapple",null,[e("X","45-70",["seeSky","day","norain"],B(FLOWER))]);
add(1020,"꿰뚫는화염","Gouging Fire",null,[e("X","70-75",[],B(["Basalt Deltas"]))]);
add(1021,"날뛰는우레","Raging Bolt",null,[e("X","60-75",["rain15","t3"],B(CAPSAKID))]);
add(1022,"무쇠암석","Iron Boulder",null,[e("X","45-60",["seeSky","night"],B(["Dark Forest"]))]);
add(1023,"무쇠감투","Iron Crown",null,[e("X","50-75",["night"],B(LUSHC))]);
add(1024,"테라파고스","Terapagos",null,[e("X","55-75",["maxY0","amethystbase"],B(["Dripstone Caves","Lush Caves","Deep Dark","Andesite Caves","Desert Caves","Diorite Caves","Fungal Caves","Granite Caves","Infested Caves","Thermal Caves","Underground Jungle"]))]);
add(1025,"복숭악동","Pecharunt",null,[e("X","60-80",["seeSky"],B(["Dark Forest","Deep Dark"]))]);
