// ---- 2세대 (COBBLEVERSE 모드팩 1.7.42 데이터팩 COBBLEVERSE-DP-v31 기준) ----
const CYNDAQUIL=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const CYNDAQUIL2=["Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"];
const SENTRET=["Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Ice Spikes","Snowy Plains","Gravel Desert","Rocky Shrubland","Snowy Badlands"];
const HOOTHOOT=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter","Deep Dark"];
const LEDYBA=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const SPINARAK=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Deep Dark"];
const CROBAT=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Mangrove Swamp","Swamp","Orchid Swamp"];
const CHINCHOU=["Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean"];
const PICHU=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"];
const CLEFFA=["Dripstone Caves","Fractured Savanna","Stony Spires"];
const CLEFFA2=["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands"];
const IGGLYBUFF=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const TOGEPI=["Cherry Grove","Flower Forest","Sakura Grove","Sakura Valley","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley","Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter"];
const NATU=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Savanna Plateau","Cherry Grove","Meadow"];
const BELLOSSOM=["Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland"];
const POLITOED=["River","Warm River","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Mushroom Fields","Fungal Caves","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Alpha Islands","Lavender Forest","Sakura Grove","Plains","Sunflower Plains","Shrubland","Brushland","Steppe","Valley Clearing"];
const WOOPER=["Swamp","Ice Marsh","Orchid Swamp"];
const MISDREAVUS=["Dark Forest","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];
const WOBBUFFET=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes"];
const GLIGAR=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa"];
const QWILFISH=["Deep Ocean","Deep Lukewarm Ocean","Ocean","Lukewarm Ocean","Warm Ocean"];
const QWILFISH2=["Cold Ocean","Deep Cold Ocean","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs"];
const TEDDIURSA=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Windswept Savanna","Lush Valley","Moonlight Valley","Savanna Slopes","Yosemite Lowlands","Stony Spires","Windswept Spires","Yosemite Cliffs","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Shield","Siberian Taiga","Yellowstone"];
const SLUGMA=["Mantle Caves","Volcanic Crater","Volcanic Peaks"];
const SWINUB=["Ice Spikes","Snowy Plains","Cold Shrubland","Gravel Desert","Rocky Shrubland","Snowy Badlands","Yellowstone"];
const REMORAID=["Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs"];
const SMOOCHUM=["Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands"];
const LARVITAR=["Meadow","Stony Peaks","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"];
const LARVITAR2=["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"];

add(152,"치코리타","Chikorita",null,[e("X","5-32",["sky"],B(FLOWER))]);
add(153,"베이리프","Bayleef",null,[e("X","16-41",["sky"],B(FLOWER))]);
add(154,"메가니움","Meganium",null,[e("X","32-53",["sky"],B(FLOWER))]);
add(155,"브케인","Cyndaquil",null,[e("X","5-31",["sky"],B(CYNDAQUIL))]);
add(155,"브케인","Cyndaquil","히스이 계열",[e("X","5-31",["sky","norain"],B(CYNDAQUIL2)),e("X","5-31",[],B(["Crimson Forest"]))]);
add(156,"마그케인","Quilava",null,[e("X","17-41",["sky"],B(CYNDAQUIL))]);
add(156,"마그케인","Quilava","히스이 계열",[e("X","17-41",["sky","norain"],B(CYNDAQUIL2)),e("X","17-41",[],B(["Crimson Forest"]))]);
add(157,"블레이범","Typhlosion",null,[e("X","36-53",["sky"],B(CYNDAQUIL))]);
add(157,"블레이범","Typhlosion","히스이",[e("X","36-53",["sky","norain"],B(CYNDAQUIL2)),e("X","36-53",[],B(["Crimson Forest"]))]);
add(158,"리아코","Totodile",null,[e("X","5-31",["sky"],B(SWAMP)),e("X","5-31",["sub","seeSky"],B(SWAMP)),e("X","5-31",["sub","indoor","sky"],B(SWAMP))]);
add(159,"엘리게이","Croconaw",null,[e("X","18-41",["sky"],B(SWAMP)),e("X","18-41",["sub","seeSky"],B(SWAMP)),e("X","18-41",["sub","indoor","sky"],B(SWAMP))]);
add(160,"장크로다일","Feraligatr",null,[e("X","30-53",["sky"],B(SWAMP)),e("X","30-53",["sub","seeSky"],B(SWAMP)),e("X","30-53",["sub","indoor","sky"],B(SWAMP))]);
add(161,"꼬리선","Sentret",null,[e("C","1-22",["sky"],B(SENTRET))]);
add(162,"다꼬리","Furret",null,[e("C","15-42",["sky"],B(SENTRET))]);
add(163,"부우부","Hoothoot",null,[e("C","1-26",["sky","night","treetop"],B(HOOTHOOT))]);
add(164,"야부엉","Noctowl",null,[e("C","20-45",["sky","night","treetop"],B(HOOTHOOT))]);
add(165,"레디바","Ledyba",null,[e("C","2-27",["sky","day","norain","treetop"],B(LEDYBA))]);
add(166,"레디안","Ledian",null,[e("C","18-39",["sky","night","norain","treetop"],B(LEDYBA))]);
add(167,"페이검","Spinarak",null,[e("C","1-25",["sky","night","norain","treetop"],B(SPINARAK)),e("C","1-25",["dim"],OW(["?#cobblemon:is_deep_dark"])),e("C","1-25",["indoor","light0","minY0"],OW(["?#cobblemon:is_deep_dark"])),e("C","1-25",["dim"],B(["Infested Caves"])),e("C","1-25",["indoor","minY62","cobweb"],S(MANSION))]);
add(168,"아리아도스","Ariados",null,[e("C","22-40",["sky","night","norain","treetop"],B(SPINARAK)),e("C","22-40",["dim"],OW(["?#cobblemon:is_deep_dark"])),e("C","22-40",["indoor","light0","minY0"],OW(["?#cobblemon:is_deep_dark"])),e("C","22-40",["dim"],B(["Infested Caves"])),e("C","22-40",["indoor","minY62","cobweb"],S(MANSION))]);
add(169,"크로뱃","Crobat",null,[e("C","41-54",["sky","night","norain"],B(CROBAT)),e("C","41-54",["dim","n025"],B(CROBAT)),e("C","41-54",["dim","d15"],OW(["?#cobblemon:is_deep_dark","숲 계열","늪 계열"])),e("U","41-54",["indoor","light0","d15"],OW(["?#cobblemon:is_deep_dark","숲 계열","늪 계열"])),e("C","41-54",["sky","norain","n15"],B(["Dark Forest","Deep Dark"])),e("U","41-54",["dim"],B(["Deep Dark","Crystal Caves","Deep Caves","Frostfire Caves","Mantle Caves","Tuff Caves"]))]);
add(170,"초라기","Chinchou",null,[e("C","8-33",["sub","seeSky","maxY48"],B(CHINCHOU)),e("C","8-33",["sub","indoor","sky","maxY48"],B(CHINCHOU)),e("C","8-33",["sub","indoor","subY"],S(SSC))]);
add(171,"랜턴","Lanturn",null,[e("C","27-46",["sub","seeSky","maxY48"],B(CHINCHOU)),e("C","27-46",["sub","indoor","sky","maxY48"],B(CHINCHOU)),e("C","27-46",["sub","indoor","subY"],S(SSC))]);
add(172,"피츄","Pichu",null,[e("U","1-21",["sky","t5"],B(PICHU))]);
add(172,"피츄","Pichu","알로라 계열",[e("U","16-32",["sky","t5"],B(["Beach"]))]);
add(173,"삐","Cleffa",null,[e("U","1-22",["sky","night"],B(CLEFFA)),e("U","1-22",["dim"],B(CLEFFA)),e("U","1-22",["sky","night"],B(CLEFFA2)),e("U","1-22",["sky","night"],B(["Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley"]))]);
add(174,"푸푸린","Igglybuff",null,[e("C","1-21",["sky","n15"],B(FLOWER)),e("C","1-21",["sky","n15"],B(IGGLYBUFF))]);
add(175,"토게피","Togepi",null,[e("R","1-25",["sky","day","norain"],B(TOGEPI))]);
add(176,"토게틱","Togetic",null,[e("R","20-41",["sky","day","norain"],B(TOGEPI))]);
add(177,"네이티","Natu",null,[e("C","7-32",["sky","day","treetop"],B(NATU)),e("C","7-32",["sky","day","minY32"],S(["Trail Ruins"]))]);
add(178,"네이티오","Xatu",null,[e("C","25-47",["sky","day","treetop"],B(NATU)),e("C","25-47",["sky","day","minY32"],S(["Trail Ruins"]))]);
add(179,"메리프","Mareep",null,[e("C","3-28",["sky","n025","t5"],B(IGGLYBUFF))]);
add(180,"보송송","Flaaffy",null,[e("C","15-37",["sky","n025","t5"],B(IGGLYBUFF))]);
add(181,"전룡","Ampharos",null,[e("C","30-51",["sky","n025","t5"],B(IGGLYBUFF))]);
add(182,"아르코","Bellossom",null,[e("C","35-49",["sky","day"],B(FLOWER)),e("C","35-49",["sky","day"],B(JUNGLE))]);
add(182,"아르코","Bellossom","발렌시아",[e("C","35-49",["sky","day"],B(BELLOSSOM))]);
add(183,"마릴","Marill",null,[e("C","14-25",["sky"],B(["River","Warm River"])),e("C","14-25",["surf","sky"],B(RIVERS))]);
add(184,"마릴리","Azumarill",null,[e("U","18-42",["sky"],B(["River","Warm River"])),e("U","18-42",["surf","sky"],B(RIVERS))]);
add(185,"꼬지모","Sudowoodo",null,[e("U","16-41",["sky","norain"],B(PICHU))]);
add(186,"왕구리","Politoed",null,[e("C","34-50",["sky","rain"],B(SWAMP)),e("C","34-50",["sub","seeSky","lily"],B(SWAMP)),e("C","34-50",["sky","rain","water"],B(POLITOED)),e("C","34-50",["sub","seeSky"],B(POLITOED)),e("C","34-50",["dim"],B(LUSHC)),e("C","34-50",["sub","dim"],B(LUSHC)),e("C","34-50",["sub","indoor","sky","lily"],B(SWAMP)),e("C","34-50",["sub","indoor","sky"],B(POLITOED)),e("C","34-50",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("C","34-50",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(187,"통통코","Hoppip",null,[e("C","1-25",["sky","norain","treetop","n025"],B(IGGLYBUFF))]);
add(188,"두코","Skiploom",null,[e("C","18-34",["sky","norain","treetop","n025"],B(IGGLYBUFF))]);
add(189,"솜솜코","Jumpluff",null,[e("C","27-46",["sky","treetop","n025"],B(IGGLYBUFF))]);
add(190,"에이팜","Aipom",null,[e("C","11-36",["sky","treetop"],B(JUNGLE)),e("C","11-36",["dim","shipY"],S(LSC))]);
add(191,"해너츠","Sunkern",null,[e("C","1-18",["sky","sunflower","n025"],B(["Sunflower Plains"])),e("C","1-18",["sky","sunflower","n025"],OW(["Sunflower Plains"]))]);
add(192,"해루미","Sunflora",null,[e("C","13-43",["sky","sunflower","n025"],B(["Sunflower Plains"])),e("C","13-43",["sky","sunflower","n025"],OW(["Sunflower Plains"]))]);
add(193,"왕자리","Yanma",null,[e("U","14-39",["surf","sky","day","norain"],B(["River","Warm River","Mangrove Swamp","Swamp","Orchid Swamp"])),e("U","14-39",["surf","dim"],B(LUSHC)),e("U","14-39",["surf","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(194,"우파","Wooper",null,[e("C","1-21",["dim"],B(LUSHC)),e("C","1-21",["sub","dim"],B(LUSHC)),e("U","1-21",["dim","maxY62","water"],OW(["무성한 계열"])),e("U","1-21",["sub","dim","maxY62"],OW(["무성한 계열"])),e("C","1-21",["sky","rain"],B(WOOPER)),e("C","1-21",["sub","seeSky"],B(WOOPER)),e("C","1-21",["sub","indoor","sky"],B(WOOPER)),e("C","1-21",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("C","1-21",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(194,"우파","Wooper","팔데아",[e("C","1-21",["sky"],B(["Mangrove Swamp","Underground Jungle"])),e("C","1-21",["sub","seeSky"],B(["Mangrove Swamp","Underground Jungle"])),e("U","1-21",["sky","water"],B(BELLOSSOM)),e("U","1-21",["sub","seeSky"],B(BELLOSSOM)),e("C","1-21",["sub","indoor","sky"],B(["Mangrove Swamp","Underground Jungle"])),e("U","1-21",["sub","indoor","sky"],B(BELLOSSOM))]);
add(195,"누오","Quagsire",null,[e("C","20-43",["dim"],B(LUSHC)),e("C","20-43",["sub","dim"],B(LUSHC)),e("U","20-43",["dim","maxY62","water"],OW(["무성한 계열"])),e("U","20-43",["sub","dim","maxY62"],OW(["무성한 계열"])),e("C","20-43",["sky","rain"],B(WOOPER)),e("C","20-43",["sub","seeSky"],B(WOOPER)),e("C","20-43",["sub","indoor","sky"],B(WOOPER)),e("C","20-43",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("C","20-43",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(196,"에브이","Espeon",null,[e("X","28-53",["sky"],B(CLEFFA2)),e("U","28-53",["sky","concrete"],OW()),e("U","28-53",["sky"],S(VILALL))]);
add(197,"블래키","Umbreon",null,[e("X","28-53",["night"],B(["Dark Forest","Deep Dark"])),e("R","28-53",["sky"],OW()),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor","minY62"],S(MANSION))]);
add(198,"니로우","Murkrow",null,[e("C","16-41",["treetop","n15"],B(["Dark Forest","Deep Dark"])),e("C","16-41",["night","treetop"],B(SWAMP)),e("C","16-41",["night","treetop"],B(CYNDAQUIL2))]);
add(199,"야도킹","Slowking",null,[e("C","37-49",["sky"],B(["Beach","Snowy Beach"]))]);
add(199,"야도킹","Slowking","가라르",[e("C","37-49",["sky","water"],B(["Mushroom Fields"]))]);
add(200,"무우마","Misdreavus",null,[e("C","19-44",["sky17","light07"],B(["Dark Forest"])),e("C","19-44",["dim"],B(MISDREAVUS)),e("C","19-44",["indoor","light0"],B(MISDREAVUS)),e("C","19-44",["sky","night"],B(SWAMP)),e("C","19-44",[],B(["Warped Forest"])),e("C","19-44",["indoor","shipY"],{all:"ow",ex:["?#cobblemon:is_deep_dark"],s:["Shipwreck Cove (All Types)"]})]);
add(201,"안농","Unown","A~Z, !, ?",[e("C","1-100",[],END),e("C","1-100",["minY48"],S(["Trail Ruins"]))]);
add(202,"마자용","Wobbuffet",null,[e("R","15-41",["dim"],B(WOBBUFFET))]);
add(203,"키링키","Girafarig",null,[e("C","21-46",["sky","n025"],B(BELLOSSOM))]);
add(204,"피콘","Pineco",null,[e("C","4-29",["sky","treetop"],B(CYNDAQUIL2))]);
add(205,"쏘콘","Forretress",null,[e("C","31-47",["sky"],B(CYNDAQUIL2))]);
add(206,"노고치","Dunsparce",null,[e("R","17-42",["indoor"],OW(["?#cobblemon:is_deep_dark"])),e("R","17-42",[],B(LUSHC))]);
add(207,"글라이거","Gligar",null,[e("U","18-43",["night","treetop"],B(GLIGAR)),e("C","18-43",[],B(["Basalt Deltas"]))]);
add(208,"강철톤","Steelix",null,[e("U","34-51",["dim"],OW(["?#cobblemon:is_deep_dark"])),e("U","34-51",[],B(["Basalt Deltas"]))]);
add(209,"블루","Snubbull",null,[e("C","5-30",[],B(WOBBUFFET)),e("C","5-30",[],S(VILALL)),e("C","5-30",["sky"],{all:"ow",ex:["얼음 계열"],s:VILALL})]);
add(210,"그랑블루","Granbull",null,[e("C","23-45",[],B(WOBBUFFET)),e("C","23-45",[],S(VILALL)),e("C","23-45",["sky"],{all:"ow",ex:["얼음 계열"],s:VILALL})]);
add(211,"침바루","Qwilfish",null,[e("U","19-44",["sub","seeSky"],B(HORSEA)),e("C","19-44",["sub","seeSky","maxY62"],{b:QWILFISH,s:OM}),e("C","19-44",["sub"],B(HORSEA)),e("C","19-44",["sub","sky","maxY62"],{b:QWILFISH,s:OM}),e("U","19-44",["sub","indoor","subY"],{all:"ow",ex:["추운 계열"],s:SSC})]);
add(211,"침바루","Qwilfish","히스이",[e("U","19-44",["sub","seeSky"],B(["Cold Ocean","Deep Cold Ocean"])),e("C","19-44",["sub","seeSky","maxY62"],{b:QWILFISH2,s:OM}),e("U","19-44",["sub","indoor","sky"],B(["Cold Ocean","Deep Cold Ocean"])),e("C","19-44",["sub","indoor","sky","maxY62"],{b:QWILFISH2,s:OM}),e("U","19-44",["sub","indoor","subY"],{b:["Cold Ocean","Deep Cold Ocean","Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands","Stony Peaks","Rocky Mountains","Windswept Spires","Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Haze Mountain","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands","Gravel Desert","Rocky Shrubland","Windswept Hills","Windswept Gravelly Hills","Windswept Forest","Stony Shore","The End","Small End Islands","End Midlands","End Highlands","End Barrens"],s:SSC})]);
add(212,"핫삼","Scizor",null,[e("U","45-50",["sky","day"],B(JUNGLE))]);
add(213,"단단지","Shuckle",null,[e("U","16-51",["dim"],B(LUSHC)),e("U","16-51",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(214,"헤라크로스","Heracross",null,[e("R","25-50",["sky","treetop","nosacch","twi5"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"])),e("U","25-50",["sky","treetop","nosacch","twi5"],B(JUNGLE)),e("U","25-50",["sky","sacch","treetop","twi5"],OW(["얼음 계열"]))]);
add(215,"포푸니","Sneasel",null,[e("U","18-43",["d025"],B(CYNDAQUIL2))]);
add(215,"포푸니","Sneasel","히스이",[e("U","18-43",["sky","n025"],B(["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Blooming Plateau","Highlands","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Sakura Valley","Temperate Highlands","Stony Spires","Windswept Spires","Yosemite Cliffs"]))]);
add(216,"깜지곰","Teddiursa",null,[e("C","8-33",["minY48","nosacch"],B(TEDDIURSA)),e("C","8-33",["sky","sacch"],OW())]);
add(217,"링곰","Ursaring",null,[e("C","30-50",["minY48","nosacch"],B(TEDDIURSA)),e("C","30-50",["sky","sacch"],OW())]);
add(218,"마그마그","Slugma",null,[e("C","1-25",[],B(["Basalt Deltas","Nether Wastes"])),e("C","1-25",["surf","inlava"],NETH),e("C","1-25",["surf","inlava"],OW(["화산 계열"])),e("C","1-25",["lavab"],B(SLUGMA))]);
add(219,"마그카르고","Magcargo",null,[e("C","38-43",[],B(["Basalt Deltas","Nether Wastes"])),e("C","38-43",["surf","inlava"],NETH),e("C","38-43",["surf","inlava"],OW(["화산 계열"])),e("C","38-43",["lavab"],B(SLUGMA))]);
add(220,"꾸꾸리","Swinub",null,[e("C","1-25",["sky"],B(SWINUB))]);
add(221,"메꾸리","Piloswine",null,[e("C","33-45",["sky"],B(SWINUB))]);
add(222,"코산호","Corsola",null,[e("C","16-41",["floor","seeSky"],B(["Warm Ocean"])),e("U","16-41",["floor","seeSky","coral"],OW(["Warm Ocean"]))]);
add(222,"코산호","Corsola","가라르",[e("U","16-41",[],B(["Beach","Snowy Beach"])),e("C","16-41",["deadcoral"],OW())]);
add(223,"총어","Remoraid",null,[e("C","5-30",["sub","seeSky"],B(REMORAID)),e("C","5-30",["sub","indoor","sky"],B(REMORAID)),e("C","5-30",["sub","indoor","subY"],S(SSC))]);
add(224,"대포무노","Octillery",null,[e("C","25-48",["floor","seeSky"],B(REMORAID)),e("C","25-48",["floor","indoor","subY"],S(SSC))]);
add(225,"딜리버드","Delibird",null,[e("U","8-33",["n025"],B(["Frozen Peaks","Jagged Peaks","Snowy Slopes","Stony Peaks","Emerald Peaks","Rocky Mountains","Scarlet Mountains","Windswept Spires"]))]);
add(226,"만타인","Mantine",null,[e("U","30-49",["sub","seeSky","minY48"],B(HORSEA)),e("U","30-49",["sub","indoor","sky","minY48"],B(HORSEA))]);
add(227,"무장조","Skarmory",null,[e("R","22-47",["sky","day"],B(["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley","Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter"]))]);
add(228,"델빌","Houndour",null,[e("U","8-33",["sky","n15"],B(GLIGAR)),e("C","8-33",[],NETH),e("U","8-33",["n15"],S(["Ruined Portal"]))]);
add(229,"헬가","Houndoom",null,[e("U","24-50",["sky","n15"],B(GLIGAR)),e("C","24-50",[],NETH),e("U","24-50",["n15"],S(["Ruined Portal"]))]);
add(230,"킹드라","Kingdra",null,[e("C","39-54",["sub","seeSky"],B(HORSEA)),e("C","39-54",["sub","indoor","sky"],B(HORSEA)),e("C","39-54",["sub","indoor","subY"],S(SSC))]);
add(231,"코코리","Phanpy",null,[e("C","8-33",["n025"],B(GLIGAR)),e("C","8-33",["n025"],B(BELLOSSOM))]);
add(232,"코리갑","Donphan",null,[e("C","25-50",["sky","n025"],B(GLIGAR)),e("C","25-50",["sky","n025"],B(BELLOSSOM))]);
add(234,"노라키","Stantler",null,[e("C","22-47",["sky","n025"],B(["Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Ice Spikes","Snowy Plains","Gravel Desert","Rocky Shrubland","Snowy Badlands","Yellowstone"]))]);
add(235,"루브도","Smeargle",null,[e("R","1-25",["sky","n025"],OW()),e("R","1-25",["sky","n025"],S(VILALL)),e("C","1-25",["indoor","minY62","wool"],S(MANSION))]);
add(236,"배루키","Tyrogue",null,[e("U","1-21",["sky","n025"],B(CLEFFA2))]);
add(237,"카포에라","Hitmontop",null,[e("U","20-46",["sky","n025"],B(CLEFFA2))]);
add(238,"뽀뽀라","Smoochum",null,[e("U","6-31",["sky","n025"],B(SMOOCHUM)),e("U","6-31",["sky","n025"],{b:SMOOCHUM,s:VILALL})]);
add(239,"에레키드","Elekid",null,[e("U","11-36",["sky","t5"],B(["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Plains","Sunflower Plains","Shrubland","Brushland","Steppe","Valley Clearing"]))]);
add(240,"마그비","Magby",null,[e("C","11-36",["sky","norain","lava"],B(CLEFFA2)),e("C","11-36",["sky","norain"],B(SLUGMA)),e("C","11-36",[],B(["Basalt Deltas","Nether Wastes"]))]);
add(241,"밀탱크","Miltank",null,[e("C","24-49",["sky","n025"],B(WOBBUFFET))]);
add(241,"밀탱크","Miltank","빨간 무시탱크",[e("C","24-49",["sky","n025"],B(["Mushroom Fields"]))]);
add(241,"밀탱크","Miltank","갈색 무시탱크",[e("C","24-49",["sky","n025"],B(["Mushroom Fields"]))]);
add(242,"해피너스","Blissey",null,[e("R","40-54",["sky","n025"],OW()),e("R","40-54",["sky","n025"],S(VILALL))]);
add(243,"라이코","Raikou",null,[e("X","60",["t3"],S(["Burned Tower (Johto)"]))]);
add(244,"앤테이","Entei",null,[e("X","60",["d3"],S(["Burned Tower (Johto)"]))]);
add(245,"스이쿤","Suicune",null,[e("X","60",["rain3"],S(["Burned Tower (Johto)"]))]);
add(246,"애버라스","Larvitar",null,[e("X","5-30",["sky"],B(LARVITAR)),e("R","5-30",["dim"],B(LARVITAR2))]);
add(247,"데기라스","Pupitar",null,[e("X","30-54",["sky"],B(LARVITAR)),e("R","30-54",["dim"],B(LARVITAR2))]);
add(248,"마기라스","Tyranitar",null,[e("X","55-60",["sky"],B(LARVITAR)),e("R","55-60",["dim"],B(LARVITAR2))]);
add(249,"루기아","Lugia",null,[e("X","60-70",["special"],S(["Whirl Island (Johto)"]))]);
add(250,"칠색조","Ho-Oh",null,[e("X","60-70",["special"],S(["Bell Tower (Johto)"]))]);
add(251,"세레비","Celebi",null,[e("X","75-80",["special"],S(["Ilex Shrine (Johto)"]))]);

// 출현 시점 안내 (LUMYVERSE 공식 사이트 안내: 칠색조, 루기아, 전설의 세 마리 개는 관동 시리즈를 끝내고 챔피언 그린을 이긴 뒤에만 나옴)
Object.assign(UNLOCK,{243:"관동 시리즈 클리어(챔피언 그린 승리) 후",244:"관동 시리즈 클리어(챔피언 그린 승리) 후",245:"관동 시리즈 클리어(챔피언 그린 승리) 후",249:"관동 시리즈 클리어(챔피언 그린 승리) 후",250:"관동 시리즈 클리어(챔피언 그린 승리) 후"});
