// ---- 3세대 (COBBLEVERSE 모드팩 1.7.42 데이터팩 COBBLEVERSE-DP-v31 기준) ----
const TORCHIC=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const POOCHYENA=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland"];
const ZIGZAGOON=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const ZIGZAGOON2=["Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"];
const WURMPLE=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"];
const DUSTOX=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"];
const TAILLOW=["Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const WINGULL=["Stony Shore","Beach","Basalt Cliffs","Granite Cliffs","White Cliffs","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Skylands Autumn","Skylands Spring","Skylands Summer"];
const RALTS=["Cherry Grove","Flower Forest","Meadow","Sunflower Plains","Sakura Grove","Sakura Valley","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest"];
const SURSKIT=["River","Warm River","Mangrove Swamp","Swamp","Orchid Swamp"];
const SHROOMISH=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"];
const SHROOMISH2=["Dark Forest","Mushroom Fields","Fungal Caves","Mirage Isles"];
const NINJASK=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"];
const WHISMUR=["Deep Dark","Crystal Caves","Deep Caves","Frostfire Caves","Mantle Caves","Tuff Caves"];
const MAKUHITA=["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"];
const SKITTY=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland"];
const MEDITITE=["Frozen Peaks","Jagged Peaks","Snowy Slopes","Stony Peaks","Emerald Peaks","Rocky Mountains","Scarlet Mountains","Windswept Spires"];
const ELECTRIKE=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Snowy Slopes","Grove","Cherry Grove","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Temperate Highlands","Yosemite Lowlands"];
const CARVANHA=["Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];
const SHARPEDO=["Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs"];
const WAILMER=["Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean"];
const NUMEL=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa"];
const NUMEL2=["Mantle Caves","Volcanic Crater","Volcanic Peaks"];
const SPOINK=["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands"];
const SPINDA=["Bamboo Jungle","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands"];
const TRAPINCH=["Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Red Oasis","Sandstone Valley"];
const CACNEA=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley"];
const SWABLU=["Stony Peaks","Rocky Mountains","Windswept Spires","Skylands Autumn","Skylands Spring","Skylands Summer"];
const LUNATONE=["Dripstone Caves","Fractured Savanna","Stony Spires"];
const SNORUNT=["Frozen Peaks","Ice Spikes","Frostfire Caves","Frozen Cliffs","Glacial Chasm"];
const SPHEAL=["Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs"];
const BELDUM=["Dripstone Caves","Fractured Savanna","Stony Spires","Frozen Peaks","Jagged Peaks","Snowy Slopes","Stony Peaks","Emerald Peaks","Rocky Mountains","Scarlet Mountains","Windswept Spires"];

add(252,"나무지기","Treecko",null,[e("X","5-31",["sky","treetop"],B(JUNGLE))]);
add(253,"나무돌이","Grovyle",null,[e("X","16-41",["sky","treetop"],B(JUNGLE))]);
add(254,"나무킹","Sceptile",null,[e("X","36-53",["sky","treetop"],B(JUNGLE))]);
add(255,"아차모","Torchic",null,[e("X","5-31",["sky"],B(TORCHIC))]);
add(256,"영치코","Combusken",null,[e("X","16-41",["sky"],B(TORCHIC))]);
add(257,"번치코","Blaziken",null,[e("X","36-53",["sky"],B(TORCHIC))]);
add(258,"물짱이","Mudkip",null,[e("X","5-31",["sky","rain15"],B(SWAMP)),e("X","5-31",["sub","seeSky"],B(SWAMP)),e("X","5-31",["dim"],B(LUSHC)),e("X","5-31",["sub","dim"],B(LUSHC)),e("X","5-31",["sub","indoor","sky"],B(SWAMP)),e("X","5-31",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("X","5-31",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(259,"늪짱이","Marshtomp",null,[e("X","16-41",["sky","rain15"],B(SWAMP)),e("X","16-41",["sub","seeSky"],B(SWAMP)),e("X","16-41",["dim"],B(LUSHC)),e("X","16-41",["sub","dim"],B(LUSHC)),e("X","16-41",["sub","indoor","sky"],B(SWAMP)),e("X","16-41",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("X","16-41",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(260,"대짱이","Swampert",null,[e("X","36-53",["sky","rain15"],B(SWAMP)),e("X","36-53",["sub","seeSky"],B(SWAMP)),e("X","36-53",["dim"],B(LUSHC)),e("X","36-53",["sub","dim"],B(LUSHC)),e("X","36-53",["sub","indoor","sky"],B(SWAMP)),e("X","36-53",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("X","36-53",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(261,"포챠나","Poochyena",null,[e("C","1-22",["night"],B(POOCHYENA)),e("C","1-22",["minY62"],S(["Pillager Outpost"]))]);
add(262,"그라에나","Mightyena",null,[e("C","18-42",["night"],B(POOCHYENA)),e("C","18-42",["sky","minY62"],S(["Pillager Outpost"]))]);
add(263,"지그제구리","Zigzagoon",null,[e("C","1-24",["sky","n15"],B(ZIGZAGOON))]);
add(263,"지그제구리","Zigzagoon","가라르",[e("C","1-24",["sky","n15"],B(ZIGZAGOON2))]);
add(264,"직구리","Linoone",null,[e("C","20-42",["sky","n15"],B(ZIGZAGOON))]);
add(264,"직구리","Linoone","가라르",[e("C","20-42",["sky","n15"],B(ZIGZAGOON2))]);
add(265,"개무소","Wurmple",null,[e("C","2-6",["sky","leaves","treetop"],B(WURMPLE))]);
add(266,"실쿤","Silcoon",null,[e("U","7-9",["sky","leaves","treetop"],B(WURMPLE))]);
add(267,"뷰티플라이","Beautifly",null,[e("U","10-32",["sky","day","norain"],B(WURMPLE)),e("U","10-40",["sky","day","norain"],B(FLOWER))]);
add(268,"카스쿤","Cascoon",null,[e("U","7-9",["sky","leaves","treetop"],B(WURMPLE))]);
add(269,"독케일","Dustox",null,[e("U","10-32",["sky"],B(["Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Alpha Islands","Forested Highlands","Mirage Isles","Temperate Highlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"])),e("U","10-40",["sky"],B(DUSTOX))]);
add(270,"연꽃몬","Lotad",null,[e("C","1-22",["sky","rain","n15"],B(SWAMP)),e("C","1-22",["surf","sky"],B(SWAMP))]);
add(271,"로토스","Lombre",null,[e("C","14-34",["sky","rain","n15"],B(SWAMP)),e("C","14-34",["surf","sky"],B(SWAMP))]);
add(272,"로파파","Ludicolo",null,[e("C","29-48",["sky","rain","n15"],B(SWAMP)),e("C","29-48",["surf","sky"],B(SWAMP))]);
add(273,"도토링","Seedot",null,[e("C","1-22",["sky","treetop"],B(DUSTOX))]);
add(274,"잎새코","Nuzleaf",null,[e("C","14-34",["sky","treetop"],B(DUSTOX))]);
add(275,"다탱구","Shiftry",null,[e("C","29-48",["sky","treetop"],B(DUSTOX))]);
add(276,"테일로","Taillow",null,[e("C","2-27",["sky","day","treetop"],B(TAILLOW))]);
add(277,"스왈로","Swellow",null,[e("C","22-46",["sky","day","treetop"],B(TAILLOW))]);
add(278,"갈모매","Wingull",null,[e("C","2-27",["sky","day","treetop"],B(WINGULL))]);
add(279,"패리퍼","Pelipper",null,[e("C","25-44",["sky","day","treetop"],B(WINGULL))]);
add(280,"랄토스","Ralts",null,[e("R","1-20",["sky"],B(RALTS)),e("R","1-20",["sky"],S(VILALL)),e("C","1-20",["indoor","minY62"],S(MANSION))]);
add(281,"킬리아","Kirlia",null,[e("R","20-29",["sky"],B(RALTS)),e("R","20-29",["sky"],S(VILALL)),e("C","20-29",["indoor","minY62"],S(MANSION))]);
add(282,"가디안","Gardevoir",null,[e("R","30-52",["sky"],B(RALTS)),e("R","30-52",["sky"],S(VILALL)),e("C","30-52",["indoor","minY62"],S(MANSION))]);
add(283,"비구술","Surskit",null,[e("U","2-27",["surf","sky","norain"],B(SURSKIT))]);
add(284,"비나방","Masquerain",null,[e("U","22-45",["surf","sky","norain"],B(SURSKIT))]);
add(285,"버섯꼬","Shroomish",null,[e("C","5-30",["sky"],B(SHROOMISH)),e("C","5-30",["sky"],B(SHROOMISH2))]);
add(286,"버섯모","Breloom",null,[e("C","23-46",["sky"],B(SHROOMISH)),e("C","23-46",["sky"],B(SHROOMISH2))]);
add(287,"게을로","Slakoth",null,[e("C","3-28",["sky","treetop"],B(JUNGLE))]);
add(288,"발바로","Vigoroth",null,[e("C","18-44",["sky","treetop"],B(JUNGLE))]);
add(289,"게을킹","Slaking",null,[e("C","36-67",["sky"],B(JUNGLE))]);
add(290,"토중몬","Nincada",null,[e("C","2-27",["dim","minY32","maxY62"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"]))]);
add(291,"아이스크","Ninjask",null,[e("C","20-46",["sky","day","norain"],B(NINJASK))]);
add(292,"껍질몬","Shedinja",null,[e("U","20-24",["night","norain"],B(NINJASK))]);
add(293,"소곤룡","Whismur",null,[e("U","1-24",["dim"],B(WHISMUR)),e("C","1-24",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(294,"노공룡","Loudred",null,[e("U","20-39",["dim"],B(WHISMUR)),e("C","20-39",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(295,"폭음룡","Exploud",null,[e("U","40-49",["dim"],B(WHISMUR)),e("C","40-49",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(296,"마크탕","Makuhita",null,[e("C","1-24",["sky","n025"],B(MAKUHITA))]);
add(297,"하리뭉","Hariyama",null,[e("C","24-47",["sky","n025"],B(MAKUHITA))]);
add(298,"루리리","Azurill",null,[e("C","1-19",["sky"],B(["River","Warm River"])),e("U","1-19",["surf","sky"],B(RIVERS))]);
add(299,"코코파스","Nosepass",null,[e("U","13-38",["dim"],OW(["?#cobblemon:is_deep_dark"]))]);
add(300,"에나비","Skitty",null,[e("C","1-35",["seeSky","norain","n15"],OW(["건조 계열","얼음 계열"])),e("C","4-29",["seeSky","n15"],B(SKITTY)),e("C","4-29",["seeSky"],B(["Cherry Grove"]))]);
add(301,"델케티","Delcatty",null,[e("U","15-55",["seeSky","norain","n15"],OW(["건조 계열","얼음 계열"])),e("U","15-55",["seeSky","n15"],B(SKITTY)),e("U","15-55",["seeSky","n15"],B(["Cherry Grove"]))]);
add(302,"깜까미","Sableye",null,[e("C","13-38",["dim","gems"],OW()),e("R","13-38",["dim"],B(WHISMUR))]);
add(303,"입치트","Mawile",null,[e("U","13-38",["dim"],B(WHISMUR)),e("R","13-38",["dim"],OW(["?#cobblemon:is_deep_dark"]))]);
add(304,"가보리","Aron",null,[e("C","8-33",[],B(MAKUHITA)),e("C","8-33",["dim","iron"],OW(["?#cobblemon:is_deep_dark"]))]);
add(305,"갱도라","Lairon",null,[e("C","32-43",[],B(MAKUHITA)),e("C","32-43",["dim","iron"],OW(["?#cobblemon:is_deep_dark"]))]);
add(306,"보스로라","Aggron",null,[e("C","42-53",[],B(MAKUHITA)),e("C","42-53",["dim","iron"],OW(["?#cobblemon:is_deep_dark"]))]);
add(307,"요가랑","Meditite",null,[e("C","3-28",["sky","n025"],B(MEDITITE))]);
add(308,"요가램","Medicham",null,[e("C","37-41",["sky","n025"],B(MEDITITE)),e("C","37-41",["minY48","n025"],OW())]);
add(309,"썬더라이","Electrike",null,[e("C","5-30",["sky","t5"],B(ELECTRIKE))]);
add(310,"썬더볼트","Manectric",null,[e("C","26-48",["sky","t5"],B(ELECTRIKE))]);
add(311,"플러시","Plusle",null,[e("U","16-41",["sky","t5"],B(TORCHIC))]);
add(312,"마이농","Minun",null,[e("U","16-41",["sky","t5"],B(TORCHIC))]);
add(313,"볼비트","Volbeat",null,[e("C","18-43",["sky","night","norain","treetop"],B(SURSKIT)),e("U","18-43",["surf","sky","night","norain"],B(SURSKIT))]);
add(314,"네오비트","Illumise",null,[e("C","18-43",["sky","night","norain","treetop"],B(SURSKIT)),e("U","18-43",["surf","sky","night","norain"],B(SURSKIT))]);
add(315,"로젤리아","Roselia",null,[e("C","23-40",["sky"],B(FLOWER))]);
add(316,"꼴깍몬","Gulpin",null,[e("C","8-25",[],B(SWAMP))]);
add(317,"꿀꺽몬","Swalot",null,[e("U","25-48",[],B(SWAMP))]);
add(318,"샤프니아","Carvanha",null,[e("C","6-31",["sub","seeSky"],B(CARVANHA)),e("C","6-31",["sub","indoor","sky"],B(CARVANHA)),e("C","6-31",["sub","indoor","subY"],S(SSC))]);
add(319,"샤크니아","Sharpedo",null,[e("C","30-46",["sub","seeSky"],B(SHARPEDO)),e("C","30-46",["sub","indoor","sky"],B(SHARPEDO)),e("C","30-46",["sub","indoor","subY"],S(SSC))]);
add(320,"고래왕자","Wailmer",null,[e("U","15-40",["sub","seeSky"],B(WAILMER)),e("U","15-40",["sub","indoor","sky"],B(WAILMER))]);
add(321,"고래왕","Wailord",null,[e("U","40-50",["sub","seeSky"],B(WAILMER)),e("U","40-50",["sub","indoor","sky"],B(WAILMER))]);
add(322,"둔타","Numel",null,[e("C","6-31",["sky","n025"],B(NUMEL)),e("C","6-31",["sky","n025"],B(NUMEL2)),e("C","6-31",[],B(["Nether Wastes"]))]);
add(323,"폭타","Camerupt",null,[e("C","33-46",["sky","n025"],B(NUMEL)),e("C","33-46",["sky","n025"],B(NUMEL2)),e("C","33-46",[],B(["Nether Wastes"]))]);
add(324,"코터스","Torkoal",null,[e("C","22-47",[],B(["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs","Caldera","Thermal Caves","Yellowstone"])),e("U","22-47",["dim","coal"],OW(["?#cobblemon:is_deep_dark","산 계열","온열 계열","평원 계열","숲 계열"])),e("C","22-47",[],B(["Basalt Deltas"]))]);
add(325,"피그점프","Spoink",null,[e("C","8-33",["sky"],B(SPOINK)),e("C","8-33",[],B(["Crimson Forest","Warped Forest"]))]);
add(326,"피그킹","Grumpig",null,[e("C","32-47",["sky"],B(SPOINK)),e("C","32-47",[],B(["Crimson Forest","Warped Forest"]))]);
add(327,"얼루기","Spinda",null,[e("U","11-36",["sky"],B(SPINDA))]);
add(327,"얼루기","Spinda","특수 무늬",[e("U","11-36",["sky"],B(SPINDA))]);
add(328,"톱치","Trapinch",null,[e("R","4-29",["sky","rain15"],B(TRAPINCH)),e("U","4-29",["dim","minY0"],B(TRAPINCH))]);
add(329,"비브라바","Vibrava",null,[e("R","35-40",["sky","rain","rain15"],B(TRAPINCH))]);
add(330,"플라이곤","Flygon",null,[e("R","45-52",["sky","rain","rain15"],B(TRAPINCH))]);
add(331,"선인왕","Cacnea",null,[e("C","9-34",["sky","n15"],B(CACNEA))]);
add(332,"밤선인","Cacturne",null,[e("C","32-48",["sky","n15"],B(CACNEA))]);
add(333,"파비코","Swablu",null,[e("U","6-31",["sky","norain","minY190","treetop","n025"],OW(["봉우리 계열","하늘 계열","얼음 계열"])),e("U","6-31",["sky","norain","treetop","n025"],B(SWABLU))]);
add(334,"파비코리","Altaria",null,[e("U","35-49",["sky","norain","minY190","treetop","n025"],OW(["봉우리 계열","하늘 계열","얼음 계열"])),e("U","35-49",["sky","norain","treetop","n025"],B(SWABLU))]);
add(335,"쟝고","Zangoose",null,[e("U","25-58",["sky"],B(TORCHIC))]);
add(336,"세비퍼","Seviper",null,[e("U","25-58",["sky"],B(TRAPINCH))]);
add(337,"루나톤","Lunatone",null,[e("U","21-46",["sky","night","fullmoon5"],B(LUNATONE)),e("C","21-46",["dim","n025"],B(LUNATONE)),e("U","21-46",["sky","night","fullmoon5"],B(MAKUHITA)),e("C","21-46",["sky","n5"],S(["Luna Henge Ruins"]))]);
add(338,"솔록","Solrock",null,[e("U","21-46",["sky","day"],B(LUNATONE)),e("C","21-46",["dim","d025"],B(LUNATONE)),e("U","21-46",["sky","day"],B(MAKUHITA)),e("C","21-46",["sky","d5"],S(["Sol Henge Ruins"]))]);
add(339,"미꾸리","Barboach",null,[e("C","4-29",["sub","seeSky"],B(SWAMP)),e("U","4-29",["sub","dim"],OW()),e("C","4-29",["sub","indoor","sky"],B(SWAMP))]);
add(340,"메깅","Whiscash",null,[e("C","30-47",["sub","seeSky"],B(SWAMP)),e("U","30-47",["sub","dim"],OW()),e("C","30-47",["sub","indoor","sky"],B(SWAMP))]);
add(341,"가재군","Corphish",null,[e("C","6-31",["sky"],B(SURSKIT)),e("C","6-31",["floor","seeSky"],B(SURSKIT))]);
add(342,"가재장군","Crawdaunt",null,[e("C","30-47",["sky"],B(SURSKIT)),e("C","30-47",["floor","seeSky"],B(SURSKIT))]);
add(343,"오뚝군","Baltoy",null,[e("U","5-30",["dim","minY0"],B(CACNEA))]);
add(344,"점토도리","Claydol",null,[e("U","36-50",["dim","minY0"],B(CACNEA)),e("C","36-50",["indoor","minY48"],OW())]);
add(345,"릴링","Lileep",null,[e("X","11-36",["floor","dim"],B(LUSHC))]);
add(346,"릴리요","Cradily",null,[e("X","40-50",["floor","dim"],B(LUSHC))]);
add(347,"아노딥스","Anorith",null,[e("X","11-36",["dim"],B(LUSHC)),e("X","11-36",["sub","dim"],B(LUSHC))]);
add(348,"아말도","Armaldo",null,[e("X","40-50",["dim"],B(LUSHC)),e("X","40-50",["sub","dim"],B(LUSHC))]);
add(349,"빈티나","Feebas",null,[e("C","1-20",["fish","slime"],OW(["해안 계열","바다 계열"])),e("C","1-20",["fish","lure1","slime"],OW(["해안 계열","바다 계열"]))]);
add(350,"밀로틱","Milotic",null,[e("C","15-54",["fish","slime"],OW(["해안 계열","바다 계열"])),e("C","15-54",["fish","lure1","slime"],OW(["해안 계열","바다 계열"]))]);
add(351,"캐스퐁","Castform","빗방울의 모습",[e("U","15-65",["rain"],B(["Beach","Snowy Beach","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"]))]);
add(351,"캐스퐁","Castform","설운의 모습",[e("U","15-65",["norain"],B(["Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands"]))]);
add(351,"캐스퐁","Castform","태양의 모습",[e("U","15-65",["day"],B(SKITTY))]);
add(351,"캐스퐁","Castform",null,[e("U","15-65",[],B(["Mushroom Fields","Deep Frozen Ocean","Frozen Ocean","Deep Cold Ocean","Cold Ocean","Deep Ocean","Ocean","Deep Lukewarm Ocean","Lukewarm Ocean","Warm Ocean","Stony Shore","Swamp","Mangrove Swamp","Snowy Slopes","Snowy Plains","Snowy Beach","Windswept Gravelly Hills","Grove","Windswept Hills","Snowy Taiga","Windswept Forest","Taiga","Plains","Meadow","Beach","Forest","Old Growth Spruce Taiga","Flower Forest","Birch Forest","Dark Forest","Savanna Plateau","Savanna","Jungle","Badlands","Desert","Wooded Badlands","Jagged Peaks","Stony Peaks","Frozen River","River","Ice Spikes","Old Growth Pine Taiga","Sunflower Plains","Old Growth Birch Forest","Sparse Jungle","Bamboo Jungle","Eroded Badlands","Windswept Savanna","Cherry Grove","Frozen Peaks","Dripstone Caves","Lush Caves","Deep Dark"]))]);
add(352,"켈리몬","Kecleon",null,[e("U","19-44",["sky"],B(JUNGLE))]);
add(353,"어둠대신","Shuppet",null,[e("C","5-30",["night"],B(["Dark Forest","Deep Dark"])),e("U","5-30",["sky","night"],OW()),e("U","5-30",["sky","night"],S(VILALL)),e("C","5-30",["indoor","night","minY62"],S(MANSION))]);
add(354,"다크펫","Banette",null,[e("C","37-46",["night"],B(["Dark Forest","Deep Dark"])),e("U","37-46",["sky","night"],OW()),e("U","37-46",["sky","night"],S(VILALL)),e("C","37-46",["indoor","night","minY62"],S(MANSION))]);
add(355,"해골몽","Duskull",null,[e("C","5-30",["sky","night"],B(["Dark Forest","Deep Dark"])),e("C","5-30",[],B(["Soul Sand Valley"]))]);
add(356,"미라몽","Dusclops",null,[e("C","37-46",["sky","night"],B(["Dark Forest","Deep Dark"])),e("C","37-46",[],B(["Soul Sand Valley"]))]);
add(357,"트로피우스","Tropius",null,[e("U","21-46",["sky","n025"],B(JUNGLE))]);
add(358,"치렁","Chimecho",null,[e("U","24-46",["night"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Windswept Savanna","Lush Valley","Moonlight Valley","Savanna Slopes","Yosemite Lowlands","Stony Spires","Windswept Spires","Yosemite Cliffs","Deep Dark","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Shield","Siberian Taiga","Yellowstone"])),e("U","24-46",["sky","night"],B(MYST)),e("U","24-46",["night","bell"],OW())]);
add(359,"앱솔","Absol",null,[e("R","22-47",["sky"],B(["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Windswept Spires","Yosemite Cliffs","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Moonlight Grove","Shield","Siberian Taiga","Yellowstone"]))]);
add(360,"마자","Wynaut",null,[e("R","1-26",["sky"],B(TORCHIC))]);
add(361,"눈꼬마","Snorunt",null,[e("U","5-30",["sky"],B(SNORUNT)),e("U","5-30",["dim","minY0"],B(["Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Frozen Peaks","Ice Spikes","Frostfire Caves","Frozen Cliffs","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands","Gravel Desert","Rocky Shrubland","Yellowstone"])),e("C","5-30",["sky115"],S(["Igloo"]))]);
add(362,"얼음귀신","Glalie",null,[e("U","42-48",["sky","norain"],B(SNORUNT)),e("U","42-48",["dim","minY0"],B(["Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Ice Spikes","Snowy Plains","Cold Shrubland","Gravel Desert","Rocky Shrubland","Snowy Badlands","Yellowstone"]))]);
add(363,"대굴레오","Spheal",null,[e("C","4-29",["sky"],B(SPHEAL)),e("C","4-29",["sub","seeSky"],B(SPHEAL)),e("C","4-29",["sub","indoor","sky"],B(SPHEAL))]);
add(364,"씨레오","Sealeo",null,[e("C","32-41",["sky"],B(SPHEAL)),e("C","32-41",["sub","seeSky"],B(SPHEAL)),e("C","32-41",["sub","indoor","sky"],B(SPHEAL))]);
add(365,"씨카이저","Walrein",null,[e("C","44-53",["sky"],B(SPHEAL)),e("C","44-53",["sub","seeSky"],B(SPHEAL)),e("C","44-53",["sub","indoor","sky"],B(SPHEAL))]);
add(366,"진주몽","Clamperl",null,[e("U","10-35",["floor","seeSky","maxY48"],B(WAILMER)),e("R","10-35",["floor","seeSky"],B(["Warm Ocean"])),e("U","10-35",["floor","indoor","subY"],S(SSC))]);
add(367,"헌테일","Huntail",null,[e("U","30-49",["sub","seeSky","maxY48"],B(WAILMER)),e("R","30-49",["sub","seeSky"],B(["Warm Ocean"])),e("U","30-49",["sub","indoor","sky","maxY48"],B(WAILMER)),e("R","30-49",["sub","indoor","sky"],B(["Warm Ocean"])),e("U","30-49",["sub","indoor","subY"],S(SSC))]);
add(368,"분홍장이","Gorebyss",null,[e("U","30-49",["sub","seeSky","maxY48"],B(WAILMER)),e("R","30-49",["sub","seeSky"],B(["Warm Ocean"])),e("U","30-49",["sub","indoor","sky","maxY48"],B(WAILMER)),e("R","30-49",["sub","indoor","sky"],B(["Warm Ocean"])),e("U","30-49",["sub","indoor","subY"],S(SSC))]);
add(369,"시라칸","Relicanth",null,[e("U","24-49",["sub","maxY48"],B(WAILMER)),e("C","24-49",["sub","seeSky","maxY62"],{b:SHARPEDO,s:RUINS}),e("R","24-49",["sub","dim","maxY48"],OW(["깊은 바다 계열","무성한 계열"])),e("C","24-49",["sub","indoor","sky","maxY62"],{b:SHARPEDO,s:RUINS}),e("U","24-49",["sub","indoor","subY"],S(SSC))]);
add(370,"사랑동이","Luvdisc",null,[e("C","8-33",["sub","seeSky","day"],B(["Warm Ocean"])),e("C","8-33",["sub","indoor","sky","day"],B(["Warm Ocean"]))]);
add(371,"아공이","Bagon",null,[e("X","5-30",["sky"],B(["Stony Peaks","Rocky Mountains","Windswept Spires"])),e("X","5-30",["sky"],B(LUNATONE)),e("R","5-30",["dim"],B(LUNATONE))]);
add(372,"쉘곤","Shelgon",null,[e("X","30-42",["sky"],B(LUNATONE)),e("R","30-42",["dim"],B(LUNATONE))]);
add(373,"보만다","Salamence",null,[e("X","50-60",["sky"],B(SWABLU)),e("X","50-60",["sky"],B(LUNATONE)),e("R","50-60",["dim"],B(LUNATONE))]);
add(374,"메탕","Beldum",null,[e("X","5-30",[],B(BELDUM)),e("R","5-30",[],END)]);
add(375,"메탕구","Metang",null,[e("X","20-44",[],B(BELDUM)),e("R","20-44",[],END)]);
add(376,"메타그로스","Metagross",null,[e("X","45-60",[],B(BELDUM)),e("R","45-60",[],END)]);
add(377,"레지락","Regirock",null,[e("X","40-50",["special"],S(["Regirock Temple (Hoenn)"]))]);
add(378,"레지아이스","Regice",null,[e("X","40-50",["special"],S(["Regice Temple (Hoenn)"]))]);
add(379,"레지스틸","Registeel",null,[e("X","40-50",["special"],S(["Registeel Temple (Hoenn)"]))]);
add(380,"라티아스","Latias",null,[e("X","50-75",["special"],S(["Secret Garden (Hoenn)"]))]);
add(381,"라티오스","Latios",null,[e("X","50-75",["special"],S(["Secret Garden (Hoenn)"]))]);
add(382,"가이오가","Kyogre",null,[e("X","60-70",["special"],S(["Kyogre Dome (Hoenn)"]))]);
add(383,"그란돈","Groudon",null,[e("X","60-70",["special"],S(["Groudon Volcano (Hoenn)"]))]);
add(384,"레쿠쟈","Rayquaza",null,[e("X","70-80",["special"],S(["Sky Pillar (Hoenn)"]))]);
add(384,"레쿠쟈","Rayquaza","색이 다른 개체 (플레이어당 1마리)",[e("X","100",["special"],S(["End Podium"]))]);
add(385,"지라치","Jirachi",null,[e("X","75-80",["special"],S(["Wish Cave (Hoenn)"]))]);
add(386,"테오키스","Deoxys",null,[e("X","75-80",["special"],S(["Deoxys Meteorite (Hoenn)"]))]);

// 출현 시점 안내 (LUMYVERSE 공식 사이트 lumyverse.com/en/cobbleverse/how-to-catch-all-legendary-mythical-pokemon: 호연 데이터팩은 성도 챔피언(목호)을 이긴 뒤에 열림. 엔드 첫 입장 때 나오는 색이 다른 레쿠쟈는 별도)
Object.assign(UNLOCK,{377:"성도 시리즈 클리어(챔피언 목호 승리) 후",378:"성도 시리즈 클리어(챔피언 목호 승리) 후",379:"성도 시리즈 클리어(챔피언 목호 승리) 후",380:"성도 시리즈 클리어(챔피언 목호 승리) 후",381:"성도 시리즈 클리어(챔피언 목호 승리) 후",382:"성도 시리즈 클리어(챔피언 목호 승리) 후",383:"성도 시리즈 클리어(챔피언 목호 승리) 후",384:"하늘기둥: 성도 시리즈 클리어(챔피언 목호 승리) 후",385:"성도 시리즈 클리어(챔피언 목호 승리) 후",386:"성도 시리즈 클리어(챔피언 목호 승리) 후"});
