// ---- 5세대 (COBBLEVERSE 모드팩 1.7.42 데이터팩 COBBLEVERSE-DP-v31 기준) ----
const TEPIG=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const OSHAWOTT=["Stony Shore","Basalt Cliffs","Granite Cliffs","White Cliffs"];
const PATRAT=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes"];
const PURRLOIN=["Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const PURRLOIN2=["Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland"];
const PANSAGE=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"];
const PANSEAR=["Mantle Caves","Volcanic Crater","Volcanic Peaks"];
const PIDOVE=["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Windswept Spires","Yosemite Cliffs","Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter"];
const ROGGENROLA=["Deep Dark","Crystal Caves","Deep Caves","Frostfire Caves","Mantle Caves","Tuff Caves"];
const WOOBAT=["Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland"];
const TYMPOLE=["Swamp","Ice Marsh","Orchid Swamp"];
const THROH=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland"];
const SEWADDLE=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"];
const PETILIL=["Flower Forest","Sunflower Plains","Sakura Grove","Cloud Forest","Lavender Forest"];
const PETILIL2=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Alpha Islands","Lavender Forest","Mirage Isles","Sakura Grove"];
const PETILIL3=["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Blooming Plateau","Highlands","Cherry Grove","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Temperate Highlands","Yosemite Lowlands"];
const BASCULIN=["River","Frozen River","Warm River","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];
const SANDILE=["Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Red Oasis","Sandstone Valley"];
const DARUMAKA=["Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Red Oasis","Sandstone Valley","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"];
const DARUMAKA2=["Frozen Peaks","Ice Spikes","Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands","Cold Ocean","Deep Cold Ocean","Stony Peaks","Rocky Mountains","Windswept Spires","Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Haze Mountain","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands","Gravel Desert","Rocky Shrubland","Windswept Hills","Windswept Gravelly Hills","Windswept Forest","Stony Shore","The End","Small End Islands","End Midlands","End Highlands","End Barrens"];
const MARACTUS=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley"];
const DWEBBLE=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa"];
const SCRAGGY=["Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland"];
const ZORUA=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"];
const ZORUA2=["Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const DUCKLETT=["River","Warm River","Mangrove Swamp","Swamp","Orchid Swamp"];
const DUCKLETT2=["Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter"];
const VANILLITE=["Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands"];
const DEERLING=["Cherry Grove","Flower Forest","Meadow","Sunflower Plains","Sakura Grove","Sakura Valley","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Alpha Islands","Alpha Islands Winter","Forested Highlands","Mirage Isles","Temperate Highlands","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Highlands","Snowy Slopes","Lush Valley","Moonlight Valley","Yosemite Lowlands","Plains","Steppe","Valley Clearing","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Haze Mountain","Moonlight Grove","Shield","Siberian Taiga","Yellowstone"];
const FOONGUS=["Dark Forest","Mushroom Fields","Fungal Caves","Mirage Isles","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];
const FOONGUS2=["Dark Forest","Mushroom Fields","Fungal Caves","Mirage Isles"];
const FRILLISH=["Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs"];
const ALOMOMOLA=["Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean"];
const JOLTIK=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland"];
const KLINK=["Dripstone Caves","Lush Caves","Deep Dark","Andesite Caves","Desert Caves","Diorite Caves","Fungal Caves","Granite Caves","Infested Caves","Thermal Caves","Underground Jungle"];
const AXEW=["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"];
const CUBCHOO=["Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs"];
const MIENFOO=["Frozen Peaks","Jagged Peaks","Stony Peaks","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"];
const RUFFLET=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands"];
const RUFFLET2=["Frozen Peaks","Jagged Peaks","Stony Peaks","Stony Spires","Windswept Spires","Yosemite Cliffs"];

add(494,"비크티니","Victini",null,[e("X","50",[],B(["Crimson Forest"]))]);
add(495,"주리비얀","Snivy",null,[e("X","5-31",["sky","treetop"],B(JUNGLE))]);
add(496,"샤비","Servine",null,[e("X","17-41",["sky","treetop"],B(JUNGLE))]);
add(497,"샤로다","Serperior",null,[e("X","36-53",["sky","treetop"],B(JUNGLE))]);
add(498,"뚜꾸리","Tepig",null,[e("X","5-31",["sky"],B(TEPIG)),e("X","5-31",[],B(["Crimson Forest"]))]);
add(499,"차오꿀","Pignite",null,[e("X","17-42",["sky"],B(TEPIG)),e("X","17-42",[],B(["Crimson Forest"]))]);
add(500,"염무왕","Emboar",null,[e("X","36-53",["sky","norain"],B(TEPIG)),e("X","36-53",[],B(["Crimson Forest"]))]);
add(501,"수댕이","Oshawott",null,[e("X","5-31",["sky"],B(["Beach"])),e("X","5-31",["surf","sky"],B(["Beach"]))]);
add(501,"수댕이","Oshawott","히스이 계열",[e("X","5-31",["sky"],B(OSHAWOTT)),e("X","5-31",["surf","sky"],B(OSHAWOTT)),e("X","5-31",["sky"],B(["Snowy Beach"])),e("X","5-31",["surf","sky"],B(["Snowy Beach"]))]);
add(502,"쌍검자비","Dewott",null,[e("X","17-41",["sky"],B(["Beach"])),e("X","17-41",["surf","sky"],B(["Beach"]))]);
add(502,"쌍검자비","Dewott","히스이 계열",[e("X","17-41",["sky"],B(OSHAWOTT)),e("X","17-41",["surf","sky"],B(OSHAWOTT)),e("X","17-41",["sky"],B(["Snowy Beach"])),e("X","17-41",["surf","sky"],B(["Snowy Beach"]))]);
add(503,"대검귀","Samurott",null,[e("X","36-53",["sky"],B(["Beach"])),e("X","36-53",["surf","sky"],B(["Beach"]))]);
add(503,"대검귀","Samurott","히스이",[e("X","36-53",["sky"],B(OSHAWOTT)),e("X","36-53",["surf","sky"],B(OSHAWOTT)),e("X","36-53",["sky"],B(["Snowy Beach"])),e("X","36-53",["surf","sky"],B(["Snowy Beach"]))]);
add(504,"보르쥐","Patrat",null,[e("C","1-26",["sky"],B(PATRAT))]);
add(505,"보르그","Watchog",null,[e("C","20-42",["sky"],B(PATRAT))]);
add(506,"요테리","Lillipup",null,[e("C","3-28",["sky"],OW(["사막 계열"])),e("C","3-28",["sky"],{all:"ow",ex:["사막 계열"],s:VILALL})]);
add(507,"하데리어","Herdier",null,[e("C","16-37",["sky"],OW(["사막 계열"])),e("C","16-37",["sky"],{all:"ow",ex:["사막 계열"],s:VILALL})]);
add(508,"바랜드","Stoutland",null,[e("C","32-50",["sky"],OW(["사막 계열"])),e("C","32-50",["sky"],{all:"ow",ex:["사막 계열"],s:VILALL})]);
add(509,"쌔비냥","Purrloin",null,[e("C","3-28",["sky","night","norain"],B(PURRLOIN)),e("C","3-28",["sky","night"],B(PURRLOIN2)),e("C","3-28",["sky","norain","concrete","n15"],OW(["건조 계열","얼음 계열","타이가 계열"])),e("C","3-28",["sky","norain","n15"],{all:"ow",ex:["건조 계열","얼음 계열","타이가 계열"],s:VILALL}),e("C","3-28",["sky","concrete","n15"],B(PURRLOIN2)),e("C","3-28",["sky","n15"],{b:PURRLOIN2,s:VILALL}),e("C","3-28",["indoor","minY62"],S(MANSION)),e("C","3-28",["sky","norain","n15"],S(["Swamp Hut"]))]);
add(510,"레파르다스","Liepard",null,[e("C","20-45",["sky","night","norain"],B(PURRLOIN)),e("C","20-45",["sky","night"],B(PURRLOIN2)),e("C","20-45",["sky","norain","concrete","n15"],OW(["건조 계열","얼음 계열","타이가 계열"])),e("C","20-45",["sky","norain","n15"],{all:"ow",ex:["건조 계열","얼음 계열","타이가 계열"],s:VILALL}),e("C","20-45",["sky","concrete","n15"],B(PURRLOIN2)),e("C","20-45",["sky","n15"],{b:PURRLOIN2,s:VILALL}),e("C","20-45",["indoor","minY62"],S(MANSION)),e("C","20-45",["sky","norain","n15"],S(["Swamp Hut"]))]);
add(511,"야나프","Pansage",null,[e("U","7-32",["sky","treetop","n025"],B(JUNGLE)),e("U","7-32",["sky","treetop","n025"],B(PANSAGE))]);
add(512,"야나키","Simisage",null,[e("U","27-50",["sky","treetop","n025"],B(JUNGLE)),e("U","27-50",["sky","treetop","n025"],B(PANSAGE))]);
add(513,"바오프","Pansear",null,[e("U","7-32",["sky","treetop","n025"],B(JUNGLE)),e("U","7-32",["sky","treetop","n025"],B(PANSEAR))]);
add(514,"바오키","Simisear",null,[e("U","27-50",["sky","treetop","n025"],B(JUNGLE)),e("U","27-50",["sky","treetop","n025"],B(PANSEAR))]);
add(515,"앗차프","Panpour",null,[e("U","7-32",["sky","treetop","n025"],B(JUNGLE)),e("U","7-32",["sky","treetop","n025"],B(["River","Warm River"]))]);
add(516,"앗차키","Simipour",null,[e("U","27-50",["sky","treetop","n025"],B(JUNGLE)),e("U","27-50",["sky","treetop","n025"],B(["River","Warm River"]))]);
add(517,"몽나","Munna",null,[e("C","4-29",["sky","night"],OW()),e("C","4-29",["night","whitebed"],OW()),e("C","4-29",["sky","night"],S(VILALL))]);
add(518,"몽얌나","Musharna",null,[e("C","24-49",["sky","night"],OW()),e("C","25-50",["night","whitebed"],OW()),e("C","24-49",["sky","night"],S(VILALL))]);
add(519,"콩둘기","Pidove",null,[e("C","1-26",["sky","day","treetop"],B(PIDOVE)),e("C","1-26",["sky","day","concrete"],OW(["건조 계열","툰드라 계열"])),e("C","1-26",["sky","day"],{all:"ow",ex:["건조 계열","툰드라 계열"],s:VILALL})]);
add(520,"유토브","Tranquill",null,[e("C","21-36",["sky","day","treetop"],B(PIDOVE)),e("C","21-36",["sky","day","concrete"],OW(["건조 계열","툰드라 계열"])),e("C","21-36",["sky","day"],{all:"ow",ex:["건조 계열","툰드라 계열"],s:VILALL})]);
add(521,"켄호로우","Unfezant",null,[e("C","32-49",["sky","day","treetop"],B(PIDOVE)),e("C","32-49",["sky","day","concrete"],OW(["건조 계열","툰드라 계열"])),e("C","32-49",["sky","day"],{all:"ow",ex:["건조 계열","툰드라 계열"],s:VILALL})]);
add(522,"줄뮤마","Blitzle",null,[e("C","5-30",["sky","n025","t5"],B(PURRLOIN2))]);
add(523,"제브라이카","Zebstrika",null,[e("C","27-50",["sky","n025","t5"],B(PURRLOIN2))]);
add(524,"단굴","Roggenrola",null,[e("C","3-28",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"])),e("U","3-28",["dim"],B(ROGGENROLA))]);
add(525,"암트르","Boldore",null,[e("C","25-39",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"])),e("U","25-39",["dim"],B(ROGGENROLA))]);
add(526,"기가이어스","Gigalith",null,[e("C","34-52",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"])),e("U","34-52",["dim"],B(ROGGENROLA))]);
add(527,"또르박쥐","Woobat",null,[e("C","7-32",["night","norain","treetop"],B(WOOBAT)),e("C","7-32",["dim","n025"],B(WOOBAT))]);
add(528,"맘박쥐","Swoobat",null,[e("C","27-43",["night","norain","treetop"],B(WOOBAT)),e("C","27-43",["dim","n025"],B(WOOBAT))]);
add(529,"두더류","Drilbur",null,[e("C","8-33",["dim"],OW(["?#cobblemon:is_deep_dark"]))]);
add(530,"몰드류","Excadrill",null,[e("C","31-51",["dim"],OW(["?#cobblemon:is_deep_dark"]))]);
add(531,"다부니","Audino",null,[e("R","19-47",["seeSky"],B(["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"]))]);
add(532,"으랏차","Timburr",null,[e("C","6-31",["sky","n025"],OW(["모래 계열","툰드라 계열"])),e("C","6-31",["sky","n025"],{all:"ow",ex:["모래 계열","툰드라 계열"],s:VILALL})]);
add(533,"토쇠골","Gurdurr",null,[e("C","25-41",["sky","n025"],OW(["모래 계열","툰드라 계열"])),e("C","25-41",["sky","n025"],{all:"ow",ex:["모래 계열","툰드라 계열"],s:VILALL})]);
add(534,"노보청","Conkeldurr",null,[e("C","36-51",["sky","n025"],OW(["모래 계열","툰드라 계열"])),e("C","36-51",["sky","n025"],{all:"ow",ex:["모래 계열","툰드라 계열"],s:VILALL})]);
add(535,"동챙이","Tympole",null,[e("C","1-21",["dim"],B(LUSHC)),e("C","1-21",["sub","dim"],B(LUSHC)),e("U","1-21",["dim","maxY62","water"],OW(["무성한 계열"])),e("U","1-21",["sub","dim","maxY62"],OW(["무성한 계열"])),e("C","1-21",["sky","rain"],B(TYMPOLE)),e("C","1-21",["sub","seeSky"],B(TYMPOLE)),e("C","1-21",["sub","indoor","sky"],B(TYMPOLE)),e("C","1-21",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("C","1-21",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(535,"동챙이","Tympole","팔데아",[e("C","1-21",["sky"],B(["Mangrove Swamp","Underground Jungle"])),e("C","1-21",["sub","seeSky"],B(["Mangrove Swamp","Underground Jungle"])),e("U","1-21",["sky","water"],B(PURRLOIN2)),e("U","1-21",["sub","seeSky"],B(PURRLOIN2)),e("C","1-21",["sub","indoor","sky"],B(["Mangrove Swamp","Underground Jungle"])),e("U","1-21",["sub","indoor","sky"],B(PURRLOIN2))]);
add(536,"두까비","Palpitoad",null,[e("C","20-43",["dim"],B(LUSHC)),e("C","20-43",["sub","dim"],B(LUSHC)),e("U","20-43",["dim","maxY62","water"],OW(["무성한 계열"])),e("U","20-43",["sub","dim","maxY62"],OW(["무성한 계열"])),e("C","20-43",["sky","rain"],B(TYMPOLE)),e("C","20-43",["sub","seeSky"],B(TYMPOLE)),e("C","20-43",["sub","indoor","sky"],B(TYMPOLE)),e("C","20-43",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("C","20-43",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(537,"두빅굴","Seismitoad",null,[e("C","20-43",["dim"],B(LUSHC)),e("C","20-43",["sub","dim"],B(LUSHC)),e("U","20-43",["dim","maxY62","water"],OW(["무성한 계열"])),e("U","20-43",["sub","dim","maxY62"],OW(["무성한 계열"])),e("C","20-43",["sky","rain"],B(TYMPOLE)),e("C","20-43",["sub","seeSky"],B(TYMPOLE)),e("C","20-43",["sub","indoor","sky"],B(TYMPOLE)),e("C","20-43",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("C","20-43",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(538,"던지미","Throh",null,[e("R","36-63",[],B(THROH))]);
add(539,"타격귀","Sawk",null,[e("R","36-63",[],B(THROH))]);
add(540,"두르보","Sewaddle",null,[e("C","6-31",["sky"],B(SEWADDLE))]);
add(541,"두르쿤","Swadloon",null,[e("C","20-38",["sky"],B(SEWADDLE))]);
add(542,"모아머","Leavanny",null,[e("C","33-50",["sky"],B(SEWADDLE))]);
add(543,"마디네","Venipede",null,[e("C","1-26",["night"],B(PANSAGE)),e("C","1-26",["night"],B(JUNGLE)),e("C","1-26",["dim"],B(LUSHC)),e("C","1-26",[],B(["Crimson Forest","Warped Forest"])),e("C","1-26",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(544,"휠구","Whirlipede",null,[e("C","22-36",["sky","night"],B(PANSAGE)),e("C","22-36",["sky","night"],B(JUNGLE)),e("C","22-36",["dim"],B(LUSHC)),e("C","22-36",[],B(["Crimson Forest","Warped Forest"])),e("C","22-36",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(545,"펜드라","Scolipede",null,[e("C","30-49",["sky","night"],B(PANSAGE)),e("C","30-49",["sky","night"],B(JUNGLE)),e("C","30-49",["dim"],B(LUSHC)),e("C","30-49",[],B(["Crimson Forest","Warped Forest"])),e("C","30-49",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(546,"소미안","Cottonee",null,[e("C","3-28",["sky","norain","n025"],B(TEPIG))]);
add(547,"엘풍","Whimsicott",null,[e("C","23-48",["sky","norain","n025"],B(TEPIG))]);
add(548,"치릴리","Petilil",null,[e("C","3-28",["sky","n025"],B(PETILIL)),e("C","3-28",["sky","n025"],B(PETILIL2))]);
add(548,"치릴리","Petilil","히스이 계열",[e("C","3-28",["sky","n025"],B(PETILIL3))]);
add(549,"드레디어","Lilligant",null,[e("C","23-48",["sky","n025"],B(PETILIL)),e("C","23-48",["sky","n025"],B(PETILIL2))]);
add(549,"드레디어","Lilligant","히스이",[e("C","23-48",["sky","n025"],B(PETILIL3))]);
add(550,"배쓰나이","Basculin","파랑줄무늬의 모습",[e("C","21-46",["sub","seeSky","moon13"],B(BASCULIN)),e("C","21-46",["sub","seeSky","moon57"],B(BASCULIN)),e("C","21-46",["sub","seeSky","moon04"],B(BASCULIN)),e("C","21-46",["sub","indoor","sky","moon13"],B(BASCULIN)),e("C","21-46",["sub","indoor","sky","moon57"],B(BASCULIN)),e("C","21-46",["sub","indoor","sky","moon04"],B(BASCULIN))]);
add(550,"배쓰나이","Basculin","빨강줄무늬의 모습",[e("C","21-46",["sub","seeSky","moon57"],B(BASCULIN)),e("C","21-46",["sub","seeSky","moon13"],B(BASCULIN)),e("C","21-46",["sub","seeSky","moon04"],B(BASCULIN)),e("C","21-46",["sub","indoor","sky","moon57"],B(BASCULIN)),e("C","21-46",["sub","indoor","sky","moon13"],B(BASCULIN)),e("C","21-46",["sub","indoor","sky","moon04"],B(BASCULIN))]);
add(550,"배쓰나이","Basculin","하양줄무늬의 모습",[e("C","21-46",["sub","seeSky","moon04"],B(BASCULIN)),e("C","21-46",["sub","indoor","sky","moon04"],B(BASCULIN))]);
add(551,"깜눈크","Sandile",null,[e("C","4-29",["sky"],B(SANDILE))]);
add(552,"악비르","Krokorok",null,[e("C","29-35",["sky"],B(SANDILE))]);
add(553,"악비아르","Krookodile",null,[e("C","40-52",["sky"],B(SANDILE))]);
add(554,"달막화","Darumaka",null,[e("C","7-32",["sky"],B(DARUMAKA)),e("C","7-32",["sky","minY62"],{b:SANDILE,s:["Desert Pyramid"]}),e("C","7-32",["sky","minY62"],{b:JUNGLE,s:["Jungle Pyramid"]}),e("C","7-32",[],{all:"nether",ex:["네더 얼음 계열","네더 석영 계열","네더 독 계열"]})]);
add(554,"달막화","Darumaka","가라르",[e("U","25-45",["seeSky"],B(DARUMAKA2))]);
add(555,"불비달마","Darmanitan",null,[e("C","35-54",["sky"],{b:DARUMAKA,s:["Cobblemon Ruins (All Types)"]}),e("C","35-54",["sky","minY62"],{b:SANDILE,s:["Desert Pyramid"]}),e("C","35-54",["sky","minY62"],{b:JUNGLE,s:["Jungle Pyramid"]}),e("C","35-54",[],{all:"nether",ex:["네더 얼음 계열","네더 석영 계열","네더 독 계열"]})]);
add(555,"불비달마","Darmanitan","가라르",[e("R","45-50",["seeSky"],B(DARUMAKA2))]);
add(556,"마라카치","Maractus",null,[e("C","21-46",["sky","n025"],B(MARACTUS))]);
add(557,"돌살이","Dwebble",null,[e("C","8-33",[],B(DWEBBLE))]);
add(558,"암팰리스","Crustle",null,[e("C","34-49",[],B(DWEBBLE))]);
add(559,"곤율랭","Scraggy",null,[e("C","10-35",["sky"],B(DWEBBLE)),e("C","10-35",["sky","concrete"],B(SCRAGGY)),e("C","10-35",["sky"],{b:SCRAGGY,s:VILALL})]);
add(560,"곤율거니","Scrafty",null,[e("C","39-49",["sky"],B(DWEBBLE)),e("C","39-49",["sky","concrete"],B(SCRAGGY)),e("C","39-49",["sky"],{b:SCRAGGY,s:VILALL})]);
add(561,"심보러","Sigilyph",null,[e("U","24-49",["sky"],B(MARACTUS)),e("C","24-49",["sky","minY62"],S(["Desert Well","Desert Pyramid"])),e("C","24-49",["sky","minY62"],S(["Jungle Pyramid"])),e("C","24-49",["sky","minY32"],S(["Trail Ruins"])),e("U","24-49",[],S(["End City"]))]);
add(562,"데스마스","Yamask",null,[e("U","5-30",["dim","minY0"],B(SANDILE)),e("C","5-30",["indoor","minY48"],S(["Desert Pyramid"]))]);
add(563,"데스니칸","Cofagrigus",null,[e("U","34-48",["dim","minY0"],B(SANDILE)),e("C","34-48",["indoor","minY48"],S(["Desert Pyramid"]))]);
add(564,"프로토가","Tirtouga",null,[e("X","15-40",["dim"],B(LUSHC)),e("X","15-40",["sub","dim"],B(LUSHC))]);
add(565,"늑골라","Carracosta",null,[e("X","37-57",["dim"],B(LUSHC)),e("X","37-57",["sub","dim"],B(LUSHC))]);
add(566,"아켄","Archen",null,[e("X","15-40",["dim"],B(LUSHC))]);
add(567,"아케오스","Archeops",null,[e("X","37-57",["dim"],B(LUSHC))]);
add(568,"깨봉이","Trubbish",null,[e("C","8-33",["n5"],B(SWAMP)),e("C","8-33",["sky","n5"],S(VILALL))]);
add(569,"더스트나","Garbodor",null,[e("C","36-47",["sky","n5"],B(SWAMP)),e("C","36-47",["sky","n5"],S(VILALL))]);
add(570,"조로아","Zorua",null,[e("U","8-33",["sky","night","newmoon5"],B(ZORUA))]);
add(570,"조로아","Zorua","히스이",[e("U","8-33",["sky","night","newmoon5"],B(ZORUA2)),e("U","8-33",[],S(["Nether Fossil"]))]);
add(571,"조로아크","Zoroark",null,[e("U","30-51",["sky","night","newmoon5"],B(ZORUA))]);
add(571,"조로아크","Zoroark","히스이",[e("U","30-51",["sky","night","newmoon5"],B(ZORUA2)),e("U","30-51",[],S(["Nether Fossil"]))]);
add(572,"치라미","Minccino",null,[e("C","5-30",["sky"],B(MYST)),e("C","5-30",["sky","concrete"],OW(["모래 계열","툰드라 계열"])),e("C","5-30",["sky"],{all:"ow",ex:["모래 계열","툰드라 계열"],s:VILALL}),e("C","5-30",["indoor","minY62"],S(MANSION))]);
add(573,"치라치노","Cinccino",null,[e("C","25-47",["sky"],B(MYST)),e("C","25-47",["sky","concrete"],OW(["모래 계열","툰드라 계열"])),e("C","25-47",["sky"],{all:"ow",ex:["모래 계열","툰드라 계열"],s:VILALL}),e("C","25-47",["indoor","minY62"],S(MANSION))]);
add(574,"고디탱","Gothita",null,[e("C","4-29",["indoor","minY62"],S(MANSION)),e("U","4-29",[],S(["End City"]))]);
add(575,"고디보미","Gothorita",null,[e("C","32-39",["indoor","minY62"],S(MANSION)),e("U","32-39",[],S(["End City"]))]);
add(576,"고디모아젤","Gothitelle",null,[e("C","41-49",["indoor","minY62"],S(MANSION)),e("U","41-49",[],S(["End City"]))]);
add(577,"유니란","Solosis",null,[e("R","4-29",[],B(LUSHC)),e("R","4-29",[],END)]);
add(578,"듀란","Duosion",null,[e("U","32-37",[],END)]);
add(579,"란쿨루스","Reuniclus",null,[e("U","41-49",[],B(LUSHC)),e("U","41-49",[],END)]);
add(580,"꼬지보리","Ducklett",null,[e("U","6-31",["surf","sky","day"],B(DUCKLETT)),e("C","6-31",["sky","n025"],B(DUCKLETT)),e("U","6-31",["surf","sky","day"],B(DUCKLETT2)),e("C","6-31",["sky","n025"],B(DUCKLETT2))]);
add(581,"스완나","Swanna",null,[e("U","35-47",["surf","sky","day"],B(DUCKLETT)),e("C","35-47",["sky","n025"],B(DUCKLETT)),e("U","35-47",["surf","sky","day"],B(DUCKLETT2)),e("C","35-47",["sky","n025"],B(DUCKLETT2))]);
add(582,"바닐프티","Vanillite",null,[e("C","6-31",["sky","dawn5"],B(VANILLITE)),e("U","6-31",["dim","minY0"],B(VANILLITE))]);
add(583,"바닐리치","Vanillish",null,[e("C","35-40",["sky","dawn5"],B(VANILLITE)),e("U","35-40",["dim","minY0"],B(VANILLITE))]);
add(584,"배바닐라","Vanilluxe",null,[e("C","47-54",["sky","dawn5"],B(VANILLITE)),e("U","47-54",["dim","minY0"],B(VANILLITE))]);
add(585,"사철록","Deerling",null,[e("C","9-34",["sky","n025"],B(DEERLING))]);
add(586,"바라철록","Sawsbuck",null,[e("C","34-48",["sky","n025"],B(DEERLING))]);
add(587,"에몽가","Emolga",null,[e("U","18-43",["sky","treetop","t5"],B(["Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"]))]);
add(588,"딱정곤","Karrablast",null,[e("C","7-32",["sky"],B(SWAMP))]);
add(589,"슈바르고","Escavalier",null,[e("C","27-50",["sky"],B(SWAMP))]);
add(590,"깜놀버슬","Foongus",null,[e("C","4-29",["dim"],B(FOONGUS)),e("C","4-29",["sky","d025"],B(FOONGUS2))]);
add(591,"뽀록나","Amoonguss",null,[e("C","39-46",["dim"],B(FOONGUS)),e("C","39-46",["sky","d025"],B(FOONGUS2))]);
add(592,"탱그릴","Frillish",null,[e("C","9-34",["sub","seeSky","maxY48","ship10"],B(FRILLISH)),e("C","9-34",["surf","sky","night"],B(FRILLISH)),e("C","9-34",["sub","indoor","sky","maxY48","ship10"],B(FRILLISH)),e("C","9-34",["sub","indoor","subY"],S(SSC))]);
add(593,"탱탱겔","Jellicent",null,[e("C","40-48",["sub","seeSky","maxY48","ship10"],B(FRILLISH)),e("C","40-48",["surf","sky","night"],B(FRILLISH)),e("C","40-48",["sub","indoor","sky","maxY48","ship10"],B(FRILLISH)),e("C","40-48",["sub","indoor","subY"],S(SSC))]);
add(594,"맘복치","Alomomola",null,[e("U","22-47",["sub","seeSky"],B(ALOMOMOLA)),e("U","22-47",["sub","indoor","sky"],B(ALOMOMOLA))]);
add(595,"파쪼옥","Joltik",null,[e("C","7-32",["sky","night","t5"],B(JOLTIK)),e("C","7-32",["dim"],OW(["?#cobblemon:is_deep_dark"])),e("C","7-32",["dim"],B(["Infested Caves"])),e("C","7-32",["sky","night","rod","t5"],OW())]);
add(596,"전툴라","Galvantula",null,[e("C","36-47",["sky","night","t5"],B(JOLTIK)),e("C","36-47",["dim"],OW(["?#cobblemon:is_deep_dark"])),e("C","36-47",["dim"],B(["Infested Caves"])),e("C","36-47",["sky","night","rod","t5"],OW())]);
add(597,"철시드","Ferroseed",null,[e("C","6-31",[],B(LUSHC)),e("C","6-31",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(598,"너트령","Ferrothorn",null,[e("C","40-49",[],B(LUSHC)),e("C","40-49",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(599,"기어르","Klink",null,[e("C","5-30",[],B(DWEBBLE)),e("C","5-30",["dim"],B(KLINK))]);
add(600,"기기어르","Klang",null,[e("C","38-44",[],B(DWEBBLE)),e("C","38-44",[],B(KLINK))]);
add(601,"기기기어르","Klinklang",null,[e("C","49-52",[],B(DWEBBLE)),e("C","49-52",[],B(KLINK))]);
add(602,"저리어","Tynamo",null,[e("C","3-28",["sub","maxY48"],B(FRILLISH)),e("U","3-28",["sub","dim","maxY48"],OW(["무성한 계열"])),e("C","3-28",["sub","indoor","subY"],S(SSC))]);
add(603,"저리릴","Eelektrik",null,[e("C","39-41",["sub","maxY48"],B(FRILLISH)),e("U","39-41",["sub","dim","maxY48"],OW(["무성한 계열"])),e("C","39-41",["sub","indoor","subY"],S(SSC))]);
add(604,"저리더프","Eelektross",null,[e("C","36-52",["sub","maxY48"],B(FRILLISH)),e("U","36-52",["sub","dim","maxY48"],OW(["무성한 계열"])),e("C","36-52",["sub","indoor","subY"],S(SSC))]);
add(605,"리그레","Elgyem",null,[e("U","9-34",[],END)]);
add(606,"벰크","Beheeyem",null,[e("U","42-49",[],END)]);
add(607,"불켜미","Litwick",null,[e("C","3-28",[],B(["Soul Sand Valley"])),e("C","3-28",["indoor","night","minY62"],S(MANSION))]);
add(608,"램프라","Lampent",null,[e("C","41-46",[],B(["Soul Sand Valley"])),e("C","41-46",["indoor","night","minY62"],S(MANSION))]);
add(609,"샹델라","Chandelure",null,[e("C","41-52",[],B(["Soul Sand Valley"])),e("C","41-52",["indoor","night","minY62"],S(MANSION))]);
add(610,"터검니","Axew",null,[e("X","7-32",[],B(AXEW))]);
add(611,"액슨도","Fraxure",null,[e("X","38-41",[],B(AXEW))]);
add(612,"액스라이즈","Haxorus",null,[e("X","48-54",[],B(AXEW))]);
add(613,"코고미","Cubchoo",null,[e("C","6-31",["sky"],B(CUBCHOO))]);
add(614,"툰베어","Beartic",null,[e("C","37-51",["sky"],B(CUBCHOO))]);
add(615,"프리지오","Cryogonal",null,[e("U","27-52",["sky","rain5"],B(VANILLITE))]);
add(616,"쪼마리","Shelmet",null,[e("C","6-31",["sky","rain5"],B(SWAMP))]);
add(617,"어지리더","Accelgor",null,[e("C","26-50",["sky","rain5"],B(SWAMP))]);
add(618,"메더","Stunfisk",null,[e("C","22-47",["floor","seeSky"],B(SWAMP))]);
add(618,"메더","Stunfisk","가라르",[e("C","22-47",["sky"],B(SWAMP))]);
add(619,"비조푸","Mienfoo",null,[e("U","10-35",["sky","n025"],B(MIENFOO))]);
add(620,"비조도","Mienshao",null,[e("U","50-51",["sky","n025"],B(MIENFOO))]);
add(621,"크리만","Druddigon",null,[e("R","24-49",["dim"],OW(["?#cobblemon:is_deep_dark","산 계열"])),e("U","24-49",["dim"],B(AXEW)),e("R","24-49",["sky","day"],B(AXEW))]);
add(622,"골비람","Golett",null,[e("U","5-30",["dim","maxY62"],{b:ROGGENROLA,s:["Ancient City"]}),e("R","5-30",["sky"],S(["Cobblemon Ruins (All Types)"])),e("C","5-30",["sky","minY32"],S(["Trail Ruins"])),e("C","5-30",["minY62"],{b:SANDILE,s:["Desert Pyramid"]}),e("C","5-30",["minY62"],{b:JUNGLE,s:["Jungle Pyramid"]})]);
add(623,"골루그","Golurk",null,[e("U","43-48",["dim","maxY62"],{b:ROGGENROLA,s:["Ancient City"]}),e("R","43-48",["sky"],S(["Cobblemon Ruins (All Types)"])),e("C","43-48",["sky","minY32"],S(["Trail Ruins"])),e("C","43-48",["minY62"],{b:SANDILE,s:["Desert Pyramid"]}),e("C","43-48",["minY62"],{b:JUNGLE,s:["Jungle Pyramid"]})]);
add(624,"자망칼","Pawniard",null,[e("U","10-38",["n25"],B(["Bamboo Jungle"]))]);
add(625,"절각참","Bisharp",null,[e("R","52-78",["n25"],B(["Bamboo Jungle"]))]);
add(626,"버프론","Bouffalant",null,[e("C","24-49",["sky","n025"],B(TEPIG))]);
add(627,"수리둥보","Rufflet",null,[e("U","10-35",["sky","day","treetop"],B(RUFFLET)),e("C","10-35",["sky","day","treetop"],B(DUCKLETT2))]);
add(627,"수리둥보","Rufflet","히스이 계열",[e("U","10-35",["sky","treetop","n025"],B(RUFFLET2)),e("C","10-35",["sky","treetop","n025"],B(DUCKLETT2))]);
add(628,"워글","Braviary",null,[e("U","54-59",["sky","day","treetop"],B(RUFFLET)),e("C","54-59",["sky","day","treetop"],B(DUCKLETT2))]);
add(628,"워글","Braviary","히스이",[e("U","54-59",["sky","treetop","n025"],B(RUFFLET2)),e("C","54-59",["sky","treetop","n025"],B(DUCKLETT2))]);
add(629,"벌차이","Vullaby",null,[e("C","15-44",["seeSky"],B(MARACTUS))]);
add(630,"버랜지나","Mandibuzz",null,[e("U","54-72",["seeSky"],B(MARACTUS))]);
add(631,"앤티골","Heatmor",null,[e("U","23-48",["sky","n025"],B(RUFFLET)),e("C","23-48",[],B(["Basalt Deltas"]))]);
add(632,"아이앤트","Durant",null,[e("C","23-48",["sky"],B(RUFFLET)),e("C","23-48",["dim"],B(RUFFLET)),e("C","23-48",[],B(["Basalt Deltas"]))]);
add(633,"모노두","Deino",null,[e("R","5-30",["dim"],B(ROGGENROLA)),e("X","5-30",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(634,"디헤드","Zweilous",null,[e("R","50-55",["dim"],B(ROGGENROLA)),e("X","50-55",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(635,"삼삼드래","Hydreigon",null,[e("R","64-69",["dim"],B(ROGGENROLA)),e("X","64-69",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(636,"활화르바","Larvesta",null,[e("U","11-36",["indoor","minY48"],{b:SANDILE,s:["Desert Pyramid"]}),e("U","11-36",["indoor","minY48"],{b:JUNGLE,s:["Jungle Pyramid"]}),e("U","11-36",["treetop"],B(["Crimson Forest"]))]);
add(637,"불카모스","Volcarona",null,[e("U","59-64",["indoor","minY48"],{b:SANDILE,s:["Desert Pyramid"]}),e("U","59-64",["indoor","minY48"],{b:JUNGLE,s:["Jungle Pyramid"]}),e("U","59-64",["treetop"],B(["Crimson Forest"]))]);
add(638,"코바르온","Cobalion",null,[e("X","50-70",["seeSky"],B(["Windswept Forest"]))]);
add(639,"테라키온","Terrakion",null,[e("X","50-70",[],B(PURRLOIN2))]);
add(640,"비리디온","Virizion",null,[e("X","50-70",[],B(PANSAGE))]);
add(641,"토네로스","Tornadus",null,[e("X","50-60",["surf","rain3"],B(FRILLISH))]);
add(642,"볼트로스","Thundurus",null,[e("X","50-60",["t3"],B(AXEW))]);
add(643,"레시라무","Reshiram",null,[e("X","70-84",["norain"],B(AXEW))]);
add(644,"제크로무","Zekrom",null,[e("X","70-84",["storm"],B(AXEW))]);
add(645,"랜드로스","Landorus",null,[e("X","50-60",["norain"],B(DWEBBLE))]);
add(646,"큐레무","Kyurem",null,[e("X","66-78",["rain"],B(["Ice Spikes"]))]);
add(647,"케르디오","Keldeo","평상시 모습",[e("X","60",["sky"],B(["Sakura Grove","Sakura Valley"]))]);
add(647,"케르디오","Keldeo","각오의 모습",[e("X","80",["sky"],B(["Sakura Grove","Sakura Valley"]))]);
add(648,"메로엣타","Meloetta",null,[e("R","50-55",[],B(["Sunflower Plains"]))]);
add(649,"게노세크트","Genesect",null,[e("X","48-68",[],B(["Dripstone Caves","Fractured Savanna","Stony Spires"]))]);
