// ---- 5세대 (cobbleverse.wiki/spawns/gen5) ----
const OSHAWOTT=["Stony Shore","White Cliffs","Snowy Beach"];
const PURRLOIN=["Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp","Plains","Sunflower Plains","Cherry Grove","Forest","Flower Forest","Meadow","Birch Forest","Dark Forest","Grove","Old Growth Birch Forest","Pale Garden","Brushland","Shrubland","Steppe","Valley Clearing","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Alpine Highlands","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Arid Highlands","Blooming Plateau"];
const PIDOVE=["Meadow","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Yosemite Cliffs"];
const WOOBAT=["Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Hot Shrubland","Red Oasis","Savanna Slopes","Shrubland"];
const TIMBURR=["Village (Plains)","Village (Taiga)","Village (Savanna)"];
const PETILIL=["Cherry Grove","Flower Forest","Sunflower Plains","Cloud Forest","Lavender Forest","Sakura Grove"];
const PETILIL2=["Forest","Cherry Grove","Flower Forest","Birch Forest","Old Growth Birch Forest","Lavender Forest","Mirage Isles","Sakura Grove"];
const PETILIL3=["Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Meadow","Alpine Highlands","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater"];
const BASCULIN=["River","Frozen River","Swamp","Mangrove Swamp","Ice Marsh","Orchid Swamp"];
const DARUMAKA=["Desert","Ancient Sands","Desert Canyon","Desert Oasis","Lush Desert","Red Oasis","Sandstone Valley","Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle"];
const DARUMAKA2=["Grove","Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Snowy Taiga","Snowy Badlands","Alpine Grove","Frozen Peaks","Ice Spikes","Glacial Chasm","Siberian Taiga","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Deep Frozen Ocean"];
const DEERLING=["Cherry Grove","Flower Forest","Meadow","Sunflower Plains","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Sakura Grove","Sakura Valley","Forest","Birch Forest","Dark Forest","Grove","Old Growth Birch Forest","Pale Garden","Forested Highlands","Mirage Isles","Temperate Highlands","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Alpine Grove","Alpine Highlands","Snowy Slopes","Lush Valley","Moonlight Valley","Yosemite Lowlands","Caldera","Volcanic Crater","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Moonlight Grove","Shield","Siberian Taiga","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const FOONGUS=["Dark Forest","Mushroom Fields","Fungal Caves","Mirage Isles","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];
const ALOMOMOLA=["Deep Ocean","Deep Cold Ocean","Deep Lukewarm Ocean"];
const JOLTIK=["Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis","Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle"];
const KLINK=["Dripstone Caves","Lush Caves","Sulfur Caves","Andesite Caves","Desert Caves","Diorite Caves","Fungal Caves","Granite Caves","Underground Jungle","Deep Caves"];
const MIENFOO=["Volcanic Peaks","Yosemite Cliffs","Frozen Peaks","Jagged Peaks","Stony Peaks","Rocky Mountains"];
const DRUDDIGON=["Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Alpine Highlands","Forested Highlands","Snowy Slopes","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Temperate Highlands","Yosemite Lowlands","Caldera","Volcanic Crater","Volcanic Peaks","Yosemite Cliffs"];
const HEATMOR=["Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Meadow","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater"];
const RESHIRAM=["Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Snowy Slopes","Lush Valley","Savanna Slopes","Moonlight Valley","Yosemite Lowlands","Caldera","Volcanic Crater","Volcanic Peaks","Yosemite Cliffs"];

add(494,"비크티니","Victini",null,[e("X","50",[],B(["Crimson Forest"]))]);
add(495,"주리비얀","Snivy",null,[e("X","5-31",["sky"],B(JUNGLE))]);
add(496,"샤비","Servine",null,[e("X","17-41",["sky"],B(JUNGLE))]);
add(497,"샤로다","Serperior",null,[e("X","36-53",["sky"],B(JUNGLE))]);
add(498,"뚜꾸리","Tepig",null,[e("X","5-31",["sky"],B(PLAINS)),e("X","5-31",[],B(["Crimson Forest"]))]);
add(499,"차오꿀","Pignite",null,[e("X","17-42",["sky"],B(PLAINS)),e("X","17-42",[],B(["Crimson Forest"]))]);
add(500,"염무왕","Emboar",null,[e("X","36-53",["clear","sky"],B(PLAINS)),e("X","36-53",[],B(["Crimson Forest"]))]);
add(501,"수댕이","Oshawott",null,[e("X","5-31",["sky"],B(["Beach"])),e("X","5-31",["surf","sky"],B(["Beach"]))]);
add(501,"수댕이","Oshawott","히스이 계열",[e("X","5-31",["sky"],B(OSHAWOTT)),e("X","5-31",["surf","sky"],B(OSHAWOTT))]);
add(502,"쌍검자비","Dewott",null,[e("X","17-41",["sky"],B(["Beach"])),e("X","17-41",["surf","sky"],B(["Beach"]))]);
add(502,"쌍검자비","Dewott","히스이 계열",[e("X","17-41",["sky"],B(OSHAWOTT)),e("X","17-41",["surf","sky"],B(OSHAWOTT))]);
add(503,"대검귀","Samurott",null,[e("X","36-53",["sky"],B(["Beach"])),e("X","36-53",["surf","sky"],B(["Beach"]))]);
add(503,"대검귀","Samurott","히스이",[e("X","36-53",["sky"],B(OSHAWOTT)),e("X","36-53",["surf","sky"],B(OSHAWOTT))]);
add(504,"보르쥐","Patrat",null,[e("C","1-26",["sky"],B(RAT))]);
add(505,"보르그","Watchog",null,[e("C","20-42",["sky"],B(RAT))]);
add(506,"요테리","Lillipup",null,[e("C","3-28",["sky"],OW(["사막 계열"])),e("C","3-28",["sky"],S(VIL4))]);
add(507,"하데리어","Herdier",null,[e("C","16-37",["sky"],OW(["사막 계열"])),e("C","16-37",["sky"],S(VIL4))]);
add(508,"바랜드","Stoutland",null,[e("C","32-50",["sky"],OW(["사막 계열"])),e("C","32-50",["sky"],S(VIL4))]);
add(509,"쌔비냥","Purrloin",null,[e("C","3-28",["clear","night","sky"],B(PURRLOIN)),e("C","3-28",["night","sky"],B(SAVANNA)),e("C","3-28",["sky","n15"],{b:SAVANNA,s:["Village (Savanna)"]}),e("C","6-26",["indoor"],S(MANSION)),e("C","6-26",["clear","sky","n15"],S(["Swamp Hut"]))]);
add(510,"레파르다스","Liepard",null,[e("C","20-45",["clear","night","sky"],B(PURRLOIN)),e("C","20-45",["night","sky"],B(SAVANNA)),e("C","20-45",["sky","n15"],{b:SAVANNA,s:["Village (Savanna)"]}),e("C","20-45",["indoor"],S(MANSION)),e("C","22-45",["clear","sky","n15"],S(["Swamp Hut"]))]);
add(511,"야나프","Pansage",null,[e("U","7-32",["sky","n025"],B(JUNGLE)),e("U","7-32",["sky","n025"],B(FOREST_ALL))]);
add(512,"야나키","Simisage",null,[e("U","27-50",["sky","n025"],B(JUNGLE)),e("U","27-50",["sky","n025"],B(FOREST_ALL))]);
add(513,"바오프","Pansear",null,[e("U","7-32",["sky","n025"],B(JUNGLE)),e("U","7-32",["sky","n025"],B(VOLC))]);
add(514,"바오키","Simisear",null,[e("U","27-50",["sky","n025"],B(JUNGLE)),e("U","27-50",["sky","n025"],B(VOLC))]);
add(515,"앗차프","Panpour",null,[e("U","7-32",["sky","n025"],B(JUNGLE)),e("U","7-32",["sky","n025"],B(["River","Warm River"]))]);
add(516,"앗차키","Simipour",null,[e("U","27-50",["sky","n025"],B(JUNGLE)),e("U","27-50",["sky","n025"],B(["River","Warm River"]))]);
add(517,"몽나","Munna",null,[e("C","4-29",["night","sky"],{all:"ow",ex:[],s:VILALL})]);
add(518,"몽얌나","Musharna",null,[e("C","24-49",["night","sky"],{all:"ow",ex:[],s:VILALL})]);
add(519,"콩둘기","Pidove",null,[e("C","1-26",["day","sky"],{b:PIDOVE,s:["Village (Plains)","Village (Taiga)"]})]);
add(520,"유토브","Tranquill",null,[e("C","21-36",["day","sky"],{b:PIDOVE,s:["Village (Plains)","Village (Taiga)"]})]);
add(521,"켄호로우","Unfezant",null,[e("C","32-49",["day","sky"],{b:PIDOVE,s:["Village (Plains)","Village (Taiga)"]})]);
add(522,"줄뮤마","Blitzle",null,[e("C","5-30",["sky","n025","t5"],B(SAVANNA))]);
add(523,"제브라이카","Zebstrika",null,[e("C","27-50",["sky","n025","t5"],B(SAVANNA))]);
add(524,"단굴","Roggenrola",null,[e("C","3-28",["dim","maxY0"],OW(["Deep Dark"])),e("U","3-28",["dim"],B(["Deep Dark","Deep Caves"]))]);
add(525,"암트르","Boldore",null,[e("C","25-39",["dim","maxY0"],OW(["Deep Dark"])),e("U","25-39",["dim"],B(["Deep Dark","Deep Caves"]))]);
add(526,"기가이어스","Gigalith",null,[e("C","34-52",["dim","maxY0"],OW(["Deep Dark"])),e("U","34-52",["dim"],B(["Deep Dark","Deep Caves"]))]);
add(527,"또르박쥐","Woobat",null,[e("C","7-32",["clear","night"],B(WOOBAT)),e("C","7-32",["dim","n025"],B(WOOBAT))]);
add(528,"맘박쥐","Swoobat",null,[e("C","27-43",["clear","night"],B(WOOBAT)),e("C","27-43",["dim","n025"],B(WOOBAT))]);
add(529,"두더류","Drilbur",null,[e("C","8-33",["dim"],OW(["Deep Dark"]))]);
add(530,"몰드류","Excadrill",null,[e("C","31-51",["dim"],OW(["Deep Dark"]))]);
add(531,"다부니","Audino",null,[e("R","19-47",["seeSky"],B(ZIGZAGOON))]);
add(532,"으랏차","Timburr",null,[e("C","6-24",["sky","n025"],OW(["모래 계열","툰드라 계열"])),e("C","8-24",["sky","n025"],S(TIMBURR))]);
add(533,"토쇠골","Gurdurr",null,[e("C","25-41",["sky","n025"],OW(["모래 계열","툰드라 계열"])),e("C","25-41",["sky","n025"],S(TIMBURR))]);
add(534,"노보청","Conkeldurr",null,[e("C","36-51",["sky","n025"],OW(["모래 계열","툰드라 계열"])),e("C","39-56",["sky","n025"],S(TIMBURR))]);
add(535,"동챙이","Tympole",null,[e("C","1-21",["dim"],B(LUSHC)),e("C","1-21",["sub","dim"],B(LUSHC)),e("U","1-21",["dim","maxY62","water"],OW(["무성한 계열"])),e("U","1-21",["sub","dim","maxY62"],OW(["무성한 계열"])),e("C","1-21",["rain","sky"],B(SW3B)),e("C","1-21",["sub","seeSky"],B(SW3B)),e("C","1-21",["sub","indoor","sky"],B(SW3B))]);
add(536,"두까비","Palpitoad",null,[e("C","20-43",["dim"],B(LUSHC)),e("C","20-43",["sub","dim"],B(LUSHC)),e("U","20-43",["dim","maxY62","water"],OW(["무성한 계열"])),e("U","20-43",["sub","dim","maxY62"],OW(["무성한 계열"])),e("C","20-43",["rain","sky"],B(SW3B)),e("C","20-43",["sub","seeSky"],B(SW3B)),e("C","20-43",["sub","indoor","sky"],B(SW3B)),e("C","20-43",["dim","shipY"],S(LSC)),e("C","20-43",["sub","dim","shipY"],S(LSC))]);
add(537,"두빅굴","Seismitoad",null,[e("C","20-43",["dim"],B(LUSHC)),e("C","20-43",["sub","dim"],B(LUSHC)),e("U","20-43",["dim","maxY62","water"],OW(["무성한 계열"])),e("U","20-43",["sub","dim","maxY62"],OW(["무성한 계열"])),e("C","20-43",["rain","sky"],B(SW3B)),e("C","20-43",["sub","seeSky"],B(SW3B)),e("C","20-43",["sub","indoor","sky"],B(SW3B)),e("C","20-43",["dim","shipY"],S(LSC)),e("C","20-43",["sub","dim","shipY"],S(LSC))]);
add(538,"던지미","Throh",null,[e("R","36-63",[],B(EKANS))]);
add(539,"타격귀","Sawk",null,[e("R","36-63",[],B(EKANS))]);
add(540,"두르보","Sewaddle",null,[e("C","6-31",["sky"],B(FOREST))]);
add(541,"두르쿤","Swadloon",null,[e("C","20-38",["sky"],B(FOREST))]);
add(542,"모아머","Leavanny",null,[e("C","33-50",["sky"],B(FOREST))]);
add(543,"마디네","Venipede",null,[e("C","1-26",["night"],B(FOREST_ALL)),e("C","1-26",["night"],B(JUNGLE)),e("C","1-26",["dim"],B(LUSHC)),e("C","1-26",[],B(["Crimson Forest","Warped Forest"]))]);
add(544,"휠구","Whirlipede",null,[e("C","22-36",["night","sky"],B(FOREST_ALL)),e("C","22-36",["night","sky"],B(JUNGLE)),e("C","22-36",["dim"],B(LUSHC)),e("C","22-36",[],B(["Crimson Forest","Warped Forest"]))]);
add(545,"펜드라","Scolipede",null,[e("C","30-49",["night","sky"],B(FOREST_ALL)),e("C","30-49",["night","sky"],B(JUNGLE)),e("C","30-49",["dim"],B(LUSHC)),e("C","30-49",[],B(["Crimson Forest","Warped Forest"]))]);
add(546,"소미안","Cottonee",null,[e("C","3-28",["clear","sky","n025"],B(PLAINS))]);
add(547,"엘풍","Whimsicott",null,[e("C","23-48",["clear","sky","n025"],B(PLAINS))]);
add(548,"치릴리","Petilil",null,[e("C","3-28",["sky","n025"],B(PETILIL)),e("C","3-28",["sky","n025"],B(PETILIL2))]);
add(548,"치릴리","Petilil","히스이 계열",[e("C","3-28",["sky","n025"],B(PETILIL3))]);
add(549,"드레디어","Lilligant",null,[e("C","23-48",["sky","n025"],B(PETILIL)),e("C","23-48",["sky","n025"],B(PETILIL2))]);
add(549,"드레디어","Lilligant","히스이",[e("C","23-48",["sky","n025"],B(PETILIL3))]);
add(550,"배쓰나이","Basculin","파랑줄무늬의 모습",[e("C","21-46",["sub","seeSky","moon13"],B(BASCULIN)),e("C","21-46",["sub","seeSky","moon57"],B(BASCULIN)),e("C","21-46",["sub","seeSky","moon04"],B(BASCULIN)),e("C","21-46",["sub","indoor","moon13","sky"],B(BASCULIN)),e("C","21-46",["sub","indoor","moon57","sky"],B(BASCULIN)),e("C","21-46",["sub","indoor","moon04","sky"],B(BASCULIN))]);
add(550,"배쓰나이","Basculin","빨강줄무늬의 모습",[e("C","21-46",["sub","seeSky","moon57"],B(BASCULIN)),e("C","21-46",["sub","seeSky","moon13"],B(BASCULIN)),e("C","21-46",["sub","seeSky","moon04"],B(BASCULIN)),e("C","21-46",["sub","indoor","moon57","sky"],B(BASCULIN)),e("C","21-46",["sub","indoor","moon13","sky"],B(BASCULIN)),e("C","21-46",["sub","indoor","moon04","sky"],B(BASCULIN))]);
add(550,"배쓰나이","Basculin","하양줄무늬의 모습",[e("C","21-46",["sub","seeSky","moon04"],B(BASCULIN)),e("C","21-46",["sub","indoor","moon04","sky"],B(BASCULIN))]);
add(551,"깜눈크","Sandile",null,[e("C","4-29",["sky"],B(SAND))]);
add(552,"악비르","Krokorok",null,[e("C","29-39",["sky"],B(SAND))]);
add(553,"악비아르","Krookodile",null,[e("C","40-52",["sky"],B(SAND))]);
add(554,"달막화","Darumaka",null,[e("C","7-32",["sky"],B(DARUMAKA)),e("C","7-32",["sky","minY62"],S(["Desert Pyramid","Jungle Pyramid"])),e("C","13-34",[],NETH)]);
add(554,"달막화","Darumaka","가라르",[e("U","25-45",["seeSky"],B(DARUMAKA2))]);
add(555,"불비달마","Darmanitan",null,[e("C","35-54",["sky"],B(DARUMAKA)),e("C","35-54",["sky","minY62"],S(["Desert Pyramid","Jungle Pyramid"])),e("C","35-54",[],NETH)]);
add(555,"불비달마","Darmanitan","가라르",[e("U","35-54",["sky"],B(DARUMAKA2))]);
add(556,"마라카치","Maractus",null,[e("C","21-46",["sky","n025"],B(CACNEA))]);
add(557,"돌살이","Dwebble",null,[e("C","8-33",[],B(BADLANDS))]);
add(558,"암팰리스","Crustle",null,[e("C","34-49",[],B(BADLANDS))]);
add(559,"곤율랭","Scraggy",null,[e("C","10-35",["sky"],B(BADLANDS)),e("C","10-35",["sky"],S(["Village (Desert)","Village (Savanna)"]))]);
add(560,"곤율거니","Scrafty",null,[e("C","39-49",["sky"],B(BADLANDS)),e("C","39-49",["sky"],S(["Village (Desert)","Village (Savanna)"]))]);
add(561,"심보러","Sigilyph",null,[e("U","24-49",["sky"],B(CACNEA)),e("C","24-49",["sky","minY62"],S(["Desert Well","Desert Pyramid"])),e("C","24-49",["sky","minY62"],S(["Jungle Pyramid"])),e("C","24-49",["sky","minY32"],S(["Trail Ruins"])),e("U","24-49",[],S(["End City"]))]);
add(562,"데스마스","Yamask",null,[e("U","5-30",["dim","minY0"],B(SAND)),e("C","5-30",["indoor","minY48"],S(["Desert Pyramid"]))]);
add(563,"데스니칸","Cofagrigus",null,[e("U","34-48",["dim","minY0"],B(SAND)),e("C","34-48",["indoor","minY48"],S(["Desert Pyramid"]))]);
add(564,"프로토가","Tirtouga",null,[e("X","15-40",["dim"],B(LUSHC)),e("X","15-40",["sub","dim"],B(LUSHC))]);
add(565,"늑골라","Carracosta",null,[e("X","37-57",["dim"],B(LUSHC)),e("X","37-57",["sub","dim"],B(LUSHC))]);
add(566,"아켄","Archen",null,[e("X","15-40",["dim"],B(LUSHC))]);
add(567,"아케오스","Archeops",null,[e("X","37-57",["dim"],B(LUSHC))]);
add(568,"깨봉이","Trubbish",null,[e("C","8-33",["sky","n5"],B(SWAMP)),e("C","8-33",["sky","n5"],S(VILALL))]);
add(569,"더스트나","Garbodor",null,[e("C","36-47",["sky","n5"],B(SWAMP)),e("C","36-47",["sky","n5"],S(VILALL))]);
add(570,"조로아","Zorua",null,[e("U","8-33",["night","sky","newmoon5"],B(FOREST_D))]);
add(570,"조로아","Zorua","히스이",[e("U","8-33",["night","sky","newmoon5"],B(AVULPIX)),e("U","8-33",[],S(["Nether Fossil"]))]);
add(571,"조로아크","Zoroark",null,[e("U","30-51",["night","sky","newmoon5"],B(FOREST_D))]);
add(571,"조로아크","Zoroark","히스이",[e("U","30-51",["night","sky","newmoon5"],B(AVULPIX)),e("U","30-51",[],S(["Nether Fossil"]))]);
add(572,"치라미","Minccino",null,[e("C","5-30",["sky"],B(MYST)),e("C","5-30",["sky"],S(TIMBURR)),e("C","5-30",["indoor"],S(MANSION))]);
add(573,"치라치노","Cinccino",null,[e("C","25-47",["sky"],B(MYST)),e("C","25-47",["sky"],S(TIMBURR)),e("C","25-47",["indoor"],S(MANSION))]);
add(574,"고디탱","Gothita",null,[e("C","4-29",["indoor"],S(MANSION)),e("U","4-29",[],S(["End City"]))]);
add(575,"고디보미","Gothorita",null,[e("C","32-39",["indoor"],S(MANSION)),e("U","32-39",[],S(["End City"]))]);
add(576,"고디모아젤","Gothitelle",null,[e("C","41-49",["indoor"],S(MANSION)),e("U","41-49",[],S(["End City"]))]);
add(577,"유니란","Solosis",null,[e("R","4-29",["sky"],B(MYST)),e("R","14-31",[],END)]);
add(578,"듀란","Duosion",null,[e("U","32-37",[],B(LUSHC)),e("U","32-37",[],END)]);
add(579,"란쿨루스","Reuniclus",null,[e("R","41-49",["sky"],B(MYST)),e("R","41-49",[],END)]);
add(580,"꼬지보리","Ducklett",null,[e("C","6-31",["sky","n025"],B(SURSKIT)),e("U","6-31",["surf","day","sky"],B(SURSKIT))]);
add(581,"스완나","Swanna",null,[e("C","35-47",["sky","n025"],B(SURSKIT)),e("U","35-47",["surf","day","sky"],B(SURSKIT))]);
add(582,"바닐프티","Vanillite",null,[e("C","6-31",["sky","dawn5"],B(FREEZE)),e("U","6-31",["dim","minY0"],B(FREEZE))]);
add(583,"바닐리치","Vanillish",null,[e("C","35-45",["sky","dawn5"],B(FREEZE)),e("U","35-45",["dim","minY0"],B(FREEZE))]);
add(584,"배바닐라","Vanilluxe",null,[e("C","47-56",["sky","dawn5"],B(FREEZE)),e("U","47-56",["dim","minY0"],B(FREEZE))]);
add(585,"사철록","Deerling",null,[e("C","9-34",["sky","n025"],B(DEERLING))]);
add(586,"바라철록","Sawsbuck",null,[e("C","34-48",["sky","n025"],B(DEERLING))]);
add(587,"에몽가","Emolga",null,[e("U","18-43",["sky","t5"],B(TAIGA))]);
add(588,"딱정곤","Karrablast",null,[e("C","7-32",["sky"],B(SWAMP))]);
add(589,"슈바르고","Escavalier",null,[e("C","27-50",["sky"],B(SWAMP))]);
add(590,"깜놀버슬","Foongus",null,[e("C","4-29",["dim"],B(FOONGUS)),e("C","7-38",["sky","d025"],B(SHROOMISH))]);
add(591,"뽀록나","Amoonguss",null,[e("C","39-46",["dim"],B(FOONGUS)),e("C","39-51",["sky","d025"],B(SHROOMISH))]);
add(592,"탱그릴","Frillish",null,[e("C","9-38",["sub","seeSky","maxY48","ship10"],B(OCEAN)),e("C","9-38",["surf","night","sky"],B(OCEAN)),e("C","9-38",["sub","indoor","sky","maxY48","ship10"],B(OCEAN)),e("C","9-38",["sub","indoor","subY"],S(SSC))]);
add(593,"탱탱겔","Jellicent",null,[e("C","40-52",["sub","seeSky","maxY48","ship10"],B(OCEAN)),e("C","40-52",["surf","night","sky"],B(OCEAN)),e("C","40-52",["sub","indoor","sky","maxY48","ship10"],B(OCEAN)),e("C","40-52",["sub","indoor","subY"],S(SSC))]);
add(594,"맘복치","Alomomola",null,[e("U","22-47",["sub","seeSky"],B(ALOMOMOLA)),e("U","22-47",["sub","indoor","sky"],B(ALOMOMOLA))]);
add(595,"파쪼옥","Joltik",null,[e("C","7-32",["night","sky","t5"],B(JOLTIK)),e("C","7-32",["dim"],OW(["Deep Dark"]))]);
add(596,"전툴라","Galvantula",null,[e("C","36-47",["night","sky","t5"],B(JOLTIK)),e("C","36-47",["dim"],OW(["Deep Dark"]))]);
add(597,"철시드","Ferroseed",null,[e("C","6-31",[],B(LUSHC)),e("C","6-31",["dim","shipY"],S(LSC))]);
add(598,"너트령","Ferrothorn",null,[e("C","40-49",[],B(LUSHC)),e("C","40-49",["dim","shipY"],S(LSC))]);
add(599,"기어르","Klink",null,[e("C","5-36",[],B(BADLANDS)),e("C","8-36",["dim"],B(KLINK))]);
add(600,"기기어르","Klang",null,[e("C","38-44",[],B(BADLANDS)),e("C","38-48",[],B(KLINK))]);
add(601,"기기기어르","Klinklang",null,[e("C","49-59",[],B(BADLANDS)),e("C","49-62",[],B(KLINK))]);
add(602,"저리어","Tynamo",null,[e("C","3-28",["sub","maxY48"],B(OCEAN)),e("U","3-28",["sub","dim","maxY48"],OW(["무성한 계열"])),e("C","5-35",["sub","indoor","subY"],S(SSC))]);
add(603,"저리릴","Eelektrik",null,[e("C","39-47",["sub","maxY48"],B(OCEAN)),e("U","39-47",["sub","dim","maxY48"],OW(["무성한 계열"])),e("C","39-49",["sub","indoor","subY"],S(SSC))]);
add(604,"저리더프","Eelektross",null,[e("C","46-55",["sub","maxY48"],B(OCEAN)),e("U","46-55",["sub","dim","maxY48"],OW(["무성한 계열"])),e("C","46-57",["sub","indoor","subY"],S(SSC))]);
add(605,"리그레","Elgyem",null,[e("U","9-38",[],END)]);
add(606,"벰크","Beheeyem",null,[e("U","42-59",[],END)]);
add(607,"불켜미","Litwick",null,[e("C","3-28",[],B(["Soul Sand Valley"])),e("C","13-40",["indoor","night"],S(MANSION))]);
add(608,"램프라","Lampent",null,[e("C","41-48",[],B(["Soul Sand Valley"])),e("C","41-50",["indoor","night"],S(MANSION))]);
add(609,"샹델라","Chandelure",null,[e("C","46-58",[],B(["Soul Sand Valley"])),e("C","46-62",["indoor","night"],S(MANSION))]);
add(610,"터검니","Axew",null,[e("X","7-37",[],B(GEO))]);
add(611,"액슨도","Fraxure",null,[e("X","38-47",[],B(GEO))]);
add(612,"액스라이즈","Haxorus",null,[e("X","48-64",[],B(GEO))]);
add(613,"코고미","Cubchoo",null,[e("C","6-31",["sky"],B(SEEL))]);
add(614,"툰베어","Beartic",null,[e("C","37-51",["sky"],B(SEEL))]);
add(615,"프리지오","Cryogonal",null,[e("U","27-52",["sky","rain5"],B(FREEZE))]);
add(616,"쪼마리","Shelmet",null,[e("C","6-31",["sky","rain5"],B(SWAMP))]);
add(617,"어지리더","Accelgor",null,[e("C","26-50",["sky","rain5"],B(SWAMP))]);
add(618,"메더","Stunfisk",null,[e("C","22-47",["floor","seeSky"],B(SWAMP))]);
add(618,"메더","Stunfisk","가라르",[e("C","22-47",["sky"],B(SWAMP))]);
add(619,"비조푸","Mienfoo",null,[e("U","10-35",["sky","n025"],B(MIENFOO))]);
add(620,"비조도","Mienshao",null,[e("U","50-60",["sky","n025"],B(MIENFOO))]);
add(621,"크리만","Druddigon",null,[e("R","24-49",["dim"],OW(["Deep Dark","산 계열"])),e("U","24-49",["dim"],B(DRUDDIGON)),e("R","24-49",["day","sky"],B(DRUDDIGON))]);
add(622,"골비람","Golett",null,[e("U","5-40",["dim","maxY62"],S(["Ancient City"])),e("R","5-40",["sky"],S(["Cobblemon Ruins (All Types)"])),e("C","5-40",["sky","minY32"],S(["Trail Ruins"])),e("C","5-40",["indoor","minY62"],S(["Desert Pyramid","Jungle Pyramid"]))]);
add(623,"골루그","Golurk",null,[e("U","43-68",["dim","maxY62"],S(["Ancient City"])),e("R","43-68",["sky"],S(["Cobblemon Ruins (All Types)"])),e("C","43-58",["sky","minY32"],S(["Trail Ruins"])),e("C","43-58",["night","minY62"],S(["Desert Pyramid","Jungle Pyramid"]))]);
add(624,"자망칼","Pawniard",null,[e("U","10-48",["n25"],B(["Bamboo Jungle"]))]);
add(625,"절각참","Bisharp",null,[e("U","52-64",["n25"],B(["Bamboo Jungle"]))]);
add(626,"버프론","Bouffalant",null,[e("C","24-49",["sky","n025"],B(PLAINS))]);
add(627,"수리둥보","Rufflet",null,[e("U","10-45",["day","sky"],B(MOUNT))]);
add(627,"수리둥보","Rufflet","히스이 계열",[e("U","10-45",["sky","n025"],B(BADLANDS))]);
add(628,"워글","Braviary",null,[e("U","54-69",["day","sky"],B(MOUNT))]);
add(628,"워글","Braviary","히스이",[e("U","54-59",["sky","n025"],B(BADLANDS))]);
add(629,"벌차이","Vullaby",null,[e("C","15-44",["seeSky"],B(CACNEA))]);
add(630,"버랜지나","Mandibuzz",null,[e("U","54-64",["seeSky"],B(CACNEA))]);
add(631,"앤티골","Heatmor",null,[e("U","23-48",["sky","n025"],B(HEATMOR)),e("R","23-48",[],B(["Basalt Deltas"]))]);
add(632,"아이앤트","Durant",null,[e("C","23-48",["sky"],B(HEATMOR)),e("C","23-48",["dim"],B(HEATMOR)),e("C","23-48",[],B(["Basalt Deltas"]))]);
add(633,"모노두","Deino",null,[e("R","5-30",["dim"],B(["Deep Dark","Deep Caves"])),e("X","5-30",["dim","maxY0"],OW(["Deep Dark"]))]);
add(634,"디헤드","Zweilous",null,[e("R","50-62",["dim"],B(["Deep Dark","Deep Caves"])),e("X","50-62",["dim","maxY0"],OW(["Deep Dark"]))]);
add(635,"삼삼드래","Hydreigon",null,[e("R","64-71",["dim"],B(["Deep Dark","Deep Caves"])),e("X","64-71",["dim","maxY0"],OW(["Deep Dark"]))]);
add(636,"활화르바","Larvesta",null,[e("U","11-46",["indoor","minY48"],S(["Desert Pyramid","Jungle Pyramid"])),e("R","21-56",[],B(["Crimson Forest"]))]);
add(637,"불카모스","Volcarona",null,[e("U","59-64",["indoor","minY48"],S(["Desert Pyramid","Jungle Pyramid"])),e("R","59-64",[],B(["Crimson Forest"]))]);
add(638,"코바르온","Cobalion",null,[e("X","50-70",["seeSky"],B(MEDITITE))]);
add(639,"테라키온","Terrakion",null,[e("X","50-70",[],B(SAVANNA))]);
add(640,"비리디온","Virizion",null,[e("X","50-70",[],B(FOREST_ALL))]);
add(641,"토네로스","Tornadus",null,[e("X","50-60",["rain3"],B(["Jagged Peaks","Snowy Beach","Snowy Plains","Grove","Snowy Slopes","Snowy Badlands","Frozen Peaks","Ice Spikes","Glacial Chasm","Ice Marsh","Siberian Taiga","Siberian Grove","Snowy Cherry Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands"]))]);
add(642,"볼트로스","Thundurus",null,[e("X","50-60",["t3"],B(["Meadow","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Alpine Highlands","Snowy Slopes","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Blooming Plateau","Yosemite Lowlands","Caldera","Yosemite Cliffs"]))]);
add(643,"레시라무","Reshiram",null,[e("X","70-84",["clear"],B(RESHIRAM))]);
add(644,"제크로무","Zekrom",null,[e("X","70-84",["storm"],B(RESHIRAM))]);
add(645,"랜드로스","Landorus",null,[e("X","50-60",["clear"],B(BADLANDS))]);
add(646,"큐레무","Kyurem",null,[e("X","66-88",["rain"],B(SWINUB))]);
add(647,"케르디오","Keldeo",null,[e("X","60-65",["sky"],B(["Cherry Grove","Sakura Grove","Sakura Valley"]))]);
add(648,"메로엣타","Meloetta",null,[e("X","50-55",[],B(["Sunflower Plains"]))]);
add(649,"게노세크트","Genesect",null,[e("X","48-68",[],B(["Dripstone Caves"]))]);
