// ---- 4세대 (cobbleverse.wiki/spawns/gen4) ----
const STARLY=["Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Meadow","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Bryce Canyon","Cloud Forest","Moonlight Grove","Shield","Siberian Taiga","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const BIDOOF=["Forest","Cherry Grove","Flower Forest","Birch Forest","Grove","Old Growth Birch Forest","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yosemite Lowlands","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const BIDOOF2=["Forest","Cherry Grove","Flower Forest","Birch Forest","Grove","Old Growth Birch Forest","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","River","Frozen River","Swamp","Mangrove Swamp","Ice Marsh","Orchid Swamp","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yosemite Lowlands","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const KRICKETOT=["Forest","Cherry Grove","Flower Forest","Birch Forest","Dark Forest","Old Growth Birch Forest","Pale Garden","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Mangrove Swamp","Swamp","Orchid Swamp"];
const SHINX=["Desert","Ancient Sands","Desert Canyon","Desert Oasis","Lush Desert","Red Oasis","Sandstone Valley","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Hot Shrubland","Savanna Slopes","Shrubland"];
const BURMY=["Beach","Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis","Desert","Ancient Sands","Desert Canyon","Desert Oasis","Lush Desert","Sandstone Valley"];
const BURMY2=["Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp","Cherry Grove","Sakura Grove","Sakura Valley"];
const COMBEE=["Plains","Sunflower Plains","Cherry Grove","Forest","Flower Forest","Meadow","Birch Forest","Old Growth Birch Forest","Brushland","Shrubland","Steppe","Valley Clearing","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Alpine Highlands","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Arid Highlands","Blooming Plateau"];
const CHERUBI=["Forest","Cherry Grove","Flower Forest","Birch Forest","Grove","Old Growth Birch Forest","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yosemite Lowlands","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const BUNEARY=["Forest","Cherry Grove","Flower Forest","Birch Forest","Dark Forest","Grove","Old Growth Birch Forest","Pale Garden","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Meadow","Alpine Grove","Alpine Highlands","Snowy Slopes","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Taiga","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Moonlight Grove","Shield","Siberian Taiga"];
const GLAMEOW=["Plains","Sunflower Plains","Meadow","Steppe","Alpine Highlands","Blooming Plateau","Valley Clearing"];
const GLAMEOW2=["Village (Desert)","Village (Snowy)","Village (Savanna)"];
const BRONZOR=["Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle","Frozen Peaks","Jagged Peaks","Snowy Slopes","Stony Peaks","Rocky Mountains","Volcanic Peaks"];
const GIBLE=["Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis","Meadow","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater","Volcanic Peaks","Yosemite Cliffs"];
const SKORUPI=["Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis","Desert","Ancient Sands","Desert Canyon","Desert Oasis","Lush Desert","Sandstone Valley","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];
const CROAGUNK=["Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];

add(387,"모부기","Turtwig",null,[e("X","5-32",["sky"],B(FOREST_G))]);
add(388,"수풀부기","Grotle",null,[e("X","18-41",["sky"],B(FOREST_G))]);
add(389,"토대부기","Torterra",null,[e("X","32-53",["sky"],B(FOREST_G))]);
add(390,"불꽃숭이","Chimchar",null,[e("X","5-31",["clear","sky"],B(LARV)),e("X","5-31",[],B(["Crimson Forest"]))]);
add(391,"파이숭이","Monferno",null,[e("X","14-41",["clear","sky"],B(LARV)),e("X","14-41",[],B(["Crimson Forest"]))]);
add(392,"초염몽","Infernape",null,[e("X","36-53",["clear","sky"],B(LARV)),e("X","36-53",[],B(["Crimson Forest"]))]);
add(393,"팽도리","Piplup",null,[e("X","5-31",["sky"],B(SEEL)),e("X","5-31",["sub","seeSky"],B(SEEL)),e("X","5-31",["sub","indoor","sky"],B(SEEL))]);
add(394,"팽태자","Prinplup",null,[e("X","16-41",["sky"],B(SEEL)),e("X","16-41",["sub","seeSky"],B(SEEL)),e("X","16-41",["sub","indoor","sky"],B(SEEL))]);
add(395,"엠페르트","Empoleon",null,[e("X","36-53",["sky"],B(SEEL)),e("X","36-53",["sub","seeSky"],B(SEEL)),e("X","36-53",["sub","indoor","sky"],B(SEEL))]);
add(396,"찌르꼬","Starly",null,[e("C","1-25",["day","sky"],B(STARLY))]);
add(397,"찌르버드","Staravia",null,[e("C","14-34",["day","sky"],B(STARLY))]);
add(398,"찌르호크","Staraptor",null,[e("C","34-49",["day","sky"],B(STARLY))]);
add(399,"비버니","Bidoof",null,[e("C","1-25",["sky"],B(SURSKIT)),e("U","1-25",["sky","water"],B(BIDOOF)),e("U","1-25",["surf","sky"],B(BIDOOF2))]);
add(400,"비버통","Bibarel",null,[e("C","15-41",["sky"],B(SURSKIT)),e("U","15-41",["sky","water"],B(BIDOOF)),e("U","15-41",["surf","sky"],B(BIDOOF2))]);
add(401,"귀뚤뚜기","Kricketot",null,[e("C","1-19",["night","sky"],B(KRICKETOT))]);
add(402,"귀뚤톡크","Kricketune",null,[e("C","10-38",["night","sky"],B(KRICKETOT))]);
add(403,"꼬링크","Shinx",null,[e("U","1-26",["sky"],B(SHINX))]);
add(404,"럭시오","Luxio",null,[e("U","15-36",["sky"],B(SHINX))]);
add(405,"렌트라","Luxray",null,[e("U","30-54",["sky"],B(SHINX))]);
add(406,"꼬몽울","Budew",null,[e("C","3-28",["sky"],B(FLOWER))]);
add(407,"로즈레이드","Roserade",null,[e("C","33-55",["sky"],B(FLOWER))]);
add(408,"두개도스","Cranidos",null,[e("X","10-35",["sky"],B(LUSHC))]);
add(409,"램펄드","Rampardos",null,[e("X","30-50",["sky"],B(LUSHC))]);
add(410,"방패톱스","Shieldon",null,[e("X","10-35",["sky"],B(LUSHC))]);
add(411,"바리톱스","Bastiodon",null,[e("X","30-50",["sky"],B(LUSHC))]);
add(412,"도롱충이","Burmy","초목도롱",[e("C","3-19",["sky"],B(FOREST_ALL))]);
add(412,"도롱충이","Burmy","모래땅도롱",[e("C","3-19",["sky"],B(BURMY))]);
add(412,"도롱충이","Burmy","슈레도롱",[e("C","3-19",["sky"],B(BURMY2))]);
add(413,"도롱마담","Wormadam","초목도롱",[e("U","20-34",["sky"],B(FOREST_ALL))]);
add(413,"도롱마담","Wormadam","모래땅도롱",[e("U","20-34",["sky"],B(BURMY))]);
add(413,"도롱마담","Wormadam","슈레도롱",[e("U","20-34",["sky"],B(BURMY2))]);
add(414,"나메일","Mothim",null,[e("R","28-45",["clear","night"],B(["Plains","Brushland","Shrubland","Steppe","Alpine Highlands","Arid Highlands","Valley Clearing","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Forested Highlands","Snowy Slopes","Lush Valley","Savanna Slopes","Moonlight Valley","Temperate Highlands","Yosemite Lowlands","Caldera","Volcanic Crater","Volcanic Peaks","Yosemite Cliffs"])),e("R","33-45",["clear","night","honey5","beenest"],OW(["꽃 계열"]))]);
add(415,"세꿀버리","Combee",null,[e("C","1-24",["clear","day","sky","bee5"],B(COMBEE)),e("C","1-24",["clear","day","sky","bee5","flowersacch"],OW(["얼음 계열"]))]);
add(416,"비퀸","Vespiquen",null,[e("C","21-47",["clear","day","sky","bee5"],B(COMBEE)),e("C","21-47",["clear","day","sky","bee5","flowersacch"],OW(["얼음 계열"]))]);
add(417,"파치리스","Pachirisu",null,[e("U","16-41",["sky","t5"],B(FOREST_G))]);
add(418,"브이젤","Buizel",null,[e("C","8-33",["sky"],B(SURSKIT)),e("C","8-33",["sub","sky"],B(SURSKIT)),e("U","8-33",["surf","sky"],B(SURSKIT))]);
add(419,"플로젤","Floatzel",null,[e("C","26-50",["sky"],B(SURSKIT)),e("C","26-50",["sub","sky"],B(SURSKIT)),e("U","26-50",["surf","sky"],B(SURSKIT))]);
add(420,"체리버","Cherubi",null,[e("C","4-25",["seeSky"],B(CHERUBI))]);
add(421,"체리꼬","Cherrim","네거티브폼",[e("U","25-36",["seeSky"],B(CHERUBI))]);
add(421,"체리꼬","Cherrim","포지티브폼",[e("U","25-36",["seeSky"],B(CHERUBI))]);
add(422,"깝질무","Shellos","동쪽바다의 모습",[e("U","8-33",["rain","sky","xpos"],B(["Beach","Snowy Beach"])),e("C","8-33",["floor","seeSky","xpos"],B(COLDO))]);
add(422,"깝질무","Shellos","서쪽바다의 모습",[e("U","8-33",["rain","sky","xneg"],B(["Beach"])),e("C","8-33",["floor","seeSky","xneg"],B(HORSEA))]);
add(423,"트리토돈","Gastrodon","동쪽바다의 모습",[e("U","30-48",["rain","sky","xpos"],B(["Beach","Snowy Beach"])),e("C","30-48",["floor","seeSky","xpos"],B(COLDO))]);
add(423,"트리토돈","Gastrodon","서쪽바다의 모습",[e("U","30-48",["rain","sky","xneg"],B(["Beach"])),e("C","30-48",["floor","seeSky","xneg"],B(HORSEA))]);
add(424,"겟핸보숭","Ambipom",null,[e("C","32-48",["sky"],B(JUNGLE)),e("C","32-48",["dim","shipY"],S(LSC))]);
add(425,"흔들풍손","Drifloon",null,[e("U","10-35",["clear","night"],OW(["건조 계열","얼음 계열"]))]);
add(426,"둥실라이드","Drifblim",null,[e("U","28-50",["clear","night"],OW(["건조 계열","얼음 계열"]))]);
add(427,"이어롤","Buneary",null,[e("C","10-35",["sky"],B(BUNEARY))]);
add(428,"이어롭","Lopunny",null,[e("C","30-48",["sky"],B(BUNEARY))]);
add(429,"무우마직","Mismagius",null,[e("C","39-53",["dim"],B(MISD)),e("C","39-53",["indoor","sky0"],B(MISD)),e("C","39-53",["night","sky"],B(SWAMP)),e("C","39-53",[],B(["Warped Forest"])),e("C","39-53",["indoor","shipY"],S(["Shipwreck Cove (All Types)"]))]);
add(430,"돈크로우","Honchkrow",null,[e("C","36-51",["sky","n15"],B(DARK)),e("C","36-51",["night","sky"],B(["Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Bryce Canyon","Cloud Forest","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yosemite Lowlands","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands"]))]);
add(431,"나옹마","Glameow",null,[e("C","6-31",["clear","sky","n15"],{b:GLAMEOW,s:["Village (Plains)","Village (Taiga)"]}),e("C","6-31",["sky","n25"],{b:MEOWA,s:GLAMEOW2}),e("C","6-31",["indoor"],S(MANSION))]);
add(432,"몬냥이","Purugly",null,[e("C","6-31",["clear","sky","n15"],{b:GLAMEOW,s:["Village (Plains)","Village (Taiga)"]}),e("C","38-45",["sky","n25"],{b:MEOWA,s:GLAMEOW2}),e("C","38-45",["indoor"],S(MANSION))]);
add(433,"랑딸랑","Chingling",null,[e("U","4-29",["night","sky"],B(["Forest","Cherry Grove","Flower Forest","Birch Forest","Dark Forest","Grove","Old Growth Birch Forest","Pale Garden","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Meadow","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Alpine Highlands","Snowy Slopes","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater","Volcanic Peaks","Yosemite Cliffs","Deep Dark","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Ice Marsh","Moonlight Grove","Shield","Siberian Taiga","Cold Shrubland","Siberian Grove","Snowy Shield","Wintry Forest","Wintry Lowlands"])),e("U","4-29",["night","sky"],B(MYST)),e("U","4-29",["night","bell"],OW())]);
add(434,"스컹뿡","Stunky",null,[e("C","3-33",["seeSky","n18"],B(SWAMP))]);
add(435,"스컹탱크","Skuntank",null,[e("U","35-56",["seeSky","n18"],B(SWAMP))]);
add(436,"동미러","Bronzor",null,[e("U","5-30",["dim","minY0"],B(BRONZOR)),e("C","5-30",["minY48"],S(["Jungle Pyramid"])),e("C","5-30",["minYm37","maxY40"],S(["Cobblemon Ruins (All Types)"])),e("C","5-30",["minY48"],S(["Trail Ruins"]))]);
add(437,"동탁군","Bronzong",null,[e("U","33-50",["dim","minY0"],B(BRONZOR)),e("C","33-50",["minY48"],S(["Jungle Pyramid","Trail Ruins"])),e("C","33-50",["minYm37","maxY40"],S(["Cobblemon Ruins (All Types)"]))]);
add(438,"꼬지지","Bonsly",null,[e("U","4-29",["clear","sky"],B(FOREST_G))]);
add(439,"흉내내","Mime Jr.",null,[e("U","6-31",["sky"],OW(["얼음 계열"])),e("U","9-33",["sky"],S(VILD)),e("C","6-31",["indoor"],S(MANSION))]);
add(439,"흉내내","Mime Jr.","가라르 계열",[e("U","6-31",["sky"],B(FREEZE)),e("U","6-31",["sky"],S(["Village (Snowy)"]))]);
add(440,"핑복","Happiny",null,[e("R","1-22",["sky","n025"],B(["Plains","Sunflower Plains","Cherry Grove","Forest","Flower Forest","Meadow","Birch Forest","Grove","Old Growth Birch Forest","Brushland","Shrubland","Steppe","Valley Clearing","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Alpine Highlands","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Arid Highlands","Blooming Plateau","Cloud Forest"])),e("R","1-22",["sky","n025"],S(VILALL))]);
add(441,"페라페","Chatot",null,[e("U","16-41",["day","sky"],B(JUNGLE)),e("C","16-41",["dim","shipY"],S(LSC))]);
add(442,"화강돌","Spiritomb",null,[e("U","24-49",["dim","maxY62"],S(["Ancient City"])),e("R","24-49",["minY48"],S(["Cobblemon Ruins (All Types)"])),e("U","34-57",["minYm37","maxY30"],S(["Crumbling Arch Ruins","Rooted Arch Ruins"])),e("R","36-55",["indoor","minY48"],S(["Desert Pyramid","Jungle Pyramid"]))]);
add(443,"딥상어동","Gible",null,[e("R","5-30",["dim","minY0"],B(GIBLE)),e("X","5-30",["sky"],B(GIBLE)),e("R","5-30",["dim","minY0","magma"],OW(["악지 계열","Deep Dark","산 계열"]))]);
add(444,"한바이트","Gabite",null,[e("R","24-47",["dim","minY0"],B(GIBLE)),e("X","24-47",["sky"],B(GIBLE)),e("R","24-47",["dim","minY0","magma"],OW(["악지 계열","Deep Dark","산 계열"]))]);
add(445,"한카리아스","Garchomp",null,[e("R","48-60",["dim","minY0"],B(GIBLE)),e("X","48-60",["sky"],B(GIBLE)),e("R","48-60",["dim","minY0","magma"],OW(["악지 계열","Deep Dark","산 계열"]))]);
add(446,"먹고자","Munchlax",null,[e("R","14-39",["sky","nosacch"],B(SNORLAX)),e("U","20-39",["sky","sacch"],OW())]);
add(447,"리오르","Riolu",null,[e("R","4-29",["sky","n025"],B(GEO))]);
add(448,"루카리오","Lucario",null,[e("R","24-53",["sky","n025"],B(GEO))]);
add(449,"히포포타스","Hippopotas",null,[e("C","8-33",["sky","rain5"],B(SAND))]);
add(450,"하마돈","Hippowdon",null,[e("C","34-53",["sky","rain5"],B(SAND))]);
add(451,"스콜피","Skorupi",null,[e("C","8-33",["sky","n15"],B(SKORUPI))]);
add(452,"드래피온","Drapion",null,[e("C","40-52",["sky","n15"],B(SKORUPI))]);
add(453,"삐딱구리","Croagunk",null,[e("C","5-30",["sky","rain5"],B(CROAGUNK))]);
add(454,"독개굴","Toxicroak",null,[e("C","37-49",["sky","rain5"],B(CROAGUNK))]);
add(455,"무스틈니","Carnivine",null,[e("U","20-45",["sky"],B(SWAMP)),e("U","20-45",["dim"],B(LUSHC)),e("U","20-45",["dim","shipY"],S(LSC))]);
add(456,"형광어","Finneon",null,[e("C","8-33",["sub","seeSky","maxY48"],B(DEEPO)),e("C","8-33",["sub","indoor","sky","maxY48"],B(DEEPO)),e("C","8-33",["sub","indoor","subY"],S(SSC))]);
add(457,"네오라이트","Lumineon",null,[e("C","31-46",["sub","seeSky","maxY48"],B(DEEPO)),e("C","31-46",["sub","indoor","sky","maxY48"],B(DEEPO)),e("C","31-46",["sub","indoor","subY"],S(SSC))]);
add(458,"타만타","Mantyke",null,[e("U","10-35",["sub","seeSky","minY48"],B(HORSEA)),e("U","10-35",["sub","indoor","sky","minY48"],B(HORSEA))]);
add(459,"눈쓰개","Snover",null,[e("C","7-32",[],B(AVULPIX))]);
add(460,"눈설왕","Abomasnow",null,[e("U","42-55",[],B(AVULPIX))]);
add(461,"포푸니라","Weavile",null,[e("U","38-51",["sky","d025"],B(TAIGA))]);
add(462,"자포코일","Magnezone",null,[e("U","42-58",["redstone"],OW(["Deep Dark"])),e("C","42-58",["sky","t5","rod"],OW())]);
add(463,"내룸벨트","Lickilicky",null,[e("U","34-56",["sky","n025"],B(RAT))]);
add(464,"거대코뿌리","Rhyperior",null,[e("C","44-62",["sky","n025"],B(RHY))]);
add(465,"덩쿠림보","Tangrowth",null,[e("C","24-59",["sky"],B(JUNGLE))]);
add(466,"에레키블","Electivire",null,[e("U","45-58",["sky","t5"],B(["Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Meadow","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Volcanic Crater","Plains","Sunflower Plains","Brushland","Shrubland","Steppe","Valley Clearing"]))]);
add(467,"마그마번","Magmortar",null,[e("C","45-58",["clear","sky"],B(MOUNTV)),e("C","45-64",[],B(["Basalt Deltas","Nether Wastes"]))]);
add(468,"토게키스","Togekiss",null,[e("R","36-55",["clear","day","sky"],B(TOGE))]);
add(469,"메가자리","Yanmega",null,[e("U","33-52",["surf","clear","day","sky"],B(SURSKIT)),e("U","33-52",["surf","dim"],B(LUSHC)),e("U","33-52",["surf","dim","shipY"],S(LSC))]);
add(470,"리피아","Leafeon",null,[e("X","28-53",["sky"],B(WURMPLE)),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor"],S(MANSION))]);
add(471,"글레이시아","Glaceon",null,[e("X","28-53",["sky"],B(FREEZE)),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor"],S(MANSION))]);
add(472,"글라이온","Gliscor",null,[e("U","38-51",["night","sky"],B(BADLANDS)),e("C","38-54",[],B(["Basalt Deltas"]))]);
add(473,"맘모꾸리","Mamoswine",null,[e("C","40-53",["sky"],B(SWINUB))]);
add(474,"폴리곤Z","Porygon-Z",null,[e("R","47-72",[],END)]);
add(475,"엘레이드","Gallade",null,[e("R","30-52",["sky"],B(RALTS)),e("R","30-52",["sky"],S(VILALL)),e("C","30-52",["indoor"],S(MANSION))]);
add(476,"대코파스","Probopass",null,[e("U","33-53",["dim"],OW(["Deep Dark"]))]);
add(477,"야느와르몽","Dusknoir",null,[e("C","41-53",["night"],B(DARK)),e("C","41-63",[],B(["Soul Sand Valley"]))]);
add(478,"눈여아","Froslass",null,[e("U","42-48",["rain","sky"],B(SNOWSAND)),e("U","42-48",["dim","minY0"],B(["Jagged Peaks","Snowy Beach","Snowy Plains","Grove","Snowy Slopes","Snowy Badlands","Frozen Peaks","Ice Spikes","Glacial Chasm","Ice Marsh","Siberian Taiga","Siberian Grove","Snowy Cherry Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands"])),e("C","42-48",["sky115"],S(["Igloo"]))]);
add(479,"로토무","Rotom",null,[e("R","20-75",["machine"],OW())]);
add(480,"유크시","Uxie",null,[e("X","70-75",["special"],S(["Lake Acuity (Sinnoh)"]))]);
add(481,"엠라이트","Mesprit",null,[e("X","70-75",["special"],S(["Lake Verity (Sinnoh)"]))]);
add(482,"아그놈","Azelf",null,[e("X","70-75",["special"],S(["Lake Valor (Sinnoh)"]))]);
add(483,"디아루가","Dialga",null,[e("X","70-80",["special"],S(["Spear Pillar (Sinnoh)"]))]);
add(484,"펄기아","Palkia",null,[e("X","70-80",["special"],S(["Spear Pillar (Sinnoh)"]))]);
add(485,"히드런","Heatran",null,[e("X","70-90",["special"],S(["Stark Mountain (Nether)"]))]);
add(486,"레지기가스","Regigigas",null,[e("X","75-90",["special"],S(["Snowpoint Temple (Sinnoh)"]))]);
add(487,"기라티나","Giratina",null,[e("X","70-90",["special"],S(["Distortion World"]))]);
add(488,"크레세리아","Cresselia",null,[e("X","70-80",["special"],S(["Fullmoon Island (Sinnoh)"]))]);
add(489,"피오네","Phione",null,[e("X","1",["breed","special"],{})]);
add(490,"마나피","Manaphy",null,[e("X","50",["inwater","special"],S(["Temple of the Sea (Sinnoh)"]))]);
add(491,"다크라이","Darkrai",null,[e("X","70-85",["special"],S(["Newmoon Island"]))]);
add(492,"쉐이미","Shaymin",null,[e("X","30-75",["special"],S(["Flower Paradise (Sinnoh)"]))]);
add(493,"아르세우스","Arceus",null,[e("X","80-100",["special"],S(["Temple of Sinnoh"]))]);
// 출현 시점 안내 (LUMYVERSE 공식 사이트 lumyverse.com/en/cobbleverse/how-to-catch-all-legendary-mythical-pokemon: 신오 데이터팩은 호연 챔피언(성호)을 이긴 뒤에 열림)
Object.assign(UNLOCK,{480:"호연 시리즈 클리어(챔피언 성호 승리) 후",481:"호연 시리즈 클리어(챔피언 성호 승리) 후",482:"호연 시리즈 클리어(챔피언 성호 승리) 후",483:"호연 시리즈 클리어(챔피언 성호 승리) 후",484:"호연 시리즈 클리어(챔피언 성호 승리) 후",485:"호연 시리즈 클리어(챔피언 성호 승리) 후",486:"호연 시리즈 클리어(챔피언 성호 승리) 후",487:"호연 시리즈 클리어(챔피언 성호 승리) 후",488:"호연 시리즈 클리어(챔피언 성호 승리) 후",489:"호연 시리즈 클리어(챔피언 성호 승리) 후",490:"호연 시리즈 클리어(챔피언 성호 승리) 후",491:"호연 시리즈 클리어(챔피언 성호 승리) 후",492:"호연 시리즈 클리어(챔피언 성호 승리) 후",493:"호연 시리즈 클리어(챔피언 성호 승리) 후"});
