// ---- 7세대 (cobbleverse.wiki/spawns/gen7) ----
const ROWLET=["Forest","Cherry Grove","Flower Forest","Birch Forest","Dark Forest","Old Growth Birch Forest","Pale Garden","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Moonlight Grove","Moonlight Valley","Shield","Yosemite Lowlands"];
const YUNGOOS=["Plains","Sunflower Plains","Meadow","Brushland","Shrubland","Steppe","Alpine Highlands","Arid Highlands","Blooming Plateau","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Hot Shrubland","Red Oasis","Savanna Slopes"];
const MAREANIE=["Beach","Stony Shore","White Cliffs"];
const MAREANIE2=["Beach","Stony Shore","White Cliffs","Warm Ocean"];
const MUDBRAY=["Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis","Plains","Sunflower Plains","Brushland","Shrubland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Arid Highlands","Desert Oasis","Hot Shrubland","Savanna Slopes","Windswept Savanna"];
const MORELULL=["Jungle","Sparse Jungle","Bamboo Jungle","Underground Jungle","Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley","Mushroom Fields","Fungal Caves"];
const SALANDIT=["Volcanic Crater","Volcanic Peaks","Basalt Deltas"];
const SALANDIT2=["Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis","Meadow","Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera","Yosemite Cliffs"];
const SANDYGAST=["Beach","Desert","Ancient Sands","Desert Canyon","Desert Oasis","Lush Desert","Sandstone Valley"];

add(722,"나몰빼미","Rowlet",null,[e("X","5-32",["sky"],B(ROWLET))]);
add(722,"나몰빼미","Rowlet","히스이 계열",[e("X","5-32",["sky"],B(AVULPIX))]);
add(723,"빼미스로우","Dartrix",null,[e("X","17-42",["sky"],B(ROWLET))]);
add(723,"빼미스로우","Dartrix","히스이 계열",[e("X","17-42",["sky"],B(AVULPIX))]);
add(724,"모크나이퍼","Decidueye",null,[e("X","34-53",["sky"],B(ROWLET))]);
add(724,"모크나이퍼","Decidueye","히스이",[e("X","34-53",["sky"],B(AVULPIX))]);
add(725,"냐오불","Litten",null,[e("X","5-32",["clear","sky"],B(JUNGLE)),e("X","5-32",[],B(["Crimson Forest"]))]);
add(726,"냐오히트","Torracat",null,[e("X","17-42",["clear","sky"],B(JUNGLE)),e("X","17-42",[],B(["Crimson Forest"]))]);
add(727,"어흥염","Incineroar",null,[e("X","34-53",["clear","sky"],B(JUNGLE)),e("X","34-53",[],B(["Crimson Forest"]))]);
add(728,"누리공","Popplio",null,[e("X","5-32",["sky"],B(SHORE)),e("X","5-32",["sub","seeSky"],B(SHORE)),e("X","5-32",["sub","indoor","sky"],B(SHORE))]);
add(729,"키요공","Brionne",null,[e("X","17-42",["sky"],B(SHORE)),e("X","17-42",["sub","seeSky"],B(SHORE)),e("X","17-42",["sub","indoor","sky"],B(SHORE))]);
add(730,"누리레느","Primarina",null,[e("X","34-53",["sky"],B(SHORE)),e("X","34-53",["sub","seeSky"],B(SHORE)),e("X","34-53",["sub","indoor","sky"],B(SHORE))]);
add(731,"콕코구리","Pikipek",null,[e("C","2-27",["day","sky"],B(JUNGLE))]);
add(732,"크라파","Trumbeak",null,[e("C","14-36",["day","sky"],B(JUNGLE))]);
add(733,"왕큰부리","Toucannon",null,[e("C","28-49",["day","sky"],B(JUNGLE))]);
add(734,"영구스","Yungoos",null,[e("C","1-19",["sky","n025"],B(YUNGOOS))]);
add(735,"형사구스","Gumshoos",null,[e("C","20-42",["sky","n025"],B(YUNGOOS))]);
add(736,"턱지충이","Grubbin",null,[e("C","5-18",["sky"],B(JOLTIK))]);
add(737,"전지충이","Charjabug",null,[e("U","22-45",["sky"],B(JOLTIK))]);
add(738,"투구뿌논","Vikavolt",null,[e("R","40-67",["sky"],B(JOLTIK))]);
add(739,"오기지게","Crabrawler",null,[e("C","9-34",["sky"],B(SHORE))]);
add(740,"모단단게","Crabominable",null,[e("U","29-48",["sky"],B(["Frozen Peaks","Jagged Peaks","Snowy Slopes","Stony Peaks","Rocky Mountains"]))]);
add(741,"춤추새","Oricorio","이글이글스타일",[e("U","18-33",["seeSky"],B(["Plains","Sunflower Plains","Meadow","Brushland","Shrubland","Steppe","Alpine Highlands","Arid Highlands","Blooming Plateau","Valley Clearing","Badlands","Wooded Badlands","Eroded Badlands","Ashen Savanna","Red Oasis"]))]);
add(741,"춤추새","Oricorio","파칙파칙스타일",[e("U","18-33",["seeSky"],B(WOOBAT))]);
add(741,"춤추새","Oricorio","훌라훌라스타일",[e("U","18-33",["seeSky"],B(FLOWER))]);
add(741,"춤추새","Oricorio","하늘하늘스타일",[e("U","18-33",["seeSky"],B(FOREST_ALL))]);
add(742,"에블리","Cutiefly",null,[e("C","5-24",["clear","day","sky"],B(FLOWER)),e("C","5-24",["clear","day","sky","flowersacch"],OW(["꽃 계열","으스스한 계열"]))]);
add(743,"에리본","Ribombee",null,[e("C","25-46",["clear","day","sky"],B(FLOWER)),e("C","25-46",["clear","day","sky","flowersacch"],OW(["꽃 계열","으스스한 계열"]))]);
add(744,"암멍이","Rockruff",null,[e("U","5-22",["seeSky"],B(MOUNT))]);
add(744,"암멍이","Rockruff","황혼의 모습",[e("R","8-24",["seeSky"],B(BADLANDS))]);
add(745,"루가루암","Lycanroc","황혼의 모습",[e("U","29-45",["seeSky","dusk"],B(GIBLE))]);
add(745,"루가루암","Lycanroc","한낮의 모습",[e("U","29-45",["seeSky","day"],B(GIBLE))]);
add(745,"루가루암","Lycanroc","한밤중의 모습",[e("U","29-55",["seeSky","night"],B(GIBLE))]);
add(746,"약어리","Wishiwashi",null,[e("C","1-18",["sub","seeSky"],B(OCEAN)),e("C","1-18",["sub","indoor","sky"],B(OCEAN))]);
add(747,"시마사리","Mareanie",null,[e("U","6-35",["sky"],B(MAREANIE)),e("C","6-35",["floor","seeSky"],B(MAREANIE2))]);
add(748,"더시마사리","Toxapex",null,[e("U","38-50",["sky"],B(MAREANIE)),e("C","38-50",["floor","seeSky"],B(MAREANIE2))]);
add(749,"머드나기","Mudbray",null,[e("C","8-29",["sky","n025"],B(MUDBRAY))]);
add(750,"만마드","Mudsdale",null,[e("C","30-50",["sky","n025"],B(MUDBRAY))]);
add(751,"물거미","Dewpider",null,[e("U","2-20",["sky"],B(SURSKIT)),e("C","2-20",["floor","seeSky"],B(SURSKIT))]);
add(752,"깨비물거미","Araquanid",null,[e("U","22-45",["sky"],B(SURSKIT)),e("C","22-45",["floor","seeSky"],B(SURSKIT))]);
add(753,"짜랑랑","Fomantis",null,[e("C","1-33",["sky","d025"],B(FLOWER)),e("C","1-33",["sky","d025"],B(JUNGLE))]);
add(754,"라란티스","Lurantis",null,[e("C","34-48",["sky","d025"],B(FLOWER)),e("C","34-48",["sky","d025"],B(JUNGLE))]);
add(755,"자마슈","Morelull",null,[e("C","4-23",["light07"],B(MORELULL)),e("C","4-23",["dim"],B(LUSHC)),e("C","4-23",[],B(["Crimson Forest","Warped Forest"])),e("C","4-23",["dim","shipY"],S(LSC))]);
add(756,"마셰이드","Shiinotic",null,[e("C","24-41",["light07"],B(MORELULL)),e("C","24-41",["dim"],B(LUSHC)),e("C","24-41",[],B(["Crimson Forest","Warped Forest"])),e("C","24-41",["dim","shipY"],S(LSC))]);
add(757,"야도뇽","Salandit",null,[e("C","7-32",[],B(SALANDIT)),e("C","7-32",["dim","lavab"],B(SALANDIT2)),e("R","7-32",[],B(["Soul Sand Valley"]))]);
add(758,"염뉴트","Salazzle",null,[e("C","33-48",[],B(SALANDIT)),e("C","33-48",["dim","lavab"],B(SALANDIT2)),e("R","33-48",[],B(["Soul Sand Valley"]))]);
add(759,"포곰곰","Stufful",null,[e("C","9-26",["sky"],B(["Bamboo Jungle"]))]);
add(760,"이븐곰","Bewear",null,[e("C","27-50",["sky"],B(["Bamboo Jungle"]))]);
add(761,"달콤아","Bounsweet",null,[e("C","1-17",["sky"],B(JUNGLE))]);
add(762,"달무리나","Steenee",null,[e("C","18-29",["sky"],B(JUNGLE))]);
add(763,"달코퀸","Tsareena",null,[e("C","28-51",["sky"],B(JUNGLE))]);
add(764,"큐아링","Comfey",null,[e("U","24-49",["clear","sky"],B(FLOWER)),e("R","24-49",["clear","sky","flowers"],OW())]);
add(765,"하랑우탄","Oranguru",null,[e("R","35-60",["sky"],B(JUNGLE))]);
add(766,"내던숭이","Passimian",null,[e("R","25-57",["sky"],B(JUNGLE))]);
add(767,"꼬시레","Wimpod",null,[e("U","1-27",["sky"],B(SHORE)),e("U","1-27",["dim","maxY0","water"],OW(["Deep Dark"])),e("U","1-27",["floor","dim","maxY0"],OW(["Deep Dark"]))]);
add(768,"갑주무사","Golisopod",null,[e("U","30-53",["sky"],B(SHORE)),e("U","30-53",["dim","maxY0","water"],OW(["Deep Dark"])),e("U","30-53",["floor","dim","maxY0"],OW(["Deep Dark"]))]);
add(769,"모래꿍","Sandygast",null,[e("C","7-40",["sky","n15"],B(SANDYGAST))]);
add(770,"모래성이당","Palossand",null,[e("C","42-58",["sky","n15"],B(SANDYGAST))]);
add(771,"해무기","Pyukumuku",null,[e("U","16-41",["sky"],B(["Beach","Snowy Beach"])),e("C","16-41",["floor","seeSky","minY48"],B(["Ocean","Lukewarm Ocean","Cold Ocean","Deep Ocean","Deep Cold Ocean","Deep Warm Ocean"])),e("C","16-41",["floor","seeSky"],B(["Warm Ocean"]))]);
add(772,"타입:널","Type: Null",null,[e("X","1",["special"],S(["Resurrection Machine"]))]);
add(774,"메테노","Minior",null,[e("R","20-30",["seeSky","day"],OW())]);
add(774,"메테노","Minior","빨간색 코어",[e("U","20-30",["seeSky","night"],B(MOUNT))]);
add(774,"메테노","Minior","주황색 코어",[e("U","20-30",["seeSky","night"],B(SAVANNA))]);
add(774,"메테노","Minior","노란색 코어",[e("U","20-30",["seeSky","night"],B(PLAINS))]);
add(774,"메테노","Minior","초록색 코어",[e("U","20-30",["seeSky","night"],B(JUNGLE))]);
add(774,"메테노","Minior","파란색 코어",[e("U","20-30",["seeSky","night"],B(BASCULIN))]);
add(774,"메테노","Minior","남색 코어",[e("U","20-30",["seeSky","night"],B(["Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Snowy Badlands","Frozen Peaks","Stony Peaks","Rocky Mountains","Cold Ocean","Deep Cold Ocean","Taiga","Snowy Taiga","Old Growth Pine Taiga","Cloud Forest","Old Growth Spruce Taiga","Bryce Canyon","Ice Marsh","Moonlight Grove","Ice Spikes","Moonlight Valley","Shield","Siberian Taiga","Yosemite Lowlands","Cold Shrubland"]))]);
add(774,"메테노","Minior","보라색 코어",[e("U","20-30",["seeSky","night"],B(GEO))]);
add(775,"자말라","Komala",null,[e("C","23-48",["sky"],B(SAVANNA))]);
add(776,"폭거북스","Turtonator",null,[e("R","24-49",[],B(["Basalt Deltas"]))]);
add(777,"토게데마루","Togedemaru",null,[e("U","19-44",["sky","t5"],B(["Windswept Forest","Windswept Gravelly Hills","Windswept Hills","Windswept Savanna","Meadow","Alpine Grove","Alpine Highlands","Blooming Valley","Forested Highlands","Snowy Slopes","Lavender Valley","Lush Valley","Arid Highlands","Savanna Slopes","Moonlight Valley","Sakura Valley","Temperate Highlands","Blooming Plateau","Yosemite Lowlands","Caldera"]))]);
add(778,"따라큐","Mimikyu",null,[e("R","23-48",["night"],B(DARK)),e("U","23-48",["indoor"],S(MANSION))]);
add(779,"치갈기","Bruxish",null,[e("U","23-48",["sub","seeSky"],B(["Warm Ocean"])),e("U","23-48",["sub","indoor","sky"],B(["Warm Ocean"]))]);
add(780,"할비롱","Drampa",null,[e("R","24-49",["sky","minY190"],B(MEDITITE))]);
add(781,"타타륜","Dhelmise",null,[e("C","27-52",["sub","seeSky"],S(["Shipwreck"])),e("C","27-52",["sub","indoor","sky"],S(["Shipwreck"])),e("C","27-52",["sub","subY"],S(["Shipwreck Cove (All Types)"]))]);
add(782,"짜랑꼬","Jangmo-o",null,[e("X","5-33",["minY0"],B(JUNGLE)),e("R","5-33",["minY0"],B(BURMY))]);
add(783,"짜랑고우","Hakamo-o",null,[e("X","35-44",["minY0"],B(JUNGLE)),e("R","35-44",["minY0"],B(BURMY))]);
add(784,"짜랑고우거","Kommo-o",null,[e("X","45-60",["minY0"],B(JUNGLE)),e("R","45-60",["minY0"],B(BURMY))]);
add(785,"카푸꼬꼬꼭","Tapu Koko",null,[e("X","50-70",["seeSky"],B(SAVANNA))]);
add(786,"카푸나비나","Tapu Lele",null,[e("X","50-70",["seeSky"],B(FLOWER))]);
add(787,"카푸브루루","Tapu Bulu",null,[e("X","50-70",["seeSky"],B(JUNGLE))]);
add(788,"카푸느지느","Tapu Fini",null,[e("X","50-70",["seeSky"],B(["River","Warm River","Frozen River","Beach","Snowy Beach"]))]);
add(789,"코스모그","Cosmog",null,[e("X","28-42",[],END)]);
add(790,"코스모움","Cosmoem",null,[e("X","44-52",[],END)]);
add(791,"솔가레오","Solgaleo",null,[e("X","55-75",[],END)]);
add(792,"루나아라","Lunala",null,[e("X","55-75",[],END)]);
add(793,"텅비드","Nihilego",null,[e("X","50-73",["sub"],B(OCEAN))]);
add(794,"매시붕","Buzzwole",null,[e("X","53-74",["seeSky"],B(JUNGLE))]);
add(795,"페로코체","Pheromosa",null,[e("X","55-69",[],END)]);
add(796,"전수목","Xurkitree",null,[e("X","58-72",[],END)]);
add(797,"철화구야","Celesteela",null,[e("X","65-80",[],END)]);
add(798,"종이신도","Kartana",null,[e("X","45-67",["seeSky"],B(VIVILLON))]);
add(799,"악식킹","Guzzlord",null,[e("X","70-78",[],END)]);
add(800,"네크로즈마","Necrozma",null,[e("X","60-75",[],END)]);
add(801,"마기아나","Magearna",null,[e("X","50-70",["seeSky"],B(TAIGA))]);
add(801,"마기아나","Magearna","500년 전의 색",[e("X","68-78",["seeSky"],B(TAIGA))]);
add(802,"마샤도","Marshadow",null,[e("X","45-68",["indoor"],B(["Deep Dark","Deep Caves"]))]);
add(803,"베베놈","Poipole",null,[e("X","40",[],S(["Dawn Tower (End)","Dusk Tower (End)"]))]);
add(804,"아고용","Naganadel",null,[e("X","48-62",[],END)]);
add(805,"차곡차곡","Stakataka",null,[e("X","60-72",["indoor"],B(["Deep Dark","Deep Caves"]))]);
add(806,"두파팡","Blacephalon",null,[e("X","55-62",["seeSky"],B(DARK))]);
add(807,"제라오라","Zeraora",null,[e("X","45-85",["seeSky"],B(MYST))]);
add(808,"멜탄","Meltan",null,[e("X","38-48",["seeSky","ironblock"],OW()),e("X","38-52",[],B(["Beach","Snowy Beach"]))]);
