// ---- 1세대 (COBBLEVERSE 모드팩 1.7.42 데이터팩 COBBLEVERSE-DP-v31 기준) ----
const CHARMANDER=["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Mantle Caves","Volcanic Crater","Volcanic Peaks"];
const SQUIRTLE=["River","Warm River","Mangrove Swamp","Swamp","Orchid Swamp","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Alpha Islands","Lavender Forest","Mirage Isles","Sakura Grove","Plains","Sunflower Plains","Shrubland","Brushland","Steppe","Valley Clearing"];
const CATERPIE=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const WEEDLE=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"];
const PIDGEY2=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter"];
const RATTATA=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes"];
const SPEAROW=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland","Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter"];
const EKANS2=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland"];
const PIKACHU=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"];
const SANDSHREW=["Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Red Oasis","Sandstone Valley"];
const SANDSHREW2=["Frozen Peaks","Ice Spikes","Frostfire Caves","Frozen Cliffs","Glacial Chasm"];
const NIDORAN=["Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland"];
const CLEFAIRY=["Dripstone Caves","Fractured Savanna","Stony Spires"];
const CLEFAIRY2=["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands"];
const CLEFAIRY3=["Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley"];
const VULPIX=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Haze Mountain","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"];
const VULPIX2=["Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands"];
const JIGGLYPUFF=["Plains","Alpine Highlands","Arid Highlands","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const ZUBAT=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Mangrove Swamp","Swamp","Orchid Swamp"];
const ZUBAT2=["Deep Dark","Crystal Caves","Deep Caves","Frostfire Caves","Mantle Caves","Tuff Caves"];
const ODDISH=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const PARAS=["Dark Forest","Mushroom Fields","Fungal Caves","Mirage Isles"];
const VENONAT=["Dark Forest","Deep Dark","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];
const MEOWTH=["Pillager Outpost","Swamp Hut","Woodland Mansion"];
const MEOWTH2=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Brushland","Fractured Savanna","Hot Shrubland","Savanna Badlands","Savanna Slopes","Shrubland","Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands"];
const MEOWTH3=["Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands","Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Haze Mountain","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"];
const PSYDUCK=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","River","Warm River","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Amethyst Canyon","Amethyst Rainforest","Moonlight Grove","Moonlight Valley"];
const PSYDUCK2=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","River","Warm River","Mangrove Swamp","Swamp","Orchid Swamp","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Amethyst Canyon","Amethyst Rainforest","Moonlight Grove","Moonlight Valley"];
const MANKEY=["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle"];
const GROWLITHE=["Frozen Peaks","Jagged Peaks","Snowy Slopes","Stony Peaks","Emerald Peaks","Rocky Mountains","Scarlet Mountains","Windswept Spires"];
const POLIWAG=["River","Warm River","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Mushroom Fields","Fungal Caves","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Alpha Islands","Lavender Forest","Sakura Grove","Plains","Sunflower Plains","Shrubland","Brushland","Steppe","Valley Clearing"];
const ABRA2=["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Alpha Islands","Alpha Islands Winter","Lavender Forest","Sakura Grove","Plains","Sunflower Plains","Shrubland","Brushland","Steppe","Valley Clearing"];
const TENTACRUEL=["Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs"];
const GEODUDE=["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"];
const PONYTA=["Plains","Alpine Highlands","Arid Highlands","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes"];
const PONYTA2=["Cherry Grove","Flower Forest","Meadow","Sunflower Plains","Sakura Grove","Sakura Valley","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley"];
const SEEL2=["Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs"];
const SHELLDER=["Cold Ocean","Deep Cold Ocean","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs"];
const SHELLDER2=["Deep Ocean","Deep Lukewarm Ocean","Ocean","Lukewarm Ocean","Warm Ocean"];
const KRABBY=["Stony Shore","Beach","Snowy Beach","Basalt Cliffs","Granite Cliffs","White Cliffs"];
const KRABBY2=["Stony Shore","Beach","Snowy Beach","Basalt Cliffs","Granite Cliffs","White Cliffs","Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs"];
const EXEGGCUTE=["Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Savanna","Savanna Plateau","Windswept Savanna","Arid Highlands","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes","Shrubland"];
const CUBONE=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Sandstone Valley"];
const CUBONE2=["Mantle Caves","Volcanic Crater","Volcanic Peaks"];
const RHYHORN=["Meadow","Cherry Grove","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Stony Spires","Volcanic Peaks","Yosemite Cliffs","Savanna","Savanna Plateau","Ashen Savanna","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Shrubland"];
const MRMIME=["Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands"];
const TAUROS2=["Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands"];
const MAGIKARP=["River","Frozen River","Warm River","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp","Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs"];
const VAPOREON=["River","Warm River","Mangrove Swamp","Swamp","Orchid Swamp","Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Sakura Grove","Sakura Valley","Temperate Highlands","Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];

add(1,"이상해씨","Bulbasaur",null,[e("X","5-32",["sky"],B(JUNGLE))]);
add(2,"이상해풀","Ivysaur",null,[e("X","16-40",["sky"],B(JUNGLE))]);
add(3,"이상해꽃","Venusaur",null,[e("X","32-52",["sky"],B(JUNGLE))]);
add(4,"파이리","Charmander",null,[e("X","5-31",["sky","norain"],B(CHARMANDER)),e("X","5-31",[],B(["Basalt Deltas"]))]);
add(5,"리자드","Charmeleon",null,[e("X","16-40",["sky","norain"],B(CHARMANDER)),e("X","16-40",[],B(["Basalt Deltas"]))]);
add(6,"리자몽","Charizard",null,[e("X","36-53",["sky","norain"],B(CHARMANDER)),e("X","36-53",[],B(["Basalt Deltas"]))]);
add(7,"꼬부기","Squirtle",null,[e("X","5-31",["sky","water"],B(SQUIRTLE)),e("X","5-31",["sub","seeSky"],B(SQUIRTLE)),e("X","5-31",["sub","indoor","sky"],B(SQUIRTLE))]);
add(8,"어니부기","Wartortle",null,[e("X","16-40",["sky","water"],B(SQUIRTLE)),e("X","16-40",["sub","seeSky"],B(SQUIRTLE)),e("X","16-40",["sub","indoor","sky"],B(SQUIRTLE))]);
add(9,"거북왕","Blastoise",null,[e("X","36-53",["sky","water"],B(SQUIRTLE)),e("X","36-53",["sub","seeSky"],B(SQUIRTLE)),e("X","36-53",["sub","indoor","sky"],B(SQUIRTLE))]);
add(10,"캐터피","Caterpie",null,[e("C","1-20",["sky","leaves","treetop"],B(CATERPIE))]);
add(10,"캐터피","Caterpie","발렌시아",[e("C","1-20",["sky","treetop"],B(JUNGLE))]);
add(11,"단데기","Metapod",null,[e("C","7-21",["sky","leaves","treetop"],B(CATERPIE))]);
add(11,"단데기","Metapod","발렌시아",[e("C","7-21",["sky","treetop"],B(JUNGLE))]);
add(12,"버터플","Butterfree",null,[e("C","10-40",["sky","day"],B(["Forest","Birch Forest","Old Growth Birch Forest","Alpha Islands","Forested Highlands","Mirage Isles","Temperate Highlands","Plains","Alpine Highlands","Arid Highlands","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"])),e("C","10-40",["sky","day"],B(FLOWER))]);
add(12,"버터플","Butterfree","발렌시아",[e("C","10-40",["sky","day"],B(JUNGLE))]);
add(13,"뿔충이","Weedle",null,[e("C","1-20",["sky","treetop"],B(WEEDLE))]);
add(14,"딱충이","Kakuna",null,[e("C","7-21",["sky","treetop"],B(WEEDLE))]);
add(15,"독침붕","Beedrill",null,[e("C","10-40",["sky","day","norain"],B(WEEDLE))]);
add(16,"구구","Pidgey",null,[e("C","1-25",["sky","day","treetop"],B(PIDGEY2))]);
add(17,"피죤","Pidgeotto",null,[e("C","18-35",["sky","day","treetop"],B(PIDGEY2))]);
add(18,"피죤투","Pidgeot",null,[e("C","36-48",["sky","day","treetop"],B(PIDGEY2))]);
add(19,"꼬렛","Rattata",null,[e("C","1-25",["sky","night"],B(RATTATA)),e("C","1-25",["dim","minY0"],OW(["?#cobblemon:is_deep_dark"])),e("U","1-25",["indoor","light0","minY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(19,"꼬렛","Rattata","알로라",[e("C","1-25",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"])),e("U","1-25",["indoor","light0","maxY0"],OW(["?#cobblemon:is_deep_dark"])),e("C","1-25",["sky","night"],B(["Dark Forest","Deep Dark"])),e("U","1-25",["indoor","light0"],B(["Dark Forest"]))]);
add(20,"레트라","Raticate",null,[e("C","20-41",["sky","night"],B(RATTATA)),e("C","20-41",["dim","minY0"],OW(["?#cobblemon:is_deep_dark"])),e("U","20-41",["indoor","light0","minY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(20,"레트라","Raticate","알로라",[e("C","20-41",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"])),e("U","20-41",["indoor","light0","maxY0"],OW(["?#cobblemon:is_deep_dark"])),e("C","20-41",["sky","night"],B(["Dark Forest","Deep Dark"])),e("U","20-41",["indoor","light0"],B(["Dark Forest"]))]);
add(21,"깨비참","Spearow",null,[e("C","1-26",["sky","day","treetop"],B(SPEAROW))]);
add(22,"깨비드릴조","Fearow",null,[e("C","20-44",["sky","day","treetop"],B(SPEAROW))]);
add(23,"아보","Ekans","클래식 무늬",[e("C","4-29",["sky"],B(EKANS2))]);
add(23,"아보","Ekans","레거시 무늬",[e("C","4-29",["sky"],B(EKANS2))]);
add(23,"아보","Ekans","어택 무늬",[e("C","4-29",["sky"],B(EKANS2))]);
add(23,"아보","Ekans","스피드 무늬",[e("C","4-29",["sky"],B(EKANS2))]);
add(23,"아보","Ekans","일루시브 무늬",[e("C","4-29",["sky"],B(EKANS2))]);
add(23,"아보","Ekans","사운드 무늬",[e("C","4-29",["sky"],B(EKANS2))]);
add(23,"아보","Ekans","어두운 무늬",[e("C","4-29",[],B(["Deep Dark"]))]);
add(24,"아보크","Arbok","클래식 무늬",[e("C","22-45",["sky"],B(EKANS2))]);
add(24,"아보크","Arbok","레거시 무늬",[e("C","22-45",["sky"],B(EKANS2))]);
add(24,"아보크","Arbok","어택 무늬",[e("C","22-45",["sky"],B(EKANS2))]);
add(24,"아보크","Arbok","스피드 무늬",[e("C","22-45",["sky"],B(EKANS2))]);
add(24,"아보크","Arbok","일루시브 무늬",[e("C","22-45",["sky"],B(EKANS2))]);
add(24,"아보크","Arbok","사운드 무늬",[e("C","22-45",["sky"],B(EKANS2))]);
add(24,"아보크","Arbok","어두운 무늬",[e("C","22-45",[],B(["Deep Dark"]))]);
add(25,"피카츄","Pikachu",null,[e("U","16-32",["sky","t2"],B(PIKACHU))]);
add(25,"피카츄","Pikachu","알로라 계열",[e("U","16-32",["sky","t5"],B(["Beach"]))]);
add(25,"피카츄","Pikachu","옷갈아입기 마담",[e("R","22-44",["sky"],B(["Sunflower Plains"]))]);
add(25,"피카츄","Pikachu","옷갈아입기 마스크드",[e("R","22-44",["sky"],B(["Savanna","Savanna Plateau","Windswept Savanna"]))]);
add(25,"피카츄","Pikachu","옷갈아입기 닥터",[e("R","22-44",["sky"],B(["Bamboo Jungle","Jungle","Sparse Jungle"]))]);
add(25,"피카츄","Pikachu","옷갈아입기 아이돌",[e("R","22-44",["sky"],B(["Cherry Grove"]))]);
add(25,"피카츄","Pikachu","옷갈아입기 하드록",[e("R","22-44",["sky"],B(["Badlands","Eroded Badlands","Wooded Badlands"]))]);
add(26,"라이츄","Raichu",null,[e("U","27-49",["sky","t5"],B(PIKACHU))]);
add(26,"라이츄","Raichu","알로라",[e("U","27-49",["sky","t5"],B(["Beach"]))]);
add(27,"모래두지","Sandshrew",null,[e("C","5-30",[],B(SANDSHREW))]);
add(27,"모래두지","Sandshrew","알로라",[e("U","15-32",[],B(SANDSHREW2))]);
add(28,"고지","Sandslash",null,[e("C","22-47",[],B(SANDSHREW))]);
add(28,"고지","Sandslash","알로라",[e("U","24-55",[],B(SANDSHREW2))]);
add(29,"니드런♀","Nidoran ♀",null,[e("U","3-28",["sky"],B(NIDORAN))]);
add(30,"니드리나","Nidorina",null,[e("U","16-37",["sky"],B(NIDORAN))]);
add(31,"니드퀸","Nidoqueen",null,[e("U","37-51",["sky"],B(NIDORAN))]);
add(32,"니드런♂","Nidoran ♂",null,[e("U","3-28",["sky"],B(NIDORAN))]);
add(33,"니드리노","Nidorino",null,[e("U","16-37",["sky"],B(NIDORAN))]);
add(34,"니드킹","Nidoking",null,[e("U","37-51",["sky"],B(NIDORAN))]);
add(35,"삐삐","Clefairy",null,[e("U","17-32",["sky","night"],B(CLEFAIRY)),e("U","17-32",["dim"],B(CLEFAIRY)),e("U","17-32",["sky","night","moon"],B(CLEFAIRY2)),e("U","17-32",["sky","night"],B(CLEFAIRY3))]);
add(36,"픽시","Clefable",null,[e("U","27-48",["sky","night"],B(CLEFAIRY)),e("U","27-48",["dim"],B(CLEFAIRY)),e("U","27-48",["sky","night","moon"],B(CLEFAIRY2)),e("U","27-48",["sky","night"],B(CLEFAIRY3))]);
add(37,"식스테일","Vulpix",null,[e("U","5-30",["sky","twi"],B(VULPIX))]);
add(37,"식스테일","Vulpix","알로라",[e("U","5-30",["sky","twi"],B(VULPIX2)),e("R","35-55",["sky"],{b:["Snowy Plains"],s:["Crown Spire"]})]);
add(38,"나인테일","Ninetales",null,[e("U","25-51",["sky","twi"],B(VULPIX))]);
add(38,"나인테일","Ninetales","알로라",[e("U","25-51",["sky","twi"],B(VULPIX2))]);
add(39,"푸린","Jigglypuff",null,[e("C","16-27",["sky","n15"],B(FLOWER)),e("C","16-27",["sky","n15"],B(JIGGLYPUFF))]);
add(40,"푸크린","Wigglytuff",null,[e("C","22-44",["sky","n15"],B(FLOWER)),e("C","22-44",["sky","n15"],B(JIGGLYPUFF))]);
add(41,"주뱃","Zubat",null,[e("C","1-25",["sky","night","norain"],B(ZUBAT)),e("C","1-25",["dim","n025"],B(ZUBAT)),e("C","1-25",["dim","d15"],OW(["?#cobblemon:is_deep_dark","숲 계열","늪 계열"])),e("U","1-25",["indoor","light0","d15"],OW(["?#cobblemon:is_deep_dark","숲 계열","늪 계열"])),e("C","1-25",["sky","norain","n15"],B(["Dark Forest","Deep Dark"])),e("U","1-25",["dim"],B(ZUBAT2))]);
add(42,"골뱃","Golbat",null,[e("C","22-46",["sky","night","norain"],B(ZUBAT)),e("C","22-46",["dim","n025"],B(ZUBAT)),e("C","22-46",["dim","d15"],OW(["?#cobblemon:is_deep_dark","숲 계열","늪 계열"])),e("U","22-46",["indoor","light0","d15"],OW(["?#cobblemon:is_deep_dark","숲 계열","늪 계열"])),e("C","22-46",["sky","norain","n15"],B(["Dark Forest","Deep Dark"])),e("U","22-46",["dim"],B(ZUBAT2))]);
add(43,"뚜벅쵸","Oddish",null,[e("C","7-32",["sky","d025"],B(JUNGLE)),e("C","7-32",["sky","d025"],B(ODDISH))]);
add(43,"뚜벅쵸","Oddish","발렌시아",[e("C","7-32",["sky","d025"],B(NIDORAN))]);
add(44,"냄새꼬","Gloom",null,[e("C","21-40",["sky","d025"],B(JUNGLE)),e("C","21-40",["sky","d025"],B(ODDISH))]);
add(44,"냄새꼬","Gloom","발렌시아",[e("C","21-40",["sky","d025"],B(NIDORAN))]);
add(45,"라플레시아","Vileplume",null,[e("C","35-49",["sky","night"],B(JUNGLE)),e("C","35-49",["sky","night"],B(ODDISH))]);
add(45,"라플레시아","Vileplume","발렌시아",[e("C","35-49",["sky","night"],B(NIDORAN))]);
add(46,"파라스","Paras",null,[e("U","4-29",["dim"],B(LUSHC)),e("C","4-29",[],B(PARAS)),e("C","4-29",[],B(["Crimson Forest"])),e("U","4-29",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(47,"파라섹트","Parasect",null,[e("U","24-41",["dim"],B(LUSHC)),e("C","24-41",[],B(PARAS)),e("C","24-41",[],B(["Crimson Forest"])),e("U","24-41",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(48,"콘팡","Venonat",null,[e("C","6-31",["sky","night"],B(VENONAT))]);
add(49,"도나리","Venomoth",null,[e("C","31-45",["sky","night","norain"],B(VENONAT))]);
add(50,"디그다","Diglett",null,[e("C","2-27",["dim","minY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(50,"디그다","Diglett","알로라",[e("C","2-27",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(51,"닥트리오","Dugtrio",null,[e("C","26-43",["dim","minY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(51,"닥트리오","Dugtrio","알로라",[e("C","26-43",["dim","maxY0"],OW(["?#cobblemon:is_deep_dark"]))]);
add(52,"나옹","Meowth",null,[e("C","4-29",["sky","norain","n15"],OW(["건조 계열","얼음 계열","타이가 계열"])),e("C","4-29",["sky","norain","n15"],{all:"ow",ex:["건조 계열","얼음 계열","타이가 계열"],s:VILALL}),e("C","4-29",["sky","n15"],B(EKANS2)),e("C","4-29",["sky","n15"],{b:EKANS2,s:VILALL})]);
add(52,"나옹","Meowth","알로라",[e("C","4-29",["sky","norain","minY62","n15"],{all:"ow",ex:["건조 계열","얼음 계열"],s:MEOWTH}),e("C","4-29",["sky","n15"],B(MEOWTH2)),e("U","4-29",["indoor","minY62"],S(MEOWTH))]);
add(52,"나옹","Meowth","가라르",[e("C","4-29",["sky","concrete","n15"],B(MEOWTH3)),e("C","4-29",["sky","n15"],{b:MEOWTH3,s:VILALL})]);
add(53,"페르시온","Persian",null,[e("C","28-44",["sky","norain","concrete","n15"],OW(["건조 계열","얼음 계열","타이가 계열"])),e("C","28-44",["sky","norain","n15"],{all:"ow",ex:["건조 계열","얼음 계열","타이가 계열"],s:VILALL}),e("C","28-44",["sky","concrete","n15"],B(EKANS2)),e("C","28-44",["sky","n15"],{b:EKANS2,s:VILALL})]);
add(53,"페르시온","Persian","알로라",[e("C","28-44",["sky","norain","minY62","n15"],{all:"ow",ex:["건조 계열","얼음 계열"],s:MEOWTH}),e("C","28-44",["sky","n15"],B(MEOWTH2)),e("U","28-44",["indoor","minY62"],S(MEOWTH))]);
add(54,"고라파덕","Psyduck",null,[e("C","7-32",["sky"],B(SWAMP)),e("C","7-32",["sky","water","flow"],B(PSYDUCK)),e("C","7-32",["sub","seeSky","sky"],B(PSYDUCK2))]);
add(55,"골덕","Golduck",null,[e("C","33-50",["sky"],B(SWAMP)),e("C","33-50",["sky","water","flow"],B(PSYDUCK)),e("C","33-50",["sub","seeSky","sky"],B(PSYDUCK2))]);
add(56,"망키","Mankey",null,[e("C","6-31",["sky","treetop"],B(MANKEY))]);
add(57,"성원숭","Primeape",null,[e("C","28-46",["sky","treetop"],B(MANKEY))]);
add(58,"가디","Growlithe",null,[e("U","10-35",["sky","concrete"],OW(["사막 계열"])),e("U","10-35",["sky"],{all:"ow",ex:["사막 계열"],s:VILALL})]);
add(58,"가디","Growlithe","히스이",[e("U","12-36",["seeSky"],B(GROWLITHE))]);
add(59,"윈디","Arcanine",null,[e("U","30-56",["sky","concrete"],OW(["사막 계열"])),e("U","30-56",["sky"],{all:"ow",ex:["사막 계열"],s:VILALL})]);
add(59,"윈디","Arcanine","히스이",[e("R","38-57",["seeSky"],B(GROWLITHE)),e("U","38-57",[],B(["Basalt Deltas"]))]);
add(60,"발챙이","Poliwag",null,[e("C","5-30",["sky","rain"],B(SWAMP)),e("C","5-30",["sub","seeSky","lily"],B(SWAMP)),e("C","5-30",["sky","rain","water"],B(POLIWAG)),e("C","5-30",["sub","seeSky"],B(POLIWAG)),e("C","5-30",["dim"],B(LUSHC)),e("C","5-30",["sub","dim"],B(LUSHC)),e("C","5-30",["sub","indoor","sky","lily"],B(SWAMP)),e("C","5-30",["sub","indoor","sky"],B(POLIWAG)),e("C","5-30",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("C","5-30",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(61,"슈륙챙이","Poliwhirl",null,[e("C","25-39",["sky","rain"],B(SWAMP)),e("C","25-39",["sub","seeSky","lily"],B(SWAMP)),e("C","25-39",["sky","rain","water"],B(POLIWAG)),e("C","25-39",["sub","seeSky"],B(POLIWAG)),e("C","25-39",["dim"],B(LUSHC)),e("C","25-39",["sub","dim"],B(LUSHC)),e("C","25-39",["sub","indoor","sky","lily"],B(SWAMP)),e("C","25-39",["sub","indoor","sky"],B(POLIWAG)),e("C","25-39",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("C","25-39",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(62,"강챙이","Poliwrath",null,[e("C","34-51",["sky","rain"],B(SWAMP)),e("C","34-51",["sub","seeSky","lily"],B(SWAMP)),e("C","34-51",["sky","rain","water"],B(POLIWAG)),e("C","34-51",["sub","seeSky"],B(POLIWAG)),e("C","34-51",["dim"],B(LUSHC)),e("C","34-51",["sub","dim"],B(LUSHC)),e("C","34-51",["sub","indoor","sky","lily"],B(SWAMP)),e("C","34-51",["sub","indoor","sky"],B(POLIWAG)),e("C","34-51",["dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC}),e("C","34-51",["sub","dim","shipY"],{all:"ow",ex:["무성한 계열"],s:LSC})]);
add(63,"캐이시","Abra",null,[e("R","6-31",["sky","night"],B(ABRA2)),e("U","6-31",["sky","night"],B(MYST)),e("C","6-31",["indoor","minY62"],S(MANSION))]);
add(64,"윤겔라","Kadabra",null,[e("R","16-40",["sky","night"],B(ABRA2)),e("U","16-40",["sky","night"],B(MYST)),e("C","16-40",["indoor","minY62"],S(MANSION))]);
add(65,"후딘","Alakazam",null,[e("R","35-50",["sky","night"],B(ABRA2)),e("U","35-50",["sky","night"],B(MYST)),e("C","35-50",["indoor","minY62"],S(MANSION))]);
add(66,"알통몬","Machop",null,[e("C","6-31",["sky","n025"],B(CLEFAIRY2))]);
add(67,"근육몬","Machoke",null,[e("C","28-41",["sky","n025"],B(CLEFAIRY2))]);
add(68,"괴력몬","Machamp",null,[e("C","36-51",["sky","n025"],B(CLEFAIRY2))]);
add(69,"모다피","Bellsprout",null,[e("C","5-30",["sky"],B(JUNGLE))]);
add(70,"우츠동","Weepinbell",null,[e("C","21-39",["sky"],B(JUNGLE))]);
add(71,"우츠보트","Victreebel",null,[e("C","34-49",["sky"],B(JUNGLE))]);
add(72,"왕눈해","Tentacool",null,[e("C","9-28",["surf","seeSky"],B(["Cold Ocean"]))]);
add(73,"독파리","Tentacruel",null,[e("C","30-52",["sub","sky"],B(TENTACRUEL))]);
add(74,"꼬마돌","Geodude",null,[e("C","5-30",["sky"],B(GEODUDE)),e("C","5-30",["dim"],OW(["?#cobblemon:is_deep_dark"]))]);
add(74,"꼬마돌","Geodude","알로라",[e("C","5-30",["iron"],OW())]);
add(75,"데구리","Graveler",null,[e("C","25-39",["sky"],B(GEODUDE)),e("C","25-39",["dim"],OW(["?#cobblemon:is_deep_dark"]))]);
add(75,"데구리","Graveler","알로라",[e("C","25-39",["iron"],OW())]);
add(76,"딱구리","Golem",null,[e("C","34-50",["sky"],B(GEODUDE)),e("C","34-50",["dim"],OW(["?#cobblemon:is_deep_dark"]))]);
add(76,"딱구리","Golem","알로라",[e("C","34-50",["iron"],OW())]);
add(77,"포니타","Ponyta",null,[e("U","16-41",["sky","norain","n025"],B(PONYTA)),e("C","16-41",[],B(["Nether Wastes"]))]);
add(77,"포니타","Ponyta","가라르",[e("U","16-41",["sky","n025"],B(PONYTA2))]);
add(78,"날쌩마","Rapidash",null,[e("U","40-50",["sky","norain","n025"],B(PONYTA)),e("C","40-50",[],B(["Nether Wastes"]))]);
add(78,"날쌩마","Rapidash","가라르",[e("U","40-50",["sky","n025"],B(PONYTA2))]);
add(79,"야돈","Slowpoke",null,[e("C","7-32",["sky"],B(["Beach","Snowy Beach"])),e("C","7-32",["sky"],B(["River","Warm River"]))]);
add(79,"야돈","Slowpoke","가라르",[e("C","7-32",["sky","water"],B(["Mushroom Fields"]))]);
add(80,"야도란","Slowbro",null,[e("C","37-49",["sky"],B(["Beach","Snowy Beach"]))]);
add(80,"야도란","Slowbro","가라르",[e("C","37-49",["sky","water"],B(["Mushroom Fields"]))]);
add(81,"코일","Magnemite",null,[e("U","8-33",["redstone"],OW(["?#cobblemon:is_deep_dark"])),e("C","8-33",["sky","rod","t5"],OW())]);
add(82,"레어코일","Magneton",null,[e("U","30-47",["redstone"],OW(["?#cobblemon:is_deep_dark"])),e("C","30-47",["sky","rod","t5"],OW())]);
add(83,"파오리","Farfetch'd",null,[e("C","13-38",["sky","leek","treetop","n025"],OW())]);
add(83,"파오리","Farfetch'd","가라르",[e("R","13-38",["sky","nowater","n025"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"]))]);
add(84,"두두","Doduo",null,[e("C","6-31",["sky","n025"],B(NIDORAN))]);
add(85,"두트리오","Dodrio",null,[e("C","31-47",["sky","n025"],B(NIDORAN))]);
add(86,"쥬쥬","Seel",null,[e("C","8-33",["sky","n025"],B(SEEL2)),e("C","8-33",["sub","seeSky","d025"],B(SEEL2)),e("C","8-33",["sub","indoor","sky","d025"],B(SEEL2))]);
add(87,"쥬레곤","Dewgong",null,[e("C","34-48",["sky","n025"],B(SEEL2)),e("C","34-48",["sub","seeSky","d025"],B(SEEL2)),e("C","34-48",["sub","indoor","sky","d025"],B(SEEL2))]);
add(88,"질퍽이","Grimer",null,[e("U","8-33",["surf","sky","n15"],B(SWAMP)),e("U","8-33",["surf","sky","concrete","n15"],OW(["늪 계열"])),e("U","8-33",["surf","sky","n15"],{all:"ow",ex:["늪 계열"],s:VILALL})]);
add(88,"질퍽이","Grimer","알로라",[e("U","8-33",["sky","concrete","n15"],B(["Beach","Snowy Beach"])),e("C","11-36",["seeSky"],B(["Beach","Snowy Beach"])),e("U","8-33",["sky","n15"],S(VILALL))]);
add(89,"질뻐기","Muk",null,[e("U","38-50",["surf","sky","n15"],B(SWAMP)),e("U","38-50",["surf","sky","concrete","n15"],OW(["늪 계열"])),e("U","38-50",["surf","sky","n15"],{all:"ow",ex:["늪 계열"],s:VILALL})]);
add(89,"질뻐기","Muk","알로라",[e("U","38-50",["sky","concrete","n15"],B(["Beach","Snowy Beach"])),e("R","38-55",["seeSky"],B(["Beach","Snowy Beach"])),e("U","38-50",["sky","n15"],S(VILALL))]);
add(90,"셀러","Shellder",null,[e("C","6-31",["floor","seeSky"],B(SHELLDER)),e("C","6-31",["floor","seeSky"],B(SHELLDER2)),e("C","6-31",["floor","indoor","subY"],S(SSC))]);
add(91,"파르셀","Cloyster",null,[e("C","26-53",["floor","seeSky"],B(SHELLDER)),e("C","26-53",["floor","seeSky"],B(SHELLDER2)),e("C","26-53",["floor","indoor","subY"],S(SSC))]);
add(92,"고오스","Gastly",null,[e("C","6-31",["sky0","light0"],B(ZUBAT2)),e("U","6-31",["indoor","light0"],OW()),e("C","6-31",["sky","light0"],B(["Dark Forest","Deep Dark"])),e("C","6-31",[],NETH)]);
add(93,"고우스트","Haunter",null,[e("C","25-41",["sky0","light0"],B(ZUBAT2)),e("C","25-41",["indoor","light0"],OW()),e("C","25-41",["sky","light0"],B(["Dark Forest","Deep Dark"])),e("C","25-41",[],NETH)]);
add(94,"팬텀","Gengar",null,[e("U","36-50",["sky0","light0"],B(ZUBAT2)),e("U","36-50",["indoor","light0"],OW()),e("U","36-50",["sky","light0"],B(["Dark Forest","Deep Dark"])),e("U","36-50",[],NETH)]);
add(95,"롱스톤","Onix",null,[e("U","14-39",["dim"],OW(["?#cobblemon:is_deep_dark"])),e("U","14-39",[],B(["Basalt Deltas"]))]);
add(96,"슬리프","Drowzee",null,[e("C","8-33",["sky","night","concrete"],OW(["얼음 계열"])),e("C","8-33",["sky","night"],{all:"ow",ex:["얼음 계열"],s:VILALL})]);
add(97,"슬리퍼","Hypno",null,[e("C","26-48",["sky","night","concrete"],OW(["얼음 계열"])),e("C","26-48",["sky","night"],{all:"ow",ex:["얼음 계열"],s:VILALL})]);
add(98,"크랩","Krabby",null,[e("C","8-33",["sky"],B(KRABBY)),e("C","8-33",["floor","seeSky"],B(KRABBY2)),e("C","8-33",["floor","indoor","subY"],S(SSC))]);
add(99,"킹크랩","Kingler",null,[e("C","28-48",["sky"],B(KRABBY)),e("C","28-48",["floor","seeSky"],B(KRABBY2)),e("C","28-48",["floor","indoor","subY"],S(SSC))]);
add(100,"찌리리공","Voltorb",null,[e("C","8-33",["sky","t5"],OW()),e("C","8-33",["sky","t5"],S(VILALL)),e("U","8-33",["sky","rod","t5"],OW())]);
add(100,"찌리리공","Voltorb","히스이",[e("U","8-33",["sky","apri","t5"],OW())]);
add(101,"붐볼","Electrode",null,[e("C","30-49",["sky","concrete","t5"],OW()),e("C","30-49",["sky","t5"],S(VILALL)),e("U","30-49",["sky","rod","t5"],OW())]);
add(101,"붐볼","Electrode","히스이",[e("U","30-49",["sky","apri","t5"],OW())]);
add(102,"아라리","Exeggcute",null,[e("C","8-33",["sky"],B(EXEGGCUTE))]);
add(102,"아라리","Exeggcute","알로라 계열",[e("U","8-33",["sky"],B(["Beach"]))]);
add(103,"나시","Exeggutor",null,[e("C","28-53",["sky"],B(EXEGGCUTE))]);
add(103,"나시","Exeggutor","알로라",[e("U","28-53",["sky"],B(["Beach"]))]);
add(104,"탕구리","Cubone",null,[e("C","7-32",["sky"],B(CUBONE))]);
add(104,"탕구리","Cubone","알로라 계열",[e("C","7-32",["sky"],B(CUBONE2)),e("C","7-32",[],B(["Soul Sand Valley"]))]);
add(105,"텅구리","Marowak",null,[e("C","28-43",["sky"],B(CUBONE))]);
add(105,"텅구리","Marowak","알로라",[e("C","28-43",["sky"],B(CUBONE2)),e("C","28-43",[],B(["Soul Sand Valley"]))]);
add(106,"시라소몬","Hitmonlee",null,[e("U","20-46",["sky","n025"],B(CLEFAIRY2))]);
add(107,"홍수몬","Hitmonchan",null,[e("U","20-46",["sky","n025"],B(CLEFAIRY2))]);
add(108,"내루미","Lickitung",null,[e("U","14-39",["sky","n025"],B(RATTATA))]);
add(109,"또가스","Koffing",null,[e("C","9-34",["sky","concrete","n5"],OW()),e("C","9-34",["sky","n5"],S(VILALL)),e("C","9-34",[],B(["Soul Sand Valley"]))]);
add(109,"또가스","Koffing","가라르 계열",[e("C","9-34",["sky","n15"],B(MYST)),e("C","9-34",["sky","n15"],B(["Dark Forest","Deep Dark"]))]);
add(110,"또도가스","Weezing",null,[e("C","35-49",["sky","concrete","n5"],OW()),e("C","35-49",["sky","n5"],S(VILALL)),e("C","35-49",[],B(["Soul Sand Valley"]))]);
add(110,"또도가스","Weezing","가라르",[e("C","35-49",["sky","n15"],B(MYST)),e("C","35-49",["sky","n15"],B(["Dark Forest","Deep Dark"]))]);
add(111,"뿔카노","Rhyhorn",null,[e("C","10-35",["sky","n025"],B(RHYHORN))]);
add(112,"코뿌리","Rhydon",null,[e("C","42-49",["sky","n025"],B(RHYHORN))]);
add(113,"럭키","Chansey",null,[e("R","17-45",["sky","n025"],OW()),e("R","17-45",["sky","n025"],S(VILALL))]);
add(114,"덩쿠리","Tangela",null,[e("C","19-44",["sky"],B(JUNGLE))]);
add(115,"캥카","Kangaskhan",null,[e("R","24-49",["sky","n025"],B(NIDORAN))]);
add(116,"쏘드라","Horsea",null,[e("C","5-30",["sub","seeSky"],B(HORSEA)),e("C","5-30",["sub","indoor","sky"],B(HORSEA)),e("C","5-30",["sub","indoor","subY"],S(SSC))]);
add(117,"시드라","Seadra",null,[e("C","32-44",["sub","seeSky"],B(HORSEA)),e("C","32-44",["sub","indoor","sky"],B(HORSEA)),e("C","32-44",["sub","indoor","subY"],S(SSC))]);
add(118,"콘치","Goldeen",null,[e("C","7-32",["sub","seeSky"],B(RIVERS)),e("C","7-32",["sub","indoor","sky"],B(RIVERS))]);
add(119,"왕콘치","Seaking",null,[e("C","33-45",["sub","seeSky"],B(RIVERS)),e("C","33-45",["sub","indoor","sky"],B(RIVERS))]);
add(120,"별가사리","Staryu",null,[e("U","9-34",["sky"],B(KRABBY)),e("U","9-34",["sub","seeSky","n15"],B(TENTACRUEL)),e("U","9-34",["sub","indoor","sky","n15"],B(TENTACRUEL)),e("U","9-34",["sub","indoor","subY"],S(SSC))]);
add(121,"아쿠스타","Starmie",null,[e("U","29-52",["sky","night"],B(KRABBY)),e("U","29-52",["sub","seeSky","n15"],B(TENTACRUEL)),e("U","29-52",["sub","indoor","sky","n15"],B(TENTACRUEL)),e("U","29-52",["sub","indoor","subY"],S(SSC))]);
add(122,"마임맨","Mr. Mime",null,[e("U","26-46",["sky"],OW(["얼음 계열"])),e("U","26-46",["sky"],{all:"ow",ex:["얼음 계열"],s:VILALL}),e("C","26-46",["indoor","minY62"],S(MANSION))]);
add(122,"마임맨","Mr. Mime","가라르",[e("U","26-46",["sky"],B(MRMIME)),e("U","26-46",["sky"],{b:MRMIME,s:VILALL})]);
add(123,"스라크","Scyther",null,[e("R","25-50",["sky","day"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Windswept Savanna","Lush Valley","Moonlight Valley","Savanna Slopes","Yosemite Lowlands"])),e("U","25-50",["sky","day"],B(JUNGLE))]);
add(124,"루주라","Jynx",null,[e("U","30-46",["sky","n025"],B(MRMIME)),e("U","30-46",["sky","n025"],{b:MRMIME,s:VILALL})]);
add(125,"에레브","Electabuzz",null,[e("U","30-50",["sky","t5"],B(["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Plains","Sunflower Plains","Shrubland","Brushland","Steppe","Valley Clearing"]))]);
add(126,"마그마","Magmar",null,[e("C","30-50",["sky","norain","lava"],B(CLEFAIRY2)),e("C","30-50",["sky","norain"],B(CUBONE2)),e("C","30-50",[],B(["Basalt Deltas","Nether Wastes"]))]);
add(127,"쁘사이저","Pinsir",null,[e("R","25-50",["sky","nosacch","n15"],B(JUNGLE)),e("U","25-50",["sky","sacch","n15"],OW(["얼음 계열"]))]);
add(128,"켄타로스","Tauros",null,[e("C","24-49",["sky","n025"],B(["Plains","Sunflower Plains","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands"]))]);
add(128,"켄타로스","Tauros","팔데아 컴뱃종",[e("C","24-49",["sky","n025"],B(TAUROS2))]);
add(128,"켄타로스","Tauros","팔데아 블레이즈종",[e("C","24-49",["sky","n025","lava5"],B(TAUROS2))]);
add(128,"켄타로스","Tauros","팔데아 워터종",[e("C","24-49",["sky","n025","water5"],B(TAUROS2))]);
add(129,"잉어킹","Magikarp",null,[e("C","1-20",["sub","seeSky"],B(MAGIKARP)),e("U","1-20",["surf","sky"],B(MAGIKARP)),e("C","1-20",["sub","indoor","sky"],B(MAGIKARP))]);
add(130,"갸라도스","Gyarados",null,[e("C","20-54",["sub","seeSky"],B(MAGIKARP)),e("U","20-54",["surf","sky"],B(MAGIKARP)),e("C","20-54",["sub","indoor","sky"],B(MAGIKARP))]);
add(131,"라프라스","Lapras",null,[e("U","29-54",["surf","sky"],B(SEEL2)),e("X","29-54",["surf","sky"],B(["Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean"]))]);
add(132,"메타몽","Ditto",null,[e("R","4-29",["sky","slime"],OW(["바다 계열"])),e("X","4-29",["sky"],OW(["바다 계열"])),e("U","4-29",["indoor","minY62"],S(MANSION))]);
add(133,"이브이","Eevee",null,[e("X","5-33",["sky"],OW(["바다 계열","온대 계열"])),e("R","5-33",["sky"],B(ODDISH)),e("U","5-33",["sky"],OW()),e("U","5-33",["sky"],S(VILALL)),e("U","5-33",["indoor","minY62"],S(MANSION))]);
add(134,"샤미드","Vaporeon",null,[e("X","28-53",["sky","water"],B(VAPOREON)),e("X","28-53",["sub","sky"],B(VAPOREON)),e("U","28-53",["sky","concrete"],OW()),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor","minY62"],S(MANSION))]);
add(135,"쥬피썬더","Jolteon",null,[e("X","28-53",["sky"],B(RATTATA)),e("U","28-53",["sky","concrete"],OW()),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor","minY62"],S(MANSION))]);
add(136,"부스터","Flareon",null,[e("X","28-53",["sky"],B(CUBONE)),e("U","28-53",["sky","concrete"],OW()),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor","minY62"],S(MANSION))]);
add(137,"폴리곤","Porygon",null,[e("U","45-68",[],END)]);
add(138,"암나이트","Omanyte",null,[e("X","11-36",["dim"],B(LUSHC)),e("X","11-36",["sub","dim"],B(LUSHC))]);
add(139,"암스타","Omastar",null,[e("X","40-50",["dim"],B(LUSHC)),e("X","40-50",["sub","dim"],B(LUSHC))]);
add(140,"투구","Kabuto",null,[e("X","11-36",["dim"],B(LUSHC)),e("X","11-36",["sub","dim"],B(LUSHC))]);
add(141,"투구푸스","Kabutops",null,[e("X","40-50",["dim"],B(LUSHC)),e("X","40-50",["sub","dim"],B(LUSHC))]);
add(142,"프테라","Aerodactyl",null,[e("X","27-52",["dim"],B(LUSHC))]);
add(143,"잠만보","Snorlax",null,[e("R","34-54",["sky","nosacch"],B(["Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Snowy Slopes","Windswept Savanna","Lush Valley","Moonlight Valley","Savanna Slopes","Yosemite Lowlands"])),e("U","34-54",["sky","sacch"],OW())]);
add(144,"프리져","Articuno",null,[e("X","50",["special"],S(["Articuno Tower (Kanto)"]))]);
add(144,"프리져","Articuno","가라르",[e("X","60",["night"],S(["Dyna Tree (Hoenn)"]))]);
add(145,"썬더","Zapdos",null,[e("X","50-60",["special"],S(["Zapdos Tower (Kanto)"]))]);
add(145,"썬더","Zapdos","가라르",[e("X","60",["storm"],S(["Dyna Tree (Hoenn)"]))]);
add(146,"파이어","Moltres",null,[e("X","50-60",["special"],S(["Moltres Tower (Nether)"]))]);
add(146,"파이어","Moltres","가라르",[e("X","60",["day"],S(["Dyna Tree (Hoenn)"]))]);
add(147,"미뇽","Dratini",null,[e("R","5-30",["surf","dim","maxY32"],OW(["?#cobblemon:is_deep_dark"])),e("R","5-30",["sub","dim","maxY32"],OW(["?#cobblemon:is_deep_dark"])),e("U","5-30",["sub","seeSky","maxY62"],{b:TENTACRUEL,s:RUINS}),e("U","5-30",["sub","indoor","sky","maxY62"],{b:TENTACRUEL,s:RUINS})]);
add(148,"신뇽","Dragonair",null,[e("R","30-42",["surf","dim","maxY32"],OW(["?#cobblemon:is_deep_dark"])),e("R","30-42",["sub","dim","maxY32"],OW(["?#cobblemon:is_deep_dark"])),e("U","30-42",["sub","seeSky","maxY62"],{b:TENTACRUEL,s:RUINS}),e("U","30-42",["sub","indoor","sky","maxY62"],{b:TENTACRUEL,s:RUINS})]);
add(149,"망나뇽","Dragonite",null,[e("R","55-60",["dim","maxY32","water"],OW(["?#cobblemon:is_deep_dark"])),e("U","55-60",["sub","seeSky","maxY62"],{b:TENTACRUEL,s:RUINS}),e("X","55-60",["sky","rain"],B(["Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter"])),e("U","55-60",["sub","indoor","sky","maxY62"],{b:TENTACRUEL,s:RUINS})]);
add(150,"뮤츠","Mewtwo",null,[e("X","1-10",["special"],S(["Team Rocket Radio Tower (Johto)"])),e("X","1",["special"],S(["Resurrection Machine"]))]);
add(151,"뮤","Mew",null,[e("X","75-90",["special"],S(["Origin Temple (Kanto)"]))]);
