// ---- 1세대 (cobbleverse.wiki/spawns/gen1) ----
[[1,"이상해씨","Bulbasaur","5-32"],[2,"이상해풀","Ivysaur","16-40"],[3,"이상해꽃","Venusaur","32-52"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("X",l,["sky"],B(JUNGLE))]));
[[4,"파이리","Charmander","5-31"],[5,"리자드","Charmeleon","16-40"],[6,"리자몽","Charizard","36-53"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("X",l,["clear","sky"],B(MOUNTV)),e("X",l,[],B(["Basalt Deltas"]))]));
[[7,"꼬부기","Squirtle","5-31"],[8,"어니부기","Wartortle","16-40"],[9,"거북왕","Blastoise","36-53"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("X",l,["sky","water"],B(TEMPERATE)),e("X",l,["sub","seeSky"],B(TEMPERATE)),e("X",l,["sub","indoor","sky"],B(TEMPERATE))]));
[[10,"캐터피","Caterpie","1-20"],[11,"단데기","Metapod","7-21"]].forEach(([d,k,n,l])=>{add(d,k,n,null,[e("C",l,["sky"],B([...FOREST,...PLAINS]))]);add(d,k,n,"발렌시아",[e("C",l,["sky"],B(JUNGLE))]);});
add(12,"버터플","Butterfree",null,[e("C","10-40",["day","sky"],B(BUTTER)),e("C","10-40",["day","sky"],B(FLOWER))]);
add(12,"버터플","Butterfree","발렌시아",[e("C","10-40",["day","sky"],B(JUNGLE))]);
add(13,"뿔충이","Weedle",null,[e("C","1-20",["sky"],B([...FOREST_D,...JUNGLE]))]);
add(14,"딱충이","Kakuna",null,[e("C","7-21",["sky"],B([...FOREST_D,...JUNGLE]))]);
add(15,"독침붕","Beedrill",null,[e("C","10-40",["clear","day","sky"],B([...FOREST_D,...JUNGLE]))]);
[[16,"구구","Pidgey","1-25"],[17,"피죤","Pidgeotto","18-35"],[18,"피죤투","Pidgeot","36-48"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["day","sky"],B(PIDGEY))]));
[[19,"꼬렛","Rattata","1-25"],[20,"레트라","Raticate","20-41"]].forEach(([d,k,n,l])=>{
 add(d,k,n,null,[e("C",l,["night","sky"],B(RAT)),e("C",l,["dim","minY0"],OW(["Deep Dark"])),e("U",l,["indoor","sky0","minY0"],OW(["Deep Dark"]))]);
 add(d,k,n,"알로라",[e("C",l,["dim","maxY0"],OW(["Deep Dark"])),e("U",l,["indoor","sky0","maxY0"],OW(["Deep Dark"])),e("C",l,["night","sky"],B(DARK))]);});
add(21,"깨비참","Spearow",null,[e("C","1-26",["day","sky"],B(BADL))]);
add(22,"깨비드릴조","Fearow",null,[e("C","20-44",["day","sky"],B(BADL))]);
[[23,"아보","Ekans","4-29"],[24,"아보크","Arbok","22-45"]].forEach(([d,k,n,l])=>{add(d,k,n,null,[e("C",l,["sky"],B(EKANS))]);add(d,k,n,"특수 무늬",[e("C",l,["sky"],B(EKANS))]);add(d,k,n,"어두운 무늬",[e("C",l,[],B(["Deep Dark"]))]);});
add(25,"피카츄","Pikachu",null,[e("U","16-32",["sky","t2"],B(FOREST_G))]);
add(25,"피카츄","Pikachu","알로라 계열",[e("U","16-32",["sky","t5"],B(["Beach"]))]);
[["마담",["Sunflower Plains"]],["마스크드",["Savanna"]],["닥터",["Jungle"]],["아이돌",["Cherry Grove"]],["하드록",["Badlands"]]].forEach(([f,b])=>add(25,"피카츄","Pikachu","옷갈아입기 "+f,[e("R","22-44",["sky","t25"],B(b))]));
add(26,"라이츄","Raichu",null,[e("U","27-49",["sky","t5"],B(FOREST_G))]);
add(26,"라이츄","Raichu","알로라",[e("U","27-49",["sky","t5"],B(["Beach"]))]);
add(27,"모래두지","Sandshrew",null,[e("C","5-30",[],B(SAND))]);
add(27,"모래두지","Sandshrew","알로라",[e("U","15-32",[],B(SNOWSAND))]);
add(28,"고지","Sandslash",null,[e("C","22-47",[],B(SAND))]);
add(28,"고지","Sandslash","알로라",[e("U","24-55",[],B(SNOWSAND))]);
[[29,"니드런♀","Nidoran ♀","3-28"],[30,"니드리나","Nidorina","16-37"],[31,"니드퀸","Nidoqueen","37-51"],[32,"니드런♂","Nidoran ♂","3-28"],[33,"니드리노","Nidorino","16-37"],[34,"니드킹","Nidoking","37-51"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("U",l,["sky"],B(SAVANNA))]));
[[35,"삐삐","Clefairy","17-32"],[36,"픽시","Clefable","27-48"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("U",l,["night","sky"],B(CLEF1)),e("U",l,["dim"],B(["Dripstone Caves"])),e("U",l,["night","moon","sky"],B(MOUNT))]));
[[37,"식스테일","Vulpix","5-30"],[38,"나인테일","Ninetales","25-51"]].forEach(([d,k,n,l])=>{
 add(d,k,n,null,[e("U",l,["sky","twi"],B([...FOREST,...BADLANDS])),e("C",l,[],B(["Crimson Forest"]))]);
 add(d,k,n,"알로라",[e("U",l,["sky","twi"],B(AVULPIX)),e("R","35-55",["sky"],S(["Crown Spire"]))]);});
[[39,"푸린","Jigglypuff","16-27"],[40,"푸크린","Wigglytuff","22-44"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["sky","n15"],B(FLOWER)),e("C",l,["sky","n15"],B(PLAINS3))]));
[[41,"주뱃","Zubat","1-25"],[42,"골뱃","Golbat","22-46"]].forEach(([d,k,n,l])=>add(d,k,n,null,[
 e("C",l,["clear","night","sky"],B([...FOREST,...SWAMP3])),e("C",l,["dim","n025"],B([...FOREST,...SWAMP3])),
 e("C",l,["dim","d15"],OW(["Deep Dark","숲 계열","늪 계열"])),e("U",l,["indoor","sky0","d15"],OW(["Deep Dark","숲 계열","늪 계열"])),
 e("C",l,["clear","sky","n15"],B(DARK)),e("U",l,["dim"],B(["Deep Dark","Deep Caves"]))]));
[[43,"뚜벅쵸","Oddish","7-32",["sky","d025"]],[44,"냄새꼬","Gloom","21-40",["sky","d025"]],[45,"라플레시아","Vileplume","35-49",["night","sky"]]].forEach(([d,k,n,l,c])=>{
 add(d,k,n,null,[e("C",l,c,B(JUNGLE)),e("C",l,c,B([...FLOWER,...PLAINS3]))]);add(d,k,n,"발렌시아",[e("C",l,c,B(SAVANNA))]);});
[[46,"파라스","Paras","4-29"],[47,"파라섹트","Parasect","24-41"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("U",l,["dim"],B(LUSHC)),e("C",l,[],B(PARAS2)),e("U",l,["dim","shipY"],S(LSC))]));
add(48,"콘팡","Venonat",null,[e("C","6-31",["night","sky"],B([...DARK,...SWAMP]))]);
add(49,"도나리","Venomoth",null,[e("C","31-45",["clear","night","sky"],B([...DARK,...SWAMP]))]);
[[50,"디그다","Diglett","2-27"],[51,"닥트리오","Dugtrio","26-43"]].forEach(([d,k,n,l])=>{add(d,k,n,null,[e("C",l,["dim","minY0"],OW(["Deep Dark"]))]);add(d,k,n,"알로라",[e("C",l,["dim","maxY0"],OW(["Deep Dark"]))]);});
add(52,"나옹","Meowth",null,[e("C","4-29",["clear","sky","n15"],OW(["건조 계열","얼음 계열","타이가 계열"])),e("C","4-29",["clear","sky","n15"],S(["Village (Plains)","Village (Desert)","Village (Savanna)"]))]);
add(52,"나옹","Meowth","알로라",[e("C","4-29",["clear","sky","n15"],S(["Pillager Outpost","Swamp Hut","Woodland Mansion"])),e("C","4-29",["sky","n15"],B(MEOWA))]);
add(52,"나옹","Meowth","가라르",[e("C","4-29",["sky","n15"],B(MEOWG)),e("C","4-29",["sky","n15"],S(["Village (Taiga)","Village (Snowy)"]))]);
add(53,"페르시온","Persian",null,[e("C","28-44",["clear","sky","n15"],OW(["건조 계열","얼음 계열","타이가 계열"])),e("C","28-44",["clear","sky","n15"],S(["Village (Plains)"])),e("C","28-44",["sky","n15"],S(["Village (Desert)","Village (Savanna)"]))]);
add(53,"페르시온","Persian","알로라",[e("C","28-44",["clear","sky","n15"],S(["Pillager Outpost","Swamp Hut","Woodland Mansion"])),e("C","28-44",["sky","n15"],B(MEOWA))]);
[[54,"고라파덕","Psyduck","7-32"],[55,"골덕","Golduck","33-50"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["sky"],B(SWAMP)),e("C",l,["sky","water","flow"],B(["River",...MYST])),e("C",l,["sub","seeSky","sky"],B(["River","Swamp","Mangrove Swamp","Orchid Swamp",...MYST]))]));
add(56,"망키","Mankey",null,[e("C","6-27",["sky"],B([...MOUNT,...JUNGLE]))]);
add(57,"성원숭","Primeape",null,[e("C","28-46",["sky"],B([...MOUNT,...JUNGLE]))]);
add(58,"가디","Growlithe",null,[e("U","10-35",["sky"],OW(["사막 계열"])),e("U","10-35",["sky"],S(VIL4))]);
add(58,"가디","Growlithe","히스이",[e("U","12-36",["seeSky"],B(HGROW))]);
add(59,"윈디","Arcanine",null,[e("U","30-56",["sky"],OW(["사막 계열"])),e("U","30-56",["sky"],S(VIL4))]);
add(59,"윈디","Arcanine","히스이",[e("R","38-57",["seeSky"],B(HGROW)),e("U","38-57",[],B(["Basalt Deltas"]))]);
add(60,"발챙이","Poliwag",null,[e("C","5-30",["rain","sky"],B(SWAMP)),e("C","5-30",["sub","lily"],B(SWAMP)),e("C","5-30",["rain","sky","water"],B(POLI)),e("C","5-30",["sub","seeSky"],B(POLI)),e("C","5-30",["sub","dim"],B(LUSHC)),e("C","5-30",["inwater","dim","shipY"],S(LSC))]);
add(61,"슈륙챙이","Poliwhirl",null,[e("C","25-39",["rain","sky"],B(SWAMP)),e("C","25-39",["sub","lily"],B(SWAMP)),e("C","25-39",["rain","sky","water"],B(POLI)),e("C","25-39",["sub","seeSky"],B(POLI)),e("C","25-39",["sub","dim"],B(LUSHC)),e("C","25-39",["sub","indoor","sky"],B(POLI)),e("C","25-39",["sub","dim","shipY"],S(LSC))]);
add(62,"강챙이","Poliwrath",null,[e("C","34-51",["rain","sky"],B(SWAMP)),e("C","34-51",["sub","lily"],B(SWAMP)),e("C","34-51",["rain","sky","water"],B(POLI)),e("C","34-51",["sub","seeSky"],B(POLI)),e("C","34-51",["sub","dim"],B(LUSHC)),e("C","34-51",["inwater","dim","shipY"],S(LSC))]);
[[63,"캐이시","Abra","6-31"],[64,"윤겔라","Kadabra","16-40"],[65,"후딘","Alakazam","35-50"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("R",l,["night","sky"],B(ABRA)),e("U",l,["night","sky"],B(MYST)),e("C",l,["indoor"],{all:"ow",ex:[],s:MANSION})]));
[[66,"알통몬","Machop","6-31"],[67,"근육몬","Machoke","28-41"],[68,"괴력몬","Machamp","36-51"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["sky","n025"],B(MOUNT))]));
[[69,"모다피","Bellsprout","5-30"],[70,"우츠동","Weepinbell","21-39"],[71,"우츠보트","Victreebel","34-49"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["sky"],B(JUNGLE))]));
add(72,"왕눈해","Tentacool",null,[e("C","9-28",["surf","seeSky"],B(OCEAN)),e("C","9-28",["sub","sky"],B(OCEAN))]);
add(73,"독파리","Tentacruel",null,[e("C","30-52",["surf","sky"],B(OCEAN)),e("C","30-52",["sub","seeSky"],B(OCEAN))]);
[[74,"꼬마돌","Geodude","5-30"],[75,"데구리","Graveler","25-39"],[76,"딱구리","Golem","34-50"]].forEach(([d,k,n,l])=>{add(d,k,n,null,[e("C",l,["sky"],B(GEO)),e("C",l,["dim"],OW(["Deep Dark"]))]);add(d,k,n,"알로라",[e("C",l,["iron"],OW())]);});
[[77,"포니타","Ponyta","16-41"],[78,"날쌩마","Rapidash","40-50"]].forEach(([d,k,n,l])=>{add(d,k,n,null,[e("U",l,["clear","sky","n025"],B(RAT)),e("C",l,[],B(["Nether Wastes"]))]);add(d,k,n,"가라르",[e("U",l,["sky","n025"],B([...FLOWER,...MYST]))]);});
add(79,"야돈","Slowpoke",null,[e("C","7-32",["sky"],B(["Beach","Snowy Beach"])),e("C","7-32",["sky"],B(["River","Warm River"]))]);
add(79,"야돈","Slowpoke","가라르",[e("C","7-32",["sky","water"],B(["Mushroom Fields"]))]);
add(80,"야도란","Slowbro",null,[e("C","37-49",["sky"],B(["Beach","Snowy Beach"]))]);
add(80,"야도란","Slowbro","가라르",[e("C","37-49",["sky","water"],B(["Mushroom Fields"]))]);
[[81,"코일","Magnemite","8-33"],[82,"레어코일","Magneton","30-47"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("U",l,["redstone"],OW(["Deep Dark"])),e("C",l,["sky","t5","rod"],OW())]));
add(83,"파오리","Farfetch'd",null,[e("C","13-38",["sky","n025","leek"],OW())]);
add(83,"파오리","Farfetch'd","가라르",[e("R","13-38",["sky","n025","nowater"],B(FOREST_ALL))]);
[[84,"두두","Doduo","6-30"],[85,"두트리오","Dodrio","31-47"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["sky","n025"],B(SAVANNA)),e("C",l,["sky"],B(["Plains","Meadow"]))]));
[[86,"쥬쥬","Seel","8-33"],[87,"쥬레곤","Dewgong","34-48"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["sky","n025"],B(SEEL)),e("C",l,["sub","seeSky","d025"],B(SEEL)),e("C",l,["sub","indoor","sky","d025"],B(SEEL))]));
[[88,"질퍽이","Grimer","8-33"],[89,"질뻐기","Muk","38-50"]].forEach(([d,k,n,l])=>{add(d,k,n,null,[e("U",l,["surf","sky","n15"],B(SWAMP)),e("U",l,["surf","sky","n15"],S(VILGR))]);add(d,k,n,"알로라",[e("U",l,["sky","n15"],B(["Beach"]))]);});
[[90,"셀러","Shellder","6-31"],[91,"파르셀","Cloyster","26-53"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["floor","seeSky"],B(COLDO)),e("C",l,["floor","seeSky"],B(WARMO)),e("C",l,["floor","indoor","subY"],S(SSC))]));
[[92,"고오스","Gastly","6-31",["C","U","C","C"]],[93,"고우스트","Haunter","25-41",["C","C","C","C"]],[94,"팬텀","Gengar","36-50",["U","U","U","U"]]].forEach(([d,k,n,l,r])=>add(d,k,n,null,[e(r[0],l,["light0","sky0"],B(["Deep Dark","Deep Caves"])),e(r[1],l,["indoor","sky0"],OW()),e(r[2],l,["light0","sky"],B(DARK)),e(r[3],l,[],{all:"nether",ex:[]})]));
add(95,"롱스톤","Onix",null,[e("U","14-39",["dim"],OW(["Deep Dark"])),e("U","14-39",[],B(["Basalt Deltas"]))]);
add(96,"슬리프","Drowzee",null,[e("C","8-33",["night","sky"],S(VILD))]);
add(97,"슬리퍼","Hypno",null,[e("C","26-48",["night","sky"],S(VILD))]);
[[98,"크랩","Krabby","8-33"],[99,"킹크랩","Kingler","28-48"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["sky"],B(SHORE)),e("C",l,["floor","seeSky"],B([...SHORE,...OCEAN])),e("C",l,["floor","indoor","subY"],S(SSC))]));
[[100,"찌리리공","Voltorb","8-33"],[101,"붐볼","Electrode","30-49"]].forEach(([d,k,n,l])=>{add(d,k,n,null,[e("C",l,["sky","t5"],OW()),e("C",l,["storm","sky"],S(VILALL)),e("U",l,["sky","t5","rod"],OW())]);add(d,k,n,"히스이",[e("U",l,["sky","t5","apri"],OW())]);});
add(102,"아라리","Exeggcute",null,[e("C","8-33",["sky"],B([...JUNGLE,...SAVANNA]))]);
add(102,"아라리","Exeggcute","알로라 계열",[e("U","8-33",["sky"],B(["Beach"]))]);
add(103,"나시","Exeggutor",null,[e("C","28-53",["sky"],B([...JUNGLE,...SAVANNA]))]);
add(103,"나시","Exeggutor","알로라",[e("U","28-53",["sky"],B(["Beach"]))]);
add(104,"탕구리","Cubone",null,[e("C","7-32",["sky"],B([...BADLANDS,...DESERT]))]);
add(104,"탕구리","Cubone","알로라 계열",[e("C","7-32",["sky"],B(["Volcanic Crater","Volcanic Peaks"])),e("C","7-32",[],B(["Soul Sand Valley"]))]);
add(105,"텅구리","Marowak",null,[e("C","28-43",["sky"],B([...BADLANDS,...DESERT]))]);
add(105,"텅구리","Marowak","알로라",[e("C","28-43",["sky"],B(["Volcanic Crater","Volcanic Peaks"])),e("C","28-43",[],B(["Soul Sand Valley"]))]);
add(106,"시라소몬","Hitmonlee",null,[e("U","20-46",["sky","n025"],B(MOUNT))]);
add(107,"홍수몬","Hitmonchan",null,[e("U","20-46",["sky","n025"],B(MOUNT))]);
add(108,"내루미","Lickitung",null,[e("U","14-39",["sky","n025"],B(RAT))]);
add(109,"또가스","Koffing",null,[e("C","9-34",["sky","n5"],OW()),e("C","12-32",["sky","n5"],S(VILALL)),e("C","9-34",[],B(["Soul Sand Valley"]))]);
add(109,"또가스","Koffing","가라르 계열",[e("C","9-34",["sky","n15"],B([...MYST,"Pale Garden","Deep Dark"]))]);
add(110,"또도가스","Weezing",null,[e("C","35-49",["sky","n5"],OW()),e("C","38-48",["sky","n5"],S(VILALL)),e("C","35-49",[],B(["Soul Sand Valley"]))]);
add(110,"또도가스","Weezing","가라르",[e("C","35-49",["sky","n15"],B([...MYST,"Pale Garden","Deep Dark"]))]);
add(111,"뿔카노","Rhyhorn",null,[e("C","10-35",["sky","n025"],B(RHY))]);
add(112,"코뿌리","Rhydon",null,[e("C","42-49",["sky","n025"],B(RHY))]);
add(113,"럭키","Chansey",null,[e("R","17-45",["sky","n025"],B([...PIDGEY,"Cloud Forest"])),e("R","17-45",["sky","n025"],S(VILALL))]);
add(114,"덩쿠리","Tangela",null,[e("C","19-44",["sky"],B(JUNGLE))]);
add(115,"캥카","Kangaskhan",null,[e("R","24-49",["sky","n025"],B(SAVANNA))]);
[[116,"쏘드라","Horsea","5-30"],[117,"시드라","Seadra","32-44"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["sub","seeSky"],B(HORSEA)),e("C",l,["sub","indoor","sky"],B(HORSEA)),e("C",l,["sub","indoor","subY"],S(SSC))]));
[[118,"콘치","Goldeen","7-32"],[119,"왕콘치","Seaking","33-45"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("C",l,["sub","seeSky"],B(RIVERS)),e("C",l,["sub","indoor","sky"],B(RIVERS))]));
add(120,"별가사리","Staryu",null,[e("U","9-34",["sky"],B(SHORE)),e("U","9-34",["sub","seeSky","n15"],B(OCEAN)),e("U","9-34",["sub","indoor","sky","n15"],B(OCEAN)),e("U","9-34",["sub","indoor","subY"],S(SSC))]);
add(121,"아쿠스타","Starmie",null,[e("U","29-52",["night","sky"],B(SHORE)),e("U","29-52",["sub","seeSky","n15"],B(OCEAN)),e("U","29-52",["sub","indoor","sky","n15"],B(OCEAN)),e("U","29-52",["sub","indoor","subY"],S(SSC))]);
add(122,"마임맨","Mr. Mime",null,[e("U","26-46",["sky"],OW(["얼음 계열"])),e("U","34-48",["sky"],S(VILD)),e("C","26-46",["indoor"],S(MANSION))]);
add(122,"마임맨","Mr. Mime","가라르",[e("U","26-46",["sky"],B(FREEZE)),e("U","26-46",["sky"],S(["Village (Snowy)"]))]);
add(123,"스라크","Scyther",null,[e("R","25-50",["day","sky"],B([...FOREST,...SCY_M])),e("U","25-50",["day","sky"],B(JUNGLE))]);
add(124,"루주라","Jynx",null,[e("U","30-46",["sky","n025"],{b:FREEZE,s:["Village (Snowy)"]})]);
add(125,"에레브","Electabuzz",null,[e("U","30-50",["sky","t5"],B([...MOUNT,...PLAINS2]))]);
add(126,"마그마","Magmar",null,[e("C","30-50",["clear","sky","lava"],B(MOUNT.filter(b=>b!=="Volcanic Crater"))),e("C","30-50",["clear","sky"],B(["Volcanic Crater","Volcanic Peaks"])),e("C","30-50",[],B(["Basalt Deltas","Nether Wastes"]))]);
add(127,"쁘사이저","Pinsir",null,[e("R","25-50",["sky","n15","nosacch"],B(JUNGLE)),e("U","25-50",["sky","n15","sacch"],OW(["얼음 계열"]))]);
add(128,"켄타로스","Tauros",null,[e("C","24-49",["sky","n025"],B(TAUROS))]);
add(128,"켄타로스","Tauros","팔데아 컴뱃종",[e("C","24-49",["sky","n025"],B(PALDEA_T))]);
add(128,"켄타로스","Tauros","팔데아 블레이즈종",[e("C","24-49",["sky","n025","lava5"],B(PALDEA_T))]);
add(128,"켄타로스","Tauros","팔데아 워터종",[e("C","24-49",["sky","n025","water5"],B(PALDEA_T))]);
add(129,"잉어킹","Magikarp",null,[e("C","1-20",["sub","seeSky"],B(KARP)),e("U","1-20",["surf","sky"],B(KARP)),e("C","1-20",["sub","indoor","sky"],B(KARP))]);
add(130,"갸라도스","Gyarados",null,[e("C","20-54",["sub","seeSky"],B(KARP)),e("U","20-54",["surf","sky"],B(KARP)),e("C","20-54",["sub","indoor","sky"],B(KARP))]);
add(131,"라프라스","Lapras",null,[e("U","29-54",["surf","sky"],B(SEEL)),e("X","29-54",["surf","sky"],B(OCEAN.filter(b=>b!=="Frozen Ocean")))]);
add(132,"메타몽","Ditto",null,[e("R","4-29",["slime","sky"],OW(["바다 계열"])),e("X","4-29",["sky"],OW(["바다 계열"])),e("U","4-29",["indoor"],S(MANSION))]);
add(133,"이브이","Eevee",null,[e("R","5-33",["sky"],B(PIDGEY)),e("U","5-33",["sky"],OW()),e("U","5-33",["sky"],S(VILALL)),e("U","5-33",["indoor"],S(MANSION))]);
add(134,"샤미드","Vaporeon",null,[e("X","28-53",["sky","water"],B(VAPO)),e("X","28-53",["sub","sky"],B(VAPO)),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor"],S(MANSION))]);
add(135,"쥬피썬더","Jolteon",null,[e("X","28-53",["sky"],B(JOLT)),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor"],S(MANSION))]);
add(136,"부스터","Flareon",null,[e("X","28-53",["sky"],B([...BADLANDS,...DESERT])),e("U","28-53",["sky"],S(VILALL)),e("U","28-53",["indoor"],S(MANSION))]);
add(137,"폴리곤","Porygon",null,[e("U","45-68",[],{all:"end",ex:[]})]);
[[138,"암나이트","Omanyte","11-36"],[139,"암스타","Omastar","40-54"],[140,"투구","Kabuto","11-36"],[141,"투구푸스","Kabutops","40-54"]].forEach(([d,k,n,l])=>add(d,k,n,null,[e("X",l,["dim"],B(LUSHC)),e("X",l,["sub","dim"],B(LUSHC))]));
add(142,"프테라","Aerodactyl",null,[e("X","27-62",["dim"],B(LUSHC))]);
add(143,"잠만보","Snorlax",null,[e("R","34-54",["sky","nosacch"],B(SNORLAX)),e("U","34-54",["sky","sacch"],OW())]);
add(144,"프리져","Articuno",null,[e("X","50-60",["special"],S(["Articuno Tower (Kanto)"]))]);
add(144,"프리져","Articuno","가라르",[e("X","60-70",["night"],S(["Dyna Tree (Hoenn)"]))]);
add(145,"썬더","Zapdos",null,[e("X","50-60",["special"],S(["Zapdos Tower (Kanto)"]))]);
add(145,"썬더","Zapdos","가라르",[e("X","60-70",["storm"],S(["Dyna Tree (Hoenn)"]))]);
add(146,"파이어","Moltres",null,[e("X","50-60",["special"],S(["Moltres Tower (Nether)"]))]);
add(146,"파이어","Moltres","가라르",[e("X","60-70",["day"],S(["Dyna Tree (Hoenn)"]))]);
add(147,"미뇽","Dratini",null,[e("R","5-29",["surf","dim","maxY32"],OW(["Deep Dark"])),e("R","5-29",["sub","dim","maxY32"],OW(["Deep Dark"])),e("U","14-29",["sub","seeSky","maxY62"],S(RUINS)),e("U","5-30",["sub","indoor","sky","maxY62"],S(RUINS))]);
add(148,"신뇽","Dragonair",null,[e("R","30-42",["surf","dim","maxY32"],OW(["Deep Dark"])),e("R","30-42",["sub","dim","maxY32"],OW(["Deep Dark"])),e("U","30-42",["sub","seeSky","maxY62"],S(RUINS)),e("U","30-42",["sub","indoor","sky","maxY62"],S(RUINS))]);
add(149,"망나뇽","Dragonite",null,[e("R","55-70",["dim","maxY32","water"],OW(["Deep Dark"])),e("U","55-70",["sub","seeSky","maxY62"],S(RUINS)),e("U","55-70",["sub","indoor","sky","maxY62"],S(RUINS))]);
add(150,"뮤츠","Mewtwo",null,[e("X","1",["special"],S(["Resurrection Machine"]))]);
add(151,"뮤","Mew",null,[e("X","75-90",["special"],S(["Origin Temple (Kanto)"]))]);

