// ---- 8세대 (COBBLEVERSE 모드팩 1.7.42 데이터팩 COBBLEVERSE-DP-v31 기준) ----
const SCORBUNNY=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Savanna","Savanna Plateau","Windswept Savanna","Ashen Savanna","Desert Oasis","Fractured Savanna","Hot Shrubland","Red Oasis","Savanna Badlands","Savanna Slopes"];
const SOBBLE=["Bamboo Jungle","Jungle","Sparse Jungle","Underground Jungle","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];
const SKWOVET=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"];
const ROOKIDEE=["Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Blooming Plateau","Highlands","Snowy Slopes","Grove","Cherry Grove","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Temperate Highlands","Yosemite Lowlands","Skylands Autumn","Skylands Spring","Skylands Summer","Skylands Winter","Dark Forest","Deep Dark","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Shield","Siberian Taiga","Yellowstone"];
const BLIPBUG=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"];
const BLIPBUG2=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing"];
const NICKIT=["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands"];
const NICKIT2=["Plains","Sunflower Plains","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Shrubland","Brushland","Steppe","Valley Clearing","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"];
const WOOLOO=["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Windswept Spires","Yosemite Cliffs","Plains","Sunflower Plains","Shrubland","Brushland","Steppe","Valley Clearing"];
const CHEWTLE=["River","Warm River","Mangrove Swamp","Swamp","Orchid Swamp"];
const ROLYCOLY=["Dripstone Caves","Lush Caves","Deep Dark","Andesite Caves","Desert Caves","Diorite Caves","Fungal Caves","Granite Caves","Infested Caves","Thermal Caves","Underground Jungle","Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"];
const SILICOBRA=["Desert","Ancient Sands","Desert Canyon","Desert Caves","Desert Oasis","Desert Spires","Lush Desert","Red Oasis","Sandstone Valley"];
const CRAMORANT=["Stony Shore","Beach","Basalt Cliffs","Granite Cliffs","White Cliffs","Mushroom Fields","Alpha Islands","Mirage Isles","Warped Mesa","Skylands Autumn","Skylands Spring","Skylands Summer"];
const ARROKUDA=["Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Mangrove Swamp","Swamp","Orchid Swamp"];
const SIZZLIPEDE=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Mantle Caves","Volcanic Crater","Volcanic Peaks"];
const CLOBBOPUS=["Stony Shore","Beach","Snowy Beach","Basalt Cliffs","Granite Cliffs","White Cliffs"];
const CLOBBOPUS2=["Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean"];
const SINISTEA=["Flower Forest","Meadow","Sunflower Plains","Blooming Plateau","Blooming Valley","Cloud Forest","Lavender Forest","Lavender Valley","Dark Forest","Amethyst Canyon","Amethyst Rainforest","Moonlight Grove","Moonlight Valley","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Highlands","Grove","Forested Highlands","Lush Valley","Temperate Highlands","Yosemite Lowlands","Stony Spires","Windswept Spires","Yosemite Cliffs","Plains","Steppe","Valley Clearing","Snowy Beach","Snowy Plains","Ice Spikes","Frostfire Caves","Glacial Chasm","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands","Deep Dark","Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Haze Mountain","Shield","Siberian Taiga","Gravel Desert","Rocky Shrubland"];
const PERRSERKER=["Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands","Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Haze Mountain","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"];
const MRRIME=["Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands"];
const EISCUE=["Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs"];
const CUFANT=["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Cherry Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Savanna","Savanna Plateau","Brushland","Desert Oasis","Fractured Savanna","Hot Shrubland","Savanna Badlands","Shrubland"];
const DREEPY=["Stony Shore","Beach","Basalt Cliffs","Granite Cliffs","White Cliffs","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean"];
const BASCULEGION=["River","Frozen River","Warm River","Mangrove Swamp","Swamp","Ice Marsh","Orchid Swamp"];
const OVERQWIL=["Cold Ocean","Deep Cold Ocean","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs"];

add(810,"흥나숭","Grookey",null,[e("X","5-31",["sky","treetop"],B(JUNGLE))]);
add(811,"채키몽","Thwackey",null,[e("X","16-42",["sky","treetop"],B(JUNGLE))]);
add(812,"고릴타","Rillaboom",null,[e("X","35-53",["sky","treetop"],B(JUNGLE))]);
add(813,"염버니","Scorbunny",null,[e("X","5-31",["sky"],B(SCORBUNNY))]);
add(814,"래비풋","Raboot",null,[e("X","16-42",["sky"],B(SCORBUNNY))]);
add(815,"에이스번","Cinderace",null,[e("X","35-53",["sky"],B(SCORBUNNY))]);
add(816,"울머기","Sobble",null,[e("X","5-31",["sky"],B(SWAMP)),e("X","5-31",["sky","water"],B(JUNGLE)),e("X","5-31",["sub","seeSky"],B(SOBBLE))]);
add(817,"누겔레온","Drizzile",null,[e("X","16-42",["sky"],B(SWAMP)),e("X","16-42",["sky","water"],B(JUNGLE)),e("X","16-42",["sub","seeSky"],B(SOBBLE))]);
add(818,"인텔리레온","Inteleon",null,[e("X","35-53",["sky"],B(SWAMP)),e("X","35-53",["sky","water"],B(JUNGLE)),e("X","35-53",["sub","seeSky"],B(SOBBLE))]);
add(819,"탐리스","Skwovet",null,[e("C","3-28",["sky","treetop"],B(SKWOVET))]);
add(820,"요씽리스","Greedent",null,[e("C","24-46",["sky","treetop"],B(SKWOVET))]);
add(821,"파라꼬","Rookidee",null,[e("C","1-25",["sky","day","treetop"],B(ROOKIDEE))]);
add(822,"파크로우","Corvisquire",null,[e("C","18-37",["sky","day","treetop"],B(ROOKIDEE))]);
add(823,"아머까오","Corviknight",null,[e("C","38-50",["sky","day","treetop"],B(ROOKIDEE))]);
add(824,"두루지벌레","Blipbug",null,[e("C","2-9",["seeSky","treetop"],B(BLIPBUG)),e("C","2-9",["seeSky","leaves","treetop"],B(BLIPBUG2))]);
add(825,"레돔벌레","Dottler",null,[e("U","11-29",["seeSky","treetop"],B(BLIPBUG)),e("U","12-28",["seeSky","leaves","treetop"],B(BLIPBUG2))]);
add(826,"이올브","Orbeetle",null,[e("R","32-47",["seeSky"],B(BLIPBUG2))]);
add(827,"훔처우","Nickit",null,[e("C","1-25",["night"],B(NICKIT)),e("U","1-25",["night"],B(NICKIT2))]);
add(828,"폭슬라이","Thievul",null,[e("C","18-46",["night"],B(NICKIT)),e("U","18-46",["night"],B(NICKIT2))]);
add(829,"꼬모카","Gossifleur",null,[e("C","1-25",["sky","norain","n025"],B(FLOWER))]);
add(830,"백솜모카","Eldegoss",null,[e("C","20-46",["sky","norain","n025"],B(FLOWER))]);
add(831,"우르","Wooloo",null,[e("C","2-27",["sky","n025"],B(WOOLOO))]);
add(832,"배우르","Dubwool",null,[e("C","24-49",["sky","n025"],B(WOOLOO))]);
add(833,"깨물부기","Chewtle",null,[e("C","3-28",["sky"],B(CHEWTLE)),e("C","3-28",["floor","seeSky"],B(CHEWTLE))]);
add(834,"갈가부기","Drednaw",null,[e("C","22-49",["sky"],B(CHEWTLE)),e("C","22-49",["floor","seeSky"],B(CHEWTLE))]);
add(835,"멍파치","Yamper",null,[e("C","2-27",["sky","t5"],OW(["얼음 계열"])),e("C","2-27",["sky","t5"],{all:"ow",ex:["얼음 계열"],s:VILALL})]);
add(836,"펄스멍","Boltund",null,[e("C","25-49",["sky","concrete","t5"],OW(["얼음 계열"])),e("C","25-49",["sky","t5"],{all:"ow",ex:["얼음 계열"],s:VILALL})]);
add(837,"탄동","Rolycoly",null,[e("C","6-17",["coal"],B(ROLYCOLY)),e("U","5-16",[],B(ROLYCOLY))]);
add(838,"탄차곤","Carkol",null,[e("C","18-33",["coal"],B(ROLYCOLY)),e("U","19-33",[],B(ROLYCOLY))]);
add(839,"석탄산","Coalossal",null,[e("R","36-65",["coal"],B(ROLYCOLY)),e("X","35-47",[],B(ROLYCOLY))]);
add(840,"과사삭벌레","Applin",null,[e("U","12-25",["seeSky"],B(NICKIT))]);
add(841,"애프룡","Flapple",null,[e("R","37-52",["seeSky"],B(NICKIT))]);
add(842,"단지래플","Appletun",null,[e("R","36-50",["seeSky"],B(NICKIT))]);
add(843,"모래뱀","Silicobra",null,[e("C","7-32",["sky"],B(SILICOBRA))]);
add(844,"사다이사","Sandaconda",null,[e("C","36-51",["sky"],B(SILICOBRA))]);
add(845,"윽우지","Cramorant",null,[e("U","23-48",["sky","n025"],B(CRAMORANT)),e("U","23-48",["surf","sky","day"],B(CRAMORANT))]);
add(846,"찌로꼬치","Arrokuda",null,[e("C","3-28",["sub","seeSky"],B(ARROKUDA)),e("C","3-28",["sub","indoor","sky"],B(ARROKUDA))]);
add(847,"꼬치조","Barraskewda",null,[e("C","26-49",["sub","seeSky"],B(ARROKUDA)),e("C","26-49",["sub","indoor","sky"],B(ARROKUDA))]);
add(848,"일레즌","Toxel",null,[e("U","1-24",["dim"],B(SWAMP)),e("C","1-24",["sky","concrete","n15"],OW())]);
add(849,"스트린더","Toxtricity",null,[e("U","30-50",["dim"],B(SWAMP)),e("C","30-50",["sky","concrete","n15"],OW())]);
add(850,"태우지네","Sizzlipede",null,[e("C","6-31",["sky"],B(SIZZLIPEDE)),e("C","6-31",[],B(["Basalt Deltas"])),e("C","6-31",[],B(["Nether Wastes"]))]);
add(851,"다태우지네","Centiskorch",null,[e("C","28-53",["sky"],B(SIZZLIPEDE)),e("C","28-53",[],B(["Basalt Deltas"])),e("C","28-53",[],B(["Nether Wastes"]))]);
add(852,"때때무노","Clobbopus",null,[e("U","6-31",["sky"],B(CLOBBOPUS)),e("U","6-31",["floor","seeSky"],B(CLOBBOPUS2)),e("U","6-31",["floor","indoor","subY"],S(SSC))]);
add(853,"케오퍼스","Grapploct",null,[e("U","35-48",["sky"],B(CLOBBOPUS)),e("U","35-48",["floor","seeSky"],B(CLOBBOPUS2)),e("U","35-48",["floor","indoor","subY"],S(SSC))]);
add(854,"데인차","Sinistea","위작폼",[e("U","6-31",["indoor","day","minY62"],B(SINISTEA)),e("U","6-31",["night","minY62"],{b:SINISTEA,s:VILALL}),e("C","6-31",["indoor","minY62"],S(MANSION)),e("U","6-31",["indoor","day","minY62"],{b:SINISTEA,s:VILALL})]);
add(854,"데인차","Sinistea","진작폼",[e("U","6-31",["indoor","day","minY62"],B(SINISTEA)),e("U","6-31",["night","minY62"],B(SINISTEA)),e("C","6-31",["indoor","minY62"],S(MANSION)),e("U","6-31",["indoor","day","minY62"],{b:SINISTEA,s:VILALL}),e("U","6-31",["night","minY62"],{b:SINISTEA,s:VILALL})]);
add(855,"포트데스","Polteageist","위작폼",[e("U","26-51",["indoor","day","minY62"],B(SINISTEA)),e("U","26-51",["night","minY62"],B(SINISTEA)),e("C","26-51",["indoor","minY62"],S(MANSION)),e("U","26-51",["indoor","day","minY62"],{b:SINISTEA,s:VILALL}),e("U","26-51",["night","minY62"],{b:SINISTEA,s:VILALL})]);
add(855,"포트데스","Polteageist","진작폼",[e("U","26-51",["indoor","day","minY62"],B(SINISTEA)),e("U","26-51",["night","minY62"],{b:SINISTEA,s:VILALL}),e("C","26-51",["indoor","minY62"],S(MANSION)),e("U","26-51",["indoor","day","minY62"],{b:SINISTEA,s:VILALL})]);
add(856,"몸지브림","Hatenna",null,[e("U","2-27",["sky"],B(MYST)),e("C","2-27",["sky"],S(["Swamp Hut"])),e("C","2-27",["indoor","minY62"],S(MANSION))]);
add(857,"손지브림","Hattrem",null,[e("U","32-37",["sky"],B(MYST)),e("C","32-37",["sky"],S(["Swamp Hut"])),e("C","32-37",["indoor","minY62"],S(MANSION))]);
add(858,"브리무음","Hatterene",null,[e("U","42-51",["sky"],B(MYST)),e("C","42-51",["sky"],S(["Swamp Hut"])),e("C","42-51",["indoor","minY62"],S(MANSION))]);
add(859,"메롱꿍","Impidimp",null,[e("C","2-27",["sky","n15"],B(["Dark Forest","Amethyst Canyon","Amethyst Rainforest","Mirage Isles","Moonlight Grove","Moonlight Valley","Deep Dark"])),e("C","2-27",[],B(["Warped Forest"]))]);
add(860,"쏘겨모","Morgrem",null,[e("C","32-37",["sky","n15"],B(MYST)),e("C","32-37",[],B(["Warped Forest"]))]);
add(861,"오롱털","Grimmsnarl",null,[e("C","42-51",["sky","n15"],B(MYST)),e("C","42-51",[],B(["Warped Forest"]))]);
add(862,"가로막구리","Obstagoon",null,[e("C","35-52",["sky","n15"],B(["Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Grove","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands"]))]);
add(863,"나이킹","Perrserker",null,[e("C","28-44",["sky","n15"],B(PERRSERKER)),e("C","28-44",["sky","n15"],{b:PERRSERKER,s:VILALL})]);
add(864,"산호르곤","Cursola",null,[e("U","38-51",[],B(["Beach","Snowy Beach"])),e("C","38-51",["deadcoral"],OW()),e("C","38-51",["floor","deadcoral"],OW())]);
add(865,"창파나이트","Sirfetch'd",null,[e("R","33-51",["sky","nowater","n025"],B(NICKIT))]);
add(866,"마임꽁꽁","Mr. Rime",null,[e("U","42-52",["sky"],B(MRRIME)),e("U","42-52",["sky"],{b:MRRIME,s:VILALL})]);
add(867,"데스판","Runerigus",null,[e("U","34-53",["night","maxY60"],B(["Dark Forest","Deep Dark"])),e("R","34-63",["night","maxY62"],S(["Ancient City"]))]);
add(868,"마빌크","Milcery",null,[e("C","2-27",["cake"],OW()),e("C","2-27",["sacch"],OW()),e("U","2-27",["sugarcane","nosacch"],OW()),e("C","2-27",["minY62","carpet"],S(MANSION))]);
add(869,"마휘핑","Alcremie",null,[e("C","22-50",["cake"],OW()),e("C","22-50",["sacch"],OW()),e("U","22-50",["sugarcane","nosacch"],OW()),e("C","22-50",["minY62","carpet"],S(MANSION))]);
add(870,"대여르","Falinks",null,[e("U","22-47",["sky","n025"],B(["Badlands","Eroded Badlands","Wooded Badlands","Ashen Savanna","Red Oasis","Warped Mesa","White Mesa"])),e("U","22-47",[],S(["Bastion Remnant","Nether Fortress"]))]);
add(871,"찌르성게","Pincurchin",null,[e("U","19-44",["floor","seeSky","kelpsea"],B(["Stony Shore","Beach","Snowy Beach","Basalt Cliffs","Granite Cliffs","White Cliffs","Deep Frozen Ocean","Deep Cold Ocean","Deep Ocean","Deep Lukewarm Ocean","Frozen Ocean","Ocean","Cold Ocean","Lukewarm Ocean","Warm Ocean","Frozen Cliffs"])),e("U","19-44",["floor","indoor","subY"],S(SSC))]);
add(872,"누니머기","Snom",null,[e("C","15-36",["night"],B(MRRIME))]);
add(873,"모스노우","Frosmoth",null,[e("U","15-36",["night"],B(MRRIME))]);
add(874,"돌헨진","Stonjourner",null,[e("R","22-47",["sky"],B(BLIPBUG2)),e("U","22-47",["sky","dusk"],B(BLIPBUG2)),e("C","22-47",["sky","dusk5"],S(["Stonjourner Henge Ruins"]))]);
add(875,"빙큐보","Eiscue",null,[e("C","22-47",["sky"],B(EISCUE)),e("C","22-47",["surf","sky"],B(EISCUE))]);
add(876,"에써르","Indeedee","암컷",[e("R","35-67",["seeSky"],B(MYST))]);
add(876,"에써르","Indeedee","수컷",[e("R","35-67",["seeSky"],B(MYST))]);
add(877,"모르페코","Morpeko",null,[e("U","19-44",["sky","berries","t5"],B(NICKIT))]);
add(878,"끼리동","Cufant",null,[e("U","8-33",["sky","n025"],B(CUFANT))]);
add(879,"대왕끼리동","Copperajah",null,[e("U","34-50",["sky","n025"],B(CUFANT))]);
add(884,"두랄루돈","Duraludon",null,[e("R","38-58",[],END)]);
add(885,"드라꼰","Dreepy",null,[e("X","2-27",["sky","dusk5"],B(DREEPY)),e("X","2-27",["surf","sky","dusk"],B(DREEPY))]);
add(886,"드래런치","Drakloak",null,[e("X","50-55",["sky","dusk5"],B(DREEPY)),e("X","50-55",["surf","sky","dusk"],B(DREEPY))]);
add(887,"드래펄트","Dragapult",null,[e("X","60-65",["sky","dusk5"],B(DREEPY)),e("X","60-65",["surf","sky","dusk"],B(DREEPY))]);
add(888,"자시안","Zacian",null,[e("X","65-80",[],B(["Dark Forest"]))]);
add(889,"자마젠타","Zamazenta",null,[e("X","65-80",[],B(["Dark Forest"]))]);
add(890,"무한다이노","Eternatus",null,[e("X","70-90",["special"],S(["Eternatus Cocoon (End)"]))]);
add(891,"치고마","Kubfu",null,[e("X","30-50",[],B(["Cherry Grove"]))]);
add(892,"우라오스","Urshifu",null,[e("X","60-80",[],B(["Cherry Grove"]))]);
add(893,"자루도","Zarude",null,[e("X","70",[],B(["Jungle"]))]);
add(894,"레지에레키","Regieleki",null,[e("X","70-80",["special"],S(["Split Decision Temple (Sinnoh)"]))]);
add(895,"레지드래고","Regidrago",null,[e("X","70-80",["special"],S(["Split Decision Temple (Sinnoh)"]))]);
add(896,"블리자포스","Glastrier",null,[e("X","60",["special"],S(["Crown Spire"]))]);
add(897,"레이스포스","Spectrier",null,[e("X","60",["special"],S(["Crown Cemetery"]))]);
add(898,"버드렉스","Calyrex",null,[e("X","50-70",["special"],S(["Crown Spire","Crown Cemetery"]))]);
add(899,"신비록","Wyrdeer",null,[e("C","42-53",["sky","n025"],B(["Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Ice Spikes","Snowy Plains","Gravel Desert","Rocky Shrubland","Snowy Badlands","Yellowstone"]))]);
add(900,"사마자르","Kleavor",null,[e("R","45-50",["sky","day"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Cherry Grove","Alpha Islands","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Meadow","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Windswept Savanna","Lush Valley","Moonlight Valley","Savanna Slopes","Yosemite Lowlands"]))]);
add(901,"다투곰","Ursaluna",null,[e("C","45-55",["minY48","nosacch"],B(["Forest","Flower Forest","Birch Forest","Old Growth Birch Forest","Dark Forest","Grove","Cherry Grove","Alpha Islands","Alpha Islands Winter","Blooming Valley","Forested Highlands","Lavender Forest","Lavender Valley","Mirage Isles","Sakura Grove","Sakura Valley","Temperate Highlands","Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Windswept Savanna","Lush Valley","Moonlight Valley","Savanna Slopes","Yosemite Lowlands","Stony Spires","Windswept Spires","Yosemite Cliffs","Taiga","Snowy Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Alpine Grove","Cold Shrubland","Siberian Grove","Snowy Maple Forest","Snowy Shield","Wintry Forest","Wintry Lowlands","Bryce Canyon","Cloud Forest","Haze Mountain","Ice Marsh","Moonlight Grove","Shield","Siberian Taiga","Yellowstone"])),e("C","45-55",["sky","sacch"],OW())]);
add(901,"다투곰","Ursaluna","붉은달",[e("R","55-65",["night"],B(NICKIT))]);
add(902,"대쓰여너","Basculegion",null,[e("C","41-53",["sub","seeSky","moon04"],B(BASCULEGION)),e("C","41-53",["sub","indoor","sky","moon04"],B(BASCULEGION))]);
add(903,"포푸니크","Sneasler",null,[e("U","38-51",["sky","n025"],B(["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Blooming Plateau","Highlands","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Sakura Valley","Temperate Highlands","Stony Spires","Windswept Spires","Yosemite Cliffs"]))]);
add(904,"장침바루","Overqwil",null,[e("U","39-51",["sub","seeSky"],B(["Cold Ocean","Deep Cold Ocean"])),e("C","39-51",["sub","seeSky","maxY62"],{b:OVERQWIL,s:OM}),e("U","39-51",["sub","indoor","sky"],B(["Cold Ocean","Deep Cold Ocean"])),e("C","39-51",["sub","indoor","sky","maxY62"],{b:OVERQWIL,s:OM}),e("U","39-51",["sub","indoor","subY"],{b:["Cold Ocean","Deep Cold Ocean","Frozen River","Jagged Peaks","Snowy Beach","Snowy Plains","Snowy Slopes","Deep Frozen Ocean","Frozen Ocean","Frozen Cliffs","Frozen Peaks","Ice Spikes","Frostfire Caves","Glacial Chasm","Alpha Islands Winter","Ice Marsh","Siberian Grove","Snowy Cherry Grove","Snowy Maple Forest","Grove","Snowy Taiga","Alpine Grove","Cold Shrubland","Snowy Shield","Wintry Forest","Wintry Lowlands","Emerald Peaks","Scarlet Mountains","Skylands Winter","Snowy Badlands","Stony Peaks","Rocky Mountains","Windswept Spires","Taiga","Old Growth Pine Taiga","Old Growth Spruce Taiga","Bryce Canyon","Cloud Forest","Haze Mountain","Moonlight Grove","Moonlight Valley","Shield","Siberian Taiga","Yellowstone","Yosemite Lowlands","Gravel Desert","Rocky Shrubland","Windswept Hills","Windswept Gravelly Hills","Windswept Forest","Stony Shore","The End","Small End Islands","End Midlands","End Highlands","End Barrens"],s:SSC})]);
add(905,"러브로스","Enamorus",null,[e("X","50",["t4"],B(["Meadow","Frozen Peaks","Jagged Peaks","Stony Peaks","Snowy Slopes","Cherry Grove","Windswept Hills","Windswept Forest","Windswept Gravelly Hills","Alpine Highlands","Arid Highlands","Blooming Plateau","Highlands","Grove","Windswept Savanna","Blooming Valley","Forested Highlands","Lavender Valley","Lush Valley","Moonlight Valley","Sakura Valley","Savanna Slopes","Temperate Highlands","Yosemite Lowlands","Stony Spires","Volcanic Peaks","Windswept Spires","Yosemite Cliffs"]))]);
