const CATS=[
["숲",{"Snowy Maple Forest":"눈 덮인 단풍 숲","Forest":"숲","Birch Forest":"자작나무 숲","Old Growth Birch Forest":"오래된 자작나무 숲","Flower Forest":"꽃 숲","Dark Forest":"어두운 숲","Pale Garden":"창백한 정원","Cherry Grove":"벚나무 숲","Grove":"산림","Lavender Forest":"라벤더 숲","Sakura Grove":"벚꽃 숲","Mirage Isles":"신기루 섬","Cloud Forest":"운무림","Moonlight Grove":"달빛 숲","Amethyst Rainforest":"자수정 우림","Taiga":"타이가","Old Growth Pine Taiga":"오래된 소나무 타이가","Old Growth Spruce Taiga":"오래된 가문비나무 타이가"}],
["정글",{"Jungle":"정글","Sparse Jungle":"듬성듬성한 정글","Bamboo Jungle":"대나무 정글","Underground Jungle":"지하 정글"}],
["평원과 골짜기",{"Rocky Shrubland":"바위 관목 지대","Plains":"평원","Sunflower Plains":"해바라기 평원","Meadow":"목초지","Brushland":"덤불 지대","Shrubland":"관목 지대","Steppe":"스텝","Valley Clearing":"골짜기 공터","Blooming Valley":"꽃피는 골짜기","Blooming Plateau":"꽃피는 고원","Lavender Valley":"라벤더 골짜기","Sakura Valley":"벚꽃 골짜기","Lush Valley":"무성한 골짜기","Moonlight Valley":"달빛 골짜기"}],
["산과 고원",{"Basalt Cliffs":"현무암 절벽","Emerald Peaks":"에메랄드 봉우리","Granite Cliffs":"화강암 절벽","Haze Mountain":"안개 산","Highlands":"고지대","Scarlet Mountains":"진홍 산맥","Stony Spires":"돌 첨탑","Windswept Spires":"바람이 부는 첨탑","Yellowstone":"옐로스톤","Windswept Hills":"바람이 부는 언덕","Windswept Gravelly Hills":"바람이 부는 자갈 언덕","Windswept Forest":"바람이 부는 숲","Alpine Grove":"고산 산림","Alpine Highlands":"고산 고원","Forested Highlands":"숲 고원","Temperate Highlands":"온대 고원","Arid Highlands":"건조한 고원","Stony Peaks":"돌 봉우리","Rocky Mountains":"바위 산맥","Yosemite Lowlands":"요세미티 저지대","Yosemite Cliffs":"요세미티 절벽","Caldera":"칼데라","Volcanic Crater":"화산 분화구","Volcanic Peaks":"화산 봉우리","Shield":"순상지","Amethyst Canyon":"자수정 협곡"}],
["사바나와 악지",{"Fractured Savanna":"갈라진 사바나","Savanna Badlands":"사바나 악지","Warped Mesa":"뒤틀린 메사","White Mesa":"하얀 메사","Savanna":"사바나","Savanna Plateau":"사바나 고원","Windswept Savanna":"바람이 부는 사바나","Savanna Slopes":"사바나 비탈","Ashen Savanna":"잿빛 사바나","Hot Shrubland":"뜨거운 관목 지대","Badlands":"악지","Wooded Badlands":"나무가 우거진 악지","Eroded Badlands":"침식된 악지","Red Oasis":"붉은 오아시스","Bryce Canyon":"브라이스 협곡"}],
["사막",{"Desert Spires":"사막 첨탑","Gravel Desert":"자갈 사막","Desert":"사막","Ancient Sands":"고대 모래","Desert Canyon":"사막 협곡","Desert Oasis":"사막 오아시스","Lush Desert":"무성한 사막","Sandstone Valley":"사암 골짜기"}],
["눈과 얼음",{"Frozen Cliffs":"얼어붙은 절벽","Snowy Plains":"눈 덮인 평원","Ice Spikes":"역고드름","Snowy Taiga":"눈 덮인 타이가","Snowy Slopes":"눈 덮인 비탈","Frozen Peaks":"얼어붙은 봉우리","Jagged Peaks":"뾰족한 봉우리","Snowy Beach":"눈 덮인 해변","Snowy Badlands":"눈 덮인 악지","Glacial Chasm":"빙하 협곡","Siberian Taiga":"시베리아 타이가","Siberian Grove":"시베리아 산림","Ice Marsh":"얼음 습지","Snowy Cherry Grove":"눈 덮인 벚나무 숲","Cold Shrubland":"추운 관목 지대","Snowy Shield":"눈 덮인 순상지","Wintry Forest":"겨울 숲","Wintry Lowlands":"겨울 저지대","Frozen River":"얼어붙은 강"}],
["물가와 늪",{"Alpha Islands":"알파 섬","Alpha Islands Winter":"겨울 알파 섬","River":"강","Warm River":"따뜻한 강","Swamp":"늪","Mangrove Swamp":"맹그로브 늪","Orchid Swamp":"난초 늪","Beach":"해변","Stony Shore":"돌 해안","White Cliffs":"하얀 절벽","Mushroom Fields":"버섯 들판"}],
["바다",{"Ocean":"바다","Deep Ocean":"깊은 바다","Warm Ocean":"따뜻한 바다","Deep Warm Ocean":"깊은 따뜻한 바다","Lukewarm Ocean":"미지근한 바다","Deep Lukewarm Ocean":"깊은 미지근한 바다","Cold Ocean":"차가운 바다","Deep Cold Ocean":"깊은 차가운 바다","Frozen Ocean":"얼어붙은 바다","Deep Frozen Ocean":"깊은 얼어붙은 바다"}],
["동굴과 지하",{"Crystal Caves":"수정 동굴","Frostfire Caves":"서리불 동굴","Infested Caves":"벌레 먹은 동굴","Mantle Caves":"맨틀 동굴","Thermal Caves":"지열 동굴","Tuff Caves":"응회암 동굴","Lush Caves":"무성한 동굴","Dripstone Caves":"점적석 동굴","Deep Dark":"깊은 어둠","Deep Caves":"깊은 동굴","Fungal Caves":"균류 동굴","Sulfur Caves":"유황 동굴","Andesite Caves":"안산암 동굴","Desert Caves":"사막 동굴","Diorite Caves":"섬록암 동굴","Granite Caves":"화강암 동굴"}],
["네더",{"Nether Wastes":"네더 황무지","Crimson Forest":"진홍빛 숲","Soul Sand Valley":"영혼 모래 골짜기","Basalt Deltas":"현무암 삼각주","Warped Forest":"뒤틀린 숲"}],
["엔드",{"The End":"엔드","Small End Islands":"작은 엔드 섬","End Barrens":"엔드 불모지","End Highlands":"엔드 고지","End Midlands":"엔드 중지"}],
["하늘 섬",{"Skylands Spring":"하늘 섬 (봄)","Skylands Summer":"하늘 섬 (여름)","Skylands Autumn":"하늘 섬 (가을)","Skylands Winter":"하늘 섬 (겨울)"}],
["기타",{"#cobblemon:is_sky":"높은 하늘 (is_sky 태그)"}]
];
const STRUCT_KO={"Village (Plains)":"마을 (평원)","Village (Desert)":"마을 (사막)","Village (Taiga)":"마을 (타이가)","Village (Snowy)":"마을 (눈)","Village (Savanna)":"마을 (사바나)","Village (All Types)":"마을 (모든 종류)","Woodland Mansion":"삼림 대저택","Pillager Outpost":"약탈자 전초기지","Swamp Hut":"늪지 오두막","Crown Spire":"크라운 첨탑","Lush Shipwreck Cove":"무성한 난파선 만","Submerged Shipwreck Cove":"수중 난파선 만","Cold Ocean Ruins":"차가운 바다 폐허","Warm Ocean Ruins":"따뜻한 바다 폐허","Articuno Tower (Kanto)":"프리져 탑 (관동)","Zapdos Tower (Kanto)":"썬더 탑 (관동)","Moltres Tower (Nether)":"파이어 탑 (네더)","Dyna Tree (Hoenn)":"다이나 트리 (호연)","Resurrection Machine":"복원 장치","Origin Temple (Kanto)":"기원의 신전 (관동)","Shipwreck Cove (All Types)":"난파선 만 (모든 종류)","Dawn Tower (End)":"새벽의 탑 (엔드)","Dusk Tower (End)":"황혼의 탑 (엔드)","Trail Ruins":"오솔길 폐허","Trial Chambers":"시련의 회당","Ocean Monument":"바다 유적","Ruined Portal":"폐허가 된 차원문","Burned Tower (Johto)":"불탄 탑 (성도)","Team Rocket Radio Tower (Johto)":"로켓단 라디오타워 (성도)","Whirl Island (Johto)":"소용돌이 섬 (성도)","Bell Tower (Johto)":"방울탑 (성도)","Ilex Shrine (Johto)":"너도밤나무숲 사당 (성도)","Secret Garden (Hoenn)":"비밀 정원 (호연)","Luna Henge Ruins":"루나 헨지 유적","Sol Henge Ruins":"솔 헨지 유적","Igloo":"이글루","Regirock Temple (Hoenn)":"레지락 신전 (호연)","Regice Temple (Hoenn)":"레지아이스 신전 (호연)","Registeel Temple (Hoenn)":"레지스틸 신전 (호연)","Kyogre Dome (Hoenn)":"가이오가 돔 (호연)","Groudon Volcano (Hoenn)":"그란돈 화산 (호연)","End Podium":"엔드 출구 차원문","Sky Pillar (Hoenn)":"하늘기둥 (호연)","Wish Cave (Hoenn)":"소원 동굴 (호연)","Deoxys Meteorite (Hoenn)":"테오키스 운석 (호연)","Jungle Pyramid":"정글 사원","Desert Pyramid":"사막 사원","Ancient City":"고대 도시","Cobblemon Ruins (All Types)":"코블몬 유적 (모든 종류)","Spear Pillar (Sinnoh)":"창기둥 (신오)","Crumbling Arch Ruins":"무너진 아치 유적","Rooted Arch Ruins":"뿌리 내린 아치 유적","Lake Acuity (Sinnoh)":"예지호수 (신오)","Lake Verity (Sinnoh)":"진실호수 (신오)","Lake Valor (Sinnoh)":"입지호수 (신오)","Stark Mountain (Nether)":"하드마운틴 (네더)","Snowpoint Temple (Sinnoh)":"선단 신전 (신오)","Distortion World":"깨어진 세계","Fullmoon Island (Sinnoh)":"만월섬 (신오)","Temple of the Sea (Sinnoh)":"바다의 신전 (신오)","Newmoon Island":"신월섬","Flower Paradise (Sinnoh)":"꽃의 낙원 (신오)","Temple of Sinnoh":"신오 신전","End City":"엔드 도시","Nether Fossil":"네더 화석","Desert Well":"사막 우물","Stronghold":"요새","Shipwreck":"난파선","Split Decision Temple (Sinnoh)":"결단의 신전 (신오)","Crown Cemetery":"크라운 묘지","Bastion Remnant":"보루 잔해","Nether Fortress":"네더 요새","Stonjourner Henge Ruins":"돌헨진 헨지 유적","Eternatus Cocoon (End)":"무한다이노 고치 (엔드)","Grasswither Shrine":"초목 시듦의 사당","Icerend Shrine":"얼음 갈라짐의 사당","Groundblight Shrine":"대지 재앙의 사당","Firescourge Shrine":"불 재앙의 사당"};

